### ISSUE TITLE
Status of reading messages sent by the bot in the group

### ISSUE THREAD

**Issue by shtrihs** [php-telegram-bot/core#1004]
Good evening! Please suggest a solution. 1) my bot sends a message to groups of people. How to make messages from the bot, also written to the database, as well as messages from ordinary users in the group? 2) you Want to know which of the users in the group, read the message from the bot. How to do it?

At the moment, messages from the bot are sent via the script in

`                               $result =  Request::sendMessage([
                                         'chat_id' => $chat_id,
                                         'text'    => $messageText,
                                                                                      ]);`

**Comment by jacklul** [comment]
1. https://github.com/php-telegram-bot/core#mysql-storage-recommended
2. Not possible

**Comment by shtrihs** [comment]
> 1. https://github.com/php-telegram-bot/core#mysql-storage-recommended
> 2. Not possible

1. I have this done, but persist only messages users, not bot
2. Is it not implemented in principle in telegram api or only in this library ?

**Comment by jacklul** [comment]
1. If you really want to log every bot's message you would've have to override `Request` class and modify `sendXXX` functions.
2. No such functionality exists in the bots api - https://core.telegram.org/bots/api
