### ISSUE TITLE
Webhooks do not work

### ISSUE THREAD

**Issue by atomdigital** [php-telegram-bot/core#1006]
|?|!|
|-|-|
| Operating system          | 3.16.0-4-amd64 GNU/Linux
| PHP Telegram Bot version  | 0.60.0
| PHP version               | 5.6.33-0+deb8u1
| MySQL version             | 5.5.55-0+deb8u1
| Update Method             | Webhook / getUpdates
| Self-signed certificate   | no

#### Summary

1)
/var/www/mail-pbx/data/www/mail-pbx.love-sochi.com/love-sochi-bot/hook.php:
https://yadi.sk/i/k4eI8X8IXJvvqg

After run: set.php
message: "Webhook was set", but the update does not occur, the bot does not respond to my messages: https://yadi.sk/i/yeHFqahbiSeW3Q

2) if you add cron.php file execution to the systemD, then nothing happens either....

3) the update occurs only after you turn off the webhooks and set the file getUpdatesCLI.php to run through systemD 

please tell me why webhooks do not work?

**Comment by noplanman** [comment]
Hi @atomdigital, did you manage to find the issue?

I assume you have a `StartCommand.php` in your `Commands` folder, yes?
Can you execute the `/debug` command? Does that return anything?

Also, you can try to [add logging](https://github.com/php-telegram-bot/core/blob/46646884f5c05f1161f10605a0705aa24df3e583/doc/01-utils.md) to see if there is some underlying issue.

**Comment by Sergey-Shabanov** [comment]
Hi, in the manual [https://core.telegram.org/bots/api#getting-updates](https://core.telegram.org/bots/api#getting-updates) it is said that

> There are **two mutually exclusive ways** of receiving updates for your bot — the getUpdates method on one hand and Webhooks on the other. Incoming updates are stored on the server until the bot receives them either way, but they will not be kept longer than 24 hours.
