### ISSUE TITLE
README Webhook installation Fatal error

### ISSUE THREAD

**Issue by VSMent** [php-telegram-bot/core#1010]
With example code from README.md I get an error when trying to set the web hook.

Fatal error: Uncaught Error: Call to a member function isOk() on string in ...

Error is here:
```
// Set webhook
    $result = $telegram->setWebhook($hook_url);
    if ($result->isOk()) {
        echo $result->getDescription();
    }
```
Result returned from `$telegram->setWebhook($hook_url)` is already a description string not an object. There are no `isOk()` and `getDescription()` methods.

**Comment by noplanman** [comment]
What version of the bot are you using?

The `setWebhook` method does return a `ServerResponse` object, so I'm not sure why yours is returning a string :thinking:

**Comment by VSMent** [comment]
I am using
php 7.3, Windows, composer
```{
    "name": "yourproject/yourproject",
    "type": "project",
    "require": {
        "php": ">=5.5",
        "longman/telegram-bot": "*"
    }
}
```

**Comment by VSMent** [comment]
Figured out it is version 0.0.5
longman\telegram-bot\src\Telegram.php
```
    protected $version = '0.0.5';
```

**Comment by VSMent** [comment]
Edited with composer.json with
```
"longman/telegram-bot": ">=0.60-stable"
```

**Comment by noplanman** [comment]
We've seen issues with the `*` version constraint... I need to check with packagist why this doesn't fetch the latest version.
