### ISSUE TITLE
Symfony support

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#1011]
Hi everyone!

How can I use this library in Symfony 4 Project? So is it hard to make it?

**Comment by cybernet** [comment]
[TelegramBotBundle](https://github.com/BoShurik/TelegramBotBundle)

**Comment by BoShurik** [comment]
It build on top of [telegram-bot/api](https://github.com/TelegramBot/Api)

**Comment by greenplugin** [comment]
You can use [this package](https://github.com/tg-bot-api/bot-api-base)

**Comment by noplanman** [comment]
@MyZik Did you manage to integrate it?

I have no experience with Symfony, sorry!

**Comment by MyZik** [comment]
Hi, @noplanman!

No, I use the another library...
