### ISSUE TITLE
Exception should not be swallowed when creating command instance

### ISSUE THREAD

**Issue by CyberKoo** [php-telegram-bot/core#1014]
### 🎉 Feature Request
using exception chaining
#### Summary

https://github.com/php-telegram-bot/core/blob/46646884f5c05f1161f10605a0705aa24df3e583/src/Telegram.php#L252

this line may be changed to 
`throw new TelegramException('Error getting commands from path: ' . $path, $e);`

attach the original exception can be provide more information to the developer.

**Comment by noplanman** [comment]
@CyberKoo Thanks for the suggestion, this is a good idea!

Feel free to make a PR if you like :+1:
