### ISSUE TITLE
Empty tables in connected data base

### ISSUE THREAD

**Issue by Bl0ck154** [php-telegram-bot/core#1020]
#### Required Information

|  ?                        |  !
| ---                       | ---
| PHP Telegram Bot version  | 0.60.0
| PHP version               | 7.3
| MySQL version             | 10.1.41-MariaDB - MariaDB Server
| Update Method             | Webhook 
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

Hello. I'm using php-telegram-bot library and it works fine.
But I found that not all DB tables are filled with data.
I'm currently interested in a table "callback_query", because I actively use this type of query in my application. 
I have checked method 'insertCallbackQueryRequest' in 'telegram-bot/src/DB.php' and and this method executes and returns 'true' value, but my table is always empty.

At the same time tables: users, conversations, chats - work fine.

Everything else, in the logs I get only a warning "AH01215: PHP Warning:  PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'poll' in 'field list' in /home/u6613647/domains/bl0ck.rurs.net/public_html/bots/vendor/longman/telegram-bot/src/DB.php on line 1012: /php73bin/u6613647/php-cgi"

**Comment by jacklul** [comment]
You didn't run SQL upgrade scripts after upgrading `telegram-bot` package.
Check https://github.com/php-telegram-bot/core/tree/master/utils/db-schema-update

**Comment by Bl0ck154** [comment]
But I did not upgrade telegram-bot package. This problem was from the very beginning of work on the project (about a month ago), I did not pay attention.

**Comment by jacklul** [comment]
`poll` field was added in `0.57.0`.

**Comment by Bl0ck154** [comment]
I got error  when I tried to run file 0.57.0-0.58.0.sql , I think it's because I use version 0.60.0
> #1060 - Duplicate column name 'reply_markup'

**Comment by jacklul** [comment]
Oh my bad, I meant `0.56.0-0.57.0.sql`, that's where the `poll` update is!

**Comment by Bl0ck154** [comment]
> 
> 
> `poll` field was added in `0.57.0`.
> Run `0.57.0-0.58.0.sql` migration and see if that fixed the issue.



> 
> 
> Oh my bad, I meant `0.56.0-0.57.0.sql`, that's where the `poll` update is!

Anyway, I already have all this changes. I tried to run every single update from 0.44.1 to 0.60 and always got an error that columns already defined. It's all because I use `structure.sql` from `0.60.0` version, I think there's all the changes included.

**Comment by jacklul** [comment]
`Unknown column 'poll' in 'field list' in` error indicates you do not have `poll` field in message table, can you verify this?

**Comment by Bl0ck154** [comment]
Yes, there was an error when I inserted prefixes into tables.
I don’t understand what the table_prefix parameter is for if tables are not created automatically. Why?
`$telegram->enableMySql($mysql_credentials, $bot_username . '_');` second parameter is table_prefix, we need to add it manually

**Comment by jacklul** [comment]
If you're using table prefix then you gotta edit the migration sql file yourself, generally you don't need to use table prefix in most cases.
