### ISSUE TITLE
0.60.0-0.61.0.sql

### ISSUE THREAD

**Issue by rsdsoft** [php-telegram-bot/core#1023]
0.60.0-0.61.0.sql

ALTER TABLE `message`
DROP KEY `message_id`,
ADD KEY `message_id` (`message_id`),
ADD KEY `chat_message_id` (`chat_id`, `message_id`);

Tables `message` has no message_id field.

**Comment by noplanman** [comment]
Right, this bug slipped in, sorry. It is supposed to be the `telegram_update` table.

Will be fixed in the next release!
