### ISSUE TITLE
Monolog logging engine. (#1009)

### ISSUE THREAD

**Issue by Bl0ck154** [php-telegram-bot/core#1028]
### ❓ Support Question

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  | x.y.z
| PHP version               | x.y.z
| MySQL version             | x.y.z / none
| Update Method             | Webhook / getUpdates
| Self-signed certificate   | yes / no
| RAW update (if available) | `{...}`

#### Summary

❗️ Monolog has been removed as built-in logging engine. (#1009)

**So what we have to use now for logging?**

**Comment by noplanman** [comment]
Hi, take a look here:
https://github.com/php-telegram-bot/core/blob/master/doc/01-utils.md

**Comment by Bl0ck154** [comment]
The link you sent just uses the Monolog library, but it was deleted in the latest version of php-telegram-bot.
Do I understand correctly that now I have to manually connect Monolog through the composer to use it?

**Comment by jacklul** [comment]
Yes, it's done this way so that people can use any PSR-3 logger and not just Monolog.
