### ISSUE TITLE
Add Shortlink PHP 

### ISSUE THREAD

**Issue by Techno-bots** [php-telegram-bot/core#1029]
#### Summary

Can add Shorten Url feature ? 
https://github.com/noplanman/PHP-URL-Shortener.git

thanks

**Comment by noplanman** [comment]
What exactly do you mean?

If you want to use the shortener you linked, that needs to be installed and run separately. Then you can simply call the API to get a short link.

Hope that helps!

**Comment by Techno-bots** [comment]
I installed it on my hosting but I don't know how to run it in bot

**Comment by noplanman** [comment]
It's a very basic shortener, which was used for a specific project, so it has no internal functionality to create shortcodes.

You can create them by calling the URL it's hosted on though, something like this:
```php
$shortened_url = file_get_contents('https://yourdomain.com/shorten.php?url=' . urlencode('https://your.url.to/shorten'));
```

You can then validate the returned value, to make sure it's a correctly shortened URL and not an error message:
```php
if (false === filter_var($shortened_url, FILTER_VALIDATE_URL)) {
    // It was an error! :-s
} else {
    // Ok, it's a valid shortened URL! =)
}
```

Good luck!

**Comment by Techno-bots** [comment]
wow thanks i try it thanks @noplanman
