### ISSUE TITLE
After some time the bot not response anymore, back to work after create new bot

### ISSUE THREAD

**Issue by DarkSaTla** [php-telegram-bot/core#1032]
Hello guys, 
I started my telegram bot yesterday and he works good without any problems, but the bot got blocked or something like that after one day, so now my question is i dont use the bot for spam or something like a spam and i still got blocked.
I readed that the bot can get blocked if he send 30-40 requests per minute and my bot do only 20 -30 requests per 10 minutes so what is the problem here?
Thanks you guys.

**Comment by noplanman** [comment]
@DarkSaTla Do you get any error message or anything?

**Comment by DarkSaTla** [comment]
> @DarkSaTla Do you get any error message or anything?

No nothing, this is why that so weird.

**Comment by noplanman** [comment]
Your original bot still doesn't work, but the new one does?

I'm not sure that it's a problem of this library. Have you tried getting in touch with [@BotSupport](https://t.me/BotSupport)?
