### ISSUE TITLE
Possibility to set own pre execution checks

### ISSUE THREAD

**Issue by silas229** [php-telegram-bot/core#1033]
#### Summary

Please add the possibility to hook own checks to the pre execution function (where `$need_mysql` and `$private_only` are already checked).

#### Use Case
I want to log the user into a service and have commands that should be only executable, when the user is already signed in. So the easiest way to check this would be to add a protected variable `$need_signed_in = true;` to the class.

**Comment by noplanman** [comment]
Have you tried to override the `preExecute` method?
At the moment you'll have to do it manually and copy some existing code from the existing `preExecute` method.

I like your idea of adding custom checks though, so I'll leave this issue open :+1:

**Comment by noplanman** [comment]
As part of this maybe: #1045
