### ISSUE TITLE
The commands on the channels are not executed

### ISSUE THREAD

**Issue by josegarzi2** [php-telegram-bot/core#1034]
Good Morning
I will surely be missing some configuration that I cannot find.

I have created a command that simply returns to the channel from which any message was issued, it is only to see if it works.

From the bot's own channel it works correctly, but from a channel where the bot is an administrator it doesn't work.

I have validated that telegram sends the messages, but they do not reach the code of my command.

Any idea what it could be?

Thank you

**Comment by noplanman** [comment]
This is correct behaviour as it is now.
Messages that come in from a channel get handled by the `ChannelpostCommand` or then the `GenericCommand`.

I can help more if you can share the part of your code that handles the message :blush:

**Comment by josegarzi2** [comment]
Good Morning
Thanks for the reply.
It didn't work because as you said it wasn't implementing the ChannelpostCommand class.
I have seen that in the groups managed by bots a button with the enabled commands may appear, can it be done for the channels, if so, how should it be done?

Thank you

**Comment by noplanman** [comment]
You can use the `PostchannelCommand` for this.

From there you can execute the command that would be called.
Something like this:
```php
$this->getTelegram()->executeCommand($this->getChannelPost()->getCommand());
```

Be aware that you'll need to adjust your commands, as `$this->getMessage()` is `null` when it's called from a channel.
Best use:
```php
$message = $this->getMessage() ?: $this->getChannelPost();
```
