### ISSUE TITLE
sending image attachment from form website to telegram bot

### ISSUE THREAD

**Issue by Adkhambek** [php-telegram-bot/core#1036]
<?php
define ('url',"https://api.telegram.org/bot*****");
$name = $_GET['name'];
$message = $_GET['message'];
$tur=$_GET['maxsulot'];
$image=$_FILES['image']['tmp_name']; //sending image
$chat_id = '*****';

$message = urlencode("Name:".$name."\n Message : ".$message."\n Maxsulot turi:".$tur."\n Rasm:".$image);
file_get_contents(url."sendmessage?text=".$message."&chat_id=".$chat_id."&parse_mode=HTML");

?>

**Comment by noplanman** [comment]
In your PHP code that handles the form, you can use the `Request::sendPhoto` method.

You can find the necessary parameters here:
https://core.telegram.org/bots/api#sendphoto

**Comment by Adkhambek** [comment]
Can you give me example. I cannot use Request::sendPhoto method in my code.

**Comment by Adkhambek** [comment]
> In your PHP code that handles the form, you can use the `Request::sendPhoto` method.
> 
> You can find the necessary parameters here:
> https://core.telegram.org/bots/api#sendphoto

Can you give me example for this method. I cannot use it in my code. please, help me

**Comment by jacklul** [comment]
```
Request::sendPhoto(
	[
		'chat_id' => 123456,
		'photo' => 'https://placekitten.com/200/300';
		'caption' => 'placekitten'
	]
);
```

**Comment by noplanman** [comment]
@Adkhambek Are you using the PHP Telegram Bot library that you've posted this issue in?

Or what do you mean by:

> I cannot use it in my code.
