### ISSUE TITLE
SSL error 

### ISSUE THREAD

**Issue by dasturchiuz** [php-telegram-bot/core#1037]
Hello friends, I am using https://sslforfree.com/ certificate getting error SSL error {error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed 
`Server:  Debian 9, php: 7.2, nginx`

nginx: 
```
listen 443;
    ssl on;
    ssl_certificate /var/www/.../ssl/ssl-bundle.crt;
    ssl_certificate_key /var/www/..../ssl/private.key;
```

how to fix this error? 
pls help me!

**Comment by lasanthaa** [comment]
Hi dasturchiuz,
Did you solve this issue?

**Comment by asafov** [comment]
Why use don't just use letsencrypt?
