### ISSUE TITLE
Make changes to manual

### ISSUE THREAD

**Issue by tec-devel** [php-telegram-bot/core#1039]
Hi!

I suggest to make changes on main manual page in GitHub.

In article where described how to use self-signed sertificate wrote:

$result = $telegram->setWebhook($hook_url, **['certificate' => '/path/to/certificate']**); 

Use certificate path as array - is wrong and get error, because in sources (_longman/telegram-bot/src/Telegram.php:701_) path uses as string:

    ...
    /**
     * Set Webhook for bot
     *
     * @param string       $url
     * @param string|null  $path_certificate
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     */
    public function setWebHook($url, $path_certificate = null)
    {
    ...

Thanks!

**Comment by noplanman** [comment]
Not sure what version of the code you're looking at.

The array parameter to pass the certificate has been the way to do it for a very long time.

**Comment by tec-devel** [comment]
Ok, i see array in **master**

but if i try install php-telegram-bot via composer (https://github.com/php-telegram-bot/core#require-this-package-with-composer) it installs 0.35.0 version :(

**Comment by noplanman** [comment]
What version of PHP are you using?
Are there any other dependencies in your project? Maybe one of them is blocking a later version.

**Comment by tec-devel** [comment]
PHP 7.2
No, a took composer.json file from a manual as is.

upd: re-launch **composer update** is updated bot to 0.61.0
it's not my fault.. :)

Thank you!
