### ISSUE TITLE
error Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' 

### ISSUE THREAD

**Issue by shaiho** [php-telegram-bot/core#1041]
#### Required Information

Operating system: ubuntu 16.04
PHP version: 7.3
PHP Telegram Bot version: Latest version
Using MySQL database: yes
MySQL version: 5.7.28
Update Method: getupdate
Self-signed certificate: no

#### Summary

i try to run my first bot by use the example but i got this error:

PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /var/www/html/phpbot/vendor/longman/telegram-bot/src/DB.php:86

**Comment by noplanman** [comment]
Make sure you have the PDO MySQL extension installed for your version of PHP.

**Comment by ulises-castro** [comment]
If you are using docker containers, you should add the below command into your dockerfile.

`RUN docker-php-ext-install pdo_mysql mysqli && docker-php-ext-enable pdo_mysql`
