### ISSUE TITLE
Minimum PHP 7.4 support

### ISSUE THREAD

**Issue by klevialent** [php-telegram-bot/core#1053]
I want to do fork without backward compatibility.
Code-style will be PSR-12.

https://github.com/klevialent/core

Any wishes?

**Comment by noplanman** [comment]
Hi @klevialent, would you like to join in the development here instead of forking?

**Comment by klevialent** [comment]
Hi @noplanman, yes i would like. What should i do?

**Comment by noplanman** [comment]
@klevialent Excuse the late reply...

Of course there is the issues list of things that need looking into and testing the develop branch is always appreciated!

We're looking at moving to a minimum PHP version of 7.2, to stick to versions that are still supported. So you can also look at migrating to 7.2 if you feel inspired to do so.

It would help to do things in smaller steps, not a PR with 10'000 changes :wink: 

Let me know what you think!
