### ISSUE TITLE
Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.

### ISSUE THREAD

**Issue by Theolodewijk** [php-telegram-bot/core#1054]
composer require longman/telegram-bot
Using version ^0.61.1 for longman/telegram-bot
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.5.2): Loading from cache
  - Installing psr/log (1.1.2): Loading from cache
  - Installing longman/telegram-bot (0.61.1): Downloading (100%)
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.
Writing lock file
Generating autoload files

**Comment by noplanman** [comment]
This comes from an underlying dependency, not this library directly.

@Theolodewijk What version of PHP are you using?
