### ISSUE TITLE
Phpunit testing

### ISSUE THREAD

**Issue by zhkuskov** [php-telegram-bot/core#1056]
Hello!  Is there documentation on testing with phpunit?  thanks!

**Comment by noplanman** [comment]
Not really. What exists at the moment, is what you see in the repo.

When you install via composer it also installs the dev tools, including PHPUnit, which is used for testing. The only thing you need, is a test database where test can run against. You can provide the DB details in a custom `phpunit.xml` file, you can use [`phpunit.xml.dist`](https://github.com/php-telegram-bot/core/blob/85d52f67b5ecf3ac81471fbcfacc37f61abb0c8e/phpunit.xml.dist) as a template.

Unfortunately there aren't that many tests yet, so if you're up for writing some or simply giving feedback on what already exists, that would be awesome!

**Comment by noplanman** [comment]
Consolidate test-related comments in #979
