### ISSUE TITLE
Select users by language_code 

### ISSUE THREAD

**Issue by omentes** [php-telegram-bot/core#1057]
#### Summary

Hello everybody!

My bot is used by people from different countries, and sometimes I need to do sending messages to users by user's language.

I easily solved this problem by adding a few lines of code that I want to suggest adding to the master branch of the project

#### Request Changes

 https://github.com/omentes/core/commit/752dda94b3ff24ccd7f2e34d7440f1da153ea787

**Comment by noplanman** [comment]
Great idea and thanks for the PR, check my comment there :+1:
