### ISSUE TITLE
zlib error -5

### ISSUE THREAD

**Issue by Hess1337** [php-telegram-bot/core#1060]
Hi, 
I try to install a webhook on my server, but I get an error
`{"ok":true,"result":{"url":"**","has_custom_certificate":false,"pending_update_count":12,"last_error_date":1584900139,"last_error_message":"Bad Request: zlib error -5","max_connections":40}}`
I tried to install my let'sencrypt, but I get this error
`"last_error_message":"SSL error {337047686, error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed}"
`

**Comment by noplanman** [comment]
This shouldn't have anything to do with this library, but with your SSL certificate.

Can you access your domain correctly with the certificate installed? Try to renew it and restart the webserver to make sure the new one is loaded correctly.
