### ISSUE TITLE
broken markup on long messages

### ISSUE THREAD

**Issue by kur1977** [php-telegram-bot/core#1062]
Hi there ))
**Request::sendMessage**

```php
        do {
            //Chop off and send the first message
            $data['text'] = mb_substr($text, 0, 4096);
            $response     = self::send('sendMessage', $data);

            //Prepare the next message
            $text = mb_substr($text, 4096);
        } while (mb_strlen($text, 'UTF-8') > 0);
```

This breaks markup on long texts. 
I remove this and found that texst that are longer than 4096 symbols are successfully delivers to the chat.

So, may be this part of code is a bug or something?

**Comment by jacklul** [comment]
That code cuts the text but doesn't account for any markdown or HTML markup, if it cuts text while a tag is still open it will error out. In this case you should handle it yourself with your own helper function

**Comment by noplanman** [comment]
According to [the docs](https://core.telegram.org/bots/api#sendmessage) the message (without any markup) can be no longer than 4096 characters.

@kur1977 Out of curiosity, how long is the message you're successfully sending when you remove the snippet?

**Comment by kur1977** [comment]
@noplanman 
After removing this part of code I succesfully sended the marked-up messages that more than twice bigger than 4096 charecters.

**Comment by noplanman** [comment]
@kur1977 I've updated the method in #1163 to allow for splitting or not, returning all message responses.

With that I'll close this off and let users manage their own message sending.
