### ISSUE TITLE
How I can get chat_id from callback_query when callback_query  is sent from InlineQueryResultArticle reply_markup?

### ISSUE THREAD

**Issue by ogtayhuseynov0** [php-telegram-bot/core#1064]
#### Required Information
| ? | ! |
| - | - |
| Operating system          | Linux |
| PHP Telegram Bot version  | latest/ bot-example |
| PHP version               | 7.3 |
| MySQL version             | none |
| Update Method             | Webhook |
| Self-signed certificate   | yes |
| RAW update (if available) | `{"update_id":123, "callback_query":{"id":"123 ","from":{"id":123,"is_bot":false,"first_name":"asd","last_name":"asd","username":"asd","language_code":"en"},"inline_message_id":"asdasd","chat_instance":"-asdasd","data":"data123"}}` |

#### Summary
I am getting call_back data from webhook, there is no problem but I need chat_id for further dev. There is only chat_instance field in update however there is not method to send message to chat_instance, all methods need chat_id. If there is a way of getting chat_id please inform me.

**Comment by jacklul** [comment]
Inline messages doesn't provide chat object because you can paste them everywhere.

Currently bot cannot obtain info about chats and users that did not interact with the it - this is why inline message doesn't contain that data.

**Comment by ogtayhuseynov0** [comment]
What I am trying to get is that I have bunch of categories which I want to Chats (both users and groups) to get subscribed so that, bot will send them daily updates according to category. Categories can be found through inline search, when user choose a category reply_markup is sent to them (subscribe, or not). Is there another way of doing it?, Categories are more than 100 :/.

**Comment by jacklul** [comment]
Bot's cannot initiate chats, so even if they click the button from inline message (for example in a group) the bot will not be able to send them any daily updates until they `/start` the bot.

You can get id of private chat with specific user that clicked the button via `$this->getCallbackQuery()->getFrom()->getId()` (id of chat and user are the same for private chats).

**Comment by ogtayhuseynov0** [comment]
Thanks for answers.
