### ISSUE TITLE
Seamless Telegram Login example

### ISSUE THREAD

**Issue by rick20** [php-telegram-bot/core#1065]
Does someone actually managed to successfully implement the seamless telegram login?
The best I can do is showing the inline button, which then showing login confirmation when the button got clicked, exactly like this

![login confirmation](https://core.telegram.org/file/811140015/1734/8VZFkwWXalM.97872/6127fa62d8a0bf2b3c)

But when I click Open, it just opens a regular link without anything appended to the url.

I googled everything from login_url, keyboardButtonUrlAuth, requestUrlAuth, and whatever the documentation said, but it looks to me that there's no one ever really use this feature.

What I actually need is quite simple, to know who's opening the page.
Does seamless telegram login is the right feature to handle this case?

Greatly appreciate any advice :)

**Comment by noplanman** [comment]
@rick20 Try this code in the command that sends the keyboard with the login button:
```php
use Longman\TelegramBot\Entities\InlineKeyboard;
use Longman\TelegramBot\Entities\LoginUrl;

$text         = 'Go to https://example.com!';
$reply_markup = new InlineKeyboard([
    ['text' => 'Login', 'login_url' => new LoginUrl(['url' => 'https://example.com/login_url', 'forward_text' => 'Login (forwarded)'])],
    ['text' => 'Open', 'url' => 'https://example.com/url'],
]);

return $this->replyToUser($text, compact('reply_markup'));
```

Your domain must be assigned to the bot through [@BotFather](https://t.me/BotFather) for this to work.

**Comment by noplanman** [comment]
Also, to verify the request, you can use this little helper I wrote some time ago:
https://git.feneas.org/noplanman/service-webhook-handler/#telegram-login

**Comment by rick20** [comment]
@noplanman @ossiach this is really my bad...it's actually working since the first time. Many thanks for the same guide you both share.
Your advice convince me I'm already at the right path.
I can see now it's now returning the id, first_name, last_name, username, auth_date, and hash in query string.

The problem was that it only works on app while im trying to debug from desktop chrome.
Many thanks for all of your help, I'll close this issue now

**Comment by ivioninjs** [comment]
hello!
I have a same problem, please help me.

1. I want to  make authorization my website using Seamless telegram login https://core.telegram.org/bots/api#loginurl  
2. But, in my telegram' bot don't show popup window for login like this https://core.telegram.org/file/811140015/1734/8VZFkwWXalM.97872/6127fa62d8a0bf2b3c

What should I do?
Please help me.

I used - firebase functions, telegraf.js, vuejs

This my code:
Telegraf.js

```
const Telegraf = require('telegraf')
const Extra = require('telegraf/extra')
const Markup = require('telegraf/markup')
const functions = require('firebase-functions')

const bot = new Telegraf(functions.config().telegram.bot)

const keyboard = Markup.inlineKeyboard([
  Markup.loginButton('Login', 'https://my-domain.app', {
    bot_username: 'my_bot',
    request_write_access: 'true'
  })
])

bot.start((ctx) => ctx.reply('Hello', Extra.markup(keyboard)))

bot.on('sticker', ctx => ctx.reply('👍'))

bot.catch((err, ctx) => {
  console.log(`Ooops, encountered an error for ${ctx.updateType}`, err)
})

exports.bot = functions
  .region('us-central1')
  .https.onRequest(
    (req, res) => bot.handleUpdate(req.body, res).then(rv => !rv && res.sendStatus(200))
  )
```

Vue.JS

```
mounted(){
    const script = document.createElement('script')
    script.async = true
    script.src = 'https://telegram.org/js/telegram-widget.js?3'
    script.setAttribute('data-size', 'large')
    script.setAttribute('data-userpic', this.userpic)
    script.setAttribute('data-telegram-login', 'my_bot')
    script.setAttribute('data-request-access', 'read')
    window.onTelegramAuth = this.onTelegramAuth
    script.setAttribute('data-onauth', 'window.onTelegramAuth(user)')

    this.$refs.telegram.appendChild(script)
},
methods: {
    onTelegramAuth(user) {
       console.log('welcome', JSON.stringify(user))
     }
  }
```

**Comment by noplanman** [comment]
@ivioninjs Hi, this is the repository for the PHP Telegram Bot library, so not sure if anybody can help out with this JS problem.

A common mistake with the seamless login is to not have set it up correctly.
So first make sure you've followed the steps correctly here: https://core.telegram.org/widgets/login

Then maybe start with a simple example file from Telegram, to make sure it's working. Then you can progress to implement your code 👍 

Hope that helps!
