### ISSUE TITLE
Telegram returned an invalid response

### ISSUE THREAD

**Issue by saeed2922** [php-telegram-bot/core#1069]
|?|!|
| ---                       | ---
| Operating system          |win7
| PHP Telegram Bot version  |?
| PHP version               |5.5.12
| MySQL version             | 5.6.17
| Update Method             | Webhook 
| Self-signed certificate   | no

#### Summary

i create anr run set.php 
but :Telegram returned an invalid response!

**Comment by noplanman** [comment]
What version of the bot was installed?
You can check in `vendor/longman/telegram-bot/src/Telegram.php` file, in the `$version` variable.

Be sure to check your bot username and API token.

**Comment by JobirYusupov** [comment]
Hi. I have same respons:  Telegram returned an invalid response!
"longman/telegram-bot": "^0.62.0" in my composer.json
protected $version = '0.62.0'; in vendor/longman/telegram-bot/src/Telegram.php
my bot username: zetSoftTestBot (i also tried @zetSoftTestBot );
my token is corrent. 
i tried to manumally send get request to https://api.telegram.org/bot<my-token>/setWebhook?url=<my-url> and it returned : 
{
ok: true,
result: true,
description: "Webhook was set"
}


"Telegram returned an invalid response!" how can i fix this. pls help me

**Comment by JobirYusupov** [comment]
i fixed it.
![image](https://user-images.githubusercontent.com/35604486/79433971-3618f680-7fe7-11ea-8794-19b2c16ca1d1.png)
![image](https://user-images.githubusercontent.com/35604486/79434030-429d4f00-7fe7-11ea-98b1-8fa35e5e43dc.png)

**Comment by noplanman** [comment]
Glad it's working now 👍
