### ISSUE TITLE
Check if my robot is admin of a channel

### ISSUE THREAD

**Issue by irmmr** [php-telegram-bot/core#1070]
Hi guys, how can I check if my robot is the admin of Channel X or not?
Also, does it have access to send messages or not?

> X is the username of a channel.

**Comment by jacklul** [comment]
Bots can only be added to channels as administrators, a successful `getChat` query will indicate it is.
To check access to sending messages use `getChatMember` and check if `can_post_messages` in the reply is set to true.

**Comment by irmmr** [comment]
Thank you !
