### ISSUE TITLE
installing getUpdates installation

### ISSUE THREAD

**Issue by Theolodewijk** [php-telegram-bot/core#1072]
### ❓ Support Question

 Sorry, this group is not accessible
-->

#### Required Information
|  ?                        |  !
| ---                       | ---
| Operating system          | CentOS 8 (Directadmin Nginx)
| PHP Telegram Bot version  | last version
| PHP version               | 7.3
| MySQL version             | 8.0
| Update Method             | getUpdates
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

I tray the setup 'getUpdates installation' but if I exequte I get an error 
[root@mail telegram]#  ./getUpdatesCLI.php
-bash: ./getUpdatesCLI.php: /usr/local/bin: bad interpreter: Permission denied

**Comment by Theolodewijk** [comment]
if I use #!/usr/bin/env php
/usr/bin/env: ‘php\r’: No such file or directory

**Comment by jacklul** [comment]
That's not library issue, it's CentOS.
Run it by calling PHP: `php ./getUpdatesCLI.php`

**Comment by Theolodewijk** [comment]
@jacklul awesome thanks it works :)
