### ISSUE TITLE
Get started

### ISSUE THREAD

**Issue by Theolodewijk** [php-telegram-bot/core#1073]
Who can help me to get started with Telegram API from Longman.

I used various APIs that were outdated in the past, and now want to use the possibilities of telegram in the right way.

I've looked here and there on Indetnet but haven't really been able to find anything that matches the API of Longman, likes video's and tutorials.

who has links here to how to get started and something i can learn from.

I have read a few things, but I do come across some things where I notice that it is better to first delve deeper into how it works.

**Comment by noplanman** [comment]
The best place is to check the example commands here:
https://github.com/php-telegram-bot/example-bot/tree/master/Commands

And the official Bot API here:
https://core.telegram.org/bots/api

Apart from that, it's probably easiest to ask specific questions, if there is something you'd like to achieve with a bot :smiley:
