### ISSUE TITLE
Sending message to UserID without interaction

### ISSUE THREAD

**Issue by iflirch** [php-telegram-bot/core#1075]
Hi, I would like to know how I can send a message to a userID without interaction.
I tried to follow a script here [Send message to user channel without interaction](https://github.com/php-telegram-bot/core/wiki/How-to-send-message-to-channel-user-without-user-interaction)

But I always get this error:
![Error](https://i.imgur.com/OJE736t.jpg)

Can someone please help me with this?.

**Comment by jacklul** [comment]
1. Did this user initiated chat with the bot at least once? - Bots cannot initiate conversations in private chats - this is to prevent spam bots.
2. Are you from Russia? - Telegram is blocked in Russia and you have to use a proxy.

**Comment by noplanman** [comment]
@iflirch Did you get this working, can I close off here?

**Comment by iflirch** [comment]
@noplanman Yes please ^^ thank you
