### ISSUE TITLE
how SELECT data from databas host and send telegrambot

### ISSUE THREAD

**Issue by msalmipour** [php-telegram-bot/core#1079]
$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
               $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
               $stmt = $conn->prepare("SELECT `ostan`,`nam_shobe`,`address`,`tel`,`fax` FROM 
               `shobe_ordibehesht` WHERE `ostan`='$ostan'");
                $stmt->execute();
                $result = $stmt->fetch(PDO::FETCH_ASSOC);
                 send_message( $result);
    function send_message($result) {
        
        $reply = $msg;
        $url = $GLOBALS['bot_url'] . "/sendMessage";
        $post_params = [ 'chat_id' =>  $GLOBALS['chat_id'] , 'text' => $reply ];
        send_reply($url, $post_params);
    }

**Comment by Theolodewijk** [comment]
I use for that unreal4u library

Example ::

```
$bot_api_key 				= '';
$bot_username 			= '';
$bot_username_without 	= '';
$chat_id					= '';

include './../vendor/autoload.php';

use React\EventLoop\Factory;
use unreal4u\TelegramAPI\HttpClientRequestHandler;
use unreal4u\TelegramAPI\Telegram\Methods\SendPhoto;
use unreal4u\TelegramAPI\Telegram\Types\Custom\InputFile;
use unreal4u\TelegramAPI\TgLog;

$i = 0;

$stmt = $db->prepare("SELECT * FROM ads WHERE status = ? AND telegram = ? ORDER BY ads_id ASC LIMIT 30");
$stmt->execute(array(1, 0)); 
$data = $stmt->fetchAll();
foreach ($data as $row) {
	$i++;
	$ads_id 	= $row['ads_id'];
	$image 		= $row['image'] && @file_get_contents($themes_path . '/img/ads/' . $row['image']) ? $row['image'] : 'default.png';
	$title 		= utf8_encode($row['title']);
	$link		= $siteurl . '/ads/view/' . $row['ads_hash'] . '/' . make_url_friendly($title);
	$content	= utf8_encode($row['content']);

	$Telegram_sendMessage = $title . "\n\n" . $link . "\n\n" . limit_text($content, 18);


	$loop = Factory::create();
	$tgLog = new TgLog($bot_api_key, new HttpClientRequestHandler($loop));

	$sendPhoto = new SendPhoto();
	$sendPhoto->chat_id = $chat_id;
	$sendPhoto->photo = new InputFile($themes_path . '/img/ads/' . $image);
	$sendPhoto->caption = $Telegram_sendMessage;

	$promise = $tgLog->performApiRequest($sendPhoto);

	$promise->then(
	    function ($response) {
	    	global $db, $ads_id;

	        echo '<pre>';
	        var_dump($response);
	        echo '</pre>';

	        // update message_id
            $sql = "UPDATE ads SET telegram = ?, message_id = ? WHERE ads_id = ?";
            $sql = $db->prepare($sql);
            $sql->execute(array('1', $response->message_id, $ads_id));
	    },
	    function (\Exception $exception) {
	        // Onoes, an exception occurred...
	        echo 'Exception ' . get_class($exception) . ' caught, message: ' . $exception->getMessage();
	    }
	);

	$loop->run();
}
```

**Comment by msalmipour** [comment]
Unfortunately, I did not succeed


$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
           $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
               $stmt = $conn->prepare("SELECT `ostan`,`address` FROM `shobe_ordibehesht` WHERE `ostan`='$ostan'");
              // send_message($chat_id);
              $stmt->execute(array(1, 0));
              $data = $stmt->fetchAll();
              foreach ($data as $row) {
	$i++;
	$ostan1 		= utf8_encode($row['ostan']);

	$address1	= utf8_encode($row['address']);
	send_message($ostan1);
}

**Comment by noplanman** [comment]
Sending a message is as easy as:
```php
Longman\TelegramBot\Request::sendMessage([
    'chat_id' => $chat_id,
    'text'    => $whatever_text,
]);
```

You just need to initialise the Telegram object before that, like:
```php
new Longman\TelegramBot\Telegram($api_key);
```

@msalmipour Is that what you mean?

**Comment by msalmipour** [comment]
Unfortunately, I did not succeed
I want to select the information I have in the database and send it to the robot, please help. The database information is in the form of an array and I want to convert the array to text and then send it to the robot.

$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$stmt = $conn->prepare("SELECT `ostan`,`address` FROM `shobe_ordibehesht` WHERE `ostan`='$ostan'");
// send_message($chat_id);
$stmt->execute(array(1, 0));
$data = $stmt->fetchAll();
foreach ($data as $row) {
	$i++;
	$ostan1 = utf8_encode($row['ostan']);

	$address1 = utf8_encode($row['address']);
	send_message($ostan1);
}
function send_message($result) {
    
    $reply = $msg;
    $url = $GLOBALS['bot_url'] . "/sendMessage";
    $post_params = [ 'chat_id' =>  $GLOBALS['chat_id'] , 'text' => $reply ];
    send_reply($url, $post_params);
}

**Comment by noplanman** [comment]
I'll close off here, as you're not using this library...

Check the official documentation on how to send a message with cURL:
- https://core.telegram.org/bots/api#making-requests
- https://core.telegram.org/bots/api#sendmessage
