### ISSUE TITLE
Class Telegram Bot Manager not found

### ISSUE THREAD

**Issue by farmaworld** [php-telegram-bot/core#1083]
### ❓ Support Question

i make this command in terminal : composer require php-telegram-bot/telegram-bot-manager
but i have some error
in manager.php 

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  | 6.1.2
| PHP version               | 7.4
| MySQL version             | x.y.z / none
| Update Method             | getUpdates
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

C:\Users\raffa\PhpstormProjects\TelegramBIS>composer require php-telegram-bot/telegram-bot-manager
Using version ^1.5 for php-telegram-bot/telegram-bot-manager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-telegram-bot/telegram-bot-manager ^1.5 -> satisfiable by php-telegram-bot/telegram-bot-manager[1.5.0].
    - php-telegram-bot/telegram-bot-manager 1.5.0 requires longman/telegram-bot ^0.59 -> satisfiable by longman/telegram-bot[0.59.0, 0.59.1] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by jacklul** [comment]
See here: https://github.com/php-telegram-bot/telegram-bot-manager/issues/54
