### ISSUE TITLE
What's thing do you suggestion alternative of Botan.io for analytic?

### ISSUE THREAD

**Issue by NabiKAZ** [php-telegram-bot/core#1084]
Botan.io is deprecate and remove.
What's thing do you suggestion alternative of Botan.io for analytic?

**Comment by jacklul** [comment]
You can basically use any statistics service, you just need to implement the wrapper yourself.

**Comment by NabiKAZ** [comment]
Is it possible to use Google Analytics?
What is your suggestion?

**Comment by jacklul** [comment]
https://developers.google.com/analytics/devguides/collection/protocol/v1/

**Comment by NabiKAZ** [comment]
https://github.com/php-telegram-bot/core/issues/528

**Comment by NabiKAZ** [comment]
Basically, I want to know what useful statistics the analytics service for Bot Telegram can give us? Due to the fact that no one has direct access to user information such as IP, cookie, operating system, etc.
Perhaps the only feature is to understand how many people have become members of the robot during the day, which can be easily understood from the our database.
Do you have any other useful features and do you need to use such statistical tools at all...?

**Comment by jacklul** [comment]
It depends on what kind of a bot you're writing, some can make use of user statistics while other may not.

As a basic statistics tool you can already use build in DB support and just extend it a little to provide more information, then just build proper SQL queries and export data as datasheet which can be displayed as a graph.
