### ISSUE TITLE
Error while processing poll answer

### ISSUE THREAD

**Issue by asafov** [php-telegram-bot/core#1086]
#### Required Information

| ? | ! |
| - | - |
| Operating system          | CentOS 7
| PHP Telegram Bot version  | 0.62.00
| PHP version               | 7.2.27
| MySQL version             | 5.7.29-32 Percona
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

1. 
PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`kdt`.`tgbot_poll_answer`, CONSTRAINT `tgbot_poll_answer_ibfk_1` FOREIGN KEY (`poll_id`) REFERENCES `tgbot_poll` (`id`)) {"exception":"[object] (ErrorException(code: 0): PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`kdt`.`tgbot_poll_answer`, CONSTRAINT `tgbot_poll_answer_ibfk_1` FOREIGN KEY (`poll_id`) REFERENCES `tgbot_poll` (`id`)) at "/vendor/longman/telegram-bot/src/DB.php:907)

2. Primary key in table poll_answer is poll_id, seems, that right PK is poll_id + user_id

#### How to reproduce

Create new non-anonymous poll by sendPoll and answer by user in chat group.

Solution:
1. Add user id to primary key
2. Remove restrict for update

**Comment by noplanman** [comment]
@asafov You're absolutely right, thanks for reporting 🙏

**Comment by noplanman** [comment]
@asafov Could you please give #1087 a try and confirm that it's working correctly? Thanks

**Comment by asafov** [comment]
Second issue is fixed, but first is still actual.
Seems, that query for poll is duplicated or something like this.
This is content of my updates table:

https://imgur.com/a/G9YFiHm

**Comment by noplanman** [comment]
That is correct behaviour, as the Telegram Bot API does send both those updates...
I know, it's strange 😕 

The constraint error is fixed now, right?

**Comment by asafov** [comment]
It was another stupid problem.
After user click some answer at poll, command GenericCommand execute and have no $this->getMessage () method, coz it's update. So catched 400 error from telegram server, while i try to send message with calling getMessage () and duplicate queries. Sorry my mistake.

**Comment by asafov** [comment]
About anonymouse polls - here is reason why answers don't put to database:
```
            if ($user = $poll_answer->getUser()) {
                $user_id = $user->getId();
                self::insertUser($user, $date);
            }
```

But table poll is correctly updated. I think that if we want to see answers at poll_answer table too, we need to generate random id for user.

Here is update for anonymouse poll:
`{"update_id":193532823, "poll":{"id":"5291776536217649157","question":"\u0413\u043e\u0442\u043e\u0432\u044b \u0437\u0430\u0432\u0442\u0440\u0430 \u0442\u0440\u0443\u0434\u0438\u0442\u044c\u0441\u044f?","options":[{"text":"\u0414\u0430 (\u041f\u0435\u0448\u0438\u0439)","voter_count":0},{"text":"\u0414\u0430 (\u0410\u0432\u0442\u043e)","voter_count":1},{"text":"\u041d\u0435\u0442","voter_count":0}],"total_voter_count":1,"is_closed":false,"is_anonymous":true,"type":"regular","allows_multiple_answers":false}}`

**Comment by asafov** [comment]
By the way - how about two new system commands?
PollSendedCommand and PollAnswerSendedCommand?

**Comment by noplanman** [comment]
Regarding new system commands, I think until we rewrite the whole command system, it will just make it more difficult by adding new ones, so not at the moment.

About the anonymous polls, the code you posted shouldn't be a problem, as the user doesn't get passed anyway with anonymous polls. When replying to an anonymous poll, only the `poll` update gets received from the Bot API, and the results (`total_voter_count`) are updated in the `poll` table.

**Comment by asafov** [comment]
Yes, it doesn't make any problems, i only mean, that if we want to see records at poll_answer table for anonymous, we should generate some unique user id for prevent duplicates at primary key.
At this moment i don't see any need for populate this table, so it's only my minds and nothing else.

**Comment by noplanman** [comment]
> that if we want to see records at poll_answer table for anonymous, we should generate some unique user id

Logging the answers is opposite of what anonymous is intended for 😬

**Comment by asafov** [comment]
You are 100% right, sorry for going crazy)

**Comment by noplanman** [comment]
I'm very grateful for your input and any feedback, so no need to apologise 😊
