### ISSUE TITLE
Log request data sended to Telegram API

### ISSUE THREAD

**Issue by asafov** [php-telegram-bot/core#1088]
#### Summary

I think it will be good idea to log request data sended to telegram server in debug log.
Maybe at dedicated "Verbose" log.

**Comment by noplanman** [comment]
Do you mean to output the `$data` values in the error log along with the HTTP response?

**Comment by asafov** [comment]
Yes

**Comment by noplanman** [comment]
I like this idea, thanks for bringing it up. I'll prepare a PR for you to check out 👌

**Comment by noplanman** [comment]
@asafov What do you think, regarding the PR?

**Comment by asafov** [comment]
Looks great. Fully as i wanted.

**Comment by jacklul** [comment]
> Looks great. Fully as i wanted. Maybe add setter and getter? What do you think?

Since it's a static class it doesn't make sens, you can simply:

```php
TelegramLog::$log_request_data = true;
```

and change this at any time on run-time.

**Comment by asafov** [comment]
OK. Merge.

**Comment by asafov** [comment]
I create PR for log response data too.
