### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by asafov** [php-telegram-bot/core#1092]
Delete

**Comment by asafov** [comment]
My error - command generic presented at custom commands, so conversation don't continue

**Comment by noplanman** [comment]
@asafov For future reference, it makes sense to just leave the title and content of issues and simply post a solution, instead of deleting everything.

There are no stupid questions, and it might just help someone who has the same issue 😉

**Comment by asafov** [comment]
It's very-very specific situation, but i understand you.
