### ISSUE TITLE
Message Id bot telegram php

### ISSUE THREAD

**Issue by aldobel** [php-telegram-bot/core#1096]
### ❓ Support Question

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  | x.y.z
| PHP version               | 7.1
| MySQL version             | 4.1.2/ none
| Update Method             | Webhook 
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

Hello guys, I’m have a function for the send message...this function:
Function sendMessage($chatid, $message){
     $url = "https://api.telegram.org/bot<token>/sendMessage?chat_id=$chatid&text=$message";

File_get_contents($url);
}

how do i extract the messageid?

Thank you.

**Comment by noplanman** [comment]
Hi @aldobel, you are clearly not using the PHP Telegram Bot library, which is what this issue tracker is for.

What you want is something like this however:
```php
$url = "https://api.telegram.org/bot/sendMessage?chat_id=$chatid&text=$message";

$response = json_decode(file_get_contents($url));

if ($response->ok) {
    $message_id = $response->result->message_id;
}
```

**Comment by aldobel** [comment]
Thank you @noplanman
