### ISSUE TITLE
Idea: Ability to pause / resume conversation

### ISSUE THREAD

**Issue by asafov** [php-telegram-bot/core#1099]
I want to realise feature for pause / resume conversation.
Use case:
For example i have bot with catalog of goods, listed by inline controls.
User see needed item and click "Add to basket". Bot ask quantity of items and save it to storage and pause conversation, for user can continue list catalog from last position.
When user want to add another item - conversation resume and etc.
And the finish line user view him basket and finish order (stopped) or cancel it.

What do you think, guys?

**Comment by noplanman** [comment]
I think that's a great idea and a nice addition 🎉 

Feel free to create a PR and some example code so we can test it out.

**Comment by asafov** [comment]
OK. Will start develop at this night.
