### ISSUE TITLE
“Telegram returned an invalid response!” error when using php-telegram-bot laravel package

### ISSUE THREAD

**Issue by ahmadbadpey** [php-telegram-bot/core#1101]
I'm using [php-telegram-bot/core][1] in larvel 7.12 to make a telegram bot.

I followed all instruction described [here][2] 

this is my routes: 

    Route::get('/setwebhook', 'BotController@setWebhook');
    Route::post('/webhook', ['as' => 'webhook', 'uses' => 'BotController@Webhook']);

And this is my BotController : 

    <?php
    
    namespace App\Http\Controllers;
    
    use Longman\TelegramBot\Request;
    use Longman\TelegramBot\TelegramLog;
    use Longman\TelegramBot\Telegram;
    
    class BotController extends Controller
    {
        public $bot_api_key;
        public $bot_username;
        public $hook_url;
        public $commands_paths;
        public $prefix_table;
    
        function __construct ()
        {
            $this->bot_api_key    = env('BOT_TOKEN');
            $this->bot_username   = env('BOT_USERNAME');
            $this->prefix_table   = env('PREFIX_TABLE');
            $this->hook_url       = env('APP_URL') . env('HOOK_URL');
            $this->commands_paths = [
                app_path('Commands')
            ];
    
            TelegramLog::initErrorLog($this->commands_paths[0] . "/{$this->bot_username}_error.log");
            TelegramLog::initDebugLog($this->commands_paths[0] . "/{$this->bot_username}_debug.log");
            TelegramLog::initUpdateLog($this->commands_paths[0] . "/{$this->bot_username}_update.log");
    
        }
    
        public function setWebhook ()
        {
            try {
                // Create Telegram API object
                $telegram = new Telegram($this->bot_api_key, $this->bot_username);
    
                // Set webhook
                $result = $telegram->setWebhook($this->hook_url);
                if ($result->isOk()) {
                    echo $result->getDescription();
                }
            } catch (\Longman\TelegramBot\Exception\TelegramException $e) {
                // log telegram errors
                echo $e->getMessage();
            }
    
        }
    
        public function Webhook ()
        {
            try {
                // Create Telegram API object
                $telegram = new Telegram($this->bot_api_key, $this->bot_username);
    
                $telegram->addCommandsPaths($this->commands_paths);
    
                $mysql_credentials = [
                    'host'     => env('DB_HOST', 'localhost'),
                    'user'     => env('DB_USERNAME'),
                    'password' => env('DB_PASSWORD'),
                    'database' => env('DB_DATABASE'),
                ];
    
                $telegram->enableMySql($mysql_credentials, $this->prefix_table . '_');
    
                Request::setClient(new \GuzzleHttp\Client([
                    'base_uri' => 'https://api.telegram.org',
                    'verify'   => false
                ]));
    
                // Handle telegram webhook request
                $telegram->handle();
            } catch (\Longman\TelegramBot\Exception\TelegramException $e) {
                // Silence is golden!
                // log telegram errors
    				echo $e->getMessage();
            }
    
        }
    }

to run a **HTTPS** url that is required by telegram I'm using ngrok service that made a url like : **https://95881c89.ngrok.io**

but whenever I run https://95881c89.ngrok.io/setwebhook address I got this error : 

> Telegram returned an invalid response!

Note that telegram is blocked in my country but I use a global proxy for windows and *api.telegram.org* run in browser withu problem. 

I tried many solution like [this][3] but can not solve the problem. 

how can I help me to solve this problem ? 

  [1]: https://github.com/php-telegram-bot/core
  [2]: https://github.com/php-telegram-bot/core#instructions
  [3]: https://github.com/php-telegram-bot/core/pull/536

**Comment by noplanman** [comment]
What version of the bot are you using?

Are there any details in your debug logs?

Also, the way you set up the loggers is deprecated and should be set up using PSR-3, you can find an example here:
https://github.com/php-telegram-bot/core/blob/master/doc/01-utils.md#initialisation

**Comment by ahmadbadpey** [comment]
I'm using version "longman/telegram-bot": "^0.62.0".

I surly that `$this->hook_url = env('APP_URL') . env('HOOK_URL');)` is correct. 

this is result of call ` getWebhookInfo`:


```
{
"ok": true,
"result": {
"url": "https://2f4d7ba0.ngrok.io/webhook",
"has_custom_certificate": false,
"pending_update_count": 23,
"last_error_date": 1590218680,
"last_error_message": "Wrong response from the webhook: 419 unknown status",
"max_connections": 40
}
}
```

**Comment by jacklul** [comment]
> `Wrong response from the webhook: 419 unknown status`

You might have CSRF verification enabled for bot routes, you should disable them.
https://github.com/botman/botman/issues/1090#issuecomment-565814144
