### ISSUE TITLE
New member in the channel

### ISSUE THREAD

**Issue by farmaworld** [php-telegram-bot/core#1103]
How can I query the bot to find out if a new user has joined the channel?

**Comment by asafov** [comment]
[See this example](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/NewchatmembersCommand.php)

**Comment by jacklul** [comment]
> [See this example](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/NewchatmembersCommand.php)

This might not work, [documentation](https://core.telegram.org/bots/api#message) does not state anything about channels.


new_chat_members | Array of User | Optional. New members that were added to the group or supergroup and information about them (the bot itself may be one of these members)
-- | -- | --

**Comment by farmaworld** [comment]
yes i see that command
but user_id is admin user id, my?
because i don't now the user_id of new user
thanks

**Comment by jacklul** [comment]
AFAIK there is no way to do this I think

**Comment by farmaworld** [comment]
if i get information about database?

**Comment by jacklul** [comment]
You can't get this information through **new_chat_members**, you can only check if specific user is member of the channel using **getChatMember** method I mentioned.

**Comment by farmaworld** [comment]
But a TG bot api with admin rights can see all its members. So even if the api doesn’t support it, it can track a count and see if it increases and then know that a new member joined. Correct?

**Comment by jacklul** [comment]
Can't be done with bot API, [can be done with regular API](https://stackoverflow.com/questions/33844290/how-to-get-telegram-channel-users-list-with-telegram-bot-api).
