### ISSUE TITLE
Execute callbackquery by code!

### ISSUE THREAD

**Issue by WISTFUL12** [php-telegram-bot/core#1104]
Is it possible to executing a callbackquery by code instead of sending it by user throught InlineKeyboard?

Any thing like this:
```
$this->executeCallback([
    'from' => $user,
    'data' => 'comment_delete_765'
]);
```
Instead of this:
```
new InlineKeyboard([
    ['text' => 'Delete Comment', 'callback_data' => 'comment_delete_765'],
])
```

**Comment by asafov** [comment]
You can use helpers for put shared functions to it.

**Comment by jacklul** [comment]
You should play with something like this:

```php
(new CallbackQuery([
'id' => '99999999999',
'from' => $this->getMessage()->getFrom(),
'message' => $this->getMessage(),
'data' => 'comment_delete_765',
]))->execute();
```

**Comment by WISTFUL12** [comment]
I get this error:

```
Error - Cannot use object of type Longman\TelegramBot\Entities\Message as array;
File: /xxx/vendor/longman/telegram-bot/src/Entities/Entity.php; Line: 42; Time: 10:25:35 / 02.06.2020;
```

**Comment by jacklul** [comment]
> I get this error:
> 
> ```
> Error - Cannot use object of type Longman\TelegramBot\Entities\Message as array;
> File: /xxx/vendor/longman/telegram-bot/src/Entities/Entity.php; Line: 42; Time: 10:25:35 / 02.06.2020;
> ```

Try with `'message' => (array)$this->getMessage(),`

**Comment by WISTFUL12** [comment]
> Try skipping 'message' field completly - remove if from array, if it doesn't work:
> Try with `'message' => (array)$this->getMessage(),` or maybe `'message' => json_decode(json_encode($this->getMessage()), true),`

Issue solved by `'message' => (array)$this->getMessage()` !  thank you for your answers ....
