### ISSUE TITLE
get message related to InlineKeyboardButton telegram bot after touch it

### ISSUE THREAD

**Issue by ahmadbadpey** [php-telegram-bot/core#1109]
I have a command to get some suggestion/criticism in some specific categories that are shown as some InlineKeyboardButton. first user touch one of them and then should be send a simple text as suggestion/criticism. 

this is my command: 

    class SuggestionCommand extends SystemCommand
    {
        protected $name        = 'suggestion';                     // Your command's name
        protected $description = 'Suggestion Command';             // Your command description
        protected $usage       = '/suggestion';                    // Usage of your command
        protected $version     = '1.0.0';                          // Version of your command
    
        public function execute()
        {
            $inlineKeyboard = new InlineKeyboard([]);
    
            $inlineKeyboard->addRow(new InlineKeyboardButton([
                'text'          => 'Sellers',
                'callback_data' => 'suggestion_sellers'
            ]), new InlineKeyboardButton([
                'text'          => 'Products',
                'callback_data' => 'suggestion_products'
            ]));
    
    
            $chat_id = $this->getMessage()->getChat()->getId();
    
            $data = [
                'chat_id'      => $chat_id,
                'text'         => 'In which of the following areas is your suggestion / criticism: ',
                'reply_markup' => $inlineKeyboard
            ];
    
            return Request::sendMessage($data);
        }
    }

 What I want to do is do that is when user enter his text I want to recognize which button is touched in The previous step because I want to do other actions based on that button. 

is there any way to do that?

**Comment by jacklul** [comment]
`CallbackQueryCommand`

**Comment by ahmadbadpey** [comment]
@jacklul 
I don't think you understood what I meant.

I can recognize touched inline Button . but my problem is that when user enter some text and I want to know which button is touched before that

**Comment by jacklul** [comment]
Start a conversation after the button is pressed and insert which button was pushed into notes.

**Comment by ahmadbadpey** [comment]
@jacklul 
Can you help me more for that. I'm confused how and when can I start conversation.

**Comment by jacklul** [comment]
Good starter: https://github.com/php-telegram-bot/example-bot/blob/master/Commands/GenericmessageCommand.php#L65
