### ISSUE TITLE
I have a bot problem that does not work

### ISSUE THREAD

**Issue by samaup2** [php-telegram-bot/core#1110]
Hello, the web hook is made for the domain and the bot does not respond

Longman\TelegramBot\Exception\TelegramException: Input is empty! in /var/www/html/source/core/src/Telegram.php:379 Stack trace: #0 /var/www/html/Brainy/webhook.php(15): Longman\TelegramBot\Telegram->handle() #1 {main}

**Comment by asafov** [comment]
Show your webhook url, that you set in telegram API.

**Comment by samaup2** [comment]
https://api.telegram.org/bot1266730125:AAEe_kKQH0YauGJh_g3dhLPtndvGG-bPrmg/setwebhook?url=https://sbotele.com/Brainy/webhook.php

**Comment by samaup2** [comment]
> اعرض عنوان urlhh الخاص بك ، الذي قمت بتعيينه في telegram API.

https://api.telegram.org/bot1266730125:AAEe_kKQH0YauGJh_g3dhLPtndvGG-bPrmg/setwebhook?url=https://sbotele.com/Brainy/webhook.php

**Comment by jacklul** [comment]
@samaup2 you posted your bot token publicly, you should generate new one ASAP, always remove it from anything you post.

**Comment by samaup2** [comment]
> @ samaup2 قمت بنشر رمز الروبوت الخاص بك علنًا ، يجب عليك إنشاء رمز جديد في أسرع وقت ممكن ، وإزالته دائمًا من أي شيء تنشره.
{"ok":true,"result":true,"description":"Webhook was set"}

**Comment by asafov** [comment]
Webhook should not respond anything by direct request to url from browser.
What you mean under "bot does not respond"? Show your webook.php file (Without tokens!!!)

**Comment by samaup2** [comment]
> يجب ألا يستجيب Webhook لأي شيء عن طريق طلب مباشر لعنوان URL من المتصفح.
> ماذا تقصد تحت عنوان "البوت لا يستجيب"؟ إظهار ملف webook.php الخاص بك (بدون الرموز المميزة !!!)

<?php

require '/var/www/html/source/core/vendor/autoload.php';
use Longman\TelegramBot\Commands;
$API_KEY = '';
$BOT_NAME = '';
$commands_path = "/var/www/html/Commands/";

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);
    $telegram->enableBotan('');
    $telegram->addCommandsPath($commands_path);
    // Handle telegram webhook request
    $telegram->handle();

} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // Silence is golden!
    // log telegram errors
    echo $e;
}

**Comment by asafov** [comment]
1. Botan don't work anymore.
2. Did you create any commands for test bot? How you test it?

**Comment by samaup2** [comment]
<?php

require '/var/www/html/source/core/vendor/autoload.php';
use Longman\TelegramBot\Commands;
$API_KEY = '';
$BOT_NAME = '';
$commands_path = "/var/www/html/Commands/";

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);
    $telegram->enableBotan('');
    $telegram->addCommandsPath($commands_path);
    // Handle telegram webhook request
    $telegram->handle();

} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // Silence is golden!
    // log telegram errors
    echo $e;
}

**Comment by samaup2** [comment]
```
<?php

require '/var/www/html/source/core/vendor/autoload.php';
use Longman\TelegramBot\Commands;
$API_KEY = '';
$BOT_NAME = '';
$commands_path = "/var/www/html/Commands/";

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);
    $telegram->enableBotan('');
    $telegram->addCommandsPath($commands_path);
    // Handle telegram webhook request
    $telegram->handle();

} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // Silence is golden!
    // log telegram errors
    echo $e;
}

```

**Comment by asafov** [comment]
Do you have any commands created at /var/www/html/Commands?

**Comment by samaup2** [comment]
> هل لديك أي أوامر تم إنشاؤها على / var / www / html / Commands؟

Yes, there are commands in a file

**Comment by asafov** [comment]
Okey. I defined webhook. Do you have StartCommand?
What happens when you send /start to your bot?

**Comment by samaup2** [comment]
Yes I have a StartCommand file
The bot is not receiving orders

**Comment by asafov** [comment]
What you mean under "orders"? You understand, that it's no any data for analyze where is your error.
Show StartCommand.

**Comment by samaup2** [comment]
How to solve the problem of the appearance of error
https://sbotele.com/Brainy/webhook.php

**Comment by asafov** [comment]
webhook.php SHOULD NOT RESPONSE ANYTHING BY REQUEST VIA BROWSER!
This file will be request by telegram api server on each message sended to your bot!
Seems that you don't understand how it works.

**Comment by samaup2** [comment]
The bot does not work yet. There is an image
![photo_2020-06-13_09-51-58](https://user-images.githubusercontent.com/66838118/84562257-bd6eb600-ad5b-11ea-9924-aa1e2da8d6dd.jpg)

**Comment by asafov** [comment]
Show your StartCommand.

**Comment by samaup2** [comment]
<?php
namespace Longman\TelegramBot\Commands\SystemCommands;
use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Entities\InlineKeyboard;
use Longman\TelegramBot\Entities\InlineKeyboardButton;
/**
 * Start command
 */
class SetCommand extends SystemCommand{
    protected $name = 'set';
    protected $description = 'Start command';
    protected $usage = '/set';
    protected $version = '1.1.0';
    // data before _ in callback query data => actual command
    public static $menuSet = [-----------
    ];
    /**
     * Command execute method
     */
    public function execute(){
      $message      = $this->getMessage();
      $getMessageId = $message->getMessageId();
      $chat_id      = $message->getChat()->getId();
      $form_id      = $message->getFrom()->getId();
      $Activate     = $this->Redis->get("db9:gr:$chat_id");
      if(!$Activate){
        return Request::emptyResponse();
      }
      $Setting = $this->getAllSettings($chat_id); // Get all Settings id Group
      $Admins  = $this->getAdmins($form_id, $chat_id);
      $allSilent = $this->Redis->get("db9:allSilent:$chat_id");
      if($allSilent and $Admins != true and $form_id != ------and $form_id != ------){
        return Request::deleteMessage(['chat_id' => $chat_id,'message_id'=> $getMessageId]);
      }
      if($Setting['oneSilent'] == 2 and $Admins != true and $form_id != 1266730125 and $form_id != 159722265){
         return Request::deleteMessage(['chat_id' => $chat_id,'message_id'=> $getMessageId]);
      }
      $Forward = $message->getForwardFrom();
      if($Setting["forbidden"] == 2){
        if($Setting["forForward"] == 2 and $Forward == true){
          return Request::deleteMessage(['chat_id' => $chat_id,'message_id'    => $getMessageId]);
        } // Forbidden
      }
      $getFirstName = $message->getChat()->getFirstName();
      $getText      = $message->getText();
      $getTitle     = $message->getChat()->getTitle();
      // $getStatus = $this->getCreator($chat_id);
      $getType      =  $message->getChat()->getType();
      $getAdmins    = $chat_id;
      if($getType == 'supergroup'){
        // Check Creator And Admins
        $Admins    = $this->ModeratorsAll($form_id, $chat_id);
        $AdminsOne = $this->ModeratorsAllOne($form_id, $chat_id);
        if($Admins == true or $AdminsOne == true){

          $I = new InlineKeyboard([]);----------------
          $I->addRow($One1, $Three3);

          $Text = $this->sLang('menu_set');
          Request::sendMessage([
            'chat_id'      => $chat_id,
            'message_id'   => $getMessageId,
            'text'         => $Text,
            'reply_markup' => $I,
          ]);
        }// Check Creator And Admins
      }//$getType
    }

}

**Comment by asafov** [comment]
Format code please. It's unreal to read.

**Comment by samaup2** [comment]
protected $version = '1.1.0';

**Comment by asafov** [comment]
You are kidding me?)
https://pastebin.com/
Paste code here and give me link for review.

**Comment by samaup2** [comment]
https://pastebin.com/q33bZHwq
