### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by andrtechno** [php-telegram-bot/core#1113]
getCommandObject() I think you should look away ReflectionClass

**Comment by andrtechno** [comment]
Request::editMessageReplyMarkup

started issuing
_message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message_


at 0.62.0 is ok

**Comment by jacklul** [comment]
> Request::editMessageReplyMarkup
> 
> started issuing
> _message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message_
> 
> at 0.62.0 is ok

This is reply from the API everytime you invoke 'edit' method but send the same content as the original message, you have to adjust your code for this.

**Comment by andrtechno** [comment]
reply_markup different...
in ver. 0.62.0 is ok

https://www.youtube.com/watch?v=mPhaGgyagXY

**Comment by andrtechno** [comment]
```
parse_str($callback_data, $params);
$this->telegram->setCommandConfig('catalog', [
    'id' => $params['id']
]);
return $this->telegram->executeCommand('catalog');
```

CatalogCommand do not get 'id' => $params['id']

**Comment by andrtechno** [comment]
```
public function executeCommand($command)
    {
        $command = mb_strtolower($command);
        if (isset($this->commands_objects[$command])) {
            $command_obj = $this->commands_objects[$command];
        } else {
            $command_obj = $this->getCommandObject($command);
        }
....
}
```
the problem is here $this->commands_objects, for some reason I don’t want to work with him

**Comment by andrtechno** [comment]
in general, it all came down to the fact that it was necessary to redesign the project, I had teams separately, and others ..

I also have my Command.php, SystemCommand.php, UserCommand.php, something like this is missing


Telegram.php example

```
const SYSTEM _NS_COMMAND = 'my\\ns\\SystemCommand ';
const АДМИН_NS_COMMAND = 'my\\ns\\AdminCommand ';
const USER_NS_COMMAND = 'my\\ns\\UserCommand ';

getCommandObject(){

                switch ($auth) {
                    case 'System':
                        if ($command_obj instanceof self::SYSTEM _NS_COMMAND) {
                            return $command_obj;
                        }
                        break;
....
                }
}
```

**Comment by noplanman** [comment]
@andrtechno As long as your own `SystemCommand` (and the others) extends the ones from the library, it should work, as the `instanceof` check should be true.

Strange that the new code to get the command doesn't work for you. I have a feeling something else is bugged, as the `commands_objects` array is filled with command objects that are found within the custom command folders. So not sure why it's breaking for you.

Have you managed to debug this and find out why the commands aren't loaded correctly?

**Comment by andrtechno** [comment]
@noplanman works with such a code
```
class MyTelegram extends \Longman\TelegramBot\Telegram
{

    public function getCommandObject($command, $filepath = null)
    {
....

        foreach ($which as $auth) {

.....

            if (class_exists($command_class)) {
                $command_obj = new $command_class($this, $this->update);

                switch ($auth) {
                    case 'System':
                        if ($command_obj instanceof My\ns\SystemCommand) {
                            return $command_obj;
                        }
                        break;

                    case 'Admin':
                        if ($command_obj instanceof My\ns\AdminCommand) {
                            return $command_obj;
                        }
                        break;

                    case 'User':
                        if ($command_obj instanceof My\ns\UserCommand) {
                            return $command_obj;
                        }
                        break;
                }
            }
        }

        return null;
    }


    public function executeCommand($command)
    {

        $command = mb_strtolower($command);
        //if (isset($this->commands_objects[$command])) {
        //    $command_obj = $this->commands_objects[$command];
        //} else {
            $command_obj = $this->getCommandObject($command);
        //}

 ......
    }

}
```

I had to redo the project to make it work
and move the command folder to another location

**Comment by noplanman** [comment]
@andrtechno Are you able to test the latest develop branch for your project?

Would be great if a rewrite of the Telegram class (as you're doing it) wouldn't be necessary.
