### ISSUE TITLE
back to previous step in a conversation via a keyboard button in current step

### ISSUE THREAD

**Issue by ahmadbadpey** [php-telegram-bot/core#1116]
I want to add a "back" button in beginning of keyboard button that is shown in each step of a conversation. when user touch that button Will be returned to exactly prev step conversation. 

I added an else if block With the content you see that sets `$notes['state']` value to prev step index:
```
//State machine
//Entrypoint of the machine state if given by the track
//Every time a step is achieved the track is updated
switch ($state) {
    case 0:
        if ($text === '') {
            $notes['state'] = 0;
            $this->conversation->update();

            $data['text']         = 'Type your name:';
            $data['reply_markup'] = Keyboard::remove(['selective' => true]);

            $result = Request::sendMessage($data);
            break;
        }

        $notes['name'] = $text;
        $text          = '';

    // no break
    case 1:
        if ($text === '') {
            $notes['state'] = 1;
            $this->conversation->update();

            $keyboard = new Keyboard(
                ['⬅ Back'],
                ['item1','item2','item3' ]
            );

            $keyboard
                ->setOneTimeKeyboard(true)
                ->setResizeKeyboard(true);

            $data['reply_markup'] = $keyboard;

            $result = Request::sendMessage($data);
            break;
        } else if ($text === '⬅ Back'){
            $notes['state']  =   0;
            $this->conversation->update();
            break;
        }

        $notes['surname'] = $text;
        $text             = '';

            // no break
```

**Comment by noplanman** [comment]
Hi @ahmadbadpey, what is your question exactly? Does the code you have not work then?

**Comment by ahmadbadpey** [comment]
@noplanman 
no does not work and What I expect will not happen.is correct content of that else if block?

**Comment by asafov** [comment]
I recomment you to use inline buttons for this feature.
It more stable for do things like this.
So at "Back" button will be callback for function, which will update state of conversation and call first switch statement.

**Comment by noplanman** [comment]
Code seems right. Please check in the database to see if the state is changed.
You aren't sending any new message in that `else` block, so the bot isn't sending anything back to the user.

**Comment by noplanman** [comment]
@ahmadbadpey Any update here?
