### ISSUE TITLE
DB schema update scripts

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/core#112]
Having update scripts for the database schema will make it a lot easier to make sure that the correct structure is being used and no errors happen.

For this we need to save the current database schema version somewhere in the database, which we can do by adding an extra table, e.g. `options`. For the future, we could also use this table to save options, like the bot name and API key for example.

**Comment by MBoretto** [comment]
Will come with monolog feature
https://github.com/akalongman/php-telegram-bot/issues/167

**Comment by noplanman** [comment]
@MBoretto 
This issue here is about DB update scripts that simply update the schema depending on the library version. It's different to the "import all data" that you have implemented with the Monolog PR.

The problem is, that users who haven't logged all the requests, will have the same problem every time the schema is changed, because they can't just reimport everything 😕

**Comment by MBoretto** [comment]
ok

**Comment by noplanman** [comment]
Right, I'm at a stage where foreign key constraints are not my best friends 😄 

Check out my work so far here:
https://github.com/noplanman/php-telegram-bot/tree/db_schema_update/utils/db-schema-update

This script automatically:
- fetches all tags from the live repo
- imports and dumps each structure.sql
- compares them for changes
- creates a migration script for any changes
- applies the migration to a test database

It starts at version 0.16.0, as anything before then is very shaky and unstable.
This migration works perfectly when starting with a DB at version 0.16.0, but has issues when starting the migration at any version in between.

Reason for this: *drumroll...* **key constraints**!

So I'm in the process of trying to figure out how best to solve this. The problem is, that each time a foreign key is set without explicitly setting a constraint name (via `ADD CONSTRAINT \`<this-name!>\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\` (\`id\`);`), a new one with an auto-incremented name is generated (`message_ibfk_1`, `message_ibfk_2`, etc.).
Because of this, as the migration proceeds, some get removed and re-added, thus making the number go up. So when starting the process somewhere in between, the numbers are wrong, causing issues (e.g. `Duplicate foreign key constraint name 'tmp/message_ibfk_X'`).

I'm really working towards a fully automated way of handling this, but it's becoming more and more complex and I'm not sure it's worth it 😕 

I might just leave this as is and make dedicated migration scripts manually...

As for any new structure changes, with each change, a migration script is a **MUST**, to prevent this mess.

What do you think? Any thoughts or ideas?

**Comment by Sogl** [comment]
What about adding a small ORM and stop using FK?

**Comment by noplanman** [comment]
> small ORM

Do you have any in mind? Changing and upgrading the database layer is a todo item that has been around for a while, but nobody has found the time yet to think it through and implement it.

As for the migration process, even with a newly designed DB layer, updating to the "new" system will still be very painful. For that reason, some kind of migration scripts need to be made.

I'm looking into https://github.com/robmorgan/phinx, which looks really nice and easy and does the job.
@Sogl Do you have any experience with migrations that might help?

**Comment by Sogl** [comment]
I work with Zend_DB and Laravel Eloquent ORMs and all my projects not using FK now. 

Good migration mechanism is present in Laravel and it works with CLI by command `php artisan migrate`.
That's how it looks in folder structure:

![image](https://cloud.githubusercontent.com/assets/7556290/24939378/ab409fe8-1f88-11e7-8b8b-f5597e43afe4.png)


One migration code:
```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTestPositionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('testPositions', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('positionId')
                ->unsigned()->nullable();
            $table->string('positionName', 255)
                ->nullable();
            $table->integer('testId')
                ->unsigned()->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('testPositions');
    }
}
```

It seems that Phinx do the same thing, but it contains only migrations, no ORM part.
Also you need to link migrations with `php-telegram-bot` versions.

**Comment by MBoretto** [comment]
@Sogl I think that add a orm is a very good idea. I learned few month ago to use Eloquent  and migration. Implements it requires a bit of time since the table schema is made of several table.
For what concern removing foreign keys is absolutely a bad idea. Foreign keys are database internal check to ensure integrity.

**Comment by noplanman** [comment]
I agree with @MBoretto to keep the foreign keys, as they force the DB to stay "valid".

It would be great to have statistics of how many users have old versions of the bot running, to know if it even makes sense to make fully automated DB update scripts up to this point.
For the future (fingers crossed) when we have an ORM doing the heavy lifting, migrations should be a breeze.

The only ORM I've worked with is [RedBean](https://github.com/gabordemooij/redbean/), but am more than happy to learn anything new that does a great job 🎉

**Comment by noplanman** [comment]
At the moment the easiest is to create manual update scripts for any DB changes necessary from release to release.

https://github.com/php-telegram-bot/core/tree/master/utils/db-schema-update
