### ISSUE TITLE
Command Aliases

### ISSUE THREAD

**Issue by hasbi204** [php-telegram-bot/core#1120]
How to create Command Aliases? For Example I have Command /register. Then these commands can be run using Alias: REGISTER NOW?

**Comment by noplanman** [comment]
You can catch the `REGISTER NOW` text in `GenericmessageCommand` and then execute the `/register` command from there, like this:

```php
// GenericmessageCommand.php
public function execute(): ServerResponse
{
    if ($this->getMessage()->getText(true) === 'REGISTER NOW') {
        return $this->getTelegram()->executeCommand('register');
    }
}
```

**Comment by hasbi204** [comment]
Solved. thank you very much sir 🙏
