### ISSUE TITLE
Sendtochannel command does not ask needed information and not send any message

### ISSUE THREAD

**Issue by disu** [php-telegram-bot/core#1121]
#### Required Information

| Operating system          | Windows 10
| PHP Telegram Bot version  | 0.62.0
| PHP version               | 7.3.11
| MySQL version             | 5.6.33
| Update Method             | Webhook
| Self-signed certificate   | no

#### Summary

I have setted up my public channel by adding bot to its administrators, enabling admins and adding channel to your_channel parameter (trying with channel name and channel id).
When I call /sendtochannel without parameters I expect that the bot ask me the channel id or its name.
Instead I receive always this message:

```
Message will look like this:
text testchannel
Would you like to post it?
Type Yes or No
```

Same result if I call command adding channel name as first parameter.
Why command does not ask my information needed with prompt messages? How can I make it work?
Note, I've tried calling directly the Telegram API and it send the channel message correctly.

**Comment by noplanman** [comment]
Hi @disu 

It seems like you're in the middle of a command 🤔 

Copy the [example `/cancel` command](https://github.com/php-telegram-bot/example-bot/blob/a388d2b62c19adc294d64805e053a706b463beec/Commands/CancelCommand.php) to your custom commands and send `/cancel` to your bot to stop any active conversation, then try again with `/sendtochannel`.
You are correct, that the bot should present a keyboard with any channels saved in the config, and allow you to enter any ID as text.

**Comment by disu** [comment]
> Hi @disu
> 
> It seems like you're in the middle of a command 🤔
> 
> Copy the [example `/cancel` command](https://github.com/php-telegram-bot/example-bot/blob/a388d2b62c19adc294d64805e053a706b463beec/Commands/CancelCommand.php) to your custom commands and send `/cancel` to your bot to stop any active conversation, then try again with `/sendtochannel`.
> You are correct, that the bot should present a keyboard with any channels saved in the config, and allow you to enter any ID as text.

It is correct and now, cancelling the conversation, I'm able to see the channel list as saved in the config. But selecting my channel (in which my bot is administrator) nothing happened; i received no other messages or prompt.

**Comment by noplanman** [comment]
Right. Have you copied the necessary code to your `GenericmessageCommand.php` file to handle conversations?

https://github.com/php-telegram-bot/example-bot/blob/a388d2b62c19adc294d64805e053a706b463beec/Commands/GenericmessageCommand.php#L64-L73

**Comment by disu** [comment]
> Right. Have you copied the necessary code to your `GenericmessageCommand.php` file to handle conversations?
> 
> https://github.com/php-telegram-bot/example-bot/blob/a388d2b62c19adc294d64805e053a706b463beec/Commands/GenericmessageCommand.php#L64-L73

Perfect! Now it works!
I didn't find any documentation about this necessary change in GenericmessageCommand.php...

**Comment by noplanman** [comment]
Ah, right! I'll add an entry to the `SurveyCommand.php` example file, thanks for letting me know 👍
