### ISSUE TITLE
How to make Seamless Telegram Login

### ISSUE THREAD

**Issue by ivioninjs** [php-telegram-bot/core#1123]
hello!
help me please make '[Seamless Telegram Login](https://core.telegram.org/api/url-authorization)' 

I want to make authorization my website using Seamless telegram login https://core.telegram.org/bots/api#loginurl
But, in my telegram' bot don't show popup window for login like this https://core.telegram.org/file/811140015/1734/8VZFkwWXalM.97872/6127fa62d8a0bf2b3c
What should I do?
Please help me.

I used - firebase functions, telegraf.js, vuejs

This my code:
Telegraf.js

```
const Telegraf = require('telegraf')
const Extra = require('telegraf/extra')
const Markup = require('telegraf/markup')
const functions = require('firebase-functions')

const bot = new Telegraf(functions.config().telegram.bot)

const keyboard = Markup.inlineKeyboard([
  Markup.loginButton('Login', 'https://my-domain.app', {
    bot_username: 'my_bot',
    request_write_access: 'true'
  })
])

bot.start((ctx) => ctx.reply('Hello', Extra.markup(keyboard)))

bot.on('sticker', ctx => ctx.reply('👍'))

bot.catch((err, ctx) => {
  console.log(`Ooops, encountered an error for ${ctx.updateType}`, err)
})

exports.bot = functions
  .region('us-central1')
  .https.onRequest(
    (req, res) => bot.handleUpdate(req.body, res).then(rv => !rv && res.sendStatus(200))
  )
V
```ue.JS

```
mounted(){
    const script = document.createElement('script')
    script.async = true
    script.src = 'https://telegram.org/js/telegram-widget.js?3'
    script.setAttribute('data-size', 'large')
    script.setAttribute('data-userpic', this.userpic)
    script.setAttribute('data-telegram-login', 'my_bot')
    script.setAttribute('data-request-access', 'read')
    window.onTelegramAuth = this.onTelegramAuth
    script.setAttribute('data-onauth', 'window.onTelegramAuth(user)')

    this.$refs.telegram.appendChild(script)
},
methods: {
    onTelegramAuth(user) {
       console.log('welcome', JSON.stringify(user))
     }
  }
```

Sorry my bad english :((

**Comment by jacklul** [comment]
Wrong repository, you're looking for https://github.com/telegraf/telegraf
