### ISSUE TITLE
0.62 -> 0.63 – Syntax error near 'CONSTRAINT `message_ibfk_6`'…

### ISSUE THREAD

**Issue by 0xEAB** [php-telegram-bot/core#1125]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | CentOS 7
| PHP Telegram Bot version  | 0.63.1
| PHP version               | 7.3.21
| MySQL version             |  5.5.5-10.1.29-MariaDB

#### Summary

Migration script produces the following error:
```
(1064): Syntax error near 'CONSTRAINT `message_ibfk_6`' 
```

#### How to reproduce

Run the v0.63 migration script on a v0.62 DB.

#### Expected behaviour

Migration script just works.

**Comment by noplanman** [comment]
@0xEAB Thanks for reporting.

This may have to do with earlier MySQL versions having a different syntax for removing foreign key constraints.

Try with this and let me know if that works please:
```mysql
ALTER TABLE `message`
    DROP FOREIGN KEY IF EXISTS `message_ibfk_6`,
    DROP INDEX IF EXISTS `message_ibfk_6`;
```

**Comment by 0xEAB** [comment]
thanks, working fine here
