### ISSUE TITLE
How Can I generate fake service message in Groups/Channel?

### ISSUE THREAD

**Issue by hshahbodaghkhan** [php-telegram-bot/core#1134]
Hi everyone.
How can I create a fake service message in Channels/Groups such as channel/group creation date?

**Comment by jacklul** [comment]
You can't, those are created by Telegram.

**Comment by hshahbodaghkhan** [comment]
> 
> 
> You can't, those are created by Telegram.

Can I edit them?

**Comment by Hitmare** [comment]
> > You can't, those are created by Telegram.
> 
> Can I edit them?

No you can't. You can only delete Service Messages
