### ISSUE TITLE
Inline button link to command

### ISSUE THREAD

**Issue by CashCode** [php-telegram-bot/core#1144]
Hello everybody!

Is there any way to click old inline button, when my session is on another command and it will be executed by an old command?

Also, is there any way to link keyboard button with command? I mean inline text to /command, I made it by myself in telegram class, but I think there is standartway or should I pull request it?

And what is the standart way to use chains, I mean chain of messages and answers, inline keyboard selects?
I use state in notes field and so on, it's good practice?

Thanks.

**Comment by noplanman** [comment]
There's a few questions here, for the future it's better to create an issue for each one 😉 

> Is there any way to click old inline button, when my session is on another command and it will be executed by an old command?

You will need to manually check the value of a callback from the inline keyboard button and route it to the new code. It might make sense to then also edit the current message and update the inline keyboard buttons.

> Also, is there any way to link keyboard button with command? I mean inline text to /command, I made it by myself in telegram class, but I think there is standartway or should I pull request it?

There are quite a few issues about this already, try the search:
https://github.com/php-telegram-bot/core/issues?page=1&q=inline+command

> And what is the standart way to use chains, I mean chain of messages and answers, inline keyboard selects?
I use state in notes field and so on, it's good practice?

There are different ways to solve this. In the `survey` command example we use normal messages with a state, but using inline keyboard buttons you could add the state to the callback data itself and handle it accordingly. Of course it depends how complex your conversation flow (or chain) is, but it sure does make sense to split up your command into different methods that can then be called separately depending on the state your conversation is in.

**Comment by pooriamo** [comment]
@noplanman Hi. I'm looking for SurveyCommand.php but I can't find it. I'm going crazy!

**Comment by noplanman** [comment]
@pooriamo You can find it in the example-bot repo here:
https://github.com/php-telegram-bot/example-bot

**Comment by pooriamo** [comment]
@noplanman Oh thanks. I was totally lost :)))
