### ISSUE TITLE
add jpgraph

### ISSUE THREAD

**Issue by imidazil** [php-telegram-bot/core#1145]
#### Summary

how can i add the jpgraph class? Sorry for my English :-(

- jpgraph/jpgraph.php

**Comment by noplanman** [comment]
I assume you're talking about this?
https://packagist.org/packages/amenadiel/jpgraph

When you `Stroke()` your graph, you can add an extra parameter to save it to a file, like `$graph->Stroke('/path/to/graph')`.
Then you can send that file using `Request::sendPhoto(['chat_id' => $chat_id, 'photo' => '/path/to/graph'])`.

Hope that helps!

(I'll close off here, as this is question is not directly related to the library.)

**Comment by imidazil** [comment]
I solved. Thanks :-)
