### ISSUE TITLE
How to use kickchatmember?

### ISSUE THREAD

**Issue by andreybolonin** [php-telegram-bot/core#1148]
Hello everyone, 
any example to use https://core.telegram.org/bots/api#kickchatmember inside this telegram-bot ?

**Comment by noplanman** [comment]
You can use the `Request::kickChatMember()` method, like this, using the respective chat and user ID to kick:

```php
use Longman\TelegramBot\Request;

Request::kickChatMember([
    'chat_id' => $chat_id,
    'user_id' => $user_id,
]);
```

**Comment by andreybolonin** [comment]
@noplanman any example ho to send request to telegram API by cron job?

**Comment by noplanman** [comment]
You can see how i do it for the support bot here:
https://github.com/php-telegram-bot/support-bot/blob/b69792c7164f9fa7e38354dd87425f506810e909/cron.php

Basically set up the `$telegram` object with all necessary options and DB connection (if required) and then execute whatever you want 👌
