### ISSUE TITLE
no error log file is written to disk

### ISSUE THREAD

**Issue by derived-coder** [php-telegram-bot/core#1151]
### 🐞 Bug Report

No error log file is created.
I enabled log like this in the `hook.php`

```
 Longman\TelegramBot\TelegramLog::initialize(
       new Monolog\Logger('telegram_bot', [
           (new Monolog\Handler\StreamHandler($config['logging']['debug'], Monolog\Logger::DEBUG))->setFormatter(new Monolog\Formatter\LineFormatter(null, null, true)),
           (new Monolog\Handler\StreamHandler($config['logging']['error'], Monolog\Logger::ERROR))->setFormatter(new Monolog\Formatter\LineFormatter(null, null, true)),
       ]),
       new Monolog\Logger('telegram_bot_updates', [
           (new Monolog\Handler\StreamHandler($config['logging']['update'], Monolog\Logger::INFO))->setFormatter(new Monolog\Formatter\LineFormatter('%message%' . PHP_EOL)),
       ])
    );
```
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | linux
| PHP Telegram Bot version  | 0.64
| PHP version               | php-7.3.25
| MySQL version             |  / none
| Update Method             | Webhook 
| Self-signed certificate   | yes 
| RAW update (if available) | `{...}`

#### Current behaviour

No error log is written

#### How to reproduce

Use the example bot. Create an invalid response command.
use the hook approach.

enable logging files, see code above and in the config:
```
  // Logging (Debug, Error and Raw Updates)
     'logging'  => [
         'debug'  => __DIR__ . '/php-telegram-bot-debug.log',
         'error'  => __DIR__ . '/php-telegram-bot-error.log',
         'update' => __DIR__ . '/php-telegram-bot-update.log',
     ],
```

#### Expected behavior

log file is written to disk

**Comment by noplanman** [comment]
@derived-coder Your config looks ok.

Just to be sure, you've put your code **before** the `$telegram->handle();` call, right?

Do you see the `*update.log` created when the bot receives an update?

**Comment by derived-coder** [comment]
Yes, it is before the `$telegram->handle();` I commented out your code basically.

yes, the update and debug log are written to file. but not error log.
Maybe no error happened. but I am sure I send some bad requests already out.
How can I force that an error happens and it will write it to the file?

**Comment by noplanman** [comment]
The logging does seem to be working then.

Errors are only logged for incoming updates, not requests you send.
You can test it in your command like `TelegramLog::error('does this work?');`

**Comment by derived-coder** [comment]
I can confirm, when I use this error statement it is working. The log is created.

**Comment by opravdin** [comment]
@derived-coder, I have the same issue, how did you fixed that?

**Comment by noplanman** [comment]
@opravdin Make sure you define the logging **before** handling the request:

Then, to log data, you can use the static methods provided by the `TelegramLog` class, e.g.:
```php
TelegramLog::error('Log some error here');
```

**Comment by opravdin** [comment]
@noplanman thank you for fast reply :)
Already tried that before: file have been created when I manually triggered ::error method, but nothing more have been written to log files. Also, I stuck with version 0.62 for now, maybe it'll be fine in newer versions.

**Comment by noplanman** [comment]
>  Do I understand correctly that exceptions that occur when executing commands should go into Error?

It depends if you want it to 😉 

Looking at the [example hook.php file](https://github.com/php-telegram-bot/example-bot/blob/c513b9c5d2f40793fb3853500d38ac25f9ef16c5/hook.php#L69), exceptions from the library are logged.
Check to make sure you're logging it correctly in the `catch` clause.

Also note that this catches *only* exceptions from the library itself (`Longman\TelegramBot\Exception\TelegramException`), so if you throw any custom exceptions in your code, make sure it's caught appropriately 😃 

Hope that helps!
