### ISSUE TITLE
How use a menu more times?

### ISSUE THREAD

**Issue by annuncispot** [php-telegram-bot/core#1153]
Hi,

i want use a menu, for example:

"Soccer Champions"
"Basket Champions"
"Sci Champions" 

when an user click on button "Soccer Champions" i show the first ten champions. 
After i want show again the menu, how can implement all this?

I've seen and tested this example: https://github.com/php-telegram-bot/example-bot/blob/master/Commands/Conversation/SurveyCommand.php and it works fine.

But it seems that there isn't possible to repeat the operations, as if the flow were single and not cyclical.

Can help me to understand?

Thanks

**Comment by noplanman** [comment]
When you send the message to the user, you can simply attach the menu again in the reply_markup field, like when you send the initial message.

**Comment by annuncispot** [comment]
Ok, Thanks a lot. :-)
