### ISSUE TITLE
How connect an external database that contain values to extract?

### ISSUE THREAD

**Issue by annuncispot** [php-telegram-bot/core#1154]
Hi,

i've configured database connection and its works fine. 
Now i want extract values to show on telegram from a different database, that i've installed on same host. 
What is the best practice to use?

Thanks

**Comment by noplanman** [comment]
There is no fixed way to do this, so it's up to you!

Since you need to have PDO set up anyway to run this library, I'd suggest to just use that.

This should help you out:
https://phpdelusions.net/pdo

**Comment by annuncispot** [comment]
Ok, thanks.
