### ISSUE TITLE
sendPhoto, using url, not works on my wordpress website

### ISSUE THREAD

**Issue by annuncispot** [php-telegram-bot/core#1157]
I've tried to use sendPhoto with an url of image on Amazon and it works fine.
But if i use an image present on my wordpress website it doesn't work.

What could be?

**Comment by noplanman** [comment]
Are you using a relative path to the file or the actual URL to the image?

**Comment by annuncispot** [comment]
I've tried with actual URL to the image

**Comment by noplanman** [comment]
This would indicate that the Telegram servers cannot access the path to your image.

Are you sure it's publicly accessible?
Also ensure that you've set the `https://` address correctly.

**Comment by annuncispot** [comment]
Great! It's wasn't pubblicly accessible. Now it's work. 
Thank you.
