### ISSUE TITLE
How hide box message text?

### ISSUE THREAD

**Issue by annuncispot** [php-telegram-bot/core#1159]
Hi,

how can i hide the box message text (image is in attachment) to avoid person insert text instead select one menu's voice?

I'm using this code:

 $keyboard = new Keyboard(['Mostrami il prossimo', 'Elenco Categorie', 'Torna al menù']);
 $keyboard->setOneTimeKeyboard(true)->setResizeKeyboard(true);
 $data['reply_markup'] = $keyboard;

Thanks
![1](https://user-images.githubusercontent.com/57658450/101283884-93afbc80-37dd-11eb-9b33-42f7e7e9a72e.png)

**Comment by noplanman** [comment]
As far as I know that isn't possible!

Basically, when a user clicks a keyboard button, it's as if they wrote that text as a message.

So if you want to prevent any other text, you'll need to filter / limit it to the values from your buttons.

**Comment by annuncispot** [comment]
Ok, thanks.
