### ISSUE TITLE
Downloading file on self-hosted bot API

### ISSUE THREAD

**Issue by zickkeen** [php-telegram-bot/core#1161]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Ubuntu 18.04
| PHP Telegram Bot version  | dev-master (for api Bot API 5.0 #1146, https://github.com/php-telegram-bot/core/pull/1147#issue-519457697)
| PHP version               | 7.3
| MySQL version             | 10.3.25-MariaDB
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary
Repair or adjustments are required regarding the technical download files in the "self-hosted bot API"

#### Current behaviour
The path pattern still applies to the api.telegram.bot server, while for self-hosted it will be in the path of telegram-bot-api work directory
https://github.com/php-telegram-bot/core/blob/fb55e78e980dfabef4bed606c2385f6897dd2d84/src/Request.php#L543

or custom url if we use http or https to serve file.

> The files are downloaded to bot's folder inside server's working directory. You need to set up your HTTPS server serve static files from subfolders of these folders. "/file/bot&lt;token>/path/file_id.ext" should be translated to a path "&lt;server's working directory>/&lt;token>/path/file_id.ext".
> 
> _Originally posted by @levlam in https://github.com/tdlib/telegram-bot-api/issues/59#issuecomment-744467794_

#### Expected behaviour

I think the custom path option is needed if we use the "self-hosted Bot API"

**Comment by noplanman** [comment]
After looking into this, i think the solution is that users who use a custom Bot API server must implement their own way of retrieving the files.

The `downloadFile` method you're referring to is a helper to fetch files from the Telegram server. When using a custom Bot API server, the files are already downloaded, so it's just a matter of accessing them from the folder.

In that sense, the `getFile` method returns the path and it doesn't need downloading, as it's already there.

Does that make sense?

**Comment by zickkeen** [comment]
Yes, I think so.
We need a custom location of path for the local api.
It also includes "local api and php-telegram-bot" on one machine, or a different machine.

**Comment by noplanman** [comment]
Right, for non-local it would require a custom URL, unless the server is properly set up to serve files according to the custom Bot API specification.

In that case, a simple variable to be set should suffice. Will take another deeper look at this 👍

**Comment by noplanman** [comment]
@zickkeen Please check out #1168. I appreciate any feedback 🙏
