### ISSUE TITLE
Custom command don't working in laravel (lumen)

### ISSUE THREAD

**Issue by maffinca69** [php-telegram-bot/core#1166]
I've been trying to create a team for 5 hours but can't. I do not know why
I am using Lumen (Laravel).
Adding custom commands to my controller of the __construct function:
```
$this->telegram = new Telegram(config('bot.api_key'), config('bot.username'));
$commands_paths = [
         __DIR__ . '/../../Commands',
];

$this->telegram->addCommandsPaths($commands_paths, false);
```
And ... it doesn't work
Problem: When sending a command / test to the bot, nothing happens. I will note that the data is received correctly and I can send a message, but the command class is not called
It seems to me that this library does not support laravel and lumen because their file structure is specific
Here is my structure:

![image](https://user-images.githubusercontent.com/35261681/103480695-29dffe00-4def-11eb-88b2-1ef022c233a2.png)

**Comment by noplanman** [comment]
Hi, can you share the contents of your `TestCommand.php`?
Remember to extend the `Longman\TelegramBot\Commands\UserCommand` (or `AdminCommand`)

**Comment by maffinca69** [comment]
No, unfortunately I have already deleted the class, because I found a solution: it consisted in writing my own runCommand method
Below I am attaching all the code that I wrote in order for my commands to work correctly

My bot controller (lumen):
```
class BaseBotController
{
    /** @var Telegram */
    protected $telegram;

    /** @var Update */
    protected $update;

    /**
     * @param Request $request
     */
    protected function handle(Request $request) {
        $this->update = self::prepareRequest($request->all());
        $this->init();
    }

    private function init()
    {
        $this->telegram = new Telegram(config('bot.api_key'), $this->update, config('bot.username'));
        $commands_paths = [
            __DIR__ . '/../../Commands',
        ];
        $this->telegram->useGetUpdatesWithoutDatabase();
        $this->telegram->addCommandsPaths($commands_paths, false);
    }

    /**
     * @param array $data
     * @return Update
     */
    private static function prepareRequest(array $data)
    {
        return new Update($data, config('bot.username'));
    }
}
```

Custom Telegram class:
```
class Telegram extends \Longman\TelegramBot\Telegram
{
    public function __construct(string $api_key,  Update $update, string $bot_username = '')
    {
        parent::__construct($api_key, $bot_username);

        $this->update = $update;

        $this->sendAction();
    }

    public function runCommand($command = ''): void
    {
        if (empty($command)) {
            throw new TelegramException('No command(s) provided!');
        }

        $this->run_commands = true;

        // Load up-to-date commands list
        $this->commands_objects = $this->getCommandsList();

        $this->executeCommand($command);
    }


    public function sendAction(string $action = ChatAction::TYPING)
    {
        return Request::sendChatAction([
            'chat_id' => $this->update->getMessage()->getChat()->getId(),
            'action'  => $action,
        ]);
    }
}
```

Example command:
```
class PingCommand extends UserCommand
{

    protected $name = 'ping';
    protected $description = 'Пинг';
    protected $usage = '/ping';
    protected $version = '1.0.0';

    public function execute(): ServerResponse
    {
        $data = [
            'chat_id' => 1, // insert your chat id
            'text'    => 'Pong'
        ];

        return Request::sendMessage($data);
    }
}
```

As you can see above, I wrote my runCommand method, because the current method from the runCommands library did not work correctly - the bot sent a message to itself and telegrams generated an access error, which is logical
It is likely that my use is incorrect, but the documentation does not describe how it should be used (this includes the executeCommand method)

**Comment by dasturchiuz** [comment]
Declaration of Longman\TelegramBot\Commands\SystemCommands\StartCommand::execute() must be compatible with Longman\TelegramBot\Commands\Command::execute(): Longman\TelegramBot\Entities\ServerResponse {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Longman\\TelegramBot\\Commands\\SystemCommands\\StartCommand::execute() must be compatible with Longman\\TelegramBot\\Commands\\Command::execute(): Longman\\TelegramBot\\Entities\\ServerResponse at /var/www/botshop/app/Commands/StartCommand.php:10)"} []

**Comment by maffinca69** [comment]
It's incredible! I fixed this problem but spent a lot of time looking at the source code library  
My problem is I am not calling the handle method when using the webhook, but doing the request processing manually
Unfortunately, the documentation does not indicate this explicitly, more precisely - it is not specified at all how the commands work. @noplanman,  I think it is worth improving this moment

Below i wrote success working code:
```php
class BaseBotController
{
    /** @var Telegram */
    protected Telegram $telegram;

    /**
     * @param Request $request
     */
    protected function handle(Request $request) {
        $this->init();

        $this->telegram->handle();
    }

    private function init()
    {
        $this->telegram = new Telegram(config('bot.api_key'), config('bot.username'));
        $commands_paths = [
            __DIR__ . '/../../Commands',
        ];
        $this->telegram->useGetUpdatesWithoutDatabase();
        $this->telegram->addCommandsPaths($commands_paths, false);
    }
}
```

**Comment by noplanman** [comment]
When i was looking at your code from the previous comment with your custom implementation, I was wondering why you're rewriting what is already there 🤔  Now it makes sense to me!

How do you suggest the documentation / readme should be changed, it seems very clear to me.
I'm all for improving it and making it more clear! 👍
