### ISSUE TITLE
kill all previous conversations

### ISSUE THREAD

**Issue by ahmadbadpey** [php-telegram-bot/core#1167]
some times while user is interacted with current conversation maybe enter `/start` command and the see Start commad message that contain other buttons. in this case beacause prev conversation is Incomplete , bot suppose start commands are replay to that conversation And this causes conflicts and Errors. 

is there any way to stop all other conversation when a new command was run?

**Comment by noplanman** [comment]
@ahmadbadpey Take a look at the [`/cancel` command](https://github.com/php-telegram-bot/example-bot/blob/d29a7b266ecfa43df71db2d28ec7cb94c34b66f9/Commands/Conversation/CancelCommand.php) in the examples 👌
