### ISSUE TITLE
example use entities and caption_entities

### ISSUE THREAD

**Issue by reactmore** [php-telegram-bot/core#1170]
### ❓ Support Question

Any examples of using entities messages?

if I use / echo command and use bold text style it will be saved to database

[{"offset": 0, "length": 5, "type": "bot_command"}, ** {"offset": 6, "length": 7, "type": "bold"}] **

how can I use this ** {"offset": 6, "length": 7, "type": "bold"}] ** to have the bot reply to the user with that entities option?

**Comment by noplanman** [comment]
Hi @reactmore, please elaborate and maybe explain with an example what it is you'd like to achieve?

**Comment by justinkruit** [comment]
My guess is that @reactmore is trying to make the bot echo the message including the formatting. Currently getText() results in the message without any formatting. The raw data shows that it knows about the bold text, although we both don't know a proper way to then implement it.

**Comment by jacklul** [comment]
`offset` - tells at which character the specific entity starts
`length` - how many characters (starting at the `offset`) are included

You just need to write a function that re-adds those entities back.

**Comment by reactmore** [comment]
Thanks guys for info , i solved my case use this helper https://github.com/davtur19/TelegramEntityParser and worked,
