### ISSUE TITLE
How to post message in Channel and then post comment/reply to it in linked Discussion group?

### ISSUE THREAD

**Issue by czertowski** [php-telegram-bot/core#1171]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | linux 3.10.0-1127.19.1.el7.x86_64
| PHP Telegram Bot version  | 0.70.1
| PHP version               | 7.4
| MySQL version             | 5.7.27-30
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

I want to achieve this scenario:
1. My bot posts **a message** in a Channel
2. **the message** is being autoposted at linked Discussion group
3. **THE TASK**: I want my bot (the same one) to auto post first comment (reply) to **the message** in the thread at Discussion group (so in the Channel we can see that **the message** has comments)

I know it is needed **reply_message_id** for reply, but I only got ID of **the message** in Channel and can't figure out how to get message id of auto posted the same message in linked discussion group.

I have found this method https://core.telegram.org/method/messages.getDiscussionMessage
and it says "**Bots can use this method**"

How can I implement this method in my bot? Or it's not what I should use?

**Comment by noplanman** [comment]
I suggest you [add logging](https://github.com/php-telegram-bot/core/blob/2093cffa2a8e0497d12183178e17cadcc1d0f6d5/doc/01-utils.md#logging) to your bot to investigate the updates that get sent to your bot from Telegram.

There, you can see that when a comment is posted in the discussion, that message can be processed by your bot. You will see that the message comes from a bot called `@GroupAnonymousBot` and contains the channel message (`message.get_reply_to_message`) and the message in your discussion group (`message`). Then in your custom message handling, you can perform whatever action you like.

I hope this is enough info for you to achieve what you're trying.

**Comment by czertowski** [comment]
Thanks for reply, Armando! I'll try and give a feedback if it works for me. 

Could you please clarify a bit about the method I mentioned above – is there a way it could be used (I'm interested not only in this particular method, there are plenty of those with the same label: "Bots can use this method" in this documentation section) or I misunderstood smth and those core methods couldn't be implemented?

**Comment by noplanman** [comment]
I honestly don't know. That documentation is for the core Telegram API, not for bots. No idea how the methods with "Bots can use this method" can be used via the bot API.

Checking the official bot API, I can't find any methods for handling discussion methods, apart from the way I described in my comment above.

**Comment by jherrerogb98** [comment]
Im trying to do the same. Did you manage to find a way in the end? Thanks in advance

**Comment by alexandredepape** [comment]
I got the same issue at the moment: 

<img width="396" alt="image" src="https://github.com/php-telegram-bot/core/assets/25705704/1201848c-5b86-4d69-9fee-e56fa0298fad">

So instead of going into the comment section, the message gets posted to the main channel, as a reply, but what I actually want is to reply in the comment section ! :)

**Comment by akolotov** [comment]
Thanks @flazouh ! Based on your idea I've got the following example for the demonstration (worked on v21.5):

```python
import os
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Get environment variables
BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
CHANNEL_ID = os.getenv("TELEGRAM_CHANNEL_ID")
DISCUSSION_GROUP_ID = os.getenv("TELEGRAM_DISCUSSION_GROUP_ID")

# Global variable to store the channel message ID
channel_message_id = None

async def start(update: Update, context):
    await update.message.reply_text("Bot started. Use /post to send a message to the channel.")

async def post_to_channel(update: Update, context):
    global channel_message_id
    message = await context.bot.send_message(chat_id=CHANNEL_ID, text="This is a test message in the channel.")
    channel_message_id = message.message_id
    await update.message.reply_text(f"Message sent to channel. Waiting for it to appear in the discussion group...")

async def handle_discussion_message(update: Update, context):
    global channel_message_id
    message = update.message

    channel = await context.bot.get_chat(CHANNEL_ID)          

    if message.forward_origin and message.forward_origin.chat.id == channel.id and message.forward_origin.message_id == channel_message_id:
        # This is the message we're looking for
        comments = [
            "This is the first comment.",
            "Here's a second comment.",
            "And a third comment to wrap it up."
        ]

        for comment in comments:
            await context.bot.send_message(
                chat_id=DISCUSSION_GROUP_ID,
                text=comment,
                reply_to_message_id=message.message_id
            )
        
        await context.bot.send_message(chat_id=update.effective_chat.id, text="All comments added successfully.")
        
        # Reset the channel_message_id
        channel_message_id = None

def main():
    application = Application.builder().token(BOT_TOKEN).build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("post", post_to_channel))
    application.add_handler(MessageHandler(filters.ChatType.GROUPS & filters.FORWARDED, handle_discussion_message))

    application.run_polling(allowed_updates=Update.ALL_TYPES)

if __name__ == "__main__":
    main()
```
