### ISSUE TITLE
Callback query is not working for me

### ISSUE THREAD

**Issue by alexisml-12** [php-telegram-bot/core#1172]
Hello, I'm programming a telegram bot with php and I need help with the inlineKeyboard. The problem is that when I choose an option in the InlineKeyboard it doesn't respond.

    $data = $update->callback_query->data;
    $chatId2 = $update->callback_query->message->chat->id;

This are my variables for the callback query.

    $name1 = 'das';
    $name2 = 'dsa';
    $placeId1 = '1';
    $placeId2 = '2';
    $keyboard = [
                'inline_keyboard' => [[['text' =>  $name1, 'callback_data' => $placeId1]], [['text' =>  $name2, 'callback_data' => $placeId2]]],
            ];
        
    $reply = json_encode($keyboard);
        
    $content = array('chat_id' => $chatId, 'text' => 'Test', 'reply_markup' => $reply);
    $telegram->sendMessage($content);
        
    // $url = $web."/sendmessage?chat_id=".$chatId."&text=select : &reply_markup=".$reply;
    // file_get_contents($url);
        
    if ($data == "1") {
        sendMessage($chatId, "done");
    }else {
        sendMessage($chatId, "no");
    }

And this is my inline keyboard that doesn't work.

Please any help I will appreciate

**Comment by jacklul** [comment]
Are you sure you're using this library? The code you provided shows that you do not.

**Comment by alexisml-12** [comment]
> Hello, I'm programming a telegram bot with php and I need help with the inlineKeyboard. The problem is that when I choose an option in the InlineKeyboard it doesn't respond.
> 
> ```
> $data = $update->callback_query->data;
> $chatId2 = $update->callback_query->message->chat->id;
> ```
> 
> This are my variables for the callback query.
> 
> ```
> $name1 = 'das';
> $name2 = 'dsa';
> $placeId1 = '1';
> $placeId2 = '2';
> $keyboard = [
>             'inline_keyboard' => [[['text' =>  $name1, 'callback_data' => $placeId1]], [['text' =>  $name2, 'callback_data' => $placeId2]]],
>         ];
>     
> $reply = json_encode($keyboard);
>     
> $content = array('chat_id' => $chatId, 'text' => 'Test', 'reply_markup' => $reply);
> $telegram->sendMessage($content);
>     
> // $url = $web."/sendmessage?chat_id=".$chatId."&text=select : &reply_markup=".$reply;
> // file_get_contents($url);
>     
> if ($data == "1") {
>     sendMessage($chatId, "done");
> }else {
>     sendMessage($chatId, "no");
> }
> ```
> 
> And this is my inline keyboard that doesn't work.
> 
> Please any help I will appreciate
