### ISSUE TITLE
$result->getStatus() not working

### ISSUE THREAD

**Issue by akbari-mh** [php-telegram-bot/core#1173]
Hello. this is my code:
`$result = Request::getChatMember([
"chat_id" => "id",
"user_id" => "user id",
]);`
but $result->getStatus() is null
but if I see the $reslut, its 
`{"ok":true, "result":{"user" .......
},"status":"creator"}}
`

**Comment by jacklul** [comment]
In that context you should try
```php
$result = Request::getChatMember([ "chat_id" => "id", "user_id" => "user id", ]);
if ($result->isOk()) {
    var_dump($result->getResult()->getStatus());
}
```

**Comment by akbari-mh** [comment]
> In that context you should try
> 
> ```
> $result = Request::getChatMember([ "chat_id" => "id", "user_id" => "user id", ]);
> if ($result->isOk()) {
>     var_dump($result->getResult()->getStatus());
> }
> ```

also get result is null.
i wanna check, if the user that send a message to bot, is also member of channel, then Request::sendMessage to that user.

**Comment by jacklul** [comment]
>     var_dump($result->getResult()->getStatus());

Are you saying that `var_dump($result->getResult());` is NULL? (noticed modified code)

**Comment by akbari-mh** [comment]
> > ```
> > var_dump($result->getResult()->getStatus());
> > ```
> 
> Are you saying that `var_dump($result->getResult());` is NULL? (notice modified code)

im not making site. its telegram webhook. if i use var_dump, then where can i see the result?

**Comment by jacklul** [comment]
> > > ```
> > > var_dump($result->getResult()->getStatus());
> > > ```
> > 
> > 
> > Are you saying that `var_dump($result->getResult());` is NULL? (notice modified code)
> 
> im not making site. its telegram webhook. if i use var_dump, then where can i see the result?

For testing and debugging you can run bot using getupdates to get console outputs, or use `error_log()` to log messages to PHP error log.

**Comment by akbari-mh** [comment]
> > > > ```
> > > > var_dump($result->getResult()->getStatus());
> > > > ```
> > > 
> > > 
> > > Are you saying that `var_dump($result->getResult());` is NULL? (notice modified code)
> > 
> > 
> > im not making site. its telegram webhook. if i use var_dump, then where can i see the result?
> 
> For testing and debugging you can run bot using getupdates to get console outputs, or use `error_log()` to log messages to PHP error log.

i dont have any error. just null or empty result

**Comment by jacklul** [comment]
> but if I see the $reslut, its
> `{"ok":true, "result":{"user" ....... },"status":"creator"}}`

@noplanman is there possibility the data isn't transformed into object properly in the newer version?

**Comment by akbari-mh** [comment]
> > but if I see the $reslut, its
> > `{"ok":true, "result":{"user" ....... },"status":"creator"}}`
> 
> @noplanman is there possibility the data isn't transformed into object properly in the newer version?

do you have telegram account to see the bot result?

**Comment by akbari-mh** [comment]
first bot answer is for first code and second answer is for second code.
![Capture3](https://user-images.githubusercontent.com/18505305/105816385-7fac5e00-5fc9-11eb-98b7-9a16bcfd07f1.PNG)
![Capture2](https://user-images.githubusercontent.com/18505305/105816671-d6199c80-5fc9-11eb-8e86-8d65f5916165.PNG)
![Capture](https://user-images.githubusercontent.com/18505305/105816690-da45ba00-5fc9-11eb-9b6b-becb43181503.PNG)

**Comment by jacklul** [comment]
@akbari-mh what's your library version?
Let's wait for @noplanman answer

**Comment by akbari-mh** [comment]
> @akbari-mh what's your library version?
> Let's wait for @noplanman answer

0.70.1
i download it yesterday.

**Comment by akbari-mh** [comment]
I think its the problem about json to object. when i use 
`$class = new Longman\TelegramBot\Entities\ChatMember([json_decode($chatMember)], $bot_username);
    foreach($chatMember as $key=>$value){
        $class->{$key}=$value;
    }`
then getOk method work. but other methods not work.

**Comment by noplanman** [comment]
@akbari-mh It works correctly for me.

The problem here is, that you're trying to put an object (`getResult()`) into a string, which is why it gives you `null`.
If you try to get the status directly, that should work.

Adapt your code to use `'True ' . $result->getResult()->getStatus();` instead of just `'True ' . $result->getResult();`

**Comment by akbari-mh** [comment]
> @akbari-mh & @jacklul It works correctly for me.
> 
> The problem here is, that you're trying to put an object (`getResult()`) into a string, which is why it gives you `null`.
> If you try to get the status directly, that should work.
> 
> Adapt your code to use `'True ' . $result->getResult()->getStatus();` instead of just `'True ' . $result->getResult();`

i also tried that. in that case, it causes an error which says :
PHP Fatal error:  Uncaught Error: Call to a member function getStatus() on null in ~/WebHook.php:62

**Comment by akbari-mh** [comment]
@noplanman would is it because php version?

**Comment by noplanman** [comment]
Shouldn't be the problem, but what version are you on?

**Comment by akbari-mh** [comment]
> Shouldn't be the problem, but what version are you on?

0.70.1
i dont know why, but now its working very well.
thank you❤

**Comment by noplanman** [comment]
Ok, glad to hear it's working now! 🎉
