### ISSUE TITLE
handleGetUpdates in loop ? 

### ISSUE THREAD

**Issue by seuaCoder** [php-telegram-bot/core#1174]
### ❓ Support Question

i'm using the getUpdates methods wihtout database.

should $telegram->handleGetUpdates(); be wrapped in an infinite loop ? When i run the script getUpdatesCLI.php nothing happen and it close.

**Comment by noplanman** [comment]
Yes, that could run in a loop in your CLI.

Alternatively, you can make the loop in the PHP script itself, with an infinite `while(true) {...}` loop.

You can try to uncomment the `echo $e;` lines in the `catch` statements, to see what error is being outputted.

**Comment by noplanman** [comment]
@seuaCoder Did you manage to find a solution that works for you?

**Comment by seuaCoder** [comment]
yes alright now, thank you.
