### ISSUE TITLE
How to "reset" $message->getPhoto() in a Conversation?

### ISSUE THREAD

**Issue by CarlosNegrao** [php-telegram-bot/core#1175]
### ❓ Support Question

I'm posting this here, in the hopes that it may help someone else later.

I'm trying to get several photos in row from a conversation, pretty much just replicating code from the example Conversation:
```php
            case 4:
                if ($message->getPhoto() === null) {
                    $notes['state'] = 4;
                    $this->conversation->update();

                    $data['text'] = "Fotos 1.";

                    $result = Request::sendMessage($data);
                    break;
                }

                $photo             = $message->getPhoto()[0];
                $notes['foto_antes_1'] = $photo->getFileId();
				$notes['state'] = 5;
				$this->conversation->update();			
				$message = $this->getMessage();
            case 5:
                if ($message->getPhoto() === null) {
                    $notes['state'] = 5;
                    $this->conversation->update();

                    $data['text'] = 'Foto 2';

                    $result = Request::sendMessage($data);
                    break;
                }

                $photo             = $message->getPhoto()[0];
                $notes['foto_antes_2'] = $photo->getFileId();
				
				$this->conversation->update();				
				$message = $this->getMessage();
```

But I get at most two different photos out of at least four that must be sent. The remaining ones just get the same id as the second one, if not the first, like this:
{
	"state": 8,
	"job id": "12345",
	"longitude": -43.xxxx,
	"latitude": -22.xxxx,
	"descricao": "Teste",
	"causa": "1",
	"sub_causa": "2",
	"foto 1": "AgACAgEAAxkBAAIB72AYWQkjnAMnHASKygGKxNNusJ_jAALZqDEbA6nBRAABSmpBbWT01mbd6EsXAAMBAAMCAANtAAMgEgACHgQ",
	"foto 2": "AgACAgEAAxkBAAIB9WAYWReaywvCdH5-ogfUhlvjfjqsAALaqDEbA6nBRAyZ_IVJtW-UXd_oSxcAAwEAAwIAA20AA1oSAAIeBA",
	"foto 3": "AgACAgEAAxkBAAIB9WAYWReaywvCdH5-ogfUhlvjfjqsAALaqDEbA6nBRAyZ_IVJtW-UXd_oSxcAAwEAAwIAA20AA1oSAAIeBA",
	"foto 4": "AgACAgEAAxkBAAIB9WAYWReaywvCdH5-ogfUhlvjfjqsAALaqDEbA6nBRAyZ_IVJtW-UXd_oSxcAAwEAAwIAA20AA1oSAAIeBA"
}

Do I have to somehow "reset" $message->getPhoto() for it to work?

**Comment by noplanman** [comment]
Hi @CarlosNegrao, you are absolutely right, this is a known issue at the moment.

Take a look at the comment here that provides a solution, which is exactly what you suggest with your last question:
https://github.com/php-telegram-bot/core/issues/215#issuecomment-224381608

**Comment by CarlosNegrao** [comment]
Thank you, I'll take a look in a couple of hours or at most tomorrow.  
Sorry I can't do it sooner to close the issue.

**Comment by CarlosNegrao** [comment]
I added both functions to /vendor/longman/telegram-bot/src/Commands/Command.php and stuck the line
```php
$this->setObjectProperty($message, 'photo', null);
```
right before the "case", and it didn't work.  
Every subsequent request for a photo got skipped.
 
Then I attempted to set "notes['state']" to the next case adn add a break, nothing.  
Finally, I added 
```php
file_put_contents('/tmp/dump.txt', print_r ($ref_object->getProperties(), true ));
```
to setObjectProperty so I could see the reflection object and check if "photo" didn't have a different name, but it looks like setObjectProperty never gets called.  

Sorry about asking what might be a basic question, but do you have any ideas? Was there a different place I should have added setObjectProperty?

**Comment by noplanman** [comment]
@CarlosNegrao any changes you make in the "vendor" folder get lost when an update comes out. Best is to create a custom class with helper methods. Then you can include that file / class and use it anywhere in your project. The reflection method i posted should work as mentioned, so not sure why it isn't.

What version of PHP are you using?

**Comment by CarlosNegrao** [comment]
TBH, I forgot about using a custom class, as I tired as I was of troubleshooting.  
I'm currently using PHP 7.3.19, since it's packaged with the Debian install I have on my current VPS.
