### ISSUE TITLE
Request limiter should accept chat ID as integer and string

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/core#1176]
#### Summary

Request limiter currently only works for requests that pass the chat id as integer values.
This needs to be cleaned up, to allow both integer and string (for `@channels` and `@groups`).

Reported here:
https://t.me/PHP_Telegram_Bot_Support/27539

#### Current behaviour

Error message:
```
telegram_bot.ERROR: Argument 1 passed to Longman\TelegramBot\DB::getTelegramRequestCount() must be of the type int or null, string given, called in /vendor/longman/telegram-bot/src/Request.php on line 877 [] []
```

https://github.com/php-telegram-bot/core/blob/2093cffa2a8e0497d12183178e17cadcc1d0f6d5/src/Request.php#L877

#### How to reproduce

Send a request with `$data['chat_id'] = '@channel';` for example.

#### Expected behaviour

It should work with both integer and string chat ID values.

**Comment by Sergey-Shabanov** [comment]
Good afternoon, can you please tell me how to add such a beautiful display of a code fragment when filling out a ticket?

![](https://i.ibb.co/Dg7Q13b/image.jpg)

**Comment by noplanman** [comment]
@Sergey-Shabanov Off-topic, but you can do that by pasting a direct link to a line of code. GitHub then automatically makes it "pretty" 😃 

The link i posted in the issue here, is this: `https://github.com/php-telegram-bot/core/blob/2093cffa2a8e0497d12183178e17cadcc1d0f6d5/src/Request.php#L877`

**Comment by Sergey-Shabanov** [comment]
So I did, but I didn't get nice formatting. I will try again. Anyway, thanks for the explanation, and have a nice day!
