### ISSUE TITLE
PHP_Telegram_Bot_Support - Can't post messages...

### ISSUE THREAD

**Issue by massadm** [php-telegram-bot/core#1179]
### ❓ Support Question

> Before asking a question here, please try asking in the support group first.
https://telegram.me/PHP_Telegram_Bot_Support

Can't post messages...

After receiving the message _"Please read and agree to the rules"_ with link to the bot `/start`, i took the following steps:

* Read the rules in bot's PM, Agree with them and get back to group;
* Click **Join to group**;

Receive a welcome message but with reply_markup blocked with message about write permission is deny.

"Rules" message from bot now has no callback buttons.

Id: 1248569524

**Comment by noplanman** [comment]
Hi @massadm, I have adjusted the permissions, you can post to the group now. Not sure why the restriction was set by the bot, will investigate 🔍
