### ISSUE TITLE
Keyboard constructor crashes when called without parameters

### ISSUE THREAD

**Issue by hutattedonmyarm** [php-telegram-bot/core#1183]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Debian Buster
| PHP Telegram Bot version  | 0.70.1
| PHP version               | 7.4.10
| MySQL version             | -
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | -

#### Summary

The Keyboard constructor calls `createFromParams` which calls `reset` on the parameter array. If the parameter array is empty, `reset` returns false. The following line `if ($from_data = array_key_exists($keyboard_type, (array) $data)) {` crashes when force-casting this into an array.

**Comment by noplanman** [comment]
Hi @hutattedonmyarm, casting to array shouldn't crash the script. It doesn't for me anyway.
If the value is `false`, casting to an array should convert it to an array, like `[false]`.

Please provide the error you get, as it may be some other problem causing the crash.

**Comment by hutattedonmyarm** [comment]
> Hi @hutattedonmyarm, casting to array shouldn't crash the script. It doesn't for me anyway.
> If the value is `false`, casting to an array should convert it to an array, like `[false]`.
> 
> Please provide the error you get, as it may be some other problem causing the crash.

You are right of course, I only skimmed the error log. The actual issue is, happens in when returning from `createFromParams`. `$data = reset($args);` causes `$data` to be set to `false` and the rest of the function works as intended. However, `$data` itself is never overwritten. 

```
$new_keyboard = [];

// $args is an empty array, so this is skipped
foreach ($args as $row) {
    $new_keyboard[] = $this->parseRow($row);
}

// new_keyboard is an empty array, so !empty($new_keyboard) is false
if (!empty($new_keyboard)) {
    if (!$from_data) {
        $data = [];
    }
    $data[$keyboard_type] = $new_keyboard;
}

// $data is still "false"
return $data;
```

This makes the function return `false` which results in a PHP error:

```
[05-Mar-2021 13:57:16 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Return value of Longman\TelegramBot\Entities\Keyboard::createFromParams() must be of the type array, bool returned in [...]vendor/longman/telegram-bot/src/Entities/Keyboard.php:121
Stack trace:
#0 [...]vendor/longman/telegram-bot/src/Entities/Keyboard.php(35): Longman\TelegramBot\Entities\Keyboard->createFromParams()
#1 [...]Commands/EventsCommand.php(114): Longman\TelegramBot\Entities\Keyboard->__construct()
#2 [...]vendor/longman/telegram-bot/src/Commands/Command.php(182): Longman\TelegramBot\Commands\UserCommands\EventsCommand->execute()
#3 [...]vendor/longman/telegram-bot/src/Telegram.php(603): Longman\TelegramBot\Commands\Command->preExecute()
#4 [...]vendor/longman/telegram-bot/src/Telegram.php(575): Longman\TelegramBot\Telegram->executeComma in [...]vendor/longman/telegram-bot/src/Entities/Keyboard.php on line 121


```

Casting $data to an array before returning it would also work, although I'm unsure whether `[false]` is an expected return value, and if an empty array wouldn't be a better option
