### ISSUE TITLE
How to exclude default library commands from "Commands paths"?

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [php-telegram-bot/core#1187]
This is a part of my /debug command (and it works):
```
TelegramBot version: 0.70.1
Commands paths:
[
    "/var/www/app/TelegramBot/Commands/SystemCommands/",
    "/var/www/app/TelegramBot/Commands/UserCommands/",
    "/var/www/vendor/longman/telegram-bot/src/Commands/SystemCommands",
    "/var/www/vendor/longman/telegram-bot/src/Commands/AdminCommands"
]
```
Where did the last 2 lines come from? A never added these paths to the `commands paths`.

This is a fragment of my `composer.json`:
```json
"autoload": {
        "psr-4": {
            "Longman\\TelegramBot\\Commands\\UserCommands\\": "app/TelegramBot/Commands/UserCommands/",
            "Longman\\TelegramBot\\Commands\\SystemCommands\\": "app/TelegramBot/Commands/SystemCommands/"
        },
    },
```

I also tried to exclude default commands, but it doesn't work (But this way worked at least at `0.60.0` version).
```json
        "exclude-from-classmap": [
            "vendor/longman/telegram-bot/src/Commands/SystemCommands/",
            "vendor/longman/telegram-bot/src/Commands/UserCommands/"
        ],
```

All my **system** commands just don't work. But user commands work well (Apparently, because of `/var/www/vendor/longman/telegram-bot/src/Commands/UserCommands` is not present in the `commands paths`).

How can I remove default library paths from `commands paths`?

**Comment by CaliforniaMountainSnake** [comment]
I defined a custom Telegram class, with `setCommandsPaths()` method and it turned out to be removed `/var/www/vendor/longman/telegram-bot/src/Commands/SystemCommands` from `commands paths`.

```php
class BaseTelegram extends Telegram
{
    /**
     * @param array $paths
     */
    public function setCommandsPaths(array $paths): void
    {
        $this->commands_paths = [];
        $this->addCommandsPaths($paths);
    }
}
```
```
Commands paths:
[
    "/var/www/app/TelegramBot/Commands/SystemCommands/",
    "/var/www/app/TelegramBot/Commands/UserCommands/",
    "/var/www/vendor/longman/telegram-bot/src/Commands/AdminCommands"
]
```

But the library still tries to define its own system commands...
```
[2021-03-10 15:04:09] testing.ERROR: Cannot declare class App\TelegramBot\Commands\SystemCommands\GenericCommand, because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot declare class App\\TelegramBot\\Commands\\SystemCommands\\GenericCommand, because the name is already in use at /var/www/app/TelegramBot/Commands/SystemCommands/GenericCommand.php:14)
[stacktrace]
#0 {main}
"} 

```

**Comment by CaliforniaMountainSnake** [comment]
UPD: it seems my system commands start to work when I used the `setCommandsPaths()` method from above.

**Comment by noplanman** [comment]
Hi @CaliforniaMountainSnake, sorry for the very late reply!

The way the whole commands are built isn't the most optimal, for sure. What's lacking to redesign it, is time unfortunately.

There are a few open issues regarding commands and how they could be managed better. If somebody feels the drive to tackle it, that would be great.

For the moment though, and for the vast majority of users, the command system as it is now works well enough.
Thanks a lot for your input and code examples to solve certain command-related issues 🙏 

(maybe you can get in touch with me directly on Telegram if you'd be up for contributing to the library directly and getting some of your ideas into the core project?)
