### ISSUE TITLE
Endless repetition in `Longman\TelegramBot\Telegram::handleGetUpdates()` for unknown updates

### ISSUE THREAD

**Issue by massadm** [php-telegram-bot/core#1194]
### 🐞 Bug Report

Critical

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Linux 5.11.6-1-MANJARO
| PHP Telegram Bot version  | 0.71.0
| PHP version               | 8.0.1
| MySQL version             | 10.5.8-MariaDB
| Update Method             | getUpdates
| Self-signed certificate   | no

#### Summary

Due to Telegram Bot API updates, the TelegramBot instance may receive updates that have not yet been implemented by the library. With the current implementation of `getUpdates`, processing of such updates will be repeated indefinitely.

#### How to reproduce

Get `my_chat_member` or any other currently unimplemented update from Telegram using `getUpdates`.

#### Expected behaviour

Need the way to process unknown updates.

**Comment by massadm** [comment]
Call to get incoming updates using long polling looks like this:

```php
$response = Request::getUpdates(..., $offset = $this->last_update_id + 1)
```

`$this->last_update_id` populated from the database like this:

```sql
SELECT `id` FROM `telegram_update` ORDER BY `id` DESC LIMIT 1
```

The problem is that `DB::insertRequest($this->update)` does not populate the database with information about unknown updates. At the next iteration, the database will not contain information about the processing of unimplemented update, so `$this->last_update_id` will remain the same as in the previous iteration. And so it turns out to be an endless cycle.

**Comment by noplanman** [comment]
You're absolutely right, thanks for reporting. This will be fixed in the next version, which will also have the Bot API 5.1 integrated.

It will also be more future-proof for when new update types get added by Telegram 👌

**Comment by noplanman** [comment]
@massadm Your suggestion sounds like a great idea! Would you like to make a PR for it? 😇

**Comment by noplanman** [comment]
Maybe we could combine this with #1124?

**Comment by massadm** [comment]
I'll see what I can do.
