### ISSUE TITLE
Command key incorrect capitalization in \Longman\TelegramBot\Telegram::$commands_objects

### ISSUE THREAD

**Issue by alpipego** [php-telegram-bot/core#1197]
### 🐞 Bug Report

The \Longman\TelegramBot\Telegram::$commands_objects array keys get `mb_strtolower`ed in https://github.com/php-telegram-bot/core/blob/master/src/Telegram.php#L265. When searching for a command in https://github.com/php-telegram-bot/core/blob/master/src/Telegram.php#L557-L562 the "key" does not get manipulated in the same way and thus even if the key `photo` exists in \Longman\TelegramBot\Telegram::$commands_objects, it isn't found because the key `Photo` is searched.

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Windows 10/WSL2/Docker
| PHP Telegram Bot version  | 0.71.0
| PHP version               | 7.4.15
| MySQL version             | 10.4.17+maria~focal
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Current behaviour

no command object can be found.

#### How to reproduce

Register a `PhotoCommand` extending the `UserCommand` and upload a photo to your bot.

#### Expected behaviour

My aforementioned `PhotoCommand` should handle the upload.

**Comment by massadm** [comment]
@noplanman check ` \Longman\TelegramBot\Telegram::getCommandObject()`: in `$command_class = $command_namespace . '\\' . $this->ucFirstUnicode($command) . 'Command'` method `ucFirstUnicode` is used forcibly to get the correct class name while in `if (isset($this->commands_objects[$command])) { return $this->commands_objects[$command]; }` no string manipulations are performed on key cmp.

**Comment by noplanman** [comment]
Yes, that is correct, because the command names are always lower case, but the classes have the first letter capitalised.
I still don't get any error when doing what @alpipego has reported.

Am I missing something here?

**Comment by massadm** [comment]
> command names are always lower case

`$message->getCommand()` return raw user input as command [here](https://github.com/php-telegram-bot/core/blob/9ca6158f9fe6cf5aa06f9c46377b3c1164bdf444/src/Telegram.php#L560) so lookup in `getCommandObject()` will be succeed only if the user has used lowercase characters.

**Comment by massadm** [comment]
Just break in `getCommandObject` method and see what happened here. It always gets executed correctly only because of the second part of the method where `ucFirstUnicode` is used forcibly to get the correct class name. As a result, `new $command_class($this, $this->update)` is returned (each time).

The necessary changes in `getCommandObject` can be described as follows:
```php
$lookup_key = mb_convert_case($command, MB_CASE_LOWER, 'UTF-8');
if (isset($this->commands_objects[$lookup_key])) {
    return $this->commands_objects[$lookup_key];
}
```

**Comment by noplanman** [comment]
Thanks for getting back to us @alpipego.

@massadm I'm still struggling to find out what exactly provokes a problem 🤷‍♂️ 

> Can you provide a step-by-step example of how to provoke the error?

**Comment by massadm** [comment]
@noplanman Issue command `/CaNCeL`, for example, break in `getCommandObject` method and see what happened here. You get `CaNCeL` in `$command` so lookup in `$this->commands_objects` always fails. As a result, `new $command_class($this, $this->update)` is returned each time.
