### ISSUE TITLE
Add `allowed_updates` parameter for getUpdates method

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/core#1201]
#### Summary

The [`getUpdates`](https://core.telegram.org/bots/api#getupdates) method must allow for the `allowed_updates` parameter to be passed.

This is vital to allow the new `chat_member` update type to be retrieved.

Looking at the current [`handleGetUpdates`](https://github.com/php-telegram-bot/core/blob/9ca6158f9fe6cf5aa06f9c46377b3c1164bdf444/src/Telegram.php#L400) method, best solution would be to add an extra array parameter to pass the allowed update types.

**Comment by massadm** [comment]
This is the correct way to implement `update_filter`. Check https://github.com/php-telegram-bot/core/blob/9ca6158f9fe6cf5aa06f9c46377b3c1164bdf444/src/Telegram.php#L528

**Comment by noplanman** [comment]
@massadm, so what you're saying, is to define all known types specifically [here](https://github.com/php-telegram-bot/core/blob/9ca6158f9fe6cf5aa06f9c46377b3c1164bdf444/src/Telegram.php#L444) and the user can then filter by using the provided callback function?

**Comment by massadm** [comment]
`update_filter` is `null` by default so no one update will be missed. If some updates is not welcome the right policy is not to receive them at all. Decision can be made after each iteration with help of `setUpdateFilter`.

**Comment by noplanman** [comment]
The problem here is, that for the `chat_member` update type, the value **must** be defined in the `allowed_updates` field. As it is now, it will never get that update, so the `update_filter` also never gets it.

Check #1202

**Comment by massadm** [comment]
Btw, found an error in the following piece of code:
```php
    /**
     * Update filter
     * Filter updates
     *
     * @var callback
     */
    protected $update_filter;
```
`@var` must be `callable` here, not "callback".

**Comment by massadm** [comment]
> The problem here is, that for the `chat_member` update type, the value **must** be defined in the `allowed_updates` field. As it is now, it will never get that update, so the `update_filter` also never gets it.

I see. Let it remain so: an empty list to get all types of updates except for `chat_member`, until the user changes it with `update_filter`.

**Comment by massadm** [comment]
> Check #1202

IMO, update types better to implement as constants and make use of `update_filter` instead of an additional parameter. Bot can use `setUpdateFilter` method to change behavior at any time.

**Comment by noplanman** [comment]
Hi @massadm, thanks for your input, I've reflected your thoughts in the PR.

I've removed the defined parameters from `Telegram::handleGetUpdates` and put the generic `$data` array, as with other API methods too.

Would you mind having a look to have a second pair of eyes check the code? Thanks! 😇
