### ISSUE TITLE
User custom commands not being executed. Error :Command not found.

### ISSUE THREAD

**Issue by nightwatcher1star** [php-telegram-bot/core#1203]
hi

I am not getting my command executed in telegram bot. when i type /, the command is shown but when i click on it it says command not found.

Found this on my error log : PHP Fatal error:  Uncaught Error: Class 'Longman\TelegramBot\Commands\UserCommand'. Please provide some guidance.

Thanks

**Comment by noplanman** [comment]
Hi @nightwatcher1star 

Is it possible for you to post the command that is giving you problems?

**Comment by nightwatcher1star** [comment]
HI @noplanman 

Thanks for the reply. so i have like 5 commands in the command folder. 3 of them are working fine. 

ISSUE 1

RsCommand should fire when a user sends /satellite, however it is giving command not found error.
RsCommand.php code:

<?php


namespace Longman\TelegramBot\Commands\UserCommands;


use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;



class RsCommand extends UserCommand
{
    /**
     * @var string
     */
    protected $name = 'satellite';

    /**
     * @var string
     */
    protected $description = 'Fetch image';

    /**
     * @var string
     */
    protected $usage = '/satellite';

    /**
     * @var string
     */
    protected $version = '1.2.0';

    /**
     * Main command execution
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute(): ServerResponse
    {
        $message = $this->getMessage();

        // Use any extra parameters as the caption text.
        $caption = trim($message->getText(true));


        
 
        $image1 = 'https://ma.gov.in/Sat/rswm_vis.jpg';
        $image2 = 'https://m.gov.in/Sat/rswm_ir1.jpg';
      
        
        $t=time();
       
       
       
       return Request::sendMediaGroup([
            'chat_id' => $message->getFrom()->getId(),
            
            'media'   => ([
        ['type' => 'photo','caption' => 'VISIBLE RAPID ', 'media' => $image1.'?'.$t ],
        ['type' => 'photo','caption' => 'INFRARED RAPID ', 'media' => $image2.'?'.$t ],
      
    ]),
            
        ]);
            
    }

}


// However i have the same code with a different user command in satCommand.php file which is working fine. Both the codes are the same.

satCommand.php code starts:

<?php


namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;

class satCommand extends UserCommand
{
    /**
     * @var string
     */
    protected $name = 'sat';

    /**
     * @var string
     */
    protected $description = 'Fetch image ';

    /**
     * @var string
     */
    protected $usage = '/sat';

    /**
     * @var string
     */
    protected $version = '1.2.0';

    /**
     * Main command execution
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute(): ServerResponse
    {
        $message = $this->getMessage();

        // Use any extra parameters as the caption text.
        $caption = trim($message->getText(true));

        // Make sure the Upload path has been defined and exists.
        $upload_path = $this->telegram->getUploadPath();
        if (!is_dir($upload_path)) {
            return $this->replyToChat('Upload path has not been defined or does not exist.');
        }

        $image1 = 'https://xyz.com/Bot/Upload/infrared.jpg';
        $image2 = 'https://xyz.com/Bot/Upload/cloudtop.jpg';
      

        $t=time();
        $result = $message->getFrom()->getId();
       
       
       return Request::sendMediaGroup([
            'chat_id' => $result,
            
            'media'   => ([
        ['type' => 'photo','caption' => 'INFRARED IMAGE ', 'media' => $image1.'?'.$t ],
        ['type' => 'photo','caption' => 'CLOUD TOP IMAGE ', 'media' => $image2.'?'.$t ],
    
    ]),
            
        ]);
            
    }

  
}

ISSUE 2

on my bot, when i type '/' , only the satellite command shows up. rest of the commands dont show up. However if i type the command and send it to the bot, only the /satellite command shows command not found. Rest all including /sat gets executed and gives result to the user.

Both file have same permission 0644.

Kindly help me out with this issue.

Thanks

**Comment by noplanman** [comment]
@nightwatcher1star Thanks for the detailed reply, I hugely appreciate it! 😃 

1. The command and the file name must match, so `/satellite` command should be in `SatelliteCommand.php` file. This is why the `/sat` command works correctly. _This is a limitation at the moment, sorry for the inconvenience! 😓_
2. You must set the list of commands displayed when typing `/` with [@BotFather](https://t.me/BotFather) directly. Use the `/setcommands` command for that. Alternatively you can set those commands with your bot itself, [look here](https://core.telegram.org/bots/api#setmycommands).

Hope that helps, let me know.

**Comment by nightwatcher1star** [comment]
Hi @noplanman 

OMG you are a genius. It works fine now. I wasted like two full days trying to figure out the issue. Thank you so much for the help. Really appreciate you spending your valuable time to help me out.

SideNote: if the image size is like 3mb, the command works but the file does not get sent. I was going through the documentation and it mentions that max size is 10mb. Any thoughts on why the image is not being downloaded and sent to the user?

Thanks a lot. Cheers

**Comment by noplanman** [comment]
@nightwatcher1star Check here for sending limits: https://core.telegram.org/bots/api#sending-files

Apart from that, I can't help, sorry!
