### ISSUE TITLE
Add `drop_pending_updates` parameter for deleteWebhook method

### ISSUE THREAD

**Issue by ahbanavi** [php-telegram-bot/core#1206]
#### Summary

`deleteWebhook` method has `drop_pending_updates` now for resetting pending updates to zero. (as you can see [here](https://core.telegram.org/bots/api#deletewebhook))  

Please add this parameter to deleteWebhook method as optional.

**Comment by noplanman** [comment]
Thanks so much for pointing this out!
This clearly went forgotten when implementing the Bot API 5.0

Will include it to the Bot API 5.1 implementation 💪
