### ISSUE TITLE
how to send markdown format with Request::sendMessage

### ISSUE THREAD

**Issue by dhayzon** [php-telegram-bot/core#1208]
https://sourceforge.net/p/telegram/wiki/markdown_syntax/

`  \Longman\TelegramBot\Request::sendMessage([
            'chat_id' => (int) $chat_id,
            'text'    => $message,
        ]);`

```
$message ='
 * this shows up in italics: *a happy day*
* this shows the asterisks: \*a happy day\*
';
```

**Comment by noplanman** [comment]
Check the API for available parameters:
https://core.telegram.org/bots/api#sendmessage

You need to add `'parse_mode' => 'markdown'` to your parameters 👍

**Comment by dhayzon** [comment]
Nice
