### ISSUE TITLE
runcommands from inside command

### ISSUE THREAD

**Issue by kaederukawa7** [php-telegram-bot/core#1214]
hi guys, i would like to ask a little help here.
i have a command like just call it "/greetings" and i code inside greeting to run other command like "/echo"
i put this code inside /greetings

```
$message = $this->getMessage();
$perintahraw = trim($message->getText(true));
$perintah = explode(" ",$perintahraw);

//run echo  with selected parameter
$this->getTelegram()->runCommands(["/echo ".$perintah[0]]);
```

when i call greetings like this " /greetings hi halo "

it execute /echo too, but the result is " hi halo ", what i expected is " hi "  only.

hope u guys get my point :) ... any clue to fix this ?

**Comment by dhayzon** [comment]
I think it's not possible to do that 
I modify the content of the answer with  Update
for example:
`$message = $this->getMessage(); 
   $message  = json_decode($message ->toJson(), true); 
    $message['text'] = 'Hello worl  or another custom text ';
    $new_update = new Update(
            [
                'update_id' => '-1',
                'message' => $message
            ],
            $message->getBotUsername()
        ); 
        $cmdobj = $this->getTelegram()->getCommandObject('Mycommand');
        $cmdobj->setUpdate($new_update)->preExecute();
        
`

**Comment by dhayzon** [comment]
check class EchoCommand  

 ```
 public function execute(): ServerResponse
    {
        $message = $this->getMessage();
        $text    = $message->getText(true);

        if ($text === '') {
            return $this->replyToChat('Command usage: ' . $this->getUsage());
        }

        return $this->replyToChat($text);
    }
```

double pass contend data, by default data for echo is /echo <text>

when you execute /echo  you execute  /echo $perintah[0]  + <text>

**Comment by dhayzon** [comment]
its not posible pass parameters `$this->getTelegram()->runCommands(["/echo ".$perintah[0]]);`

runCommands only execute /echo command   `$perintah[0]]` was ignored

**Comment by noplanman** [comment]
This is a bug, hope to get this fixed soon.

Thanks for reporting @kaederukawa7

**Comment by kaederukawa7** [comment]
> This is a bug, hope to get this fixed soon.
> 
> Thanks for reporting @kaederukawa7

Thank you :)

**Comment by noplanman** [comment]
After an epic delay, a fix 🙏 

https://github.com/php-telegram-bot/core/pull/1223

@kaederukawa7 Please test this to make sure it works for your use-case, thanks!

**Comment by kaederukawa7** [comment]
yeayyy it works. Thankyou @noplanman
