### ISSUE TITLE
default GenericmessageCommand.php not run

### ISSUE THREAD

**Issue by zohrehda** [php-telegram-bot/core#1221]
hi 
my problem is that the default GenericmessageCommand.php in /scr/commands/.. not run and execute 
I had a custom GenericmessageCommand and I use addCommandClass to add it and that did not work too, I delete it
another problem I have is logging. there is no log .
should I config anything to use the default GenericmessageCommand.php  . 
please help me

**Comment by zohreh-da** [comment]
> When using the `$telegram->addCommandClass(...)` method, it makes sense to not share the `Longman\TelegramBot` namespace, which is required when adding whole paths.
> 
> Please try to change the namespace and make sure the file has been autoloaded / required correctly.
> 
> For logging, please [check here](https://github.com/php-telegram-bot/core/blob/b6ea355a4d16e8b1879b6a485d664a6a5a9c6ea3/doc/01-utils.md#logging).

thanks for reply
