### ISSUE TITLE
telegram bot real time

### ISSUE THREAD

**Issue by zohreh-da** [php-telegram-bot/core#1222]
I have a bot that get data from another api and display to user depend on user request
now I need that the bot response be real time 
the api that I use have websocket api too , I want to use this webscocket api to update the respnse data real time without user request
is it possible and How??
thanks all

**Comment by noplanman** [comment]
Sorry, I'm not understanding the question here 🤔

**Comment by TiiFuchs** [comment]
Closing this ticket since there was no further explanation to the question.
If you still have a questions, feel free to reopen this ticket and give us more information. :)
