### ISSUE TITLE
Can I get receive all messages from group?

### ISSUE THREAD

**Issue by emresaracoglu** [php-telegram-bot/core#1224]
Hello,

I am using a different repo except for this repo. I send messages via CRON, but I want to save the messages written by the group members to the database. Can I receive group members' correspondence in this repo? 

Thank you!

**Comment by noplanman** [comment]
Hi @emresaracoglu, yes you can receive all messages in a group.

Make sue your bot privacy is set correctly: https://core.telegram.org/bots#privacy-mode

**Comment by emresaracoglu** [comment]
Great project, thank you. I can receive the messages, but the messages I send with the API are not registered in the database. How can I get it registered to the database?

**Comment by jacklul** [comment]
> Great project, thank you. I can receive the messages, but the messages I send with the API are not registered in the database. How can I get it registered to the database?

This is unfortunately not something that is build into this library but you can you easily implement it by extending **Request** class and modyfing **send** function to insert every request into the database AFTER executing the request (for speed and performance reasons) - **untested** example:

```php
<?

namespace YourProject\Bot;

use Longman\TelegramBot\DB;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\TelegramLog;
use Longman\TelegramBot\Entities\ServerResponse;

class LoggedRequest extends Request
{
    public static function send(string $action, array $data = []): ServerResponse
    {
        $response = parent::send($action, $data);

        if (DB::isDbConnected()) {
            $pdo = DB::getPdo();
            
            try {
                $sth = $pdo->prepare('
                    INSERT INTO `logged_request`
                    (`method`, `data`, `date`)
                    VALUES
                    (:method, :data, :date)
                ');
                $sth->bindValue(':method', $method);
                $sth->bindValue(':data', json_encode($data));
                $sth->bindValue(':date', DB::getTimestamp());
                
                $sth->execute();
            } catch (PDOException $e) {
                TelegramLog::error($e->getMessage());
            }
        }

        return $response;
    }
}
```

You will need to create database schema yourself based on the code and anywhere where you would use **Request** class you have to use **LoggedRequest** instead for the request to be logged.

**Comment by emresaracoglu** [comment]
Thank you for your help @jacklul 

I created the required table for the database, but I don't know what the required parameters are.
Is it true like this? :

	
```
        use YourProject\Bot\LoggedRequest;
	include "vendor.php";
	include "jacklul.php";  /// your class
	
	$mysql_credentials = [
		****
	];
	try { 
		$telegram = new Longman\TelegramBot\Telegram(****);
		$telegram->enableMySql($mysql_credentials); 
		$telegram->handleGetUpdates();
		LoggedRequest::send();   ////  Here it is (not sure if the location is correct)
	} catch (Longman\TelegramBot\Exception\TelegramException $e) { 
		echo $e->getMessage();
	}
```

What are the parameters required for the send function?
`public static function send(string $action, array $data = []): ServerResponse`

Get error:

```
 ArgumentCountError
Too few arguments to function YourProject\Bot\LoggedRequest::send(), 0 passed in /home/****/test1.php on line 27 and at least 1 expected
```

**Comment by jacklul** [comment]
That's not how you should use it, you replace `Request` with `LoggedRequest` in your comands.

For example if you had command https://github.com/php-telegram-bot/example-bot/blob/master/Commands/Other/WhoamiCommand.php you would replace all `Request::` calls with `LoggedRequest::`.

**Comment by emresaracoglu** [comment]
I changed it, and sending the message is successul.

```
$result = LoggedRequest::sendMessage([
		'chat_id' => '-1001305367466',
		'text' => 'Your utf8 text ...',
]);
```
Unfortunately, it does not register in the database.
The database schema is as follows, do you think there is an error/missing in the schema?

![image](https://user-images.githubusercontent.com/297968/123384370-fcedf600-d59c-11eb-9ae5-4a089efd3e47.png)

**Comment by jacklul** [comment]
Can you please put debug echo statement somewhere in my code's `send` method to verify that it's actually being executed?
_As I mentioned - I'm not sure if it will work and it is completely untested code._

**Comment by emresaracoglu** [comment]
**Thank you very much** for your patience and help. It currently works as I want it to.
cc @jacklul
