### ISSUE TITLE
setWebhook doesn't allow drop_pending_updates

### ISSUE THREAD

**Issue by TiiFuchs** [php-telegram-bot/core#1225]
The `setWebhook` method in https://github.com/php-telegram-bot/core/blob/ed2df605b2f7fa77db527ef70dc5cec7cd4fdf75/src/Telegram.php#L1028 filters the data array but does not allow the `drop_pending_updates` parameter, as described in the [Telegram Bot API](https://core.telegram.org/bots/api#setwebhook).
It's therefor not possible to drop updates, when changing the Webhook URL.

I have a pull request for this, that fixes this problem.

**Comment by TiiFuchs** [comment]
Btw: I saw that ip_address is missing too.
I think that might needs to be added too, right?!

see https://core.telegram.org/bots/api#setwebhook

**Comment by noplanman** [comment]
Nice catch! Correct @ `ip_address`, could you pop that in too please?

**Comment by TiiFuchs** [comment]
@noplanman I added it to my PR 👍
