### ISSUE TITLE
How do I create a quiz mode with comments?

### ISSUE THREAD

**Issue by emresaracoglu** [php-telegram-bot/core#1230]
Hello,
This is how I create the poll, but how do I create the poll-linked comment panel?

```
$options = array("", "", "");
return \Longman\TelegramBot\Request::sendPoll([
			'chat_id' => '',
			'question' => "",
			'options' => json_encode($options),
			'type' => 'quiz',
			'correct_option_id' => "1"
		]);
```

Example;
 
![IMG_20210626_100355](https://user-images.githubusercontent.com/297968/123505148-0c854180-d666-11eb-9aca-da74316ac207.jpg)

Thank you.

**Comment by noplanman** [comment]
Hi @emresaracoglu, this has nothing to do with the quiz, but is instead an integral part of Telegram.

Look here: https://adby.io/telegram-discussion/
