### ISSUE TITLE
Test message

### ISSUE THREAD

**Issue by jbello94** [php-telegram-bot/core#1234]
Hi, 
How i can catch everywhere  message, eg: When the user send /start the bot call the clase StartCommand, but When the user send any word how catch it?? Thanks

**Comment by jacklul** [comment]
You will want to check [GenericmessageCommand.php](https://github.com/php-telegram-bot/core/blob/develop/src/Commands/SystemCommands/GenericmessageCommand.php) (create your own based on it) for that.

**Comment by jbello94** [comment]
Thanks, i catch it
