### ISSUE TITLE
enableExternalMySql with table prefix add also 'telegram_' prefix

### ISSUE THREAD

**Issue by appoodeh** [php-telegram-bot/core#1236]
Assume that my tables are `XXX_callback_query`, `XXX_chat`, etc
Then this statment
`$telegram->enableMySql($config['mysql'], 'XXX_');`
work quite fine, But this one
`$telegram->enableExternalMySql($db, 'XXX_');`
will return this error
`telegram_bot.ERROR: Longman\TelegramBot\Exception\TelegramException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXX_telegram_update' doesn't exist`
It appends `'telegram_'` to the prefix

**Comment by jacklul** [comment]
The table is called **telegram_update** - [see here]( https://github.com/php-telegram-bot/core/blob/develop/structure.sql#L263)

Remember that if you use custom prefix you have to modify table names in **structure.sql** prior to executing it

**Comment by appoodeh** [comment]
That is right
Thanks
