### ISSUE TITLE
reply message

### ISSUE THREAD

**Issue by vadimoncheck** [php-telegram-bot/core#1237]
Hi.
This question - the client writes a message to the bot, the bot sends it to a closed group, in this group there are people who respond to such messages using the reply function, and the bot must send a response to the client that wrote this message. Can you help?
![image](https://user-images.githubusercontent.com/75079100/127652855-f829395f-70e6-4c04-999e-20af9aa30c2f.png)
![image](https://user-images.githubusercontent.com/75079100/127652927-b1089534-de65-450b-b361-cd721348c21a.png)

**Comment by noplanman** [comment]
The bot needs to be in the group as well, of course, as an administrator.

Then you should be able to get the message that is being replied to (the client message in the group). That should then also allow you to get the original message. From that message you can get the private chat ID and send a message there.

I haven't tested this with code right now, but something like that should work 😁 

Let me know how it goes!

**Comment by vadimoncheck** [comment]
I found a solution

**Comment by noplanman** [comment]
Care to share your solution for others who might have the same issue?

**Comment by vadimoncheck** [comment]
I did so I told you, but it did not help. And the solution is very simple.
In the message from the client attached his id, and then parsed message like this 
![image](https://user-images.githubusercontent.com/75079100/127958223-6c832b59-c282-484d-8584-60370dd2a3de.png)

![image](https://user-images.githubusercontent.com/75079100/127958180-c60a952b-1e11-48ba-80fa-395500f47aa5.png)

![image](https://user-images.githubusercontent.com/75079100/127957920-154d1e0d-d3dc-43e9-a384-8a556915ea97.png)
