### ISSUE TITLE
InlineKeyboard with constructor parameters

### ISSUE THREAD

**Issue by TiiFuchs** [php-telegram-bot/core#1239]
It's currently not that transparent without reading the documentation how to construct a InlineKeyboard. This is mostly because the __construct of InlineKeyboard (respectively Keyboard) uses func_get_args() to get the parameters. 
An IDE like PhpStorm is unable to hint this.

A better approach would be to use 
```
public function __construct(...$rows)
``` 
to give a hint that every Keyboard row can be passed via multiple parameters.

**Comment by noplanman** [comment]
Agreed! Feel free to PR 👍

This is still from pre PHP 5.6 times...

**Comment by henggedaren** [comment]
I have the same problem.
If my InlineKeyboard data is obtained from the database, I will not be able to pass in parameters when the new object is used.

**Comment by TiiFuchs** [comment]
Closed for #1297
