### ISSUE TITLE
Async mode for handleGetUpdates

### ISSUE THREAD

**Issue by danteif** [php-telegram-bot/core#1240]
#### Summary

Hi. This library is in my opinion the best solution.
At the moment, synchronous requests are now used to receive telegram updates.
It would be nice if this library could receive updates asynchronously.
For example, this could be used in conjunction with such solutions:
https://www.swoole.co.uk/
https://github.com/hyperf/hyperf
https://laravel.com/docs/8.x/octane

**Comment by jacklul** [comment]
I don't see any reason to implement this into the library while this can be implemented by extending **Telegram** class and rewriting `handleGetUpdates` method.
