### ISSUE TITLE
How to run another command from Callbackquery

### ISSUE THREAD

**Issue by hasbi204** [php-telegram-bot/core#1241]
I want, when the user presses the **"kembali"** button, it will automatically be directed to the Start command. My **CallbackqueryCommand.php** like this:

```
<?php

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Conversation;
use Longman\TelegramBot\Request;

class CallbackqueryCommand extends SystemCommand
{
    protected $name = 'callbackquery';
    protected $description = 'Callbackquery Command';
    protected $version = '1.1';
    protected $need_mysql = true;

    public function execute()
    {
        require 'config.php';
        $getCallbackQuery = $this->getCallbackQuery();
        $user_id = $getCallbackQuery->getFrom()->getId();
        $getData = $getCallbackQuery->getData();
        $mess_id = $getCallbackQuery->getMessage()->getMessageId();
        
        if ($getData == 'kembali') {
            return $this->getTelegram()->executeCommand('Start');
        }
        //code........
    }
}
```
But it doesn't work, is there any other alternative?

**Comment by jacklul** [comment]
How does your start command code look like? It has to take into consideration that update object passed to it will be either **Message** or **CallbackQuery**.

**Comment by hasbi204** [comment]
where should i add the code? in the start command or Callbackquery?

**Comment by jacklul** [comment]
> where should i add the code? in the start command or Callbackquery?

Depends which approach you take, the first code would go to **StartCommand** and if you choose the alternative method it would replace `$this->getTelegram()->executeCommand('Start');` call.

**Comment by hasbi204** [comment]
> How does your start command code look like? It has to take into consideration that update object passed to it will be either **Message** or **CallbackQuery** so at the top of your **StartCommand** you need something like this:
> 
> ```
> if ($message = $this->getMessage()) {
> 	$user_id = $message->getFrom()->getId();
> } elseif ($callback_query = $this->getCallbackQuery()) {
> 	$user_id = $callback_query ->getFrom()->getId();
> }
> ```
> 
> _if you're using any other variables you have to adjust this code_
> 
> An alternative approach would be instantiating **StartCommand** with fake **Update** object:
> 
> ```
> (new StartCommand(
> 	$this->getTelegram(),
> 	new Update([
> 		'update_id' => -1,
> 		'message'   => [
> 			'message_id' => -1,
> 			'date'       => time(),
> 			'from'       => $callback_query->getFrom()->getRawData(),
> 			'chat'       => $callback_query->getFrom()->getRawData(),
> 			'text'       => '/start',
> 		],
> 	])
> ))->preExecute();
> ```
> 
> _untested code, replaces **executeCommand** call_

I've added the code in the start command but it still doesn't work:
```
class StartCommand extends SystemCommand
{
    protected $name = 'start';
    protected $description = 'Start Command';
    protected $usage = '/start';
    protected $version = '1.1';
    protected $private_only = true;

    public function execute()
    {
        require 'config.php';
        $message = $this->getMessage();
        $message_id = $message->getMessageId();
        $getFirstName = $message->getFrom()->getFirstName();
        $getLastName = $message->getFrom()->getLastName();
        
        if ($message = $this->getMessage()) {
            $user_id = $message->getFrom()->getId();
        } elseif ($this->getCallbackQuery()) {
            $user_id = $this->getCallbackQuery()->getFrom()->getId();
        }

        $data['chat_id'] = $user_id;
        $data['parse_mode'] = 'markdown';
        $data['text'] = 'Hello *' . $getFirstName . ' ' . $getLastName . '*' ;
        return Request::sendMessage($data);
```

**Comment by jacklul** [comment]
It probably errors out at this line
```php
        $message_id = $message->getMessageId();
```
because `$message` is null when called from **Callback Query**, you need to put that code in `if ($message = $this->getMessage()) {` and similarly grab same data from callback query in the next statement.

**Comment by hasbi204** [comment]
> It probably errors out at this line `$message_id = $message->getMessageId();` because `$message` is null when called from **Callback Query**. Something like this should work:
> 
> ```
>         require 'config.php';
>         if ($message = $this->getMessage()) {
>             $user_id = $message->getFrom()->getId();
>             $message_id = $message->getMessageId();
>             $getFirstName = $message->getFrom()->getFirstName();
>             $getLastName = $message->getFrom()->getLastName();
>         } elseif ($callback_query = $this->getCallbackQuery()) {
>             $user_id = $callback_query->getFrom()->getId();
>             $message_id = $callback_query->getMessage()->getMessageId();
>             $getFirstName = $callback_query->getFrom()->getFirstName();
>             $getLastName = $callback_query->getFrom()->getLastName();
>         }
> ```

Work well! I really thank you sir for your help, very helpful 🙏
