### ISSUE TITLE
Problem with ngrok

### ISSUE THREAD

**Issue by wajdiToumi** [php-telegram-bot/core#1242]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  |0.64.0
| PHP version               | 7.4.0
| MySQL version             | 5.7
| Update Method             | Webhook

#### Summary
Hi i'm trying  to debbug my chatbot with xdebug on local the problem when i send my response (Request::sendMessage) to telegram i get TelegramException who says "Telegram returned an invalid response!"
I'm using **ngrok.io** to connect to my localhost with setting webhook on ngrok address 
Thank you

**Comment by noplanman** [comment]
Instead of using a webhook, try with the getUpdates method. That way you should see directly where the problem occurs.

Also, do you have any custom commands defined? If so, try to add *only* the command you're testing.
