### ISSUE TITLE
I have a question about inlinekeyboard

### ISSUE THREAD

**Issue by henggedaren** [php-telegram-bot/core#1243]
I have the same problem.
If my InlineKeyboard data is obtained from the database, I will not be able to pass in parameters when the new object is used.

or

```php
       $inline1 =[
            ['text' => '📢 ', 'callback_data' => '1'],
            ['text' => '🤦 ‍', 'callback_data' => '1']
        ];
        
        $inline2 = [
            ['text' => '📢 ', 'callback_data' => '1'],
            ['text' => '🤦‍ ', 'callback_data' => '1']
        ];
        
        $inline3 = [
            ['text' => '📢 ', 'callback_data' => '1'],
            ['text' => '🤦‍ ', 'callback_data' => '1']
        ];
        $inline_keyboard = new InlineKeyboard($inline1,$inline2,$inline3);
```

Can I dynamically pass in parameters? Because my data may be obtained through a database.

Please...

**Comment by noplanman** [comment]
@henggedaren Not sure I understand.

As long as you get the data from your database before building the keyboard, you can use it to generate your keyboard buttons.

**Comment by henggedaren** [comment]
> I have the same problem.
> If my InlineKeyboard data is obtained from the database, I will not be able to pass in parameters when the new object is used.
> 
> or
> 
> ```
>        $inline1 =[
>             ['text' => '📢 ', 'callback_data' => '1'],
>             ['text' => '🤦 ‍', 'callback_data' => '1']
>         ];
>         
>         $inline2 = [
>             ['text' => '📢 ', 'callback_data' => '1'],
>             ['text' => '🤦‍ ', 'callback_data' => '1']
>         ];
>         
>         $inline3 = [
>             ['text' => '📢 ', 'callback_data' => '1'],
>             ['text' => '🤦‍ ', 'callback_data' => '1']
>         ];
>         $inline_keyboard = new InlineKeyboard($inline1,$inline2,$inline3);
> ```
> 
> Can I dynamically pass in parameters? Because my data may be obtained through a database.
> 
> Please...

**Comment by henggedaren** [comment]
> @henggedaren Not sure I understand.
> 
> As long as you get the data from your database before building the keyboard, you can use it to generate your keyboard buttons.

`$inline1 =[
            ['text' => '📢 ', 'callback_data' => '1'],
            ['text' => '🤦 ‍', 'callback_data' => '1']
        ];
        
        $inline2 = [ ];
        
        $inline3 = [
            ['text' => '📢 ', 'callback_data' => '1'],
            ['text' => '🤦‍ ', 'callback_data' => '1']
        ];
        $inline_keyboard = new InlineKeyboard($inline1,$inline2,$inline3);`


If $inline2 is empty, it cannot be executed successfully.

But I'm not sure about the data of $inline2. It may be empty

**Comment by jacklul** [comment]
A row in inline keyboard cannot be empty, in that case you should not be adding `$inline2` to the keyboard at all.

**Comment by henggedaren** [comment]
> A row in inline keyboard cannot be empty, in that case you should not be adding `$inline2` to the keyboard at all.
> 
> Perhaps you should try something like this instead:
> 
> ```
> if ($condition1) {
>     $keyboard[] = [
>         ['text' => '📢 ', 'callback_data' => '1'],
>         ['text' => '🤦 ‍', 'callback_data' => '1']
>     ];
> }
> 
> if ($condition2) {
>     $keyboard[] = [
>         ['text' => '📢 ', 'callback_data' => '2'],
>         ['text' => '🤦 ‍', 'callback_data' => '2']
>     ];
> }
> 
> if ($condition3) {
>     $keyboard[] = [
>         ['text' => '📢 ', 'callback_data' => '3'],
>         ['text' => '🤦 ‍', 'callback_data' => '3']
>     ];
> }
> 
> $inline_keyboard = new InlineKeyboard(...$keyboard);`
> ```
> 
> Replace `$condition1`, `$condition2`, `$condition3` with your conditions or remove the if statement when it's not needed.

Great, thank you very much
