### ISSUE TITLE
I need to listen to all text messages

### ISSUE THREAD

**Issue by henggedaren** [php-telegram-bot/core#1244]
I need to listen to all text messages of the user, but I can't get text in genericcommand.php. I need to get information without "/", but it seems that filtering is done here. Only "/ ABC" type information can be obtained.

Please give me a demo that can get any message, thank you

**Comment by jacklul** [comment]
Use **GenericmessageCommand.php** instead for non-command messages.

**Comment by henggedaren** [comment]
> 使用**GenericmessageCommand.php**代替非命令消息。这将允许获取**消息**类型更新中存在的所有类型的消息- https://core.telegram.org/bots/api#message。

我复制了GenericmessageCommand.php到Commands目录下，并做了log,但仍然没有获取到消息。我代码有什么问题么？

`<?php

/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Telegram;

/**
 * Generic message command
 */
class GenericmessageCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = Telegram::GENERIC_MESSAGE_COMMAND;

    /**
     * @var string
     */
    protected $description = 'Handle generic message';

    /**
     * @var string
     */
    protected $version = '1.2.0';

    /**
     * @var bool
     */
    protected $need_mysql = true;

    /**
     * Execution if MySQL is required but not available
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function executeNoDb(): ServerResponse
    {
        // Try to execute any deprecated system commands.
        if (self::$execute_deprecated && $deprecated_system_command_response = $this->executeDeprecatedSystemCommand()) {
            return $deprecated_system_command_response;
        }

        return Request::emptyResponse();
    }

    /**
     * Execute command
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute(): ServerResponse
    {
        $message = $this->getMessage();

        file_put_contents('./message.txt',$message);

        // Try to continue any active conversation.
        if ($active_conversation_response = $this->executeActiveConversation()) {
            return $active_conversation_response;
        }

        // Try to execute any deprecated system commands.
        if (self::$execute_deprecated && $deprecated_system_command_response = $this->executeDeprecatedSystemCommand()) {
            return $deprecated_system_command_response;
        }

        return Request::emptyResponse();
    }
}
`

**Comment by henggedaren** [comment]
> Use **GenericmessageCommand.php** instead for non-command messages. This will allow getting all types of messages present in **Message** type update - https://core.telegram.org/bots/api#message.

I copied genericmessagecommand.php to the commands directory and made a log, but I still didn't get the message. What's wrong with my code?

`<?php

/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Telegram;

/**
 * Generic message command
 */
class GenericmessageCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = Telegram::GENERIC_MESSAGE_COMMAND;

    /**
     * @var string
     */
    protected $description = 'Handle generic message';

    /**
     * @var string
     */
    protected $version = '1.2.0';

    /**
     * @var bool
     */
    protected $need_mysql = true;

    /**
     * Execution if MySQL is required but not available
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function executeNoDb(): ServerResponse
    {
        // Try to execute any deprecated system commands.
        if (self::$execute_deprecated && $deprecated_system_command_response = $this->executeDeprecatedSystemCommand()) {
            return $deprecated_system_command_response;
        }

        return Request::emptyResponse();
    }

    /**
     * Execute command
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute(): ServerResponse
    {
        $message = $this->getMessage();

        file_put_contents('./message.txt',$message);

        // Try to continue any active conversation.
        if ($active_conversation_response = $this->executeActiveConversation()) {
            return $active_conversation_response;
        }

        // Try to execute any deprecated system commands.
        if (self::$execute_deprecated && $deprecated_system_command_response = $this->executeDeprecatedSystemCommand()) {
            return $deprecated_system_command_response;
        }

        return Request::emptyResponse();
    }
}
`

**Comment by jacklul** [comment]
If you're not using mysql connection use `executeNoDb` method for your code

**Comment by henggedaren** [comment]
> If you're not using mysql connection use `executeNoDb` method for your code

Thank you very much for your reply, but I still didn't get the message without DB code.

I need to get all messages sent by users, including messages that do not start with "/"

**Comment by henggedaren** [comment]
> > If you're not using mysql connection use `executeNoDb` method for your code
> 
> Thank you very much for your reply, but I still didn't get the message without DB code.
> 
> I need to get all messages sent by users, including messages that do not start with "/"

I found the problem.

Because genericmessagecommand.php exists elsewhere, the code I wrote did not execute

Thank you again
