### ISSUE TITLE
Sending Messages To Individual Telegram Users ( Not a Channel ) via PHP

### ISSUE THREAD

**Issue by marcoczen** [php-telegram-bot/core#1245]
Hi,

Right now, my php app has the ability to send email reminders to users via phpmailer. 
So i am looking for a telegram equivalent. The users cell / mobile phone number is stored in my app.

How do we do this using your library  ? 
I have seen some tutorials in youtube but they are more about sending messages to a telegram group instead of individuals.

Thanks.

**Comment by jacklul** [comment]
You cannot send messages to phone numbers on Telegram.
Users would have to explicitly authenticate your bot through https://core.telegram.org/widgets/login

**Comment by marcoczen** [comment]
My replies below ...

> You cannot send messages to phone numbers on Telegram.

Noted. 

> Users would have to explicitly authorize your bot through https://core.telegram.org/widgets/login and for you to grab their User ID

1. There is some code at https://gist.github.com/anonymous/6516521b1fb3b464534fbc30ea3573c2 

So, if  step 1 is done, will your library then be able to send messages to the user directly or is your library no longer needed  as eveything done by step 1 ?

**Comment by jacklul** [comment]
After you get user's ID you will still need a code for sending the messages. 
If that's all what you need then you could skip the library and just send Post requests to `https://api.telegram.org/botTOKEN/sendMessage` with [proper fields](https://core.telegram.org/bots/api#sendmessage), in case of private chat with the user the Chat ID = User ID.

Library usage example:
```php
$telegram_bot = new Longman\TelegramBot\Telegram($token); // Needs initialization for Request class
$result = Longman\TelegramBot\Request::sendMessage([
      'chat_id' => $user_id,
      'text' => 'Hello',
]);

if (!$result->isOk()) {
      error_log($result->getDescription()); // log error
} // else success
```

**Comment by TiiFuchs** [comment]
Looks like it was answered. :)
