### ISSUE TITLE
reply_markup is not working with sendGame

### ISSUE THREAD

**Issue by pavanyogi** [php-telegram-bot/core#1246]
working code:
`/**
     * Main command execution
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute(): ServerResponse
    {

        $message = $this->getMessage();
        $chat_id = $message->getChat()->getId();
        $text = $message->getText();

        if ($text === 'game') {
            $data = [
                'chat_id' => $chat_id,
                'game_short_name' => 'qbix_bot_game2' // change this game short name to as per your game short name
            ];
            return Request::sendGame($data);
        }

        return Request::emptyResponse();
    }`

not working code:
`/**
     * Main command execution
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute(): ServerResponse
    {

        $message = $this->getMessage();
        $chat_id = $message->getChat()->getId();
        $text = $message->getText();

        if ($text === 'game') {
            $data = [
                'chat_id' => $chat_id,
                'game_short_name' => 'qbix_bot_game2', // change this game short name to as per your game short name
                'reply_markup' => json_encode([
                    'inline_keyboard'=>[
                        [
                            ['text'=>"Play",'callback_data'=> time()]
                        ]
                    ]
                ])
                ];
            return Request::sendGame($data);
        }

        return Request::emptyResponse();
    }`

**Comment by jacklul** [comment]
Not working as not showing up in the message or the message doesn't even get send?

I've tested the **reply_markup** data with **sendMessage** method and it seems to work fine.

Have you considered using object-oriented approach for building the inline keyboard? Example below.
```php
$result = Request::sendGame([
    'chat_id' => $chat_id,
    'game_short_name' => 'qbix_bot_game2', // change this game short name to as per your game short name
    'reply_markup' => new InlineKeyboard([
        new InlineKeyboardButton([
            'text'=>"Play",
            'callback_data'=> time()
        ])
    ]),
]);

if ($result->isOk()) {
    return $result;
}

throw new Exception($result->getDescription());
```

**Comment by pavanyogi** [comment]
Ok. I tried the above code. It seems to be working but there appeared some other errors. The error is:
PHP Fatal error:  Uncaught Exception: Bad Request: REPLY_MARKUP_GAME_EMPTY

**Comment by pavanyogi** [comment]
Meanwhile, our repo is: https://github.com/Qbix/TelegramPlayground and the related command folder is Commands/Custom

**Comment by jacklul** [comment]
I believe the first button in the keyboard should contain `callback_game` variable, not `callback_data`.
https://core.telegram.org/bots/api#sendgame

**Comment by pavanyogi** [comment]
The custom play button is working now. 
Thanks.
