### ISSUE TITLE
setGameScore is not working(due to different $_SESSION variables on CallbackqueryCommand.php and index.php pages) with php telegram bot.

### ISSUE THREAD

**Issue by pavanyogi** [php-telegram-bot/core#1247]
### ❓ Support Question

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Ubuntu-16.04
| PHP Telegram Bot version  | 0.73.1
| PHP version               | 7.3.27
| MySQL version             | 5.7.3
| Update Method             | Webhook using ngrok
| Self-signed certificate   |  no
| RAW update (if available) | `{...}`

#### Summary
setGameScore is not working(due to different $_SESSION variables on CallbackqueryCommand.php and index.php pages) with php telegram bot.

Actually i am trying to convert nodejs code of this article (https://www.freecodecamp.org/news/how-to-code-chromes-t-rex-as-a-telegram-game-using-node-js-cbcf42f76f4b/) into php code, so tha t i can set setGameScore.

repo url: https://github.com/Qbix/TelegramPlayground

```php
//CallbackqueryCommand.php

public function execute(): ServerResponse
    {
        session_start();

        // Callback query data can be fetched and handled accordingly.
        $callback_query = $this->getCallbackQuery();
        $callback_data = $callback_query->getData();

        $queryId = $callback_query->getId();
        $_SESSION['qbix_'.$queryId] = $callback_query;

        $gameUrl = 'https://' . $_SERVER['SERVER_NAME'] . '/public/index.php?id='.$queryId;

        return $callback_query->answer([
            'text' => $callback_data,
            'show_alert' => (bool)random_int(0, 1), // Randomly show (or not) as an alert.
            'cache_time' => 5,
            'url' => $gameUrl
        ]);
    }
```

```php
//index.php
<?php
session_start();
?>

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=no">
    <title >chrome easter egg: t-rex runner</title>
    <link rel="stylesheet" href="index.css">
    <script src="index.js"></script>
</head>

<body id="t" class="offline">
<?php echo session_id(); echo '<br>'; echo ini_get('session.cookie_domain'); ?>
    <div id="main-frame-error" class="interstitial-wrapper">
        <div id="main-content">
            <div class="icon icon-offline" alt=""></div>
        </div>
        <div id="offline-resources">
            <img id="offline-resources-1x" src="assets/default_100_percent/100-offline-sprite.png">
            <img id="offline-resources-2x" src="assets/default_200_percent/200-offline-sprite.png">
            <template id="audio-resources">
                <audio id="offline-sound-press" src="data:audio/mpeg;base64,T2dnUwACAAAAAAAAAABVDxppAAAAABYzHfUBHgF2b3JiaXMAAAAAAkSsAAD/////AHcBAP////+4AU9nZ1MAAAAAAAAAAAAAVQ8aa....XAEEyAAEoADiPAAIcHGccHEAxN271+bn5+dt4B2YmGziAIrZMgZ4l2nedkACHggIAA=="></audio>
            </template>
        </div>
     </div>   
     <p id="sendingText" style="text-align: center;font-family:Arial, Helvetica, sans-serif;display:none;">Saving highscore...</p>
</body>

</html>
```

**Comment by pavanyogi** [comment]
`//index.php
<?php
session_start();
?>

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=no">
    <title >chrome easter egg: t-rex runner</title>
    <link rel="stylesheet" href="index.css">
    <script src="index.js"></script>
</head>

<body id="t" class="offline">
<?php echo session_id(); echo '<br>'; echo ini_get('session.cookie_domain'); ?>
    <div id="main-frame-error" class="interstitial-wrapper">
        <div id="main-content">
            <div class="icon icon-offline" alt=""></div>
        </div>
        <div id="offline-resources">
            <img id="offline-resources-1x" src="assets/default_100_percent/100-offline-sprite.png">
            <img id="offline-resources-2x" src="assets/default_200_percent/200-offline-sprite.png">
            <template id="audio-resources">
                <audio id="offline-sound-press" src="data:audio/mpeg;base64,T2dnUwACAAAAAAAAAABVDxppAAAAABYzHfUBHgF2b3JiaXMAAAAAAkSsAAD/////AHcBAP////+4AU9nZ1MAAAAAAAAAAAAAVQ8aa....XAEEyAAEoADiPAAIcHGccHEAxN271+bn5+dt4B2YmGziAIrZMgZ4l2nedkACHggIAA=="></audio>
            </template>
        </div>
     </div>   
     <p id="sendingText" style="text-align: center;font-family:Arial, Helvetica, sans-serif;display:none;">Saving highscore...</p>
</body>

</html>`

**Comment by pavanyogi** [comment]
[index.txt](https://github.com/php-telegram-bot/core/files/7195057/index.txt)

**Comment by pavanyogi** [comment]
https://github.com/Qbix/TelegramPlayground/blob/main/public/index.php

**Comment by noplanman** [comment]
The library isn't supposed to be used like you're trying.

Your web project needs to expose an API endpoint to update the score, just like the NodeJS version of the link you sent.

There are 2 different components in play that interact together:
- Web server that manages the highscore
- Telegram Bot that manages the game

I hope that makes sense to you 😊
