### ISSUE TITLE
How to forward an album?

### ISSUE THREAD

**Issue by A-H-Pooladvand** [php-telegram-bot/core#1250]
How to forward albums which contains multiple medias in telegram? I couldn't find any method in the package neither in telegram api, but my friend does that with his python package

**Comment by jacklul** [comment]
The only thing that comes to my mind is using `[sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup)` and copying file unique ids, that should send completely new album that looks like the original one.

**Comment by noplanman** [comment]
I would have said `sendMediaGroup` too, but maybe you can ask your friend how they do it in Python?

You could then share their version here and we can figure out how to do it in PHP.

**Comment by A-H-Pooladvand** [comment]
@noplanman I think that he uses an implementation of telegram API which supports [forwardMessages](https://core.telegram.org/method/messages.forwardMessages) that I believe is for users and not bots.
and because of that he can forward an album nicely
I'm not sure if there's any implementation of telegram api in php that I can use but for now I close this for now...

**Comment by noplanman** [comment]
Right, that makes sense!

You might want to check out [MadelineProto](https://docs.madelineproto.xyz/), I haven't used it but it's compatible with user bots.
