### ISSUE TITLE
Share Contact button in group

### ISSUE THREAD

**Issue by asif-rahman** [php-telegram-bot/core#1253]
### ❓ Support Question

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | WIndows 7
| PHP version               |5.5.12
| Update Method             | Webhook 
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

setRequestContact button seems not working in group. Survey command is running ok in private chat but not working in group. It stucks on share location (not showing any button), is there any way to get it working?

**Comment by jacklul** [comment]
> Available in private chats only

https://core.telegram.org/bots/api#keyboardbutton
