### ISSUE TITLE
Ability to identify texts as commands

### ISSUE THREAD

**Issue by pouriaho** [php-telegram-bot/core#1257]
### 🎉 Feature Request

Hi. Most telegram robots do not use commands that are in the « **/command** » format!

And use plain text as a command.
For example, in these robots, when the robot starts, a keyboard with different buttons is displayed to the user. Each of these buttons is a different command in that robot. When the user clicks on each one, he receives different answers from the robot.

In your library, it is only possible to specify commands in the « **/command** » format (I mean the **Commands** folder in the source code)

Please address this issue so that we can specify plain text as a command. For example, when a user sends the following text to a robot, we will send different responses to the user:

1. **Help** => Show bot commands help
2. **Bot Language** => Sending a message with inline keyboard that the user can choose his language
3. **Settings** => Sending a message that the user can change the bot settings
4. etc....

Thank you :)

**Comment by jacklul** [comment]
You can handle text messages in **GenericmessageCommand**.
