### ISSUE TITLE
All group members

### ISSUE THREAD

**Issue by Shyghar** [php-telegram-bot/core#1261]
Hi, 
I want to create a command to check if all members inside a group have the name with a specific pattern so I need to have the full memebers list. 
How can I achieve this? 
Can I only check the newEntry of a group through this library?

Thank you ^^

**Comment by jacklul** [comment]
Bots API does not have any function that would fetch the full members list. You can do that with userbot though (a bot running under regular TG account).
Your best bet would have to make the bot track all the users that enter and exit the group from it's creation.
