### ISSUE TITLE
do we have some sample examples of bot-menu in telegram bot?

### ISSUE THREAD

**Issue by pavanyogi** [php-telegram-bot/core#1262]
### ❓ Support Question

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Ubuntu 16.04
| PHP Telegram Bot version  | 0.73.1
| PHP version               | 7.3.27
| MySQL version             | 8.0.25
| Update Method             | Webhook
| Self-signed certificate   | yes
| RAW update (if available) | `{...}`

#### Summary
We need to add a menu in our telegram bot. I found some information here ()https://telegram.org/blog/animated-backgrounds#bot-menu but could not find the exact steps to add this functionality in the telegram bot. If we can have some examples/process documentation of this functionality, then it will be helpful.  

[](https://telegram.org/file/464001166/3/vI1QCxRW7Yc.3947785.mp4/98848ff44541f3c32d)

**Comment by pavanyogi** [comment]
![menu in telegram bot](https://user-images.githubusercontent.com/13834016/144880281-1162f8cf-1f35-43d6-9aed-8a21cc5b8b66.jpg)

**Comment by VVBphp** [comment]
[Already implemented](https://github.com/php-telegram-bot/core/blob/5e2e3e541be71dd5f0bae34daf9775c97afe2704/src/Request.php#L83)

**Comment by yudaapratama** [comment]
you can add command in botfather

**Comment by jacklul** [comment]
Just an example:

```php
$result = Request::setMyCommands([
	'scope' => new BotCommandScopeDefault(),
	'commands' => [
		new BotCommand(
			[
				'command' => 'settings',
				'description' => 'Change settings',
			]
		),
	],
]);
```

More available scopes are in `\src\Entities\BotCommandScope` - https://core.telegram.org/bots/api#botcommandscope

**Comment by pavanyogi** [comment]
Thanks @jacklul and @yudaapratama for providing useful insight. Yes, we can add a menu in the telegram bot using both ways. I found a SO answer also. Here is the [link](https://stackoverflow.com/questions/34457568/how-to-show-options-in-telegram-bot/34458436#34458436) 

'''
Talk to BotFather.

In the Telegram App, open the chat with BotFather.

Send him /setcommands. He will present you with a list of your bots.

Pick the bot for which you want to set the command menu.

Compose and send the command list. Using your image as an example, these 4 lines should do:

start - Description 1
menu - Description 2
help - Description 3
stop - Description 4

Note that the command part of each line(left side of - signs) must have just lowercase characters and no slashes. There should also be spaces around the - sign.

Once you complete this process, exit and kill the Telegram App. Re-open it, go to the chat with your target bot, type a / (or tab on the / button next to the text field), the command menu should come up.
'''

**Comment by TiiFuchs** [comment]
Looks like the question was answered, right?
