### ISSUE TITLE
How to request channels.getParticipants

### ISSUE THREAD

**Issue by Emaxoso** [php-telegram-bot/core#1263]
Hi, I'm trying to call the [channels.getParticipants](https://core.telegram.org/method/channels.getParticipants) function but I can't find it inside the Request class is there another way to call this?

If it's not implemented yet, is there a temporary method to call the function using the library?

**Comment by jacklul** [comment]
What you linked is Telegram API, not Telegram **Bots** API.
For bots check it out here: https://core.telegram.org/bots/api
