### ISSUE TITLE
Channel comments

### ISSUE THREAD

**Issue by Shyghar** [php-telegram-bot/core#1269]
### ❓ How can I comment a channel post? 

Example:       

             `public function execute(): ServerResponse {     
                $userTL = $this->getMessage()->getFrom();      
                $data['chat_id'] = '-10********';       
                $data['parse_mode'] = 'markdown';      
                $data['caption'] = 'markdown';      
                $data['text'] = 'Example *channel post*';       
                        
                $post= Request::sendMessage($data);   

                 // I want to comment this post 
                // and save the discussion link
                $postDirectLink = 't.me/'.$data['chat_id'].'/'.$post->result->message_id  ;

            return $this->replyToChat(
                    'Ciao!' . PHP_EOL . PHP_EOL .
                    $postDirectLink . PHP_EOL . PHP_EOL .
                    print_r($post, true)
                );
            }`

In this command I want to post a message in my channel and then tag some user in the 1st comment of the channel discussion. How can I achieve this?

**Comment by noplanman** [comment]
Hi @Shyghar 

Unfortunately I don't understand what you'd like to achieve.
Could you please explain in a bit more detail?

Thanks!

**Comment by Hitmare** [comment]
As far as i could read in the Bot API Docs https://core.telegram.org/bots/api there is no way for the Bot to make Comments in a channel, exept it may be handled as an reply

**Comment by Hitmare** [comment]
Ok i figured out how you could do it. You need a Group linked to the Channel. If you Post a message in the Channel it will appear as a Message in the Group. If you then reply on the Message of the Group, it will appear as a Comment in the Channel Post

**Comment by noplanman** [comment]
@Shyghar Have you managed to figure out what you were trying to achieve?

Look at the comments that @Hitmare posted, that should help!

**Comment by TiiFuchs** [comment]
Closed due to lack of additional feedback.
