### ISSUE TITLE
Line Break

### ISSUE THREAD

**Issue by strtob** [php-telegram-bot/core#1271]
#### Summary

Great Extension! How can I insert a line break? I've tried \n without any success...

cheers!
Toby

**Comment by jacklul** [comment]
These work:
```php
Request::sendMessage([
    'chat_id' => $this->getMessage()->getChat()->getId(),
    'text' => "test\n123",
]);
Request::sendMessage([
    'chat_id' => $this->getMessage()->getChat()->getId(),
    'text' => 'test' . PHP_EOL . '123',
]);
```

You probably tried `\n` with single quote which will not work.
[What is the difference between single-quoted and double-quoted strings in PHP?](https://stackoverflow.com/questions/3446216/what-is-the-difference-between-single-quoted-and-double-quoted-strings-in-php)
