### ISSUE TITLE
Instead of getCommand it should be getMessage 

### ISSUE THREAD

**Issue by vaterno** [php-telegram-bot/core#1272]
From a fake user we receive the text (!!!) in the form of a command.
Therefore `getText` should be used instead of `getCommand`.

https://github.com/php-telegram-bot/core/blob/5d631c36d6635da650c3689634557e11cb2cebd6/src/Telegram.php#L1201-L1208

https://github.com/php-telegram-bot/core/blob/5d631c36d6635da650c3689634557e11cb2cebd6/src/Telegram.php#L1221

**Comment by Hitmare** [comment]
you can get the command with getText(true)

**Comment by noplanman** [comment]
@vaterno Can you elaborate a bit what the problem is please?

**Comment by TiiFuchs** [comment]
Closed because we didn't get any feedback.
