### ISSUE TITLE
Run my own Bot API server

### ISSUE THREAD

**Issue by sallsabil** [php-telegram-bot/core#1273]
Hi

To run my own Bot API server by php-telegram-bot do I need tdlib ?

**Comment by TiiFuchs** [comment]
You can run your own Bot API Server by running an instance of [telegram-bot-api](https://github.com/tdlib/telegram-bot-api).

When it is running you can follow this manual to switch [here](https://github.com/tdlib/telegram-bot-api#switching).

And after that you can call in your Bot `Request::setCustomBotApiUrl($apiUrl)` with your API Url.

**Comment by sallsabil** [comment]
> Hi
> 
> To run my own Bot API server by php-telegram-bot do I need tdlib ?

**Comment by sallsabil** [comment]
Thank you @TiiFuchs
I read #1168 but at last I didn't know know how to connect them to each other

**Comment by sallsabil** [comment]
I ran it locally:
`$bin: ./telegram-bot-api --api-id=***** --api-hash=*********************** --local &`

```
$telegram = new Longman\TelegramBot\Telegram(BOT_TOKEN, BOT_USERNAME);
$telegram->useGetUpdatesWithoutDatabase();

$output = Request::logOut();

$output = Request::setCustomBotApiUri(
    $api_base_uri          = 'https://example.com', // Default: https://api.telegram.org
    $api_base_download_uri = __DIR__ . "/file/bot{BOT_TOKEN}"     // Default: /file/bot{API_KEY}
);
```

What is wring with php code ?

**Comment by sallsabil** [comment]
@TiiFuchs 
I think I have a problem in this part:

> And after that you can call in your Bot `Request::setCustomBotApiUrl($apiUrl)` with your API Url.

**Comment by TiiFuchs** [comment]
> > Fatal error: Uncaught Longman\TelegramBot\Exception\InvalidBotTokenException: Invalid bot token!
> 
> What is wrong with php code ?

The Error says it all: Your Bot Token is incorrect. You should check that you BOT_TOKEN in your first line of pasted code is set correctly to the token you received from [BotFather](https://t.me/BotFather)

**Comment by sallsabil** [comment]
The token works without local settings
Should I set the webhook with http link ?

**Comment by TiiFuchs** [comment]
Which URL do you set in your setCustomBotApiUrl() call? Is the IP address correct for your local bot api server?

**Comment by sallsabil** [comment]
I use the domain https://example.com which works correctly

**Comment by TiiFuchs** [comment]
https://example.com is NOT a correct domain... You need to specify the domain or IP address (and port) of the bot api server you launched...

**Comment by sallsabil** [comment]
Yes my domain:
https://moftaneh.ir/pnjr00/getupdates.php

**Comment by TiiFuchs** [comment]
Where is your bot api server running?

**Comment by sallsabil** [comment]
germany

**Comment by sallsabil** [comment]
Can you take a look in my server ?

**Comment by TiiFuchs** [comment]
I cannot. You need to understand the basics of network communication, if you want your bot to communicate with another bot api server. I would recommend you to use the default bot api server since it's not necessary to run your own instance of a bot api server for your bot to work correctly.

**Comment by sallsabil** [comment]
Right
