### ISSUE TITLE
Cannot get message_id after a Request::sendAnimation, loop

### ISSUE THREAD

**Issue by jacklocke** [php-telegram-bot/core#1278]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  | 5.5
| PHP version               | 7.2
| MySQL version             | none
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

After sendAnimation and get the result into a variable:
```
$sendedGIF = Request::sendAnimation([
            'chat_id' => $chat_id,
            'animation'   => Request::encodeFile('./animated/loading.gif'),
        ]);
```
If I try to get last message_id:
```
$messID = $sendedGIF->getResult()->getMessage()->getId();
```

the sendAnimation loop, and send me infinite messages with the animation only.

why?

**Comment by jacklul** [comment]
If your command gets executed in a loop that might indicate that the request didn't end up with HTTP 200 status code and Telegram is assuming that the webhook request failed and keeps retrying.

**Comment by jacklocke** [comment]
1) Ok, I will check my log, but I don't really know what to do more than look the 3 .log file (error, debug, update).
How to see more? need mysql?

2) however, this is strange, because, is just that line that loop
```$messID = $sendedGIF->getResult()->getMessage()->getId();```
if I comment this everything work.

Also, the loop is just the sendAnimation, the function doesn't continue... I thinks the problem is just in this line...
is the correct way to get message_id of last send message? (that is a sendAnimation message)

3) how can I check HTTP status return of a hook called by telegram?

Thank you for help

**Comment by jacklul** [comment]
1. and 3. Webserver error log
2. Maybe because there is no `getId()` in `Message` object?, try `getMessageId()` instead?

**Comment by jacklocke** [comment]
Thanks so much! it was my fault...

It work in this way:
```
if ($sendedGIF->isOk()) {
    // get message_id of message with animated GIF
   $gifMsgID = $sendedGIF->getResult()->getMessageId();

    // do stuff...
} else {
    // Handle error - $sentGif->getDescription();
}
```
