### ISSUE TITLE
How send message with text and few images?

### ISSUE THREAD

**Issue by siamskoi** [php-telegram-bot/core#1279]
### ❓ Support Question

How send message with text and few images?
Request::sendMessage() - send only text, Request::sendPhoto() - send only one photo. Can I have example please?

**Comment by jacklul** [comment]
https://core.telegram.org/bots/api#sendmediagroup

**Comment by siamskoi** [comment]
> Use `Request::sendMediaGroup()` - https://core.telegram.org/bots/api#sendmediagroup

Yes, I also tried this method:

```
$result = Request::sendMediaGroup([
    'chat_id' => $this->channelName,
    'media' => $media,
    'text'    => $text,
]);
```

But the message is created without text.

**Comment by siamskoi** [comment]
$media is array of InputMediaPhoto: `new InputMediaPhoto(['media' => 'https://...']);

**Comment by jacklul** [comment]
It does not support text, as per documentation

**Comment by Hitmare** [comment]
As jacklul stated a album/gallery/mediagroup does not support a cation text
you can send two requests, the first as a MediaGroup and the second Text message. that way you can even decide if you want the text above or beneath the album/gallery/mediagroup

**Comment by jacklul** [comment]
Closing this as the question has been answered

**Comment by itsMoji** [comment]
You can add caption to the media group by adding a `caption` parameter to the first element of the $media array.

```php

$caption = "Your caption";

$media[] = new InputMediaPhoto(
    [
        'media' => 'https://...',
        'caption' => $caption
    ]
);

$media[] = new InputMediaPhoto(
    [
        'media' => 'https://...',
    ]
);

...
```
![Screenshot](https://user-images.githubusercontent.com/4765718/151971949-53778a78-8077-4e97-b318-66f526b45b5b.png)
