### ISSUE TITLE
Asyn bot

### ISSUE THREAD

**Issue by burov0798** [php-telegram-bot/core#1280]
### 🎉 Feature Request

How about asynchrony? Any plans to make the bot asynchronous?

**Comment by jacklul** [comment]
Async API requests or async getUpdates?

**Comment by burov0798** [comment]
> async getUpdates

**Comment by burov0798** [comment]
It is necessary that getUpdatesCLI does not wait for the execution of a command from one user, but runs a function and immediately processes the message of another user.

**Comment by jacklul** [comment]
Unfortunately this is something you will have to implement to suit your needs.
Depending on OS the server is running on amphp or spatie-async library will help you achieve this, you could probably use pthreads extension as well but I'm not sure about compatibility with the newest PHP.
