### ISSUE TITLE
Upgrade to psr/log > version 3

### ISSUE THREAD

**Issue by pud-micha** [php-telegram-bot/core#1282]
### 🎉 Feature Request

Please upgrade psr/log to version 3.x

#### Summary

Hello,

I depend on the current version of psr/log. This project still uses the outdated version 1.x.

Thanks

**Comment by nopenopenope** [comment]
I second that! I just wanted to install it into a Symfony application, but that does not seem to be compatible to each other.

**Comment by noplanman** [comment]
@pud-micha @nopenopenope 

Thanks for the poke, this will be part of the next release 👍
