### ISSUE TITLE
Implement 'Login with telegram' as a button on the website but do not want to use the telegram widget

### ISSUE THREAD

**Issue by pavanyogi** [php-telegram-bot/core#1286]
### ❓ Support Question

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Ubuntu and 20.04
| PHP Telegram Bot version  | 0.73.1
| PHP version               | 7.3.33
| MySQL version             | 8.0 / none
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary
We need to implement 'login with telegram' on our website. We won't use the Telegram Login Widget (because it is weird, asks for the phone number, etc.). I followed the LoginUrl [example](https://github.com/php-telegram-bot/core/issues/1065) and we are able to log in if a user clicks the login button inside the telegram app (as displayed in the first image). But we need a login button on our website which will say 'Login with telegram' and when the user will click on this button then the authorization should work(as displayed in the second image). Is it possible to implement such a login button with the help of the current telegram bot API?

image-1
![Screenshot from 2022-02-15 19-26-43](https://user-images.githubusercontent.com/13834016/154081917-8db7461f-a50e-419b-9188-1f20cbe52cc0.png)

image-2
![Screenshot from 2022-02-15 19-35-50](https://user-images.githubusercontent.com/13834016/154082059-9c66df8b-f75d-4dac-a149-797dca615eea.png)

**Comment by noplanman** [comment]
Hi @pavanyogi 

Asking for the phone number is default procedure, same as when you install Telegram on any device or use the web version, as the user account is linked to the phone number.

Maybe I'm misunderstanding something.

What would you like to have happen when a user clicks the "Login with Telegram" button?

**Comment by pavanyogi** [comment]
Hi @noplanman, 
Now we are ok with the existing behavior of Seamless Telegram Login. We have included the Seamless Telegram Login.

**Comment by TiiFuchs** [comment]
So no open question in this issue, right?
