### ISSUE TITLE
chats command bug

### ISSUE THREAD

**Issue by jyxjjj** [php-telegram-bot/core#1288]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | mac 12
| PHP Telegram Bot version  | 0.75.0
| PHP version               | 8.1.3
| MySQL version             | mariadb 10
| Update Method             | getUpdates
| Self-signed certificate   | no
| RAW update (if available) | `null`

#### Summary

`vendor/longman/telegram-bot/src/Entities/Chat.php:92` has an `||` operator

#### Current behaviour

All Groups and Channels shown as a Group.

```
Private Chats: 1
Groups: 29
Super Groups: 3
Channels: 0
Total: 33
```

#### How to fix

maybe remove `||` operator

or

change `vendor/longman/telegram-bot/src/Commands/AdminCommands/ChatsCommand.php:106` and `vendor/longman/telegram-bot/src/Commands/AdminCommands/ChatsCommand.php:112` 's order.

#### Expected behaviour

```
Private Chats: 1
Groups: 0
Super Groups: 3
Channels: 29
Total: 33
```

**Comment by noplanman** [comment]
Yes, we should be able to remove that now, as it's being handled in the constructor.
