### ISSUE TITLE
serialize

### ISSUE THREAD

**Issue by jyxjjj** [php-telegram-bot/core#1289]
#### Summary

I want serialize $telegram object into redis for queue.
But PDO cannot be serialized.
Can we have a __wakeup and a __sleep to reconnect PDO.

**Comment by TiiFuchs** [comment]
I will have a look into that.

For the mean time you can just extend the Telegram class and do it yourself.

It should be as simple as clearing the `$this->pdo` in the __sleep() method and recalling `enableMySql()` or `enableExternalMySql()` in the __wakeup... 

@noplanman What's your thoughts on that?

**Comment by TiiFuchs** [comment]
I discussed this with @noplanman and we think it's not worth to go the extra mile here and implement this in the project for now. 

The need to serialize is relatively small and it would not be possible to serialize it when `enableExternalMySql()` was called. Only for `enableMySql()`. 

The way to go here would be to extend the Telegram class in your own project and implement the `__wakeup()` and `__sleep()` methods like you need it.
