### ISSUE TITLE
Clone message

### ISSUE THREAD

**Issue by Shyghar** [php-telegram-bot/core#1292]
Hi, 
I'm writing a bot to 'save' messages in my private chat. 
I want a code that clone the replyed message and send it to my private chat

Is some funztion able to do it without check video, photo, document, animations, gif and so on ?

**Comment by TiiFuchs** [comment]
You should be able to use forwardMessage to redirect any type of message. Have a look at this: https://core.telegram.org/bots/api#forwardmessage

**Comment by noplanman** [comment]
@Shyghar If you literally want to send a new message, take a look at the `sendBack` method here, as an example for you to implement yourself:
https://github.com/php-telegram-bot/core/blob/956371f2e83fa86c05165ea617f1758df3ccb6bd/src/Commands/AdminCommands/SendtochannelCommand.php#L285-L313
