### ISSUE TITLE
How to use getChatJoinRequest

### ISSUE THREAD

**Issue by Negroserias** [php-telegram-bot/core#1294]
any idea?  I need create new  file command  ChatJoinRequestCommand.php  ? 

class ChatJoinRequestCommandextends SystemCommand
{}

 not working):

**Comment by TiiFuchs** [comment]
You need to create a `GenericmessageCommand`, please take a look at this example: https://github.com/php-telegram-bot/example-bot/blob/master/Commands/Group/GenericmessageCommand.php
