### ISSUE TITLE
change $api_base_uri in order to use Request class with my own server url(tdlib)

### ISSUE THREAD

**Issue by arashnz** [php-telegram-bot/core#1295]
### 🐞 Bug Report

When I use 
\Longman\TelegramBot\Request::setCustomBotApiUri(
    $api_base_uri          = 'http://myownserver:8081', // Default: https://api.telegram.org
);
and then use  \Longman\TelegramBot\Request::sendAudio it still use https://api.telegram.org as base api url.
but when I change 'private static $api_base_uri = 'http://myownserver:8081';' in request.php manually it works!

#### Required Information

| Operating system          | Centos 8
| PHP Telegram Bot version  | latest
| PHP version               | 7.4
| MySQL version             | none
| Update Method             | Webhook
| Self-signed certificate   | not sure/use it on my own server

#### Expected behaviour

When using \Longman\TelegramBot\Request::setCustomBotApiUri(
    $api_base_uri          = 'http://myownserver:8081', // Default: https://api.telegram.org
);
for all of the usage of Request:: in that page it should use http://myownserver:8081 as base api telegram url.

**Comment by TiiFuchs** [comment]
As you can see the setCustomBotApiUrl method does exactly the same as setting the variable:
https://github.com/php-telegram-bot/core/blob/72528b72cbc576ebb86652a2541838817c0a0bec/src/Request.php#L324-L330

But the Request::initialize method copies the base_uri from the static property into a Client object.
See https://github.com/php-telegram-bot/core/blob/3cf50e76c3a4809e476b4cd274a3b22783b78882/src/Request.php#L302-L306

This initialize() method gets called in the constructor of the Telegram class...

So you need to call Request::setCustomBotApiUri BEFORE you instantiate a new Telegram class.

```
\Longman\TelegramBot\Request::setCustomBotApiUri('http://myownserver:8081/');
$bot = new Longman\TelegramBot\Telegram($token, $username);
```

For the future I made a note and will have a look into that, so we may loose that requirement or streamline it a bit more.

**Comment by arashnz** [comment]
Yes. problem solved.
Thank you.
