### ISSUE TITLE
Can add resize_keyboard option 

### ISSUE THREAD

**Issue by d-yuri** [php-telegram-bot/core#1306]
I need add a **resize_keyboard** option i do like in documentation. But don't see the result in a telegram. I go to the vendor .
So my code 

```
public function execute(): ServerResponse
    {
        $keyboard = new Keyboard([
            ['text' => self::$text]
        ]);

        $keyboard = $keyboard
            ->setResizeKeyboard(true)
            ->setOneTimeKeyboard(true);

        return $this->replyToChat('Test text.', [
            'reply_markup' => $keyboard
        ]);
    }

```
The result is a huge button in the telegram.

In vendor i go to **vendor/longman/telegram-bot/src/Request.php** and see
```
            } elseif (is_array($item) || is_object($item)) {
                // Convert any nested arrays or objects into JSON strings.
                $item = json_encode($item);
            }
```

<img width="1298" alt="Снимок экрана 2022-04-01 в 18 01 58" src="https://user-images.githubusercontent.com/22129901/161289877-5e493e7f-a67b-4599-abd4-16414ef3e86e.png">

As i see in initial class Keyboard args is only "text" from 
```
$keyboard = new Keyboard([
            ['text' => self::$text]
        ]);
```

<img width="860" alt="Снимок экрана 2022-04-01 в 18 03 07" src="https://user-images.githubusercontent.com/22129901/161290125-13ff6815-145c-4026-97bc-96529cbebe25.png">

and json_encode from Keyboard class returns only data from RawData from constructor

**What did I miss and why can't I pass the parameter I need?**

**Comment by TiiFuchs** [comment]
Are you using the latest version 0.76.1 we released 2 days ago?

**Comment by TiiFuchs** [comment]
And can you post a screenshot of the button as it is shown in Telegram?

**Comment by TiiFuchs** [comment]
I can't reproduce this with 0.76.1. I copied your code and it works for me.

When I remove the setResizeKeyboard call it's big, else it's small.

Can you check what `json_encode($keyboard)` returns after your `setResizeKeyboard()` call?

**Comment by noplanman** [comment]
@d-yuri What client are you using? Does it also look wrong on mobile?

**Comment by d-yuri** [comment]
> I can't reproduce this with 0.76.1. I copied your code and it works for me.
> 
> When I remove the setResizeKeyboard call it's big, else it's small.
> 
> Can you check what `json_encode($keyboard)` returns after your `setResizeKeyboard()` call?

reinstal composer pacage and all OK. Probably a problem with something else.

**Comment by d-yuri** [comment]
> @d-yuri What client are you using? Does it also look wrong on mobile?

probably some mistake on the installed package bat I don't know where. Reinstall help.

**Comment by TiiFuchs** [comment]
Awesome!

**Comment by d-yuri** [comment]
> I can't reproduce this with 0.76.1. I copied your code and it works for me.
> 
> When I remove the setResizeKeyboard call it's big, else it's small.
> 
> Can you check what `json_encode($keyboard)` returns after your `setResizeKeyboard()` call?

![image](https://user-images.githubusercontent.com/22129901/161296336-b3e2f26d-97cf-44b3-b8c6-4510f4a06a1f.png)

first dump is what in object second is return ` json_encode($keyboard)`


I reinstall pacages and work fine
