### ISSUE TITLE
Help | editMessageText

### ISSUE THREAD

**Issue by Shoteexke** [php-telegram-bot/core#1307]
hello friends, could anyone help me with this? 

PROBLEM: I'm trying to edit a message but it's not working. I will leave a part of my code below:

 callback_data button:

$inline_keyboard = new InlineKeyboard([ ['text' => 'Consultas', 'callback_data' => 'search'], ['text' => 'Comandos', 'callback_data' => 'commands'], ], [ ['text' => 'Planos', 'callback_data' => 'plan'], ['text' => 'Termos', 'callback_data' => 'terms'], ],[['text' => 'Avisos', 'url' => 't.me/crewapis']]);

CALLBACK:
[...]
    public function execute(): ServerResponse
    {
        // Callback query data can be fetched and handled accordingly.
        $callback_query = $this->getCallbackQuery();
        $callback_data = $callback_query->getData();

$dta = [
'chat_id' => $callback_query->getMessage()->getChat()->getId(), 
'message_id' => $callback_query->getMessage()->getMessageId(),
'text' => 'edited'
];
 
return Request::editMessageText($dta);
        }

theoretically when I had clicked on the button, it was to change the message, but that doesn't happen :(

**Comment by TiiFuchs** [comment]
Does your `execute` method get called correctly?

**Comment by Shoteexke** [comment]
My code:

<?php

/**
* This file is part of the PHP Telegram Bot example-bot package.
* https://github.com/php-telegram-bot/example-bot/
*
* (c) PHP Telegram Bot Team
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

/**
* Callback query command
*
* This command handles all callback queries sent via inline keyboard buttons.
*
* @see InlinekeyboardCommand.php
*/

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Entities\CallbackQuery; 
use Longman\TelegramBot\Entities\InlineKeyboard; 
use Longman\TelegramBot\Entities\InlineKeyboardButton; 
use Longman\TelegramBot\Entities\Keyboard;

class CallbackqueryCommand extends SystemCommand
{
    /**
    * @var string
    */
    protected $name = 'callbackquery';

    /**
    * @var string
    */
    protected $description = 'Handle the callback query';

    /**
    * @var string
    */
    protected $version = '1.2.0';

    /**
    * Main command execution
    *
    * @return ServerResponse
    * @throws \Exception
    */
    public function execute(): ServerResponse
    {
        // Callback query data can be fetched and handled accordingly.
        $callback_query = $this->getCallbackQuery();
        $callback_data = $callback_query->getData();

$dta = ['chat_id' => $callback_query->getMessage()->getChat()->getId(), 'message_id' => $callback_query->getMessage()->getMessageId(), 'text' => 'hh',];
 
return Request::editMessageText($dta);
        }

    }

**Comment by Shoteexke** [comment]
![Screenshot_20220405-215337_Code Editor](https://user-images.githubusercontent.com/95512185/161874369-434a1fdd-37ca-4ec0-96e2-d707e263b912.png)

I think so

**Comment by TiiFuchs** [comment]
Could you please double check?
Write something to a log file or anything that verifies that your method is getting called.

**Comment by Shoteexke** [comment]
could you write an example of using the editMessageText method that edits a message when it receives some callback_data ? 

when someone clicks on the button that contain some callback_data the message will be edited...

**Comment by TiiFuchs** [comment]
You can see an example of editing the text of a message here: https://github.com/php-telegram-bot/example-bot/blob/d29a7b266ecfa43df71db2d28ec7cb94c34b66f9/Commands/Message/EditmessageCommand.php#L63-L67

But I'm still not convinced that this is your problem. You need to create a GenericmessageCommand class like in https://github.com/php-telegram-bot/example-bot/blob/d29a7b266ecfa43df71db2d28ec7cb94c34b66f9/Commands/ServiceMessages/GenericmessageCommand.php and receive the callbackQuery there.

Like it's done with `$message->getDeleteChatPhoto();` but instead you need to call `$message->getCallbackQuery()`.

When you need help from someone, please accept, if they're asking you a question. Most of the time there is a very specific reason for it. So again... Please make sure you're receiving the callback_query at all. Maybe create an additional command to test `editMessageText()` before mixing everything together.

**Comment by Shoteexke** [comment]
Thanks for the explanation and sorry.

**Comment by Shoteexke** [comment]
unfortunately not, I started learning to program in PHP a few days ago, I'm the type that only understands, seeing the base file (an example file)

**Comment by TiiFuchs** [comment]
Maybe you should start with the basics of PHP and object oriented programming before you dive into the specifics of „other peoples code“ aka libraries. 

We are not able to help you with the basic understanding of how that works.
