### ISSUE TITLE
Quiz bot captcha

### ISSUE THREAD

**Issue by MaxEncryptPHP** [php-telegram-bot/core#1309]
hello friends, can someone explain to me how I make a quiz using this library? 

![Screenshot_20220408-132053_Telegram](https://user-images.githubusercontent.com/103268469/162482564-7a2c513c-8476-4469-9fca-82f7d4e191ed.png)

the captcha quiz will be activated as soon as a user joins the group

I want to kind of make a capctha, just like the print. Thank you very much in advance.

**Comment by TiiFuchs** [comment]
I don't think that the issue section is the right place for that.
Please try the support group in Telegram: https://t.me/PHP_Telegram_Bot_Support
Maybe someone else can help you there.

**Comment by MaxEncryptPHP** [comment]
Okay, thank you.
