### ISSUE TITLE
HOW

### ISSUE THREAD

**Issue by XiaomiYe** [php-telegram-bot/core#1313]
### 🐞 Bug Report

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  | x.y.z
| PHP version               | x.y.z
| MySQL version             | x.y.z / none
| Update Method             | Webhook / getUpdates
| Self-signed certificate   | yes / no
| RAW update (if available) | `{...}`

**Comment by XiaomiYe** [comment]
HOW TO sent a html message?

**Comment by TiiFuchs** [comment]
```php
Request::sendMessage([
    'chat_id' => $chatId,
    'text' => $text,
    'parse_mode' => 'HTML',
]);
```

**Comment by XiaomiYe** [comment]
thanks~
