### ISSUE TITLE
I can have the robot automatically respond to commands Start without /commads  ？

### ISSUE THREAD

**Issue by XiaomiYe** [php-telegram-bot/core#1315]
I can have the robot automatically respond to commands that the commads  Start without /commad  ？

**Comment by XiaomiYe** [comment]
@TiiFuchs

**Comment by TiiFuchs** [comment]
I'm not sure I understand your question...?

**Comment by noplanman** [comment]
Yes, using GenericmessageCommand you can execute any code by checking the text content.

**Comment by XiaomiYe** [comment]
ok,tks
