### ISSUE TITLE
StartCommand doesn't work

### ISSUE THREAD

**Issue by HenriqueValente09** [php-telegram-bot/core#1316]
Method 'Vendor VApp\Commands \StartCommand: : handle () is not compatible with method
"Telegram\Bot \ Commands\ Command : :handle()". intelephense(1038)

please, can someone help me? I'm following this guide https://telegram-bot-sdk.readme.io/docs/commands-system#writing-commands but it shows this error above

**Comment by TiiFuchs** [comment]
Wrong GitHub repository. You're using another library. Take a look at their support options here: https://telegram-bot-sdk.readme.io/changelog/join-php-chat-slack-community-for-support
