### ISSUE TITLE
php-telegram-bot with getUpdates mode won't work

### ISSUE THREAD

**Issue by Vikasitha444** [php-telegram-bot/core#1322]
I've tried to create a telegram bot. And I decided to select getUpdates mode to develop it. But the problem was, It receives all the updates, and still, I can see it in the database. But the bot won't send any message. even the bot won't respond to /start command. 

In my logs, I've received something like,
_2022-05-02 19:41:27 - Processed 1 updates_

But the bot won't do anything. Even for /start command it isn't responding. How can I fix this?

**Comment by TiiFuchs** [comment]
If you need support for this, you should share relevant parts of your code. But do not post your Bot API Token anywhere.

Maybe the Telegram Support Chat is a better/faster way to get help for your problem: https://t.me/PHP_Telegram_Bot_Support

**Comment by Vikasitha444** [comment]
```
#!/usr/bin/env php
<?php
//README
//This configuration file is intented to run the bot with the webhook method
//Uncommented parameters must be filled

#bash script
#while true; do ./getUpdatesCLI.php; done

// Load composer
require __DIR__ . '../vendor/autoload.php';

$API_KEY = '<my API key>';
$BOT_NAME = 'botwebhookytbot';
//$commands_path = __DIR__ . '/Commands/';
$mysql_credentials = [
   'host'     => 'localhost',
   'user'     => 'root',
   'password' => '1234',
   'database' => 'telegram_bot',
];

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);

    // Enable MySQL
    $telegram->enableMySQL($mysql_credentials);

    //// Enable MySQL with table prefix
    //$telegram->enableMySQL($mysql_credentials, $BOT_NAME . '_');

    //// Add an additional commands path
    //$telegram->addCommandsPath($commands_path);

    //// Here you can enable admin interface for the channel you want to manage
    //$telegram->enableAdmins(['your_telegram_id']);
    //$telegram->setCommandConfig('sendtochannel', ['your_channel' => '@type_here_your_channel']);

    //// Here you can set some command specific parameters,
    //// for example, google geocode/timezone api key for date command:
    //$telegram->setCommandConfig('date', ['google_api_key' => 'your_google_api_key_here']);

    //// Logging
    //$telegram->setLogRequests(true);
    //$telegram->setLogPath($BOT_NAME . '.log');
    //$telegram->setLogVerbosity(3);

    //// Set custom Upload and Download path
    //$telegram->setDownloadPath('../Download');
    //$telegram->setUploadPath('../Upload');

    // Handle telegram getUpdate request
    $ServerResponse = $telegram->handleGetUpdates();

    if ($ServerResponse->isOk()) {
        $n_update = count($ServerResponse->getResult());
        print(date('Y-m-d H:i:s', time()) . ' - Processed ' . $n_update . ' updates' . "\n");
    } else {
        print(date('Y-m-d H:i:s', time()) . ' - Failed to fetch updates' . "\n");
        echo $ServerResponse->printError() . "\n";
    }
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // log telegram errors
    echo $e;
}
```





This is the code and I changed nothing but my bot API and username only. The program doesn't give me any errors. But the bot isn't working/

**Comment by TiiFuchs** [comment]
The bot itself sends no messages by itself. So you must create corresponding Command classes for receiving commands, and you have to call `Request::sendMessage(...)` to send messages...

Do you have additional code that reacts to commands or sends messages? Because in this snippet you do not.

**Comment by Vikasitha444** [comment]
In which PHP file should I do it? In the getUpdatesCLI.php or anything else?

**Comment by TiiFuchs** [comment]
To react to commands you need to create a Class like this: https://github.com/php-telegram-bot/example-bot/blob/master/Commands/StartCommand.php and specify the path to those classes with `$telegram->addCommandsPath($commands_path);` (Be aware that the namespace must be inside `Longman\TelegramBot\Commands`. Alternatively you can link the classes itself with `$telegram->addCommandClasses`.

You can send messages by calling `Request::sendMessage($data)` anywhere you want. Just be aware, that all those instantiation and configuration stuff inside your getUpdatesCLI.php file needs to be done earlier. (But not the handleGetUpdates(), that's only important for receiving messages.

**Comment by TiiFuchs** [comment]
Since your questions are very basic, please have another detailled look into the documentation and the example-bot repository first. Maybe you find your answers there already.
