### ISSUE TITLE
Does not work Inline keyboard, empty callbackquery

### ISSUE THREAD

**Issue by EvgeniyUstim** [php-telegram-bot/core#1329]
| Operating system          | Name and version
| PHP Telegram Bot version  | 
| PHP version               | 7.3
| MySQL version             |yes
| Update Method             | Webhook 
| Self-signed certificate   | no
| RAW update (if available) |

**Comment by noplanman** [comment]
Hi @EvgeniyUstim, please provide more information, thanks.

**Comment by TiiFuchs** [comment]
Closing this since we didn't get any response
