### ISSUE TITLE
editMessageText not working CALLBACK

### ISSUE THREAD

**Issue by MaiconKatty2** [php-telegram-bot/core#1332]
I'm trying to edit a message when someone clicks an InlineKeyboard button, but it's not working. 

my code:

`<?php

/**
 * This file is part of the PHP Telegram Bot example-bot package.
 * https://github.com/php-telegram-bot/example-bot/
 *
 * (c) PHP Telegram Bot Team
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Callback query command
 *
 * This command handles all callback queries sent via inline keyboard buttons.
 *
 * @see InlinekeyboardCommand.php
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;

class CallbackqueryCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = 'callbackquery';

    /**
     * @var string
     */
    protected $description = 'Handle the callback query';

    /**
     * @var string
     */
    protected $version = '1.2.0';

    /**
     * Main command execution
     *
     * @return ServerResponse
     * @throws \Exception
     */
    public function execute(): ServerResponse
    {
        // Callback query data can be fetched and handled accordingly.
        $callback_query = $this->getCallbackQuery();
        $callback_data  = $callback_query->getData();
        $callback_MSG_ID  = $callback_query->getMessage()->getMessageId();
        $callback_CHAT_ID  = $callback_query->getMessage()->getChat()->getId();

if($callback_data == "consultas"){
$data['chat_id'] = $callback_CHAT_ID;
$data['message_id'] = $callback_MSG_ID;
$data['text'] = 'edited... working';

return Request::editMessageText($data);
        }
    }
}`

**Comment by TiiFuchs** [comment]
Currently not able to test it myself. But did you verify that your callback query is getting called?
i think that you might need to use a GenericmessageCommand instead of a CallbackqueryCommand.

**Comment by MaiconKatty2** [comment]
> Currently not able to test it myself. But did you verify that your callback query is getting called? i think that you might need to use a GenericmessageCommand instead of a CallbackqueryCommand.

Yes, instead of putting editMessageText, when I change it to SendMessage, when I click the InlineKeyboard button it works, the message is sent, but I will do what you said.

**Comment by fadilbjm** [comment]
In this case you are using inline so make sure you add '`reply_markup`' in editMessageText 
If you forget the `reply_markup` there is nothing change
Try this:
```
$inlineKeyboard = new InlineKeyboard();
return Request::editMessageText([
'chat_id' => $chatId,
'message_id' => $messageId,
'text' => 'editted text',
'reply_markup' => $inlineKeyboard
]);
```
You can null reply_markup if you don't want user click another callback
Sorry for late i've solved it today😅

**Comment by MaiconKatty2** [comment]
> In this case you are using inline so make sure you add '`reply_markup`' in editMessageText If you forget the `reply_markup` there is nothing change Try this:
> 
> ```
> $inlineKeyboard = new InlineKeyboard();
> return Request::editMessageText([
> 'chat_id' => $chatId,
> 'message_id' => $messageId,
> 'text' => 'editted text',
> 'reply_markup' => $inlineKeyboard
> ]);
> ```
> 
> You can null reply_markup if you don't want user click another callback Sorry for late i've solved it today😅

HaHaHa no problem, your explanation and your example helped me a lot

**Comment by noplanman** [comment]
@MaiconKatty2 Is it working for you now?

(sorry for the late reply :see_no_evil:)

**Comment by MaiconKatty2** [comment]
> @MaiconKatty2 Is it working for you now?
> 
> (sorry for the late reply 🙈)

Yes!
