### ISSUE TITLE
Passing null to strpos is deprecated

### ISSUE THREAD

**Issue by jyxjjj** [php-telegram-bot/core#1334]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Fedora 36
| PHP Telegram Bot version  | 0.75.0
| PHP version               | 8.1.7
| MySQL version             | MariaDb Podman Container Image Hash ea81af801379
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

Passing null to strpos is deprecated

#### Current behaviour

Laravel 9.18.0 Reports:

```
Version: 0.75.0
Channel: deprecations
Level: WARNING
Message: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in vendor/longman/telegram-bot/src/Entities/Message.php on line 140
```

#### How to reproduce

I did not record the raw update or say cannot connect this issue to which update to log files.

**Comment by jyxjjj** [comment]
maybe replace with ```str_start_with```

**Comment by TiiFuchs** [comment]
Please update to the latest version of PHP Telegram Bot, since earlier versions may not compatible with PHP 8.1.
The latest version should afaik.

**Comment by jyxjjj** [comment]
Ok, Thank you. i ll close first, if it continuing reports, i ll reopen here.
