### ISSUE TITLE
The SQL statement is jammed. Procedure

### ISSUE THREAD

**Issue by grayTele** [php-telegram-bot/core#1336]
### 🐞 Bug Report
<img width="974" alt="image" src="https://user-images.githubusercontent.com/79576802/176180436-cf0877e4-6aef-48cb-997e-0c488386f76c.png">

<img width="869" alt="image" src="https://user-images.githubusercontent.com/79576802/176180622-e178500c-35ca-4fe9-b18b-f9b777949408.png">

Table associated key to add index ah!

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  | x.y.z
| PHP version               | x.y.z
| MySQL version             | x.y.z / none
| Update Method             | Webhook / getUpdates
| Self-signed certificate   | yes / no
| RAW update (if available) | `{...}`

**Comment by TiiFuchs** [comment]
Closed due to the lack of more information…
