### ISSUE TITLE
How to setup the package in Laravel project?

### ISSUE THREAD

**Issue by Odilbukh** [php-telegram-bot/core#1337]
I want to use this package and telegram bot on my laravel project. So how to setup the package so both the telegram bot and laravel project works well ?

|  ?                               |  !
| ---                              | ---
| Operating system                 | Ubuntu
| PHP Telegram Bot Manager version | 1.7
| PHP Telegram Bot version         | 0.73.1
| PHP version                      | 8.1.7
| MySQL version                    | 5.3
| Update Method                    | Webhook
| Self-signed certificate          | no
| RAW update (if available)        | `{...}`
| Laravel version                             | 9.11

**Comment by noplanman** [comment]
Definitely look into this work by @TiiFuchs 
https://git.tii.tools/tii/laravel-telegram-bot

Also, for reference: https://github.com/php-telegram-bot/laravel project.

**Comment by jyxjjj** [comment]
Hey guys, i created a Laravel project too.
[jyxjjj/Telegram-Bot](https://github.com/jyxjjj/Telegram-Bot)

**Comment by noplanman** [comment]
https://github.com/php-telegram-bot/laravel
