### ISSUE TITLE
When the package will be updated for Laravel 9 and PHP 8.1 ?

### ISSUE THREAD

**Issue by Odilbukh** [php-telegram-bot/core#1340]
When the package will be updated for Laravel 9 and PHP 8.1 ?

**Comment by noplanman** [comment]
@TiiFuchs :innocent:

**Comment by jyxjjj** [comment]
You don't need to create a new issue due to #1337.

**Comment by noplanman** [comment]
https://github.com/php-telegram-bot/laravel
