### ISSUE TITLE
DB PDOSTATEMENT

### ISSUE THREAD

**Issue by MaiconKatty2** [php-telegram-bot/core#1343]
Warning: PDOStatement::execute(): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_premium' in 'field list' in /storage/emulated/0/Unreal/PROJECT/vendor/longman/telegram-bot/src/DB.php on line 450

**Comment by Hitmare** [comment]
Please add more information

What did you do?
Did you Import the DB file into your SQL ?
Is this occuring after a fresh install?
Is this occuring after an update of the Bot?

**Comment by jacklul** [comment]
Looks like someone didn't run SQL migration scripts
