### ISSUE TITLE
getFrom()

### ISSUE THREAD

**Issue by MaiconKatty2** [php-telegram-bot/core#1347]
guys, i'm facing problems using getFrom()...

I want to make a system to check if whoever clicked on the button with callback_data is the same as I use the /start command (returns the button with the callback_data) 

I tried to do like this: 

`
$callback_query = $this->getCallbackQuery();
$compare_id_01 = $callback_query->getMessage()->getReplyToMessage()->getFrom()->getId(); 
$callback_data = $callback_query->getData();
$callback_UserID = $callback_query->getFrom()->getId();

if($callback_data == 'start'){ if($callback_UserID == $compare_id_01){ return Request::sendMessage(['text' => 'working']); 

}else{ 

return $callback_query->answer([ 'text' => '🚫 Not Permission', 'show_alert' => 1, // Randomly show (or not) as an alert. 'cache_time' => 10, ]);
 } 
} 
`
this works but after a few minutes it returns in the terminal this message: Fatal error: encaught error: Call to a member function getFrom() on null... 

do you know how to help me with this?

**Comment by MaiconKatty2** [comment]
Edit: it looks like this occurs when a user doesn't use their personal account to send the command.

**Comment by fadilbjm** [comment]
before you call `getFrom()` make sure `getMessage()` first.
you can read the [telegram api docs](https://core.telegram.org/bots/api#message) and you can see the `from` type is inside `message` type

**Comment by MaiconKatty2** [comment]
> antes de ligar `getFrom()`certifique-se `getMessage()`primeiro. você pode ler os [documentos da API do telegram](https://core.telegram.org/bots/api#message) e pode ver que o `from`tipo está dentro do `message`tipo

ok, i will try that.

**Comment by MaiconKatty2** [comment]
> before you call `getFrom()` make sure `getMessage()` first. you can read the [telegram api docs](https://core.telegram.org/bots/api#message) and you can see the `from` type is inside `message` type

still returns error...

`$compare_id_01 = $callback_query->getMessage()->getReplyToMessage()->getFrom()->getId();`

**Comment by fadilbjm** [comment]
Do not add `getReplyToMessage()`
Just `$callback_query->getMessage()->getFrom()->getId();`

**Comment by MaiconKatty2** [comment]
> Do not add `getReplyToMessage()` Just `$callback_query->getMessage()->getFrom()->getId();`

Ok

**Comment by MaiconKatty2** [comment]
> Do not add `getReplyToMessage()` Just `$callback_query->getMessage()->getFrom()->getId();`

I was wanting to make a comparison between the user_ids of users who click on a button contained in a callback_data if($user_id == $user_id_compare){ ... } knows how to do ?

**Comment by fadilbjm** [comment]
> > Do not add `getReplyToMessage()` Just `$callback_query->getMessage()->getFrom()->getId();`
> 
> I was wanting to make a comparison between the user_ids of users who click on a button contained in a callback_data
> 
> `if($user_id == $user_id_compare){ ... } `
> 
> knows how to do ?

You don't need to validate user id

**Comment by MaiconKatty2** [comment]
> > > Do not add `getReplyToMessage()` Just `$callback_query->getMessage()->getFrom()->getId();`
> > 
> > 
> > I was wanting to make a comparison between the user_ids of users who click on a button contained in a callback_data
> > `if($user_id == $user_id_compare){ ... } `
> > knows how to do ?
> 
> You don't need to validate user id

I need it, because I don't want another user (who hasn't called the command) to be able to move the buttons, just the one who called the command. I managed to do this, thanks anyway!
