### ISSUE TITLE
RUN BOT LOOP

### ISSUE THREAD

**Issue by MaiconKatty2** [php-telegram-bot/core#1348]
hello guys, I'm doing a loop to keep the bot active, I use the while to call the GetUpdatesCli.php file, but the script seems to be buggy, it works a bit, but it freezes "process 0 updates..." and does not process anything else. file:

 `<?php 

while(true){ 
require 'GetUpdatesCLI.php';
 } 

?>`

 do you know of any way to run GetUpdatesCli.php other than this way, and that this error that I mentioned to you does not occur? operating system: Windows 11

**Comment by fadilbjm** [comment]
if you want bot keep alive you must be using webhook

**Comment by MaiconKatty2** [comment]
> if you want bot keep alive you must be using webhook

ok, i will try that.
