### ISSUE TITLE
Why is the bot not returning results using Request::answerInlineQuery?

### ISSUE THREAD

**Issue by goshaLoonny** [php-telegram-bot/core#1352]
Here is a piece of code that I use to send a response to an inline request.
```PHP
$update = new Update(json_decode(Request::getInput(), true));
$inlineQuery = $update->getInlineQuery();
$response = Request::answerInlineQuery([
  'inline_query_id' => $inlineQuery->getId(),
  'results' => [
    new InlineQueryResultPhoto([
      'id' => 0,
      'photo_url' => 'https://i.imgur.com/CYVeNBy.jpeg',
      'thumb_url' => 'https://i.imgur.com/CYVeNBy.jpeg'
    ]),
    new InlineQueryResultPhoto([
      'id' => 1,
      'photo_url' => 'https://i.imgur.com/189fWXd.jpeg',
      'thumb_url' => 'https://i.imgur.com/189fWXd.jpeg'
    ]),
    new InlineQueryResultPhoto([
      'id' => 2,
      'photo_url' => 'https://i.imgur.com/sFC2wIh.jpeg',
      'thumb_url' => 'https://i.imgur.com/sFC2wIh.jpeg'
    ]),
  ]
]);
```
I am not getting any errors. 
```json
{"ok":true,"result":true}
```

But for any request, the bot returns an empty result. What am I doing wrong?

![image](https://user-images.githubusercontent.com/66001433/186303642-5d346cb5-f992-4072-b514-c5a76b4d3f1e.png)

**Comment by Hitmare** [comment]
Hey

Could you pleas try the Inlinequerycommand file from the example bot? So we can check if the bot is working correctly

https://github.com/php-telegram-bot/example-bot/tree/master/Commands/InlineMode

You will need to temporary remove your Inlinequerycommand file for this to teaz

**Comment by goshaLoonny** [comment]
Thanks a lot for your answer.  Everything worked for me the next day.  I didn't make any changes to the code.

**Comment by TiiFuchs** [comment]
> Thanks a lot for your answer. Everything worked for me the next day. I didn't make any changes to the code.

Okay then we can close this issue.
