### ISSUE TITLE
Problem with web_app in InlineKeyboardButton

### ISSUE THREAD

**Issue by the-lookin** [php-telegram-bot/core#1353]
I try to send button with message, which will open Web App:

This is code:

```PHP
      $keyboard = [
          "inline_keyboard" => [
              [
                   new InlineKeyboardButton(['text' => 'message', 'web_app' => new WebAppInfo(['url' => 'https://test.com/bot.php'])])
              ]
          ]
      ];
      $result = Request::sendMessage([
        'chat_id' => $chat_id,
        'parse_mode' => 'markdown',
        'text'    => 'Send message',
        'reply_markup' => $keyboard
      ]);```

But I have an error:

```
[ok] => 
            [error_code] => 400
            [description] => Bad Request: BUTTON_TYPE_INVALID
```
Without "web_app" param - all is OK

**Comment by TiiFuchs** [comment]
Just to be sure…

you’re trying to do this in a private chat?
„Available only in private chats between a user and the bot.“

**Comment by the-lookin** [comment]
Ohhh... ok. I trying it at the channel.

**Comment by TiiFuchs** [comment]
does it work in a private chat?

**Comment by miuiv5ztl** [comment]
Is it solved?

**Comment by TiiFuchs** [comment]
@miuiv5ztl there is nothing to solve.
You can't send web_app buttons in groups or channels. Only private chats according to the api documentation.

Closing this issue, since there was no further comment by the author.
