### ISSUE TITLE
insert data to my new table

### ISSUE THREAD

**Issue by bi2b** [php-telegram-bot/core#1354]
I have created a new table in the database, how do I insert data into my new table based on the message from the user?

**Comment by TiiFuchs** [comment]
You could use the PDO adapter directly. 
`DB::getPdo()` should give you the PDO object.

**Comment by bi2b** [comment]
I want to insert it to my new table, how to do it?

**Comment by TiiFuchs** [comment]
Please understand that we cannot give general PHP support.

Try googling "php pdo insert table", there are plenty of tutorials out there.
