### ISSUE TITLE
Bot async? Help

### ISSUE THREAD

**Issue by ShoteeXp-xs** [php-telegram-bot/core#1357]
is there a way to make the bot asynchronous? when two people, for example, use the /start command, the bot responds to both people at the same time, without having to wait for the first call of the command to be performed.

**Comment by jacklul** [comment]
I'm assuming you mean `getUpdates` mode - there is no build-in way - you would have to make your own implementation by extending **Telegram** class and rewriting **handleGetUpdates** method while using one of popular async libraries.
