### ISSUE TITLE
Cant send messages or response to commands after upgrading

### ISSUE THREAD

**Issue by cimbor** [php-telegram-bot/core#1361]
### 💥 BC Break Report

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Openwrt 22.03.0
| PHP Telegram Bot version  | 0.79.0
| PHP version               | 8.1
| MySQL version             |  none
| Update Method             | Request::sendMessage and $telegram->handle();
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

Hello, i was using the bot without issues, with some custom commands using php 8.0, but after upgrading to 8.1 the bot doesnt handle request or send text replies via static method sendMessage from Request.

#### Previous behaviour

All working fine
#### Current behaviour

The bot doesnt handle requests neither can send messages

#### How to reproduce

Install php 8 in openwrt 22.03.0 and and a message after configuring webhook:

$entityBody = file_get_contents('php://input');
$chat_id = $this_message->chat->id;
    $message_id = $this_message->message_id;
 $result = Request::sendMessage([
        'chat_id' => $chat_id,
        'text'    => 'TEXT ...',
    ]);

#### Expected behaviour

reacting to commands and send messages

**Comment by noplanman** [comment]
Is there any info in your error logs?

Also, are you using this library to just send simple text notifications? If yes, i suggest you use the Bot API directly via cURL.

**Comment by cimbor** [comment]
Execution simply breaks when reaching $telegram->handle(); I tried to log some messages after it and nothing is registered, same when trying to send a text response with sendMessage() from Request.
I want my bot to send text notifications but also to react to some commands and send inline keyboards, use gd library,etc.

**Comment by noplanman** [comment]
Hi @cimbor, I saw in your code that you never initialise the Telegram object itself, so the Request class won't work.

You need to put `new Telegram($api_key, $bot_username);` (with the correct values, of course) before any call to Request.

Best check the [example-bot](https://github.com/php-telegram-bot/example-bot/) to learn how the library is used.

**Comment by TiiFuchs** [comment]
Closed due to lack of a reply.
