### ISSUE TITLE
DB issues from structure.sql

### ISSUE THREAD

**Issue by FullDad** [php-telegram-bot/core#1362]
Hey everyone,

I am almost done setting all this up and my structure.sql is having some major importing issues.  i do everything as instructed and still get errors when importing.

I am just creating the table, going to import and selecting struture.sql.  Anything else i should be doing?  utf8mb4_unicode_520_ci is how i'm importing and that seems to be the thing it doesn't like.

I'm new to all of this but i'm RIGHT THERE!  i get a new error every day and i feel like this is my last hurdle.  I am getting the errors below because i think of my structure.sql import.  helppppp please!

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Longman\TelegramBot\DB::insertTelegramUpdate() must be of the type int or null, float given, called in /var/www/html/vendor/longman/telegram-bot/src/DB.php on line 620 and defined in /var/www/html/vendor/longman/telegram-bot/src/DB.php:338
Stack trace:
#0 /var/www/html/vendor/longman/telegram-bot/src/DB.php(620): Longman\TelegramBot\DB::insertTelegramUpdate()
#1 /var/www/html/vendor/longman/telegram-bot/src/Telegram.php(644): Longman\TelegramBot\DB::insertRequest()
#2 /var/www/html/vendor/longman/telegram-bot/src/Telegram.php(516): Longman\TelegramBot\Telegram->processUpdate()
#3 /var/www/html/getUpdatesCLI.php(24): Longman\TelegramBot\Telegram->handleGetUpdates()
#4 {main}
  thrown in /var/www/html/vendor/longman/telegram-bot/src/DB.php on line 338

**Comment by FullDad** [comment]
#1267 - Illegal mix of collations (utf8mb4_general_ci,COERCIBLE) and (utf8mb4_unicode_ci,COERCIBLE) for operation '<>'

**Comment by noplanman** [comment]
I'm glad you got it working. Have fun coding your bot!
