### ISSUE TITLE
 channel subscription check with package

### ISSUE THREAD

**Issue by ataBarzegar79** [php-telegram-bot/core#1368]
### ❓ channel subscription check with package

Hi ,
I need to add a featue to my bot but I really have no idea of how to do that within the the package . 
I have read the readme file and see that this package supports the channels .
but the main issue is that  ""  I want to force all of my  users to join the channel to be able to use bot functionality . the main problem is that I have no idea of how to check a telegram user(with a unique telegram id ) is a member of specified channel ? ""

does this package has any method to check this ?

**Comment by TiiFuchs** [comment]
This is not possible due to limitations in Telegrams Bot API. See the Telegram documentation for all available methods: https://core.telegram.org/bots/api

You can get messages for newly joined members in a group or supergroup, but not in Channels.

**Comment by ataBarzegar79** [comment]
> This is not possible due to limitations in Telegrams Bot API. See the Telegram documentation for all available methods: https://core.telegram.org/bots/api
> 
> You can get messages for newly joined members in a group or supergroup, but not in Channels.

thanks , I searched the documentation , maybe I have explained in a bad way ! 
exactly I need this functionality  [https://core.telegram.org/bots/api#getchatmember](url)  
is this availabe in this package ?

**Comment by TiiFuchs** [comment]
Then you can use it via
`Request::getChatMember(...)`

But be aware, you must already know the user_id for this method. So you can't get a list of all chat members in a group/supergroup/channel.

**Comment by ataBarzegar79** [comment]
very thank you ::)

> Then you can use it via `Request::getChatMember(...)`
> 
> But be aware, you must already know the user_id for this method. So you can't get a list of all chat members in a group/supergroup/channel.

very thank you ::))
