### ISSUE TITLE
How about Bot API 6.2 & 6.3

### ISSUE THREAD

**Issue by jyxjjj** [php-telegram-bot/core#1369]
#### Summary

>How about the 6.2 and 6.3 support situation?
>>
>>It seems only added some types, easy to support,

>If unfinished, I am very busy these days, cannot help with that,
>>if you have time to upgrade, please notify here to let me know,
>
>>if you don't have time too, i am glad to help after weeks later.

**Comment by TiiFuchs** [comment]
We already support Version 6.2.
6.3 was released 2 days ago. We're working on it.
But please don't push. This is unnecessary, we are aware of new updates and don't need reminder here.
Contribute or wait until a new release is published.
