### ISSUE TITLE
Surprisingly, in a private channel where there was not a single live subscriber, the records were viewed a dozen times! I understand everything, but this discredits the developers, it is obvious that there are more of them than users. Excuse me for help. Please refrain from making recommendations. It doesn't bother me.

### ISSUE THREAD

**Issue by cuvera** [php-telegram-bot/core#1381]
### 🐞 Bug Report

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  | x.y.z
| PHP version               | x.y.z
| MySQL version             | x.y.z / none
| Update Method             | Webhook / getUpdates
| Self-signed certificate   | yes / no
| RAW update (if available) | `{...}`

**Comment by Hitmare** [comment]
This is not the Telegram Support Github?
