### ISSUE TITLE
Use more one external mysql connection?

### ISSUE THREAD

**Issue by Dedushkes** [php-telegram-bot/core#1382]
How to use more one external mysql connection from command? I need 3 different mysql connection at same time, maybe in $this->pdo1,$this-pdo2,$this->pdo3 or array style $this->pdo[0], $this->pdo[1], $this->pdo[2] ? How to do it ?

**Comment by Hitmare** [comment]
Hello

As far as i can see, multiple Database connection are not supported by this library
You might need to write your own class, containing those multiple database connections

**Comment by noplanman** [comment]
Could you provide some context and a use case example?

**Comment by TiiFuchs** [comment]
I'll close this since we didn't hear anything back...
