### ISSUE TITLE
<update> object and message is wrong for CustomCommand

### ISSUE THREAD

**Issue by uspilot** [php-telegram-bot/core#1383]
### 🐞 Bug Report

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  | 0.80.0
| PHP version               | 8.1.7
| MySQL version             | 5.5.52
| Update Method             |  getUpdates
| Self-signed certificate   |  no
| RAW update (if available) | `{...}`

#### Summary

CustomCommand doesn't get new Update. CustomCommand always use the first update that has been received
#### How to reproduce

Use any CustomCommand and check <update> object  

#### Expected behaviour

<update> object must be current

**Comment by uspilot** [comment]
The solution I used for me is:

telegram.php -> executeCommand function

            $this->last_command_response = $command_obj->setUpdate($this->update)->preExecute();

**Comment by noplanman** [comment]
Thanks for bringing this up @uspilot 

This is definitely a breaking change, as it changes the way the Update object may have been used in users' projects.

Would you be able to share more about your use-case for this?

**Comment by uspilot** [comment]
I did some censor bot which should delete messages from group chats according to defined rules. 

So, the GeneralmessageCommand class is used by default to deal with messages. Once this class is created at the first time it receives an Update object. On any later use of this class the pointer to this class has been returned without updating an Update object inside this class. So in fact you have a pointer to the class with Update object which has been sent to this class at the first use of it. So, you have a command class without any information about Update object you have to work with.

**Comment by TiiFuchs** [comment]
This is solved by #1384, hopefully there will be a release soon... Stay tuned.
