### ISSUE TITLE
Error after reinstalling web environment

### ISSUE THREAD

**Issue by platonovpavel** [php-telegram-bot/core#1385]
| Operating system          | CentOS Linux release 7.9.2009 (Core)
| PHP Telegram Bot version  | 0.80.0
| PHP version               | PHP 7.4.33 (cli) (built: Feb 14 2023 09:31:03) ( NTS )
| MySQL version             | mysql  Ver 14.14 Distrib 5.7.40-43, for Linux (x86_64) using  6.2
| Update Method             | Webhook
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

Hello everyone, сould someone help?
We really like your product and we are making a bot for ordering a pass.
Everything worked fine, than we wanted to update the php version, it didn't work for us, and we had to restore the web environment. After that, we run composer updatdate.

#### Current behaviour
We use Conversations. The bot asks the first question (requesting a number), receives a number, and then remains silent.
However, if the bot is contacted by a person who has already had a conversation before, the entire order procedure goes well. The bot does not respond only to new people. An entry is created in the users table, but not in the dialog table.
In httpd/error.log we get very big an error:

PHP Fatal error:  Uncaught TypeError: Return value of Longman\\TelegramBot\\Commands\\SystemCommands\\GenericmessageCommand::execute() must be an instance of Longman\\TelegramBot\\Entities\\ServerResponse, none returned in /home/bitrix/www/dev/bot/pass/Commands/Conversation/GenericmessageCommand.php:83\nStack trace:\n#0 /home/bitrix/www/dev/bot/pass/vendor/longman/telegram-bot/src/Commands/Command.php(204): Longman\\TelegramBot\\Commands\\SystemCommands\\GenericmessageCommand->execute()\n#1 /home/bitrix/www/dev/bot/pass/vendor/longman/telegram-bot/src/Telegram.php(685): Longman\\TelegramBot\\Commands\\Command->preExecute()\n#2 /home/bitrix/www/dev/bot/pass/vendor/longman/telegram-bot/src/Telegram.php(657): Longman\\TelegramBot\\Telegram->executeCommand()\n#3 /home/bitrix/www/dev/bot/pass/vendor/longman/telegram-bot/src/Telegram.php(568): Longman\\TelegramBot\\Telegram->processUpdate()\n#4 /home/bitrix/www/dev/bot/pass/hook.php(74): Longman\\TelegramBot\\Telegram->handle()\n#5 {main}\n  thrown in /home/bitrix/www/dev/bot/pass/Commands/Conversation/GenericmessageCommand.php on line 83

**Comment by noplanman** [comment]
Hi @platonovpavel 

It looks like you're not returning a `ServerResponse` object in your `GenericmessageCommand` here:
`/home/bitrix/www/dev/bot/pass/Commands/Conversation/GenericmessageCommand.php:83`

If there is nothing to return, you can use `return Request::emptyResponse();`

**Comment by platonovpavel** [comment]
Exactly! Now everything works great
Thank you much for your product and best wishes
