### ISSUE TITLE
No Conversation Reaction

### ISSUE THREAD

**Issue by dencen100** [php-telegram-bot/core#1392]
![image](https://user-images.githubusercontent.com/132529264/236090159-37ec0241-fdfe-4b5d-a7f6-6e2c0771ac6f.png)
![image](https://user-images.githubusercontent.com/132529264/236090214-4443b9df-5897-474a-931a-48316ac74742.png)
![image](https://user-images.githubusercontent.com/132529264/236090279-62d055d2-6f2c-487d-9bcc-677831ed3d3a.png)
![image](https://user-images.githubusercontent.com/132529264/236090802-d977b22a-239d-43bb-b414-2a18c18fc417.png)
![image](https://user-images.githubusercontent.com/132529264/236090835-ab687768-b47e-47e1-800b-38e8d89184a5.png)

![image](https://user-images.githubusercontent.com/132529264/236090398-d822e636-6b12-48e5-b561-c07fc7fbe555.png)
![image](https://user-images.githubusercontent.com/132529264/236090425-c2923cec-bd09-411c-95a1-5b25a1c28847.png)
![image](https://user-images.githubusercontent.com/132529264/236090490-d4f5cdbb-1661-45df-97fd-2e88dbbb0c23.png)
![image](https://user-images.githubusercontent.com/132529264/236090712-9f05eaa8-d345-48ad-8c84-1ec2751db279.png)

when i use mysql
![image](https://user-images.githubusercontent.com/132529264/236129849-4d44e99a-0ce5-4fc3-83e8-99cd985d583e.png)

- no error
- others work properly
- when I enable mysql > not work
- when I disable mysql > not work

Does conversation work properly ?

**Comment by Hitmare** [comment]
Hello

Do you have in your CustomCommand folder another GenericmessageCommand.php file ? 
Mysql is needed for the Conversation command

**Comment by dencen100** [comment]
Great . When I removed other folder. it works !!!!

I understand what is problem.

thank you @Hitmare

**Comment by Hitmare** [comment]
yes. as it says in the readme do not copy everything from the command folder into the customcommand folder. you cannot have any duplicates of any command files
