### ISSUE TITLE
Why is there no record of which private link a user joined the group through a private link!

### ISSUE THREAD

**Issue by zulongsss** [php-telegram-bot/core#1400]
Why is there no record of which private link a user joined the group through a private link!

**Comment by TiiFuchs** [comment]
If you add it to the allowed_updates with your getUpdates or setWebhook method, you get a `chat_member` status on joins and there should be a `invite_link` containing the link.

> Chat invite link, which was used by the user to join the chat; for joining by invite link events only.

See https://core.telegram.org/bots/api#chatmemberupdated

**Comment by zulongsss** [comment]
![QQ截图20230508151830](https://user-images.githubusercontent.com/116566528/236760521-de20fd55-9cba-40f9-b22d-50905078323e.png)

@TiiFuchs  sir, how to modify！

**Comment by TiiFuchs** [comment]
Please have a look into the API documentation for getUpdates: https://core.telegram.org/bots/api#getupdates

You can pass the required parameters as array to handleGetUpdates like this:

```php
$telegram->handleGetUpdates([
  'allowed_updates' => ['message', 'edited_channel_post', 'callback_query', 'chat_member']
]);
```

**Comment by zulongsss** [comment]
![222333](https://user-images.githubusercontent.com/116566528/236766075-0100e93e-d45e-46f4-9783-f70c9ec64e04.png)

@TiiFuchs  Thanks sir for your guidance!

**Comment by zulongsss** [comment]
Thanks sir for your guidance!
