### ISSUE TITLE
Cant math Document command (then need catch file)

### ISSUE THREAD

**Issue by Xakki** [php-telegram-bot/core#1406]
https://github.com/php-telegram-bot/core/blob/d9484af72a39e10913a60d2c6c9ceffb61d624d1/src/Telegram.php#L584C37-L584C37

I think it must be like this

```
protected function getCommandFromType(string $type): string
    {
        return mb_strtolower(str_replace('_', '', $type));
    }
```

Before, i try this example https://github.com/php-telegram-bot/example-bot/blob/master/Commands/Other/UploadCommand.php , but its not work (for me)

Use Laravel 10

**Comment by Xakki** [comment]
After this fix, this command will work correctly
```
class DocumentCommand extends UserCommand
{
    /**
     * @var string
     */
    protected $name = 'document';

    /**
     * @var string
     */
    protected $description = 'Upload and save files';

    /**
     * @var string
     */
    protected $usage = '/document';
....
```

**Comment by noplanman** [comment]
@Xakki Thanks for your report.

The line of code you are referring to shouldn't make a difference, as the command itself gets lowercased later in the code anyway.

How are you executing your command? Did you test with the exact `UploadCommand` code, when it didn't work?
