### ISSUE TITLE
Group invitation

### ISSUE THREAD

**Issue by OurWin** [php-telegram-bot/core#1407]
Hello everyone, thank you for your work. It provides a fantastic foundation for my project!

After reading and re-reading the documentation, I still can't figure out how to invite a user to a group, even though I see that it's possible in the API. Any ideas on how to implement this?

**Comment by TiiFuchs** [comment]
Where did you see that it is possible in the API? I can't find anything like that.

The Bot can create a ChatInviteLink, but it is not possible to share this link to users that the bot hasn't interacted with before. It is not possible for the bot to invite users to a group WITHOUT interaction.

Maybe I'm missing something. It would help if you can elaborate on what you're trying to do exactly.

**Comment by OurWin** [comment]
Maybe I didn't understand this method :)
https://core.telegram.org/method/channels.inviteToChannel

**Comment by OurWin** [comment]
Thank you, @jacklul !
