### ISSUE TITLE
PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bot.telegram_update' doesn't exist

### ISSUE THREAD

**Issue by iyamk** [php-telegram-bot/core#1415]
/home/user/bot/vendor/longman/telegram-bot/src/DB.php
Line 233
Error:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bot.telegram_update' doesn't exist
My code:
```
try {
    $telegram = new Longman\TelegramBot\Telegram($bot_api_key, $bot_username);

    $telegram->addCommandsPaths([
        __DIR__.'/Commands'
    ]);

    $mysql_credentials = [
   'host'     => 'localhost',
   'port'     => 3306,
   'user'     => 'root',
   'password' => '',
   'database' => 'bot'
    ];

    $telegram->enableMySql($mysql_credentials);

    $telegram->handleGetUpdates();
}
catch (Longman\TelegramBot\Exception\TelegramException $e)
{
    writeLog($e->getMessage());
}
```
What is it and where can I get a database dump?

**Comment by jacklul** [comment]
https://github.com/php-telegram-bot/core/blob/develop/structure.sql

**Comment by iyamk** [comment]
> https://github.com/php-telegram-bot/core/blob/develop/structure.sql

How tired I am of this structure already; was it really impossible to do without it? The code works just as quickly both with and without it
