### ISSUE TITLE
How to define a file name when saving a file locally?

### ISSUE THREAD

**Issue by wuaidajiejie** [php-telegram-bot/core#1420]
Here is my code:
```
$download = Request::getFile(['file_id' => $document->getFileId()]);
$savePath = 'bot/'.date('Ymd');
$saveDirectory = ROOT_PATH.'public/'.$savePath;
$this->telegram->setDownloadPath($saveDirectory);
Request::downloadFile($download->getResult());
```
The path and filename to save are `/public/bot/20230920/documents/file_x.xxx`
How do I define a file name? For example: `/public/bot/20230920/documents/896e7a99d9f0e6a17b1870d9932dbab8.xxx`

**Comment by iyamk** [comment]
Here's what you can try:
```
$f = $download->getResult();
$f->setFilePath('test');
Request::downloadFile($f);
```
If it doesn’t work, it means no, the library is very crude

**Comment by wuaidajiejie** [comment]
> Here's what you can try:
> 
> ```
> $f = $download->getResult();
> $f->setFilePath('test');
> Request::downloadFile($f);
> ```
> 
> If it doesn’t work, it means no, the library is very crude

Thanks for your reply, but I didn't test with your code, I modified the downloadFile function of Request.php for the business implementation
