### ISSUE TITLE
forward inline_keyboard with data to command

### ISSUE THREAD

**Issue by MustafaTaj** [php-telegram-bot/core#1443]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Linux
| PHP Telegram Bot version  | 0.82.0
| PHP version               | 8.2.0
| MySQL version             |  none
| Update Method             | Webhook 
| Self-signed certificate   | yes 
| RAW update (if available) | `{...}`

#### Summary

am trying to use the survey command example using the example-bot.
It works fine when I input `/survey` in the chat

but using an inline keyboard doesn't seem to make the wizard work propely 

in CallbackqueryCommand.php I tried to use:

`return $this->telegram->executeCommand('survey);`

and it only shows the first step of the wizard and doesn't continue.

this is my code CallbackqueryCommand.php
```
 public function execute(): ServerResponse
    {
        // Callback query data can be fetched and handled accordingly.
        $callback_query = $this->getCallbackQuery();
        $callback_data = $callback_query->getData();

        return $this->telegram->executeCommand($callback_data);
}
```

this is my /start command code
```
 $inline_keyboard = new InlineKeyboard([
                ['text' => 'Start surevey', 'remove_keyboard' => true, 'callback_data' => 'survey'],
            ], [
                ['text' => 'more info', 'remove_keyboard' => true, 'callback_data' => 'info'],
            ]);
            Request::sendMessage([
                'chat_id' => $callback_query->getMessage()->getChat()->getId(),
                'text' => "choose option 👇',
                'reply_markup' => $inline_keyboard,
            ]);
```

**Comment by jacklul** [comment]
Example survey command was build using regular keyboards only, it won't work properly if you try to call it from the callback query handler command.

**Comment by MustafaTaj** [comment]
i solve it by modifing the command as following:

[ - ] `$this->conversation = new Conversation($user_id, $chat_id, $this->getName());`

[ + ] `$this->conversation = new Conversation($chat_id, $chat_id, $this->getName());`

**Comment by Hitmare** [comment]
I'm not sure how good that works with chatID as userID in the database since it would cause a duplicate when 2 or more uses were start the survey from a group chat 

I've come across the issue myself and wrote a pastebin how i solved it, using InlineKeyboard in a conversation

https://pastebin.com/qxQAekwj
