### ISSUE TITLE
Why admin commands are visible to everyone in а group chat?!

### ISSUE THREAD

**Issue by CrazyRedScorp** [php-telegram-bot/core#146]
Why admin commands are visible to everyone in а group chat?! Maybe I didn't find the information again? :smiley:
I wrote command "/help" in a group chat (I'm admin!), where my bot is installed, and a him message seen all members of the group chat.

```
/help
mycats_bot v. 0.30.0

Commands List:
/hidekeyboard - Hide the custom keyboard
/markdown - Print Markdown tesxt
/forcereply - Force reply with reply markup
/image - Send Image
/keyboard - Show a custom keybord with reply markup
/chats - List or search all chats stored by the bot
/sendtoall - Send the message to all the user's bot
/sendtochannel - Send message to a channel
/echo - Show text
/date - Show date/time by location
/cancel - Cancel the currently active conversation
/weather - Show weather by location
/help - Show bot commands help
/whoami - Show your id, name and username
/slap - Slap someone with their username
/survey - Survery for bot users

For exact command help type: /help <command>
```

Why?! Maybe "/help" in a group chat must display only for users commands? But, in private chat with my bot - show all commands? But! If users send "/help" - them see only a user commands (It's right).

And may be add a sort command, example in file "HelpCommand.php":

```
        //If no command parameter is passed, show the list
        if ($command === '') {
            $text = $this->telegram->getBotName() . ' v. ' . $this->telegram->getVersion() . "\n\n";
            $text .= 'Admin commands List:' . "\n";
            foreach ($commands as $command) {
                if ($command->isAdminCommand()) {
                    $text .= '/' . $command->getName() . ' - ' . $command->getDescription() . "\n";
                }
            }
            $text .= 'Commands List:' . "\n";
            foreach ($commands as $command) {
                if ($command->isUserCommand()) {
                    $text .= '/' . $command->getName() . ' - ' . $command->getDescription() . "\n";
                }
            }

            $text .= "\n" . 'For exact command help type: /help <command>';
        } else {
```

**Comment by jacklul** [comment]
I remember once admin commands were not available in group chats at all?

**Comment by CrazyRedScorp** [comment]
Yes, the commands is not available to use users. However, users will see that they are available to the administrator. I'm about:
```
/src/Commands/AdminCommands
ChatsCommand.php
SendtoallCommand.php
SendtochannelCommand.php
```

**Comment by noplanman** [comment]
If you are admin in a group and call `/help`, of course the others will see the list you get.
Everybody sees everything, but only you (or any other admin) can execute them. When in a group, best to know the commands off by heart without needing the /help command 😜 

Hope this clears it up, or is there something else I'm missing?
The whole point of the `/help` command is to show which commands are available to the person calling it.

**Comment by CrazyRedScorp** [comment]
I agree with you.

> best to know the commands off by heart

I just decided to clarify. But what about the sort of commands? Is there a better method?

**Comment by noplanman** [comment]
What do you mean by this?
> sort of commands

The order in which they're sorted or the type of command it is (System, Admin or User)?

**Comment by jacklul** [comment]
I'm using this: https://gist.github.com/jacklul/efd8ce2408670a156d3f0390d4b3f7f3
Is that what you want?

**Comment by CrazyRedScorp** [comment]
**noplanman**
> What do you mean by this?

Ideally - list of commands:
```
1. The admin list
1.1. A...
1.2. B ...
1.3. C ...
1.x. Z...
2. The user list
2.1. A...
2.2. B ...
2.3. C ...
2.x. Z...
```

**jacklul**
Thanks for  the idea.

**Comment by MBoretto** [comment]
Would be nice to divide them!

**Comment by noplanman** [comment]
Updated in example-bot repo: https://github.com/php-telegram-bot/example-bot/commit/83a6e360ae67fb0b5647b3539f536d56229b9c1f
