### ISSUE TITLE
How to set the timing between the same commands?

### ISSUE THREAD

**Issue by CrazyRedScorp** [php-telegram-bot/core#148]
How to set the timing between the same specific commands? Users in chat sent many of the identical commands. Example:

```
09:00 user 1 sent /news <site>
09:00 bot say: The news...
09:00 user 2 sent /news <site>
09:00 bot say: The news...
09:00 user 3 sent /news <site>
09:00 user 4 sent /news <site>
09:00 user 5 sent /news <site>
09:00 bot say: The news...
09:00 bot say: The news...
09:00 bot say: The news...
```

"site" - everywhere the same value.

Is it possible to make:

```
09:00 user 1 sent /news <site>
09:00 bot say: The news...
09:00 user 2 sent /news <site>
09:00 bot say: Look a little higher.
..timing..
09:12 user 3 sent /news <site>
09:12 bot say: The news...
```

**Comment by jacklul** [comment]
I'm using something like this in my bot: https://gist.github.com/jacklul/ee4939c4a83246e64c4739e2fb20d9ba

Little changes and you can alternatively use DB for this!

**Comment by CrazyRedScorp** [comment]
Thank you for the idea!

**Comment by MBoretto** [comment]
Interested! Maybe this can be implemented with the database, can be also used to trigger spammers!

**Comment by CrazyRedScorp** [comment]
I just don't want multiple identical queries permanent (one after the other). And I'm totally against spammers!

**Comment by noplanman** [comment]
This could also be solved with caching, which is something we should look into as well.
