### ISSUE TITLE
Make bot follow the limits

### ISSUE THREAD

**Issue by jacklul** [php-telegram-bot/core#157]
sendToActiveChats() can easily block your bot for few minutes if you go over the limit

https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

**Comment by aliemam** [comment]
Tanx...

**Comment by MBoretto** [comment]
What I'm thinking that we can create 'something' (maybe related to the task manager https://github.com/akalongman/php-telegram-bot/issues/156) that sends a little amount of messages every time an update is received.
Then with the command /sendtochats you can set a message to send and see the overall process 150/2500 user reached.
What do you think?

**Comment by commfort** [comment]
@jacklul @MBoretto not sure if limits  should be part of API wrapper. You need to leave it for custom logic. 
Let's say my bot has billions of users in groups and privates. Than I need to give priority for group admins over plain visitors. And I need to think about action limitation for single user and even to have ability to ban/unban spam users. 

On other hand I can prefer implement limits/task manager using memcache or rabbit, or by storing history in mysql and scheduling some cron job.

**Comment by jacklul** [comment]
Currently testing: https://github.com/jacklul/php-telegram-bot/tree/limiter_test
