### ISSUE TITLE
Pass additional arguments to a Command

### ISSUE THREAD

**Issue by BoShurik** [php-telegram-bot/core#158]
Hello!

I am planing to use this package as a part of Symfony project. Is it possible to inject commands as an objects (e.g. symfony services), but not as a path to a dir with command classes?

**Comment by MBoretto** [comment]
Hello,
I don't have experience with Symfony, maybe you can trigger your service calling it inside a command.
Let me know is works or if you find another soultion

**Comment by BoShurik** [comment]
Unfortunately, to call service inside a command I need to pass a service container to it :)

Solution, IMO, is to create CommandInterface, something like this:
``` php
interface CommandInterface
{
    /**
     * Command name
     *
     * @return string
     */
    public function getName();

    /**
     * Execute command
     *
     * @param Telegram $telegram
     * @param Update $update
     *
     * @return Entities\ServerResponse
     */
    public function execute(Telegram $telegram, Update $update = null);

    /**
     * If this is a system command
     *
     * @return bool
     */
    public function isSystemCommand();

    /**
     * If this is an admin command
     *
     * @return bool
     */
    public function isAdminCommand();

    /**
     * If this is a user command
     *
     * @return bool
     */
    public function isUserCommand();
}
```

and a method `addCommand(CommandInterface $command)` for Telegram object
but it will be a BC breakes

**Comment by MBoretto** [comment]
https://github.com/akalongman/php-telegram-bot/issues/106
Did you seen this issue? we would like to separate the commands logic from the telegram one.
Maybe in this refactoring we can implement this  feature, let me know

**Comment by BoShurik** [comment]
Yea, it may be helpful. Thank you
