### ISSUE TITLE
sendtoall bug

### ISSUE THREAD

**Issue by alhazmy13** [php-telegram-bot/core#181]
Hi

When I send a message with command /sendtoall , the message sent to users more than 8 times, how i can stop it?

Regards,,

**Comment by MBoretto** [comment]
Messages are send to each chat. If a user belong  to many chat, it will receive  the  message many times. You can modify this behavior, take a look at this function :
https://github.com/akalongman/php-telegram-bot/blob/master/src/Request.php#L782

**Comment by jacklul** [comment]
It would actually make sense to prevent sending multiple messages!

**Comment by MBoretto** [comment]
We could develop a version of the /sendtoall command with conversation that let you customize the behavior

**Comment by noplanman** [comment]
Having a quick look at this and not sure if this can be fixed really.

If a user is in multiple groups, they will get multiple messages because the "groups" get the message.

Am I seeing this wrong, or is there a way to send a message to a group without notifying certain users of that group?
