### ISSUE TITLE
Get callback query data in current conversation

### ISSUE THREAD

**Issue by khaninejad** [php-telegram-bot/core#256]
Hi,
I want to get selected InlineKeyboardButton data with current conversation.
Web someone clicked on the inline keyboard data sent to CallbackqueryCommand and in return our selected button.
But how can i get this data without need to send callbackquery or pass this data to current conversation?
![email-21](https://cloud.githubusercontent.com/assets/4404500/16948161/4fdf88f4-4dc8-11e6-85df-4ca1307f42b0.jpg)
![email-222](https://cloud.githubusercontent.com/assets/4404500/16948162/4fe5bdb4-4dc8-11e6-8c50-d4e4d47911a8.jpg)

**Comment by jacklul** [comment]
You will have to redirect it to your command via callbackquerycommand.php, then in your own command also add support for incoming callback queries and handle it there.

Simple redirect idea is to use this data scheme in callback queries: "command_userdata", for example: 'register_yourmail@dot.com' (whole data cant exceed 64 bytes, and shouldnt contain any special characters)

**Comment by khaninejad** [comment]
Can you give me a sample code?

**Comment by jacklul** [comment]
callbackquerycommand.php
```php

class CallbackqueryCommand extends SystemCommand
{
    protected $name = 'callbackquery';
    protected $description = 'Reply to callback query';

    private $commands = [
        'help' => 'help',
        'reply' => 'contact',
    ];

    public function execute()
    {
        $update = $this->getUpdate();
        $callback_query = $update->getCallbackQuery();
        $user_id = $callback_query->getFrom()->getId();
        $data = $callback_query->getData();

        $command = explode('_', $data);
        $command = $command[0];

        if (isset($this->commands[$command]) && $this->getTelegram()->getCommandObject($this->commands[$command])) {
            return $this->getTelegram()->executeCommand($this->commands[$command], $update);
        } else {
            $data = [];
            $data['callback_query_id'] = $callback_query->getId();
            $data['text'] = 'Invalid request!';
            $data['show_alert'] = true;
        }

        return Request::answerCallbackQuery($data);
    }
}

```

for in-command usage example see https://github.com/akalongman/php-telegram-bot/issues/182#issuecomment-218896824

**Comment by nesttle** [comment]
I edited my `CallbackqueryCommand.php` with @jacklul example, but how can I execute this command?
`/callbackquery help_test` no response
`/callbackquery help_reply` no response
`/callbackquery help _ 111` no response

I'm missing something about callback feature I think :

**Comment by jacklul** [comment]
Executing `/callbackquery` won't trigger it as code expects callback query object, not message. It must be used with Inline buttons with callback data.

**Comment by nesttle** [comment]
Trying to understand callbacks but can't get it working, hope I can find some example, thanks

**Comment by jacklul** [comment]
`InlinekeyboardCommand.php` + `CallbackqueryCommand.php`

Execute `/inlinekeyboard`, click the callback button, see what happens then look into `CallbackqueryCommand`.
