### ISSUE TITLE
how to use edit message inline bot  ????

### ISSUE THREAD

**Issue by ahora007** [php-telegram-bot/core#290]
hi 
i m problem in edite message..
i m use callback query & inline message  in bot
now edite message in  inline after click on callback_query

![capture](https://cloud.githubusercontent.com/assets/21077830/18190334/4ed8fe4a-70d7-11e6-9151-ce696f293d87.PNG)

see pic click on click callback_query and show message but not edite message **remain: 1 page** 
how edite **remain : 1 page** ???

I see #235 and #249  
please example code

thanx

**Comment by MBoretto** [comment]
are you returning before editing?

**Comment by ahora007** [comment]
no 
my create voting 

now  after send vote by user update result for user 

but message result not update 

what's the solution؟؟؟

**Comment by jacklul** [comment]
Did you managed to do it, @ahora007?

**Comment by natanrufino** [comment]
It's something like this:

<?php

if (isset($update['callback_query']['id'])){ //When a inline keyboard is pressed
	
	$call_back_data = $update['callback_query']['data'];
	$chat_id_call = $update['callback_query']['message']['chat']['id'];
	$message_id_call = $update['callback_query']['message']['message_id'];

if ($call_back_data === "v-2"){
		
$inline_explica = urlencode("<b>MODO INLINE</b>".
"\n\nAssista alguns vídeos para entender melhor como usar os recursos do Modo Inline do Telegram no MySwordBot. ");
			
$keyboard = [	'inline_keyboard' => 
				[[['text' => '1','callback_data' => 'v-1'],['text' => '2','callback_data' => 'v-2']]]
			];			
$keyboard = json_encode($keyboard, true);

file_get_contents(API_URL.'answerCallbackQuery?callback_query_id=' . $update['callback_query']['id'] .'&text=VÍDEO 1&cache_time = 0&show_alert = true');	 //This message will appear on the top

file_get_contents(API_URL."editMessageText?chat_id=".$chat_id_call."&message_id=".$message_id_call."&text=".$inline_explica."&parse_mode=HTML&disable_web_page_preview=false&disable_notification=false&reply_markup=".$keyboard); // this message will replace the old one specified on $message_id_call.

}

}

?>

**Comment by natanrufino** [comment]
`It's something like this:

<?php

if (isset($update['callback_query']['id'])){ //When a inline keyboard is pressed
	
	$call_back_data = $update['callback_query']['data'];
	$chat_id_call = $update['callback_query']['message']['chat']['id'];
	$message_id_call = $update['callback_query']['message']['message_id'];

if ($call_back_data === "v-2"){
		
$inline_explica = urlencode("<b>MODO INLINE</b>".
"\n\nAssista alguns vídeos para entender melhor como usar os recursos do Modo Inline do Telegram no MySwordBot. ");
			
$keyboard = [	'inline_keyboard' => 
				[[['text' => '1','callback_data' => 'v-1'],['text' => '2','callback_data' => 'v-2']]]
			];			
$keyboard = json_encode($keyboard, true);

file_get_contents(API_URL.'answerCallbackQuery?callback_query_id=' . $update['callback_query']['id'] .'&text=VÍDEO 1&cache_time = 0&show_alert = true');	 //This message will appear on the top

file_get_contents(API_URL."editMessageText?chat_id=".$chat_id_call."&message_id=".$message_id_call."&text=".$inline_explica."&parse_mode=HTML&disable_web_page_preview=false&disable_notification=false&reply_markup=".$keyboard); // this message will replace the old one specified on $message_id_call.

}

}

?>`
