### ISSUE TITLE
Is it possible to send Dociment without reading it from file?

### ISSUE THREAD

**Issue by pavlyuts** [php-telegram-bot/core#325]
Hi!

I need to send bot-generated content as a file, and guess I have to write it ti the disk first.
I've tryed to check it by myself, but only fund that I can supply filename string and send file. Going deep, I found that you prepare multipart only if one of the data parts is a resource. So, I even have no idea how to fix it.

**Comment by noplanman** [comment]
You might be able to make use of the `php://memory` stream, but I'm not sure.

Could you give me a concrete example (preferably with some code) of what you'd like to send as file content?
Then I could play around and see if we can implement it as a feature 😃

**Comment by pavlyuts** [comment]
I spent a night to going deep :(
php://memory does not work, guess because gizzle not able to retrieve file name.
I have traced that:
sendDocument opens file for reading by calling encodeFile, with fopen, and puts open descriptor with 'document' key.
Then it go to self::send('sendDocument', $data); and then to self::execute()
Here it scans $data for entry type of resource, and any found, puts it to 
$request_params['multipart'][] = array('name' => $key, 'contents' => $item);
Finally, this means we have record under 'multipart', with 'name'=>'document' and 'contents' => file descriptor.
And then it goes to self::$client->post, means gizzle http component.
And all the magic about multipart urlencoded form creation goes somewhere inside gizzle.

Any way, it's not critical issue to rework all the workframe.

As an example, if we taking picture from DB BLOB we have first to put it to the file and then send to Telegram. Or we have to form the request completely outside of the framework.
The same if we create vcf business card and send. Same problem.

**Comment by noplanman** [comment]
I think the easiest is to use [`tmpfile`](https://secure.php.net/manual/en/function.tmpfile.php) or [`tempnam`](https://secure.php.net/manual/en/function.tempnam.php).

**Comment by pavlyuts** [comment]
It's about the same as fopen, fwrite, rewind, pass to the gizzle and fclose.

I need to check gizzle docs. If I found that gizzle is able to do it right, I will think about patch the workframe to be able to do this way.

**Comment by noplanman** [comment]
That would be great! I'll leave this issue open then.

**Comment by pavlyuts** [comment]
It's quite simple in theory. Have a look on the gizzle docs here: http://docs.guzzlephp.org/en/latest/request-options.html#multipart

At this moment we sent to gizzle something like this:

$client->request('POST', '/post', [
    'multipart' => [
         +++other fields here+++
        [
            'name'     => 'document',
            'contents' => fopen('/path/to/file', 'r')
        ],
    ]
]);

To send file directly from string we need to send

$client->request('POST', '/post', [
    'multipart' => [
         +++other fields here+++
        [
            'name'     => 'document',
            'contents' => string, containing the file body
            'filename' => 'filename.ext'
        ],
]);

However!

In the Request::execute(..) we have these lines:

++++++++++++++++++
        //Check for resources in data
        $contains_resource = false;
        foreach ($data as $item) {
            if (is_resource($item)) {
                $contains_resource = true;
                break;
            }
        }

        //Reformat data array in multipart way
        if ($contains_resource) {
            foreach ($data as $key => $item) {
                $request_params['multipart'][] = array('name' => $key, 'contents' => $item);
            }
        } else {
            $request_params['form_params'] = $data;
        }
++++++++++++++++
This means it checks the params for resource and handles it differently: as form_params if no resource and as multipart if any.

Even if I pass correct record containing filename and data, this code will rework it to form_params.

So, it's not a simple fix!

I see two approaches:
1. Pass extra the 'mode' identifier to Requesr::execute which force it to use one of modes and keep it automatic if no supplyed (backward compatible). 
2. Remove 'detection' code from Request::execute and pass implicitly the type of request, defining it somewhere near to the place where resources are opened.

Then we have to define something like Request::sendDocumentDirect((array $data, $filename, $content) - method to send document directly because we have ho ways to detect is it filename or file body passed.

Due of this point significantly affects the framework core I don't think it's good idea me to supply the solution. Some architectural decisions must be done before.

So, hope for BigBoss attention )))

**Comment by pavlyuts** [comment]
By the way, Guzzle docs says that it accepts there PSR-7 stream interface as well. But I am not so familiar to it to say is it meaning or not.

**Comment by pavlyuts** [comment]
I've checked with docs. Guuzzle accepts PSR-7 stream on place on file descriptor. This shoud work.
However, we have to change the code mentioned above. Today it goes to multipart if any resources found. To accept psr-7 it should go multipart if any resource or interface object found.
I will try to think how to change it keeping back compatibility in mind and will try to supply pull request within couple of weeks due it's not critical for me.

**Comment by pavlyuts** [comment]
Guzzle ability to handle any of  PSR-7 stream or string file content confirmed.

This works well:
```
$stream = Psr7\stream_for('File contents here');

$response = $client->post('https://api.telegram.org/bot<API KEY>/sendDocument', 
[
    'multipart' => [
        [
            'name'     => 'chat_id',
            'contents' => '<chat_id>'
        ],
        [
            'name'     => 'document',
            'contents' => $stream,
            'filename' => 'filename.txt',
        ]
    ]
]);
```
And this one works as well:
```
$stream = Psr7\stream_for('File contents here');

$response = $client->post('https://api.telegram.org/bot<API KEY>/sendDocument', 
[
    'multipart' => [
        [
            'name'     => 'chat_id',
            'contents' => '<chat_id>'
        ],
        [
            'name'     => 'document',
            'contents' => 'File contents here',
            'filename' => 'filename.txt',
        ]
    ]
]);
```
Please, pay attention that 'filname' is mandatory here!

So, this will work for any kind of files Telegram work with. Mean: Photo, Audio, Document, Sticker, Video, Voice, because the same way used.

The same question regards file download. Your approach to put it on the disk.

Now, it;s clear for me how to work around this thing in my project. The question is: how many people need in-memory file processing? Do it really useful to make a big fix to your workframe? Guess, I have to add a method for each of Photo, Audio, Document, Sticker, Video, and Voice plus another exec method. Sorry, but I have no idea how to make ot in your cuurrent approach and keep it back compatible.

Any suggestions?

**Comment by pavlyuts** [comment]
Resolved with pull request 329

https://github.com/akalongman/php-telegram-bot/pull/329

Finally, that much simpler that expected.
