### ISSUE TITLE
Conversation: implicit start on demand and check if in conversation without creating

### ISSUE THREAD

**Issue by pavlyuts** [php-telegram-bot/core#327]
Hi All!

Thanks great for conversations workframe, but I see some inflexible logics inside.

The conversation workframe built around idea that any command is conversational or not.

If we do new conversation class instance - the conversation starts and the record to DB will be inserted. If any conversation exists with another command, then old conv. closed and new one started. Nice and clear approach. 

However, if I have a command with both conversational and simple mode. For example, I parse some user input and found that I have 3 of 5 things I hope to find. Let,s, for example, I ask for 5 colours.

The problem is that I can't know is I am alredy in conversation or no. If I define new conversation object - the new conversation will start. However, I don't know in the moment if I need to go to conversation.

Of course, I can stop it immediately. 

I try to analyse the code and see that the constructor behaviour is unclear. It will try load any existingconversation, and if NO command name passed, returnins existing conversation object for user&chat or empty conversation object. But if command name passed it will start new one.

Why not to do implicit start?

**Comment by jacklul** [comment]
I believe there is existence check example in GenericMessagecommand...

**Comment by pavlyuts** [comment]
IMHO, the conversations looks like not well-integrated. First we hit DB to check is any conversation on place. Then, the command should hit DB again to check if any conversation on place. 

It's not ecological to useless hit the DB ;)

Conversation is NOT command-level thing. It is chat+user level thing. As we process updates one by one, one message per update => it is update level thing.

Therefore it's better to have it checked somewhere inside Telegram::processUpdate()

Think, it's good idea try to load by user+chat conv. from table once, and on success fill Telegram->conversation property, keeping it null if no conv. found. Therefore, the command may use $this->telegram->conversation without hitting DB twice. Or we may  put conversation object to command object as well as update/message object.

And finally, we may extent command with conversation features and methods.

This is just some thoughts, not reqirements! ;)

**Comment by noplanman** [comment]
Just linking this to #227 and closing here.
