### ISSUE TITLE
Add /debug command

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/core#363]
It would be helpful to add a `/debug` command that shows a whole bunch of debug info.

Namely PHP version, MySQL version, Bot version, maybe the last 10 lines from the error/update log and anything else that might help with debugging.

**Comment by jacklul** [comment]
Including API replies from getWebhookInfo and others might be useful here too!
It might be some kind of command that could generate report useful in issue reporting.

**Comment by noplanman** [comment]
> generate report useful in issue reporting

Yes, that's what I was thinking too 😃 
It's to decide what exactly we want to pack into it.

**Comment by noplanman** [comment]
I'm busy working on this one and this is the output so far:
```
TelegramBot version: 0.38.1
PHP version: 7.0.12 (64bit); apache2handler; Darwin
Maximum PHP script execution time is 30 seconds
MySQL version: 5.6.33
Web Server: Apache
curl version: 7.50.3; OpenSSL/1.0.2j
Webhook Info: {"ok":true,"result":{"url":"https:\/\/bot.url\/hook.php","has_custom_certificate":false,"pending_update_count":1,"max_connections":5,"allowed_updates":["message","edited_message","inline_query","chosen_inline_result","callback_query"]}}
```

I was also thinking of adding the latest errors and updates, but that's a LOT of text and the errors can be multiline when there is a stack trace, so that's a whole different story.

What else would make sense to put it here?

**Comment by jacklul** [comment]
In addition to /debug command it would be good to have some kind of debug script which can troubleshoot some issues automatically!

For example when host has self signed cert installed but no certificate was supplied while setting the webhook:
```
Longman\TelegramBot\Entities\WebhookInfo Object
(
    [url] => https://example.com/webhook.php
    [has_custom_certificate] => 
    [pending_update_count] => 0
    [last_error_date] => 1483222863
    [last_error_message] => SSL error {336134278, error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed}
    [max_connections] => 100
    [allowed_updates] => Array
        (
            [0] => message
            [1] => inline_query
            [2] => chosen_inline_result
        )
		
)
```

**Comment by noplanman** [comment]
> Is it possible to make some kind of integrity check if database is ok? Like check tables for required columns etc?

#112 is kind of the idea for this, which hasn't happened yet 😁 

> troubleshoot some issues automatically

Define *"automatically"*.
Do you mean it does certain checks and reports issues to the user?
Or that it literally does some automatic configurations? If so, which ones?

We'd have to decide what checks should be made. Or maybe (similar to the `/debug` command) create a summary page of all the available parameters and settings, marking the ones that need attention.

Examples for this:
- User ID which isn't an integer
- Non-existent command paths
- Failed database connection
- Check for self-signed cert (not sure how, but it's on this list anyway)
- Permissions to write log files
- any others...

**Comment by jacklul** [comment]
> Define "automatically".

Common things, script could try to send fake update to the bot to check if it replies ok, could also check vendor integrity, are the classes properly loaded, are the permissions ok...

**Comment by noplanman** [comment]
`/debug` command merged with #387 

Leaving this open, as the other part of this is a standalone script for issue debugging...

**Comment by chuv1** [comment]
How about to add some sort of `log` command in addition to `debug`?

Something like this, for example:
```
  /**
   * Log some data to some channel, chat or directly to user
   *
   * @param   $data     mixed
   * @param   $channel  mixed
   * @param   $format   string | boolean
   *
   * @return  bool
   */
  private function log($data, $channel = false, $format = false) {

    // Getting admin
    $admin = $this->getTelegram()->getAdminList();

    // No channel to send
    if(empty($admin[0]) && empty($channel)) return false;

    // Place to add chat name placeholders
    $chats = [
        'owner'     => $admin[0]
    ];

    // Send to first admin in the admins list by default 
    $channel = $channel === false ? $chats['owner']: $channel;
    
    // Channel id should be a key from chats array, string with '@' in front or integer 
    if(is_string($channel) && !empty($chats[$channel])){
      $channel = $chats[$channel];
    }
    elseif(!(is_string($channel) && strpos($channel,'@') === 0) && !is_int($channel)){
      $channel = $admin[0];
    }
  
    // Data to log. var_export() it if not a string
    if(is_string($data)) $notification = $data;
    else                 $notification = var_export($data, true);

    // Notification message
    $notify = [
        'chat_id'              => $channel,
        'text'                 => $notification,
        'disable_notification' => true
    ];

    // If apply formatting if $format is set
    if(strtolower($format) == 'markdown' || strtolower($format) == 'html'){
      $notify['parse_mode'] = strtolower($format) == 'markdown' ? 'Markdown' : 'HTML';
    }
    
    // Send log data
    $result = Request::sendMessage($notify);

    return $result->isOk();
  }
```

**Comment by noplanman** [comment]
@chuv1 You can just create a custom admin command `/log` for yourself 👍 

Or did I misunderstand?
What is your intention?

**Comment by chuv1** [comment]
I mean to add it globally to the code, maybe even Request::Log or some sort of. 
I'm not really familiar with github so it's not a pull request. )

**Comment by chuv1** [comment]
And since I'm here. It seems a good idea to me to add some sort of public accessible markdown sanitizers as well. When you not sure that chat title or username contains _ (underscore), for example. Like User::tryMention(true), but for any string.

```


  /**
   * Removes markdown from text = ` _ * [ ] ( )
   *
   * Returns error definition on error
   *
   * @param $str
   * @return string
   */
  private function removeMarkdown($str){

    $str = !empty($str) ? preg_replace('/([\`\_\*\[\]\(\)])/iu','\\'.'\\\1', $str) : false;

    return $str !== null ? $str : array_flip(get_defined_constants(true)['pcre'])[preg_last_error()];

  }

  /**
   * Escapes markdown in text = ` _ * [ ] ( )
   *
   * Returns error definition on error
   *
   * @param $str
   * @return string
   */
  private function escapeMarkdown($str){

    $str = !empty($str) ? preg_replace('/([\`\_\*\[\]\(\)])/iu','\\'.'\\\\1', $str) : false;

    return $str !== null ? $str : array_flip(get_defined_constants(true)['pcre'])[preg_last_error()];

  }
```

**Comment by noplanman** [comment]
Aaah, now I see, you mean a log function that sends a Telegram message, right?

Hadn't thought of that, @jacklul what you think?

**Comment by chuv1** [comment]
Yes, correct.

**Comment by jacklul** [comment]
Alternatively we could make the library to log all outgoing API requests and log them to database, https://github.com/jacklul/php-telegram-bot/tree/limiter_test already logs 'some' requests, but without data.

**Comment by noplanman** [comment]
> log all outgoing API requests and log them to database

What for? To keep track of all messages going out?
With an active bot this table could explode.

**Comment by ami-web-designer** [comment]
hi 
thank you for your excellent API.
I do every things was said in get started, set.php said "webhook was set".
but when i get webhook info it tells an error. and my robot does not response to any message or commands.
this is the webhookinfo:
""last_error_date":1497938307,"last_error_message":"SSL error {337047686, error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed}","max_connections":40}}"

**Comment by ami-web-designer** [comment]
I use self-sign certificate and set the the "certificate" parameter for "setwebhook".
it does not work.

**Comment by noplanman** [comment]
Hi @ami-web-designer 

Please create a [new issue](https://github.com/php-telegram-bot/core/issues/new) for this! You can just copy-paste your comments above to the new issue, then we can look at it there, thanks.
