### ISSUE TITLE
Any 0 to 100 example?

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#401]
I know php, I have used [Hello Bot](https://core.telegram.org/bots/samples/hellobot) but still don't know how to use this lib.

Where to write my own code?
I need to write many ifs and elses and show some keyboard to the user, but I can't find any clear documentation on explaining functions or how to have a simple conversation with a user.

**Comment by nesttle** [comment]
https://github.com/akalongman/php-telegram-bot/tree/master/src/Commands/UserCommands

**Comment by jacklul** [comment]
`$telegram->addCommandsPath($commands_path);`

And you place your commands in that directory.

**Comment by ttvd94** [comment]
Thanks for the answers, but I was mostly talking about an A to Z documentation. Something like Telegram API itself.

**Comment by noplanman** [comment]
Following the readme is pretty much that, from setting up a new bot to installing the library etc.

If you check out the examples folder you can find the resources necessary to code your own custom commands easily, there should be an example around for most scenarios.

Is that what you mean?

**Comment by ttvd94** [comment]
Readme just says the basics. Maybe you're right and I have to get to the examples and figure things out by myself, but I was looking for some friendly designed online documentation that explains everything.

By saying "friendly designed documentation" I mean something like this page: [https://core.telegram.org/bots/api](https://core.telegram.org/bots/api)

**Comment by santilin** [comment]
Still the same problem. I want to use this library to send a message to a Chat and after half an hour reading the docs and looking up issues, I have not found where do I set up my telegram bot API key and how do I send a message to a chat.

**Comment by noplanman** [comment]
Hi @santilin 

Have you had a look at the [example-bot](https://github.com/php-telegram-bot/example-bot) repository?
After setting up your webhook (or getUpdates script) take a look at the `Commands` folder for examples of how to use the library in commands.

**Comment by noplanman** [comment]
@santilin If you want to use the library to literally just send a message to a chat, you can do very easily:
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

new Longman\TelegramBot\Telegram('<your-api-key>');
Longman\TelegramBot\Request::sendMessage([
    'chat_id' => '<chat-id>',
    'text'    => 'Your message',
]);
```

**Comment by santilin** [comment]
@noplanman Exactly, that was what I wanted to do and I couldn't find in the README.
Thanks!

**Comment by noplanman** [comment]
Right, that really needs to be in the docs! Sorry about that :grin:
