### ISSUE TITLE
Helpers class

### ISSUE THREAD

**Issue by chuv1** [php-telegram-bot/core#402]
Hello guys!
I'd like to create a 'helper' class, to handle all of my helpers functions like removeMarkdown / escapeMarkdown and few other. Some of them rely on built-in getMessage(), for example.
Since I'm quite a noob in OOP and all of those namespaces, I can't figure out the best place and practice to implement in without touching existing composer package structure.
I'd like to have something like `Request::sendMessage()` method, but for helpers, ex. `Helpers::removeMarkdown($str)` or `Helpers::logToDevChannel($message)`. I'll write them by myself, but not really sure about a place and the way to implement.
Could you give me a small advice, with direction to start diggin?

PS. Please add getBotID() method to Telegram.php to get bot ID (it's needed to check if bot is an admin of a group with Request::getChatMember() method, for example), since there is no way to get it easy, atm. Yes, I know that I can explode api key to get it, but that not a pretty way. )

**Comment by chuv1** [comment]
Any advice? Anyone?

**Comment by jacklul** [comment]
There is nowhere to get bot id when it comes to library code, use Request::getMe() to get the bot ID dynamically. Or like you said, explode api key or declare a constant in hook script with bot id in it. 

About the helper class, all you might have to do is have your static helper class be included before hook script execution. It should be using library's namespace and extend Telegram (not sure about this, might not be required).

**Comment by chuv1** [comment]
@jacklul howbout explode api key by ":" as I said? But not in every command, as I'm doing it right now (since I don't where to put aside "helpers" functions).

And the main question is another one, sorry for pointing that out.

**Comment by jacklul** [comment]
How I do things:

-- src (my project dir)
---- Commands (commands dir)
---- Strings.php (classes to be included are in 'src' dir)
-- vendor (contains php-telegram-bot)

Extra code in hook script:

```php
require __DIR__ . '/vendor/autoload.php';

$PROJECT_DIR = __DIR__ . '/src/';

foreach(scandir($PROJECT_DIR) as $class) {
    if (is_file($PROJECT_DIR . '/' . $class) && file_exists($PROJECT_DIR . '/' . $class)) {
        $file_parts = pathinfo($PROJECT_DIR . '/' . $class);
        if($file_parts['extension'] == 'php') {
            require_once ($PROJECT_DIR . '/' . $class);
        }
    }
}
```

Sample class: 

```php
<?php

namespace Longman\TelegramBot;

class Strings
{

}
```

This way every time I want to use Strings class I must include it:

```php
<?php

namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Strings;

class MyCommand extends UserCommand
```

**Comment by chuv1** [comment]
Got it! Thanks a lot @jacklul!

**Comment by noplanman** [comment]
I'm reopening here and think it would make sense to have a `Utils` class for general code that can be reused.
