### ISSUE TITLE
After project updating some of Classes and Folders has been removed!!!

### ISSUE THREAD

**Issue by skmohammadi** [php-telegram-bot/core#415]
Hi, after some days i have updated project using Composer and now i found that for example, InlineKeyboard is gone! why?

Additionally, i removed Vendor folder and installed packages again but problem is exist.

**Comment by noplanman** [comment]
What version were you updating from, and to which one?
Are your custom commands what is gone now, or the default ones?

Some extra info would be very helpful 😊

**Comment by skmohammadi** [comment]
One day ago you have update some core files such telegram.php, so i decided to update from version 1.0.8 to sync with new changes. after this update, some of my core files deleted!!!

**Comment by jacklul** [comment]
I have a feeling he developed the bot inside vendor/php-telegram-bot directory and commands got wiped.

**Comment by noplanman** [comment]
@skmohammadi We've never had a version 1.0.8, so I'm a bit confused... You do mean this library right? Just to make sure you're not in the wrong repository 👌 

@jacklul Was thinking the same, hence my question.

**Comment by akalongman** [comment]
Commands will be redesigned in the new version https://github.com/php-telegram-bot/core/issues/826
