### ISSUE TITLE
Botan.io short link not working

### ISSUE THREAD

**Issue by DestroyKun** [php-telegram-bot/core#428]
Version 0.40.0

Botan.php, shortenUrl() function, string number 228.
in library
`'/s?token=%1$s&user_ids=%2$s&url=%3$s',`
and it's doesen't works. 404 error.

But if we change it to this:
`'/s/?token=%1$s&user_ids=%2$s&url=%3$s',`
all works fine

**Comment by jacklul** [comment]
Maybe the URL is weird after getting urlencoded, try other URL?

**Comment by noplanman** [comment]
Botan shortener seems to be gone. Will revisit this if and when it comes back.

**Comment by chuv1** [comment]
Looks like it will not. Afaik, dev team dropped support of botanio. But api key from [appmetrica](https://appmetrica.yandex.com) works fine.

**Comment by noplanman** [comment]
So AppMetrica is the new Botan?

**Comment by jacklul** [comment]
I believe you still have to use botan api as a relay to appmetrica, unless we found out how to directly push to appmetrica

**Comment by DestroyKun** [comment]
@noplanman Botan.io is just wrapper to Yandex AppMetrica

**Comment by noplanman** [comment]
Ok, thanks @DestroyKun for explaining.

I was thinking that it might be cool to allow various other trackers to be set up, for example Piwik etc.
Will give this some thought.
