### ISSUE TITLE
InlineKeyboard and handler - simple example

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#436]
### Required Information

- PHP version: 5.6
- PHP Telegram Bot version: last
- Using MySQL database: yes
- Update Method: Webhook
- Self-signed certificate: yes

Hi everyone. How can I make very simple InlineKeyboard with text message update?
I have a message "Choose category" and under it there should be three buttons of InlineKeyboard: "Oranges", "Apples", "Pears". When I select a category, the message text must be updated. How can this be realized? Please show the code that corresponds to my example.
I delved into the files "InlineKeyboard" and "Inlinequery" but code is too complicated for understanding...
Help me pls!

**Comment by noplanman** [comment]
Hi @MyZik 

Right, here is an example which you can start playing around with:

*CallbackqueryCommand.php*
```php
<?php

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\AdminCommands\CategoryCommand;
use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;

class CallbackqueryCommand extends SystemCommand
{
    protected $name = 'callbackquery';
    protected $description = 'Reply to callback query';
    protected $version = '1.0.0';

    public function execute()
    {
        $update         = $this->getUpdate();
        $callback_query = $update->getCallbackQuery();
        $callback_data  = $callback_query->getData();

        // Only do something for the 'category' selection.
        if (strpos($callback_data, 'category_') !== 0) {
            return Request::emptyResponse();
        }

        // Get the real category from the callback_data.
        $category = substr($callback_data, strlen('category_'));

        return Request::editMessageText([
            'chat_id'    => $callback_query->getMessage()->getChat()->getId(),
            'message_id' => $callback_query->getMessage()->getMessageId(),
            'text'       => CategoryCommand::$categories[$category],
        ]);
    }
}
```
*CategoryCommand.php*
```php
<?php

namespace Longman\TelegramBot\Commands\AdminCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\InlineKeyboard;
use Longman\TelegramBot\Entities\InlineKeyboardButton;
use Longman\TelegramBot\Request;

class CategoryCommand extends UserCommand
{
    protected $name = 'category';
    protected $description = 'Choose a category, inline.';
    protected $usage = '/category';
    protected $version = '1.0.0';

    /** @var array Inline button categories (can also be dynamically generated) */
    public static $categories = [
        'apple'  => 'Yay, an apple!',
        'orange' => 'Sweetness...',
        'cherry' => 'A cherry on top.',
    ];

    public function execute()
    {
        $keyboard_buttons = [];
        foreach (self::$categories as $key => $value) {
            $keyboard_buttons[] = new InlineKeyboardButton([
                'text'          => ucfirst($key),
                'callback_data' => 'category_' . $key,
            ]);
        }
        $data = [
            'chat_id'      => $this->getMessage()->getChat()->getId(),
            'text'         => 'Choose a category:',
            'reply_markup' => new InlineKeyboard($keyboard_buttons),
        ];

        return Request::sendMessage($data);
    }
}
```
Just put these in a folder and add them as custom commands paths using `$telegram->addCommandsPath()` in your `hook.php`.

Hope this helps to get you started 👍

**Comment by MyZik** [comment]
Hi, @noplanman 
Greath thanks for your answer! I have two small questions..
1. If I have more commands with InlineKeyboard, Callback and Queries, should I recreate the file as your CallbackQuery (for example)?
2. How to make sure that when I select a category, the buttons do not disappear?

Thank you in advance!

**Comment by noplanman** [comment]
@MyZik Ok, let's see.
> If I have more commands with InlineKeyboard, Callback and Queries, should I recreate the file as your CallbackQuery (for example)?

All callback queries get sent to the `CallbackqueryCommand` class, so all handling must be made in there. Of course you can write your specific code somewhere else and then refer to it, instead of putting *everything* into 1 method (namely `CallbackqueryCommand::execute()`).

> How to make sure that when I select a category, the buttons do not disappear?

Just set the `reply_markup` when you call `Request::editMessageText()`. For this, it's easiest to create a static method that generates the keyboard:
*CategoryCommand.php*
```php
public static function getMyInlineKeyboard()
{
    $keyboard_buttons = [];
    foreach (self::$categories as $key => $value) {
        $keyboard_buttons[] = new InlineKeyboardButton([
            'text'          => ucfirst($key),
            'callback_data' => 'category_' . $key,
        ]);
    }
    return new InlineKeyboard($keyboard_buttons);
}
```
*CallbackqueryCommand.php* (note the `reply_markup` here)
```php
return Request::editMessageText([
    'chat_id'      => $callback_query->getMessage()->getChat()->getId(),
    'message_id'   => $callback_query->getMessage()->getMessageId(),
    'text'         => CategoryCommand::$categories[$category],
    'reply_markup' => CategoryCommand::getMyInlineKeyboard(),
]);
```

> How to enable Russian language support?

What do you mean? Does Telegram not display the characters properly?
If you're talking about saving data to the database that isn't working, make sure you have a MySQL collation that supports those characters.

**Comment by MyZik** [comment]
@noplanman thanks for your aswer. You helped me a lot! Development has become even more interesting for me c:

**Comment by MyZik** [comment]
@noplanman Sorry for the stupid question, but if I created a new method in Callbackquery, how can I use it in CategoryCommand? Thanks.

**Comment by noplanman** [comment]
Easiest would be to make it `static`, then call `CallbackqueryComman::whatever()`.

BUT, what exactly is the method for? Maybe it doesn't even belong in `CallbackqueryCommand`, as any methods in there "should" be mainly for the Callback Query itself.

**Comment by MyZik** [comment]
@noplanman  I want to create a new command, say, UserslistCommand, and I want the buttons InlineKeyboard to show data from the database. For example,
id: 1, name: Mojo, nickname: Mojo7
id 2, name: Alex, nickname: Alex__12
And that under the message there were buttons of turning the data. Sonething like that: [https://core.telegram.org/file/811140217/1/NkRCCLeQZVc/17a804837802700ea4](url)

**Comment by noplanman** [comment]
A quick search and I found this: http://stackoverflow.com/a/42879866
It's in node.js, but I think the general idea should make sense to you.

You can create a static `getPagination()` method in `CallbackqueryCommand` if you like and add the necessary parameters, like `callback_id`, `current`, `max`.
`callback_id`: A unique ID to know from which inline keyboard the message came from.
`current`: The current page, to know which buttons are put in which order.
`max`: To know how far the list goes.

Then, inside your `UserslistCommand`, you can simply call `CallbackqueryCommand::getPagination('userslist`, $current, $max);` to get the inline keyboard. Of course you'll have to do some maths for `$current` and `$max` according to the items you have to display.

Does that make sense to you? I haven't tested this, but the general idea "should" work :wink:

**Comment by MyZik** [comment]
@noplanman oh, how can I connect my table `users` from database? :(
```
public static function getPagination()
    {
        $update         = $this->getUpdate();
        $callback_query = $update->getCallbackQuery();
        $callback_data  = $callback_query->getData();
        
        if (strpos($callback_data, 'user_') !== 0) {
            return Request::emptyResponse();
        }

        // Get the real category from the callback_data.
        $category = substr($callback_data, strlen('user_'));

        return Request::editMessageText([
            'chat_id'    => $callback_query->getMessage()->getChat()->getId(),
            'message_id' => $callback_query->getMessage()->getMessageId(),
            'text'       => CategoryCommand::$categories[$category],
        ]);
    }
```
And I don't understand, how can I create a method in CategoryCommand, with users paginator. Sorry 😢

**Comment by noplanman** [comment]
You can get access to the database using `DB::getPdo()`, which gives you the PDO object, allowing you to execute SQL commands.

I'll have to first create a working example of this to give to you, as I've never done this before either 😄

**Comment by MyZik** [comment]
@noplanman I tried to call the getPagination method in my command file:
`Callbackquery::getPagination()`
error: `PHP Fatal error:  Class 'Longman\\TelegramBot\\Commands\\AdminCommands\\Callbackquery' not found`

```
<?php

namespace Longman\TelegramBot\Commands\AdminCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\DB;
use PDO;
use Longman\TelegramBot\Entities\InlineKeyboard;
use Longman\TelegramBot\Entities\InlineKeyboardButton;
use Longman\TelegramBot\Request;

class UserlistCommand extends UserCommand
{
...
}
```

**Comment by noplanman** [comment]
It's called `CallbackqueryCommand` 👍  (the `Command` was missing)

**Comment by MyZik** [comment]
@noplanman now `Class 'Longman\\TelegramBot\\Commands\\AdminCommands\\CallbackqueryCommand'not found` :D

**Comment by noplanman** [comment]
Ah of course, because you're in the `AdminCommands` namespace.
You also need to add `use Longman\TelegramBot\Commands\SystemCommand\CallbackqueryCommand;`

**Comment by MyZik** [comment]
@noplanman  `PHP Fatal error:  Using $this when not in object context`
Sorry, but i really don't know what to do...

**Comment by noplanman** [comment]
I'm on this, almost finished. Will post something tomorrow 👍

**Comment by noplanman** [comment]
@MyZik Did you manage to get this working? Can I close off here?

**Comment by medness** [comment]
@noplanman you could help with handling several InlineKeyboard commands? example? 
Thank you!
