### ISSUE TITLE
Disable default commands

### ISSUE THREAD

**Issue by gvmohzibat** [php-telegram-bot/core#439]
### Required Information

- PHP version: 7.0
- PHP Telegram Bot version: 
- Using MySQL database: yes
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

Hello...
There are some default commands available and enabled by default. How can I disable them? I tried to extend the Telegram class but as I'm not a pro in php programming, I wasn't able to do that. I added this code in Telegram.php file and called this function but nothing was changed:

> public function clearCommandsPathsArray() {
        unset($this->commands_paths);
        $this->commands_paths = array();
    }
    

Please help me

**Comment by lichtscheu** [comment]
related to #93

**Comment by noplanman** [comment]
As of 0.44.0, default commands have been moved to a [separate repository](https://github.com/php-telegram-bot/example-bot).
