### ISSUE TITLE
Options Table and Handling?

### ISSUE THREAD

**Issue by lichtscheu** [php-telegram-bot/core#441]
How about creating some Functions to handle a "options"-table like WordPress? 

options-table has `option_id`, `option_name` (unique), `option_value`

Functions:
`add_option('name','value')` - add option by  `option_name`, returns false if options exists
`update_option('name','value')` -  update option by  `option_name`, if not exists -> add_option
`delete_option('name')`- delete option by  `option_name`, returns false if not found

Options are handled by unique `option_name`

Functions only work when MySQL is connected, we can use this to store options for commands, and to store timestamps, infos, texts, json objects.

Let's say i want to set random texts, with these Options we don't need an extra Table or something, with /rndtext text i can add a new text, check with get_option() or else add with add_option. now json to array, add new text, array to json and then update_option().

**Comment by noplanman** [comment]
Yes, yes, yes.

We'll have to think about the `options` table in conjunction with command configs.
Do they both apply? Does the command config overrule the option? Are they totally separate?

I really like the command configs, as they allow simple options to be set, with or without DB.

Also linking to this: #112

**Comment by lichtscheu** [comment]
I think it's  separate but we could think about storing some config options in there to overwrite default, but i think it would be better to use it only for dynamic options so we do not force people to use the framework with DB! 

To overwrite default config i would prefer some sort of config File that you could load in hook or Cron File.

**Comment by noplanman** [comment]
> we do not force people to use the framework with DB

Yes, this is important.

> To overwrite default config i would prefer some sort of config File that you could load in hook or Cron File

Do you know [`phpdotenv`](https://github.com/vlucas/phpdotenv/)?

Regarding command configs, it's up to command developers to use whatever they want.

**Comment by lichtscheu** [comment]
Nope, don't know anything about phpdotenv, i only mentioned the "config file" because most projects ham some sort of config file, so you can change / add some config and include it everywhere. like mysql-data, group-ids for cronjobs etc. and you only have to do this once and include it, tought to use this also to overwrite default configs, eventually to "activate" some default commands etc.

**Comment by lichtscheu** [comment]
So what about the Option Table? Not for configuration! =)
