### ISSUE TITLE
Moving configuration to dedicated file / environment

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/core#443]
As I'm working on the database update script (#112), I obviously need to access the database, so I require the database credentials.
The way it is now, all configs are saved directly in `hook.php`, i.e. database connection, custom commands paths, admins, command configs, etc. So the user would need to re-enter them in a database update script, instead of being able to reuse them.

I really think (as @lichtscheu has also suggested [here](https://github.com/akalongman/php-telegram-bot/issues/441#issuecomment-289230435)) we should move these things to a central config file. This would also make it easier to set up different environments for development or testing.

As for the database schema updates, it would make it very easy to just include the config and run the update script.

*Some ideas:*
- Use [phpdotenv](https://github.com/vlucas/phpdotenv/) to use configs saved in environment variables. This is great because the config can easily be overridden with system environment variables. The downside is that it can't execute arbitrary PHP code, which might be helpful for some instances, like setting up arrays or configs that require some logic in them.

- Use a `config.php` file in the root folder, that sets up all necessary constants (e.g. `TG_DB_HOST`, `TG_DB_USER`, etc.) and any extra variables.

- A very different approach would be to keep it the way it is now, but add a new method to the DB class called `updateSchema`, and then writing a script that doesn't use the Telegram object to handle any requests, but just to initialise DB and call that method.

- Or as a simple fix, have a folder with a bunch of update scripts that contain pure SQL.

I'm very open for other ideas to make this as usable and flexible as possible. Maintaining backwards compatibility might not work that easily, but it should be more or less doable by simply setting the same config values within the Telegram initialisation, if no "new" config method is found.

What are your thoughts?

**Comment by lichtscheu** [comment]
I think there should be a config.php in the bot-folder, where the hook.php is, where you can check if exists, than include and check for mysql credentials, if given -> initialize mysql connection, in that way, we don't need to load this in every hook/cron.php because we should load the config file and initialize mysql if new telegram object is started.

Doing so, you can save your mysql credentials only once, can set custom config parameter, can overwrite them in runtime if needed and can access them from everywhere! something like a config class would be nice so you can have setter and getter? 

would be cool for cron so you can set a default group in cron.php and if you want to get chat id and isn't set, getId returns the default group id set in cron.php!

**Comment by noplanman** [comment]
I've given this more thought and am kind of leaning towards leaving it as it is now, giving the developer the full choice of what to use.

As this is a library which can be used as an add-on for an already existing project, there will most likely be a dedicated `config.php`-ish file around.

So what could be an option and would make more sense, is to define constants for the important configurations, like database connection details. I don't think this library will be getting many more "global" configurations, as each command can be configured individually with `setCommandConfig()`.

Personally, I really like phpdotenv, which can be used like this: https://demo.tgbot.net/hook.php
This assures that all important credentials are out of the public web space and live together.
If any extra configs are necessary, it's as easy as creating a custom `my-awesome-config.php` and including it.

@lichtscheu What do you think?

**Comment by lichtscheu** [comment]
With custom config file autoloaded you don't need to load it in every cron and every hook, but yeah, without you can create several bots..

so i have to figure out how to get my custom config working.

as long es we get the options table and functions ^^

**Comment by noplanman** [comment]
> you don't need to load it in every cron and every hook

1 `hook.php` and 1 `cron.php`, that's not such a problem, right?

How are you managing your crons? Do you have an individual file for each one?

**Comment by lichtscheu** [comment]
nope, but it is ok for me to not implement config file.

**Comment by noplanman** [comment]
Ok, then I think best would be to make a wiki entry explaining different approaches to doing this and then close off here.

Maybe in the future we'll revisit and rethink this.

**Comment by System0x20** [comment]
using json or yaml would be a user friendlier idea

**Comment by noplanman** [comment]
In the example-bot repository, I've moved to a config file that returns an array, which is a common practice in many libraries.

I'll close off here now, as most users go via example-bot anyway. It's still up to users themselves to implement whatever method they like, like JSON or YAML as @System0x20 mentioned.
