### ISSUE TITLE
Function to check if is cron?

### ISSUE THREAD

**Issue by lichtscheu** [php-telegram-bot/core#444]
How about a function to check if current Request is cron? With `isCron()` we could check `defined('STDIN')`.

An than, related to #443 we could use a config var for `cronsecretkey` and check in `isCron()` if key is set and right, or we could create an extra function like `isCronAndKey()`.

But we need to think about how to handle cronjobs over url request, like set var for cron to check if is cron, so `cron=1` or `defined('STDIN')` needs to be given to check if cron or not.

How do you think about this?

**Comment by noplanman** [comment]
I still haven't fully grasped what you're trying to achieve here.
Could you give a concrete example?

Also, have you checked this wiki entry?
https://github.com/akalongman/php-telegram-bot/wiki/Running-with-cron-(scheduled-commands)

**Comment by lichtscheu** [comment]
yeah, got some commands running with cron.

In my commands, i want to check if the command is started by cron or by command, in one command, i check some file every minute, but the command works also with /command in chat, but only when command is started by cron, i want to write some stuff to db, herefor i check defined('STDIN') in every case or set $isCron = defined('STDIN'); so it would be useful to use $this->isCron().

And if someone wants to use this but needs external cronjob to request over url, we could check for iscron=1 in request and for both cases it would be useful to optional set a secretkey, so you can check for cron and secrectkey with one method $this->isCronAndSecret() and for some cases i would provide $this->isSecret()

Method names are not the final ones ^^

**Comment by jacklul** [comment]
Can't check for STDIN, someone might be using proxy script that is bash or python or whatever else script that passes the json to our php hook script, in that case STDIN will be defined and request considered Cron. 

It must be something more universal. 

We could add something to library variables to determine if the request is Cron or not when using my runCommands (cron) implementation.

**Comment by lichtscheu** [comment]
Ah ok, crap. 

hm ok, we could provide some var which you can set to true in cron.php and check it with this one plus the secrectkey thing with config var? it's just for getting information in the command itself if it's requested by getUpdate/Webhook or with cron.php/cron and with secretkey we give the possibility to doublecheck

**Comment by MBoretto** [comment]
Closing here

**Comment by lichtscheu** [comment]
Why?

**Comment by jacklul** [comment]
Reopening as this is on my to do list.

**Comment by lichtscheu** [comment]
uh nice =)

**Comment by noplanman** [comment]
@lichtscheu Is the fix that @jacklul provided ok for you? Can we close off here?

**Comment by lichtscheu** [comment]
Perfect =)
