### ISSUE TITLE
Regarding getDocument() in message.php

### ISSUE THREAD

**Issue by harsha-tech** [php-telegram-bot/core#452]
### Required Information

- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes
- Update Method: Webhook / getUpdates
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour

getDocument() is not working , i found out that this function is not defined in Message.php.

I need this function how can get it

**Comment by jacklul** [comment]
You might be using wrong version. 
0.41.0 is the latest.
