### ISSUE TITLE
Create Language function

### ISSUE THREAD

**Issue by InSide24** [php-telegram-bot/core#460]
I like to add Language in the Telegram SDK
i tried to inlclude lang/german.php in Hook.php and add the Variable to the Command file but that doesnt go.

Kind Regards

**Comment by noplanman** [comment]
> I like to add Language

What do you mean by that? All output is handled by commands, so you can simply create your own translated version.

**Comment by InSide24** [comment]
@noplanman No i first made now a Action that on /start language must be selected and will be writen in DB. At the moment only English 6 German is selectable. 

But i want to create 1 Command that will use english text for english user & German text for German user

**Comment by noplanman** [comment]
You might want to look into something like this:
https://packagist.org/packages/gettext/gettext

**Comment by InSide24** [comment]
Could you contact me over Skype: raphael7124

Would be great for direct support ;)
End Project will be on Github.

**Comment by noplanman** [comment]
You need help on a Telegram Bot, so we use Telegram 😉 
@noplanman

I'll leave this issue open, so that you can post your end solution for others.

**Comment by jacklul** [comment]
I find this library https://github.com/oscarotero/Gettext very useful.

**Comment by noplanman** [comment]
@jacklul Yep, same lib as I linked above. Seems to be the best one around 👍
