### ISSUE TITLE
problem send data from database to user !!!!!!!!

### ISSUE THREAD

**Issue by abbe-cipher** [php-telegram-bot/core#465]
### Required Information

- PHP version: 
- PHP Telegram Bot version:
- Using MySQL database: yes 
- Update Method: Webhook 
- Self-signed certificate no
- RAW update (if available):

### Expected behaviour

Get all record (38) from databse and send to user.

### Steps to reproduce

```php
    public static function getansphoto(
        $callback_function,
        $chat_id
    ) {
        $callback_path = __NAMESPACE__ . '\Request';
        if (!method_exists($callback_path, $callback_function)) {
            throw new TelegramException('Method "' . $callback_function . '" not found in class Request.');
        }
         $dats  = array();

        $dats=DBAA::getbillphoto();
        $ccc=count($dats);                =======>>>>>>>>>>>>i have chek this and get true 38 record
        $results = [];
        $data['chat_id']=$chat_id;
        $t=urlencode('\n');
        $num=1;
        if (is_array($dats)) {
            foreach ($dats as $row) {
                $data['caption'] ='.'.PHP_EOL.$ccc.' - '.$rrr.' - '.$num++;
                // $data['caption'] ='.'.PHP_EOL.$row['txt'];
                $file=$row['file'];
                $results[]       = call_user_func_array($callback_path . '::' . $callback_function, [$data,$file]);
                $rrr=count($results);
            }
        }
// $results[]       = call_user_func_array($callback_path . '::' . $callback_function, [$data]);
        return $results;
    }
```
#####################################################################
in callbackquery .php

```php
        case '051all': 
                                $results = Request::getansphoto(
                'sendPhoto', 
                $chat_id
            );
                         return $result;
                break;
```
#####################################################################
     

### Extra details
My problem is get message first 16 record 2 time Continuous 

1 - send 16 photo from 1 to 16
2-resend 16 photo from 1 to 16
 **********   never send from 17 to 38

**Comment by jacklul** [comment]
Are those getting send in very small intervals? If yes you're exceeding Telegram API limit.

**Comment by abbe-cipher** [comment]
thanks for your quick replay yes send in 16 photo in 20 seconds.
what can i do ?

**Comment by noplanman** [comment]
@jacklul Shouldn't your request limiter be limiting submissions like that?

**Comment by jacklul** [comment]
Yes, the limiter should prevent this from happening.
There might be undocumented limit that we are not aware of.

**Comment by tchibomann** [comment]
As I read somewhere some time ago there is not only a message limit of 30 messages per second, there is also a file size limit and a limit of sending images in a row. I actually don't know the correct limits. I think it was 5 images in a short period.

**Comment by abbe-cipher** [comment]
hi again and thanks for your response.
when i change $callback_function from sendPhoto to send message all things is fine .and bot send all(38) record.whats the problem with send photo and anybody have any idea how can i handle that win sendphoto function ???????!!!!!!!!!

**Comment by noplanman** [comment]
@abbe-cipher Mind sharing your solution?

**Comment by abbe-cipher** [comment]
thanks .my problem was in my db.in 17th record to get photo address its was null.
