### ISSUE TITLE
telegram getupdates error 'Telegram returned an invalid response'

### ISSUE THREAD

**Issue by therobb** [php-telegram-bot/core#468]
### Required Information

- PHP version: 5.6.23
- PHP Telegram Bot version: last update
- Using MySQL database: yes 
- Update Method: getUpdates

### Actual behaviour

getUpdatesCLI.php returns:

> php exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Telegram returned an invalid response! Please review your bot name and API key.' in E:\xampp\htdocs\core-master\src\Request.php:333 Stack trace: #0 E:\xampp\htdocs\core-master\src\Request.php(808): Longman\TelegramBot\Request::send('getUpdates', Array) #1 E:\xampp\htdocs\core-master\src\Telegram.php(340): Longman\TelegramBot\Request::getUpdates(Array) #2 E:\xampp\htdocs\core-master\getUpdatesCLI.php(73): Longman\TelegramBot\Telegram->handleGetUpdates() #3 {main}

### Steps to reproduce

API key is correct, double-checked and is fine

**Comment by jacklul** [comment]
Windows issue.

As a development workaround:

Replace in Telegram.php:

```php
new Client(['base_uri' => self::$api_base_uri]);
```

with:

```php
new Client(['base_uri' => self::$api_base_uri, 'verify' => false]);
```

If you plan on using Botan integration you have to do the same inside Botan.php

**Comment by therobb** [comment]
@jacklul 
i could not find it on Telegram.php but i did find it on Request.ph. and this the output after i change it with yout code : 

> php 2017-04-17 09:59:28 - Processed 0 updates

is that a normal output ? i have send view messeges to my bot.

**Comment by LuizFernandoAlmeida** [comment]
muito obrigado jacklul.
