### ISSUE TITLE
When im sendMessage in HTML parse mode some link doesnt show preview.

### ISSUE THREAD

**Issue by hamidamel** [php-telegram-bot/core#469]
Hi,why some link preview dosn't show in message.
[video](http://foot-lady.ir/sanaz/Download/videos/file_386.mp4)
this link in message dosn't show preview.why?

could any body help?
@boukeversteegh @akalongman @Metallizzer @zavg @SerafimPikalov

**Comment by jacklul** [comment]
This library has nothing to do with preview generation.

**Comment by noplanman** [comment]
For what it's worth, have a look at the `disable_web_page_preview` parameter for [sendMessage](https://core.telegram.org/bots/api#sendmessage).
