### ISSUE TITLE
send to multiple chat ids

### ISSUE THREAD

**Issue by tobsn** [php-telegram-bot/core#470]
Is there a way to send to multiple IDs with one command?
I tried an array and all kinds of other methods but it seems to either just send to the first one in a list or errors out with bad request from the API.

**Comment by jacklul** [comment]
Check sendtoall admin command. 

You can have array containing chat id's and foreach the request replacing chat id each time, make sure you have request limiter feature active or the Telegram api will block sending messages after short time of mass sending.
