### ISSUE TITLE
No method can handle the form_params config key (Guzzle issue)?

### ISSUE THREAD

**Issue by ZaneCEO** [php-telegram-bot/core#482]
I'm trying to send a message to a channel my bot is admin of like this:

```
 $telegram = new \Longman\TelegramBot\Telegram(BOT_TOKEN, BOT_NAME);
        echo \Longman\TelegramBot\Request::sendMessage([
            "chat_id" => MY_CHANNEL_ID
            "text" => "Test"
        ]);
```

This morning it worked, but now I always got this exception:

> No method can handle the form_params config key

I understood that this [is a Guzzle issue](https://github.com/guzzle/guzzle/issues/1115), but also something that [has been fixed here too](https://github.com/php-telegram-bot/core/pull/254) some time ago.

What am I missing?

### Required Information
- Operating system: CentOS 6.6
- PHP version: 5.6
- PHP Telegram Bot version:  0.44.0

**Comment by noplanman** [comment]
Hi @ZaneCEO 

I can't reproduce this, as it works perfectly for me, using both the channel id (e.g. `-12345`) and the channel name (e.g. `@my_channel`).

Could you check which version of Guzzle composer is loading for you?
Open your `composer.lock` and search for `guzzlehttp/guzzle`.

From there let me know the `version` and `reference`.

**Comment by ZaneCEO** [comment]
Hi @noplanman , thanks for your reply. I've got:

> "name": "guzzlehttp/guzzle",
>             "version": "6.2.3",
>             "source": {
>                 "type": "git",
>                 "url": "https://github.com/guzzle/guzzle.git",
>                 "reference": "8d6c6cc55186db87b7dc5009827429ba4e9dc006"
>             },

Also:

>             "name": "longman/telegram-bot",
>             "version": "0.44.1",
>             "source": {
>                 "type": "git",
>                 "url": "https://github.com/php-telegram-bot/core.git",
>                 "reference": "e522050a5e2ac73a4c0fa47705896da0df37de3a"
>             },
>             "dist": {
>                 "type": "zip",
>                 "url": "https://api.github.com/repos/php-telegram-bot/core/zipball/e522050a5e2ac73a4c0fa47705896da0df37de3a",
>                 "reference": "e522050a5e2ac73a4c0fa47705896da0df37de3a",
>                 "shasum": ""
>             },
>             "require": {
>                 "ext-curl": "*",
>                 "ext-mbstring": "*",
>                 "ext-pdo": "*",
>                 "guzzlehttp/guzzle": "^6.2",
>                 "monolog/monolog": "^1.22",
>                 "php": "^5.5|^7.0"
>             },

**Comment by noplanman** [comment]
Ok, I have those same versions.

I've set up a VPS with CentOS 6.9 and PHP 5.6.30 and it works perfectly there too.

Could you give me any extra info about your setup?

**Comment by ZaneCEO** [comment]
Ok, issue found! I've phpBB composer.json requesting an outdated version of Guzzle. Since it's using composer too, that instance of Guzzle was being loaded by Telegram too.

I'm extremely sorry for thetime you wasted on me :-(

**Comment by noplanman** [comment]
No problem at all, glad to see it's fixed 😃
