### ISSUE TITLE
Change location of default upload and download path

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/core#483]
When no upload or download path is set, the default one lies in the `vendor` folder, which isn't so great.

I suggest that if no locations are set specifically, an error is logged and nothing is written to either one.

What do you guys think?

**Comment by jacklul** [comment]
Essentially we could make the paths empty when they are not set, or grab system's temp path.

**Comment by noplanman** [comment]
Problem with the temp folder is that other users may have access to it.
So depending on the files being up and downloaded, this could be a potential privacy issue in some scenarios.

I agree to just leave them blank, but then we have the problem of people using it in production with defaults set, which would then suddenly create errors when the path doesn't exist any more 😕 

Probably best to bite the bullet and break BC on this, issuing a warning when using `Request::downloadFile()` if there is no download path set.
