### ISSUE TITLE
How to execute command on message.

### ISSUE THREAD

**Issue by linkinkov** [php-telegram-bot/core#486]
For example i need listen some words to execute command, how i can do it?
User write:
Let me booking hotel room
Bot execute command:
/booking

**Comment by linkinkov** [comment]
Also can anybody give example to send location to user?

**Comment by jacklul** [comment]
Non commands messages are handled by GenericmessageCommand.

```php
$data = [
	'chat_id' => $chat_id,
	'latitude' => $latitude,
	'longitude' => $longitude,
];

Request::sendLocation($data);
```

 think variables meaning is pretty obvious.

**Comment by linkinkov** [comment]
@jacklul https://github.com/php-telegram-bot/example-bot/blob/master/Commands/GenericmessageCommand.php ?

**Comment by jacklul** [comment]
Yes, you should add your code just before `Request::emptyResponse();`.

**Comment by linkinkov** [comment]
https://pastebin.com/cC98N1Mt whats wrong i do?

**Comment by noplanman** [comment]
Coordinates should be `float` numbers, not `string`. Just remove the `'`.

**Comment by linkinkov** [comment]
nothing is change after remove ''.
https://pastebin.com/mSg8LCQ0

**Comment by noplanman** [comment]
The quotes isn't the issues, Telegram accepts it with and without quotes.

Note that the command is `/howtofind`, as your class is called `HowtofindCommand`.
Is the file name also called `HowtofindCommand.php`?

**Comment by linkinkov** [comment]
@noplanman sorry for this stupid mistake and thanks a lot for helping :)

**Comment by noplanman** [comment]
No problem, glad it's been found 👍 

(the irony of your command called `/howtofind` 😂)
