### ISSUE TITLE
Send photo from external URL

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [php-telegram-bot/core#489]
### Required Information
- Operating system: Ubuntu 17.04 x64
- PHP version: 7
- PHP Telegram Bot version: 0.44.1
- Using MySQL database: yes
- Update Method: Webhook
- Self-signed certificate: no

How can i send photo from external url?

**Comment by haiksu** [comment]
That can be done with Telegram's sendPhoto(). More info here: https://core.telegram.org/bots/api#sendphoto


And here's the gist:

$data['photo'] = "http://yoururl";
$data['caption'] = "Photo caption";
return Request::sendPhoto($data);

**Comment by AmirHosseinKarimi** [comment]
@haiksu Thank you so much friend. :+1:

**Comment by rikyminarki** [comment]
for send photo by screen shot web pages can it?

**Comment by noplanman** [comment]
@rikyminarki If you're asking about attaching a file via `sendPhoto`:
```php
Request::sendPhoto([
    'chat_id' => $chat_id,
    'photo'   => Request::encodeFile($path_to_local_file),
]);
```

Telegram bot can't make and send screenshots, you would need an external tool for that.

**Comment by rikyminarki** [comment]
so, i must used  external tool, ex wkhtmltopdf ot wktmltoimage

2018-01-16 16:01 GMT+07:00 Armando Lüscher <notifications@github.com>:

**Comment by noplanman** [comment]
Yes, that would be the easiest solution I think 👍

**Comment by rikyminarki** [comment]
can you help me to create a sample command (/) for sending images but
through the url?
I'm looking for how to make it but I do not think I can,
I will pay after I can make it
19 Jan 2018 02.35, "Armando Lüscher" <notifications@github.com> menulis:

**Comment by noplanman** [comment]
@rikyminarki Get in touch with me on Telegram directly: t.me/noplanman
