### ISSUE TITLE
How to implement my own helper functions safely?

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#491]
What is the best and safest way to implement my own functions? Should I include them in `hook.php`?
I want my functions to be able to use the current exiting classes (this plugin's) as well (like `getMessage()`).

I'm not much familiar with classes in programming.

**Comment by noplanman** [comment]
Maybe this wiki article can help you:
https://github.com/php-telegram-bot/core/wiki/Snippets

**Comment by jacklul** [comment]
I personally use composer autoloader with my own namespaces, putting all classes in one directory.

**Comment by noplanman** [comment]
I'd personally go with @jacklul's suggestion too, to implement all your code in own classes.

> I'm not much familiar with classes in programming.

This is why I thought of pointing you to the wiki 😊

**Comment by ttvd94** [comment]
@jacklul, I don't have access to terminal with my hosting plan. Can I still use composer for that purpose?

**Comment by jacklul** [comment]
I believe there were wrappers to use composer from webspace, you can always run composer locally and then upload vendor directory.

**Comment by ttvd94** [comment]
@jacklul thank you very much for helping.

**Comment by ttvd94** [comment]
@noplanman, I'm now more familiar with and interested in OOP. Can you give me some examples on how to implement my own helper class using composer with my own namespaces?

**Comment by noplanman** [comment]
@ttvd94 Great to hear that you're getting more into OOP :tada: 

To use the composer autoloader, I suggest to get a bit familiar with it by reading here:
https://getcomposer.org/doc/04-schema.md#autoload

Depending on how you want to manage your namespaces, you need to choose the specific autoloading method.

Give it a try and let me know if you need more help!

**Comment by ttvd94** [comment]
@noplanman I read the article and also watched some youtubes, but couldn't get autoloader to work. Here is my composer.json:
```
{
    "name": "telegram-bot/project-name",
    "type": "project",
    "description": "Project description",
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "Helpers\\": "Helpers/"
        }
    },
    "require": {
        "longman/telegram-bot": "*"
    }
}
```
And here is my folder structure:
```
bot-root/
├── commands/
├── Helpers/
│   ├── Helpers.php
├── vendor/
├── composer.json
├── composer.lock
└── hook.php
```

**Comment by noplanman** [comment]
Ah of course, because you'll have to add the namespace you used in your `Helper.php` file, which should be `namespace Helpers;`.

So in your `StartCommand.php` you need to put `use Helpers\Helpers;` (instead of `use Longman\TelegramBot\Helpers;`)

**Comment by noplanman** [comment]
@ttvd94 Can we close here then?

**Comment by ttvd94** [comment]
Sure. Thanks for your help @noplanman <3
