### ISSUE TITLE
return multiple message in one command

### ISSUE THREAD

**Issue by hatame** [php-telegram-bot/core#492]
### Required Information

- Operating system: ubuntu 16.04
- PHP version: 7.0
- PHP Telegram Bot version:  .44.*
- Using MySQL database:  no
- Update Method: Webhook 
- Self-signed certificate:  Let's Encrypt

### Expected behavior

how to return multiple messages in one execute the function of command?
### Actual behavior

when I use this ` return Request::sendMessage($data); ` only one message will be returned

**Comment by jacklul** [comment]
```php

$data = [
(...)
'text' => 'message1'
];
$result = Request::sendMessage($data);

if ($result->isOk()) {
$data['text'] = 'message2';
$result = Request::sendMessage($data);
}

return $result;
```

I usually keep the `$result` then before sending next message I make sure previous was sent, but it's not necessary.
