### ISSUE TITLE
Bot sometimes replies with delay

### ISSUE THREAD

**Issue by rahimasgari** [php-telegram-bot/core#493]
### Required Information

- Operating system: centos 7
- PHP version: 7.1.4
- PHP Telegram Bot version: 0.44.1
- Using MySQL database: yes 
- MySQL version: 5.5.52-MariaDB
- Update Method: Webhook
- Self-signed certificate: yes

Hi friends,
I am new to telegram bots. and have a question.

I have seen that sometimes when i issue a command it takes about 5-10 seconds for bot to reply.
and one time it took about 30 minutes for bot to reply!

I have checked my own server. It has no load and traffic.

Have you ever experienced such problems? 
Is it something wrong with telegram servers or something else?
How can i detect where is the source of problem?

Thx in advance

**Comment by jacklul** [comment]
Make sure your PHP timezone setting is correct.
You probably should put `date_default_timezone_set("your_timezone");` on the top of the hook script.

**Comment by rahimasgari** [comment]
@jacklul, It has been set in php.ini file.

**Comment by jacklul** [comment]
You should also check your web server's logs and see if the requests aren't getting any errors.
Also use `/debug` command and check if there are any webhook errors.

**Comment by noplanman** [comment]
@rahimasgari Have you managed to fix this?

**Comment by rahimasgari** [comment]
I checked webservice log and there is no error. and also there is no error in my webhook.

But sometimes the bot response with delay and i dont know why.

**Comment by noplanman** [comment]
Maybe the latency / ping of your server?
Is the server very busy with other tasks that may cause the delay?

**Comment by rahimasgari** [comment]
No, the server does not have too much load.

**Comment by noplanman** [comment]
You're still having the delay issue?
Could you try to `ping api.telegram.org` from your server that is hosting the bot and post the output?

**Comment by rahimasgari** [comment]
It is not permanent. 
Sometimes it happens and after some minutes it becomes ok.

**Comment by jacklul** [comment]
Tried tracing route to the API when it occurs?

**Comment by rahimasgari** [comment]
No, if it occurs again i will check.
Thx fo your replies.  :)

**Comment by pooriamo** [comment]
@jacklul I had the same problem. sometimes the bot simply didn't work or was working irregularly. I checked the debug file and found this:

> bot_log.ERROR: exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Timed out while waiting for a request spot!'

The timezone setting solved my problem. Thank you very much. :grinning:
