### ISSUE TITLE
InlineKeyboard Button One row in loop

### ISSUE THREAD

**Issue by naghibi-farshad** [php-telegram-bot/core#496]
### Required Information

- Operating system:
- PHP version: 5.5
- PHP Telegram Bot version :0.44.1
- Using MySQL database: yes
- MySQL version: 5.5
- Update Method: Webhook
- Self-signed certificate: yes

Hello friends
I can't create a InlineKey on row  when get data frome database in loop:

My code examples:

```php
foreach ($category as $key => $value) {
    $keyboardButton[] = new InlineKeyboardButton([
        'text' => $value['cat_name'],
        'callback_data' => $value['cat_id']
    ]);
}
$data = [
    'chat_id' => $chat_id,
    'caption' => 'Select a Category',
    'reply_markup' => new InlineKeyboard($keyboardButton)
];
Request::sendMessage($data);
```
Notic : output of each button in a row
Like: 
```
Select a Category:
-----------------------
Category 1
-----------------------
Category 2
-----------------------
Category 3
----------------------
```

**Comment by jacklul** [comment]
try `new InlineKeyboard(...$inline_keyboard)`

**Comment by naghibi-farshad** [comment]
my problem is not solved. please advise, by sample code.
How is create **InlineKeyboard** syntax for creating buttons in a row by the loop is.

**Comment by noplanman** [comment]
If you want them all in 1 row next to each other, try like this:

```php
$keyboardButtons = [];
foreach ($category as $key => $value) {
    $keyboardButtons[] = new InlineKeyboardButton([
        'text'          => $value,
        'callback_data' => $key,
    ]);
}

$inlineKeyboard = new InlineKeyboard();
call_user_func_array([$inlineKeyboard, 'addRow'], $keyboardButtons);

$data = [
    'chat_id'      => $chat_id,
    'caption'      => 'Select a Category',
    'reply_markup' => $inlineKeyboard,
];
Request::sendMessage($data);
```

@jacklul [Argument unpacking](https://secure.php.net/functions.arguments#functions.variable-arg-list) is PHP 5.6+.

**Comment by noplanman** [comment]
@naghibi-farshad Did you manage to get it working?

**Comment by naghibi-farshad** [comment]
hi @noplanman
the problem with taking a few buttons in a row.
the output should each button in a separate row.

**Comment by noplanman** [comment]
Hi @naghibi-farshad, try the following then, more simplified:
```php
$inlineKeyboard = new InlineKeyboard([]);
foreach ($category as $key => $value) {
    $inlineKeyboard->addRow(new InlineKeyboardButton([
        'text'          => $value,
        'callback_data' => $key,
    ]));
}

$data = [
    'chat_id'      => $chat_id,
    'text'         => 'Select a Category',
    'reply_markup' => $inlineKeyboard,
];
return Request::sendMessage($data);
```

**Comment by naghibi-farshad** [comment]
tanks @noplanman
problem solved

**Comment by Daniyal-Javani** [comment]
Hi
What about each of them in one row?
