### ISSUE TITLE
Example of simple conversation

### ISSUE THREAD

**Issue by asif-rahman** [php-telegram-bot/core#499]
### Required Information

- Operating system: Windows 7
- PHP version: 5.5.12
- PHP Telegram Bot version: current updated
- Using MySQL database:  no
- MySQL version:
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Extra details
Please give me a working example of conversation. Like user starts the conversation with /conv and the bot asks "What do you want?" and then user writes "Capital of a Country", then bot asks "Which country?" and the process continues to some more steps.

**Comment by MBoretto** [comment]
Here's an example of conversation

**Comment by asif-rahman** [comment]
sorry, can't see the example. would you please re-upload?

**Comment by jacklul** [comment]
https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php

**Comment by asif-rahman** [comment]
Thanks for your help.
