### ISSUE TITLE
Fix: Error while searching custom commands

### ISSUE THREAD

**Issue by MaximusBaton** [php-telegram-bot/core#503]
Hello!

First af all, I'd like to thank you for a great library, and what is more important, your support!

I have found a problem while using this library and would like to share my solution to fix that.

So, one could face a problem while using the library with a framework.

Personally I'm using `Yii2`, and after creating a custom command it was not working.

The problem was the `Longman\TelegramBot\Telegram` class, method `getCommandObject`.
This method performs a search with the following code:
```
...
            $command_namespace = __NAMESPACE__ . '\\Commands\\' . $auth . 'Commands\\' . $this->ucfirstUnicode($command) . 'Command';
            if (class_exists($command_namespace)) {
                return new $command_namespace($this, $this->update);
            }
...
```

As you may see, it starts searching from the current namespace, still the library may be in other (e.g. `./vendor/longman/telegram-bot/src`). As a result, the library will never find the custom commands even if you specify a `command path` by `addCommandsPath` method.

My solution is to extend the `Telegram` class and override the `getCommandObject` method, like so:
```
<?php

namespace app\components\bots\Telegram;

use Longman\TelegramBot\Telegram as BaseTelegram;

class Telegram extends BaseTelegram
{
    private $_customCommandsNamespace = 'app\commands\telegram';
    
    /**
     * Get an object instance of the passed command
     *
     * @param string $command
     *
     * @return \Longman\TelegramBot\Commands\Command|null
     */
    public function getCommandObject($command)
    {
        $customCommand = $this->_customCommandsNamespace . '\\' . $this->ucfirstUnicode($command) . 'Command';
        if (class_exists($customCommand)) {
            return new $customCommand($this, $this->update);
        }

        return parent::getCommandObject($command);
    }
}

```

Have fun!

**Comment by noplanman** [comment]
@MaximusBaton Thanks so much for sharing your simple solution to this!

We are aware that the command management can be improved a lot, which is on the todo list, and has been so for quite some time 😕

Hope we can get working on it in the near future, as this is a common issue with custom namespacing.

**Comment by MKiselev** [comment]
@MaximusBaton thank you very much.

**Comment by noplanman** [comment]
@MaximusBaton Would you be up for making a wiki entry for this?
You could pretty much copy paste your first comment.

That would be best for others to find it 👍
