### ISSUE TITLE
Conversation (Survey command) in group chat

### ISSUE THREAD

**Issue by asif-rahman** [php-telegram-bot/core#504]
### Required Information

- Operating system: WIndows 7
- PHP version: 5.5.12
- PHP Telegram Bot version: latest
- Using MySQL database: yes
- MySQL version:
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Extra details

The survey command seems not working in group chat. It returns "Type your name:", but after providing a name, the next question is not showing up, while the chat is active at MySQL table. Am I missing something or conversation is not supposed to work at group chats?

**Comment by jacklul** [comment]
Bot privacy in BotFather.

**Comment by mgolkardev** [comment]
Hi
I use webhook method but my database is empty,
how create tables to work servy conversion?

Thanks

**Comment by noplanman** [comment]
@mgolkardev There is a file called `structure.sql` in the project folder which you can use to create the tables in your database.

@jacklul I noticed that @asif-rahman is using Windows, could that be a factor too?

**Comment by mgolkardev** [comment]
Hi @noplanman, my problem solving and project works well. Thank you

**Comment by jacklul** [comment]
The only issue on Windows is SSL issue as far as  I know.

**Comment by noplanman** [comment]
@asif-rahman Any update on this?
