### ISSUE TITLE
Timeout send message to channel

### ISSUE THREAD

**Issue by mgolkardev** [php-telegram-bot/core#509]
Hi

i want send message to channel but timeout!
but when using api.telegram.org its work.

please help me

- Operating system:Ubuntu 16.04LS
- PHP version:7.0.18
- PHP Telegram Bot version:0.43
- Using MySQL database: yes
- MySQL version:14.14
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

![ssss](https://cloud.githubusercontent.com/assets/4500080/26591435/e7004b7c-4572-11e7-9b75-17a6cb975849.png)

**Comment by noplanman** [comment]
You can do `Request::sendMessage($data)` with the correct [parameters](https://core.telegram.org/bots/api#sendmessage) in `$data`.

**Comment by mgolkardev** [comment]
My `$data` in `Request::sendMessage($data)` equal with `https://api.telegram.org/botTOKKEN/sendMessage?chat_id=@channelUserame&text=Hi men`

```
$data['text'] = 'Hi men';
$data['chat_id'] = '@channelUserame';
```

**Comment by chuv1** [comment]
Is bot added to the channel as admin?

**Comment by mgolkardev** [comment]
@chuv1 Yes

![eee](https://cloud.githubusercontent.com/assets/4500080/26601548/827da960-4595-11e7-829c-05e492d06d30.png)

**Comment by chuv1** [comment]
Change your `execute()` code to this, and tell us if it return anything. It should send you result of the request.

```
  public function execute() {
    
    $message = $this->getMessage();
    
    $chat_id = '@channelUserame';
    $text    = 'Hi men';
    
    $data = [
    'chat_id' => $chat_id,
    'text'    => $text,
    ];
    
    $sent = Request::sendMessage($data);
    
    if($sent->isOk()){
      Request::sendMessage(['chat_id'=>$message->getFrom()->getId(),'text'=>'Message sent.']);
    }else{
      Request::sendMessage(['chat_id'=>$message->getFrom()->getId(),'text'=>'Message not sent. Reason: '.PHP_EOL.$sent->printError()]);
    }
    
    return $sent;
    
  }
```

**Comment by mgolkardev** [comment]
Your code did not result and go to exception.
my error log file:

```
[2017-05-30 21:52:47] bot_log.ERROR: Longman\TelegramBot\Exception\TelegramException: Timed out while waiting for a request spot! in /var/www/domain.me/public_html/bot/vendor/longman/telegram-bot/src/Request.php:1061
Stack trace:
#0 /var/www/domain.me/public_html/bot/vendor/longman/telegram-bot/src/Request.php(335): Longman\TelegramBot\Request::limitTelegramRequests('sendMessage', Array)
#1 /var/www/domain.me/public_html/bot/vendor/longman/telegram-bot/src/Request.php(422): Longman\TelegramBot\Request::send('sendMessage', Array)
#2 /var/www/domain.me/public_html/bot/Commands/StartCommand.php(66): Longman\TelegramBot\Request::sendMessage(Array)
#3 /var/www/domain.me/public_html/bot/vendor/longman/telegram-bot/src/Commands/Command.php(139): Longman\TelegramBot\Commands\SystemCommands\StartCommand->execute()
#4 /var/www/domain.me/public_html/bot/vendor/longman/telegram-bot/src/Telegram.php(483): Longman\TelegramBot\Commands\Command->preExecute()
#5 /var/www/domain.me/public_html/bot/vendor/longman/telegram-bot/src/Telegram.php(452): Longman\TelegramBot\Telegram->executeCommand('start')
#6 /var/www/domain.me/public_html/bot/vendor/longman/telegram-bot/src/Telegram.php(380): Longman\TelegramBot\Telegram->processUpdate(Object(Longman\TelegramBot\Entities\Update))
#7 /var/www/domain.me/public_html/bot/hook.php(85): Longman\TelegramBot\Telegram->handle()
#8 {main} [] []
```

**Comment by jacklul** [comment]
Request limiter is turned on and your PHP timezone is different from database timezone.
Please set same timezone for both.

**Comment by mgolkardev** [comment]
@jacklul I changed timezone in PHP and MySql to same timezone and add `date_default_timezone_set()` in head of `hook.php`, but i have timeout error again; **but when i disable limiter its work**!

**Comment by jacklul** [comment]
Pretty sure you will have to clean the `request_limiter` table as it may still contain records with wrong dates and times which can trigger this issue.

**Comment by mgolkardev** [comment]
I remove all tables and recreate tables, but not working again!

**Comment by jacklul** [comment]
You will have to execute a command and compare timestamp in database for `requst_limiter` table, it should be current one.

If it inserts future times it will be producing this issue.

**Comment by mgolkardev** [comment]
Hi
I found my problem.

in `Request.php` -> method `limitTelegramRequests` -> line `1033`
in line 1068 compare `$chat_id` with more then zero `$chat_id > 0`
but `channelId` is `String` and method go to `break;`

thanks guys
