### ISSUE TITLE
GenericMessage usage

### ISSUE THREAD

**Issue by ja-heller** [php-telegram-bot/core#510]
### Required Information

- Operating system: Debian 8
- PHP version: 7.1.1
- PHP Telegram Bot version: master
- Using MySQL database: no
- Update Method: Webhook
- Self-signed certificate:  no

Are there some examples on how to use the GenericMessage Class? All I would need to get up & running is to let the bot react to simple commands not starting with a "/". I don't get how to use the GenericMessage class.

**Comment by haiksu** [comment]
Here's a quick example how to get the bot to reply when you type "genericmessage"

```
public function execute()
{

  $txt = trim($message->getText(true));
  $chat_id = $message->getChat()->getId();
  $user_id = $message->getFrom()->getId();
  if($txt == "genericmessage") {
      $data = [];
      $data['chat_id'] = $chat_id;
      $data['reply_to_message_id'] = $message->message_id;
      $data['text'] = "a reply to a generic message";
      Request::sendMessage($data);
  }

  return Request::emptyResponse();

}
```

**Comment by ja-heller** [comment]
@haiksu 

Thanks for your fast reply, is there some way to write the logic inside a command and let this command being triggered?
For example when a user writes test 1234 I would like to trigger a command and get the parsed arguments ("1234"). I know this sounds strange, but when using the buttons of telegram I don't want to let every button look like /step1 etc. or is there a way to change the text of a button and let the button trigger a command "in the background", without making the text of the button the command itself.

**Comment by haiksu** [comment]
You get the whole message the user typed with "$message = $this->getMessage();". After that you can parse the string however you like. 

I haven't used conversations yet myself, so I'm afraid I can't offer any help on that.

**Comment by ja-heller** [comment]
Thanks, I thought there would be a nicer way of handling custom commands without handling all the logic inside the callback handler.

**Comment by haiksu** [comment]
Oh there might be and hopefully someone else comes back with better knowledge ^_^

**Comment by mbsmt** [comment]
@haiksu, regarding to your sample code, do we must put or own code in "GenericCommand.php" inside `src/Commands/GenericCommand.php` or we have to create a new "GenericCommand.php" inside `__DIR__.'/Commands/'` ?
By the way, imagine we don't know anything about user's answers. But we know the sequences. for example, after `/name` command, we are expecting a name, and after next question we are waiting for surname. How can we deal with such mechanism?

**Comment by noplanman** [comment]
Best check out the [`/survey`](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php) command to see how the conversation works.

@mbsmt ALL custom code must go in a separate folder, NEVER change the core files, as they will be reset when updating, thus losing all changes.

> Thanks, I thought there would be a nicer way of handling custom commands without handling all the logic inside the callback handler.

@ja-heller You are free to handle the code as you like in separate classes / methods / whatever, but it must be called from somewhere. Or I'm not fully understanding what you mean by the above comment 😕
Could you maybe elaborate on your exact use case and what you'd like to achieve?

**Comment by mbsmt** [comment]
Thank you @noplanman for `/survery`
