### ISSUE TITLE
Simple sample code for send and receive message

### ISSUE THREAD

**Issue by NabiKAZ** [php-telegram-bot/core#514]
I have problem with send and received message in the bot.

In manual wrote this:
```PHP
$result = Request::sendMessage(['chat_id' => $chat_id, 'text' => 'Your utf8 text 😜 ...']);
```
But I don't know about `$chat_id` of robot.
For test I try my chat id and user id but not happen! and not store any messages in error log!

And also I don't know how can I received user's messages.

My scenario is very simple, I just want to send `hello` in the robot, and then, my robot response `hello {user name}`. But I didn't found good sample code in this project!

```PHP
<?php
// Load composer
require_once __DIR__ . '/vendor/autoload.php';

// Add you bot's API key and name
$bot_api_key  = 'xxxxx';
$bot_username = 'xxxxx';

$mysql_credentials = [
    'host'     => 'xxxxx',
    'user'     => 'xxxxx',
    'password' => 'xxxxx',
    'database' => 'xxxxx',
];

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($bot_api_key, $bot_username);

    // Error, Debug and Raw Update logging - Don't forget to define the $path
    //Longman\TelegramBot\TelegramLog::initialize($your_external_monolog_instance);
    $path = '.';
    Longman\TelegramBot\TelegramLog::initErrorLog($path . '/' . $bot_username . '_error.log');
    Longman\TelegramBot\TelegramLog::initDebugLog($path . '/' . $bot_username . '_debug.log');
    Longman\TelegramBot\TelegramLog::initUpdateLog($path . '/' . $bot_username . '_update.log');

    // Enable MySQL
    $telegram->enableMySql($mysql_credentials);

    $result = Longman\TelegramBot\Request::sendMessage(['chat_id' => '@xxxxx', 'text' => 'Your utf8 text 😜 ...']);

    // Handle telegram webhook request
    $telegram->handle();
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // Silence is golden!
    echo $e;

    // Log telegram errors
    Longman\TelegramBot\TelegramLog::error($e);
} catch (Longman\TelegramBot\Exception\TelegramLogException $e) {
    // Silence is golden!
    // Uncomment this to catch log initilization errors
    echo $e;
}
```

**Comment by NabiKAZ** [comment]
Sorry I forgot use namespace `Longman\TelegramBot\` and cause fatal error, But now seems code return debug in log.


```
[2017-06-03 17:06:14] bot_log.DEBUG: Verbose HTTP Request output:
* Hostname was NOT found in DNS cache
*   Trying 149.154.167.197...
* Connected to api.telegram.org (149.154.167.197) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.2 / xxxxxxxx
* Server certificate:
*        subject: OU=Domain Control Validated; CN=api.telegram.org
*        start date: 2015-05-23 16:17:38 GMT
*        expire date: 2018-05-23 16:17:38 GMT
*        subjectAltName: api.telegram.org matched
*        issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*        SSL certificate verify ok.
> POST /botxxxxxxxx/sendMessage HTTP/1.1
User-Agent: GuzzleHttp/6.2.1 curl/7.38.0 PHP/5.6.15
Content-Type: application/x-www-form-urlencoded
Host: api.telegram.org
Content-Length: 59

* upload completely sent off: 59 out of 59 bytes
< HTTP/1.1 400 Bad Request
* Server nginx/1.10.0 is not blacklisted
< Server: nginx/1.10.0
< Date: Sat, 03 Jun 2017 12:36:14 GMT
< Content-Type: application/json
< Content-Length: 73
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
<
* Connection #0 to host api.telegram.org left intact
```

**Comment by noplanman** [comment]
When passing your chat_id, it does not require the `@` in front, that is only used for groups and channels.

Also, to be able to send a message to a user, that user must already have started a conversation with your bot. So just start the chat with your bot and it should work.

**Comment by NabiKAZ** [comment]
@noplanman  Thanks.
And how can I use `getMessage()` in hook file?!
I know about create a command, But I want get every messages in hook file directly and process on it.

**Comment by noplanman** [comment]
You can use the `GenericmessageCommand` for what you want, as all commands go through there.
Then you can do whatever you like with the commands.

The `hook.php` file is only used for Telegram to access your library, all handling happens further down the line.

**Comment by myehrajat** [comment]
can u make an example how i can get message and even callback_query?

**Comment by noplanman** [comment]
@myehrajat Inside a command you can use `$this->getMessage()` to get the Message object and `$this->getCallbackQuery()->getData()` to get the `callback_query`.

Please create a separate issue if you need extra help, or join the PHP Telegram Bot Support group on Telegram: [@PHP_Telegram_Bot_Support](https://telegram.me/PHP_Telegram_Bot_Support)

**Comment by NabiKAZ** [comment]
> Please create a separate issue if you need extra help, or join the PHP Telegram Bot Support group on Telegram: @PHP_Telegram_Bot_Support

![image](https://user-images.githubusercontent.com/246721/29959402-5e8a27d4-8f0c-11e7-856c-371f0135cd51.png)
