### ISSUE TITLE
Can I have and define many call back classes?

### ISSUE THREAD

**Issue by NabiKAZ** [php-telegram-bot/core#516]
Can I have and define many call back classes?
For example if I have two scenarios about `category` and `news`. Can I have separated call back classes be like `CallbackquerycategoryCommand extends SystemCommand` and `CallbackquerynewsCommand extends SystemCommand`.
I try this but does not works.

**Comment by jacklul** [comment]
You can't, you have to check the callback data inside `CallbackqueryCommand` and then redirect it to either  `CallbackquerycategoryCommand` or `CallbackquerynewsCommand` with `$this->getTelegram->executeCommand("")`.

**Comment by noplanman** [comment]
I'm busy working on a nicer solution for this, something along the lines of:
```php
CallbackqueryCommand::addCallbackHandler(function (CallbackQuery $query) {
    // Handle the callback!
});
```

In the anonymous callback (which can also be a separate function / method somewhere) the callback is handled. So one would check if this is the wanted callback and then do whatever with it.

Inside the CallbackqueryCommand itself is something like this:
```php
foreach (self::$callbacks as $callback) {
    $response = $callback($this->getUpdate()->getCallbackQuery());
}
```

@jacklul What do you think of this? Not sure if we discussed it at some point or not.

This would be the case with the default CallbackqueryCommand. Of course the custom overriding of the entire command still works as before :+1:

**Comment by jacklul** [comment]
You could always try to implement it and we would test it out. 

What about cases when callback data is like "order_39383"? I guess you took this under consideration?

**Comment by noplanman** [comment]
The way I have it now, ALL callbacks get sent to ALL handlers, so it would be up to the user to sanitize the input and see if it's the necessary one.

So the creator of the command would have to explicitly set something unique in the callback_data that can then be identified by the handler.

The other option would be to pass that unique string when setting the handler:
```php
CallbackqueryCommand::addCallbackHandler($unique_id, function (CallbackQuery $query) {
    // Handle the callback!
});
```
Then we could split the callback data in CallbackqueryCommand and only pass it on to the proper handler.
BUT, maybe some user doesn't want that and prefers a simple callback that has a totally different format! Of course we could add extra options etc. etc. but I'd prefer to keep it quite simple.

**Comment by noplanman** [comment]
@NabiKAZ, check this PR where this has been implemented.
