### ISSUE TITLE
How download original photo

### ISSUE THREAD

**Issue by mgolkardev** [php-telegram-bot/core#522]
Hi
I'm using this code.
but this code download small photo.

```php
if (strtolower($message->getType()) === 'photo') {

    $file = Request::getFile(['file_id' => $photo_id]);
    if ($file->isOk()) {
        Request::downloadFile($file->getResult());
    }
}
```

how do i download the original photo?
please help me

**Comment by noplanman** [comment]
Look here and the comments after:
https://github.com/php-telegram-bot/core/issues/386#issuecomment-271162568

**Comment by noplanman** [comment]
@mgolkardev Did you manage to solve your problem?
