### ISSUE TITLE
Reset and manage file name download

### ISSUE THREAD

**Issue by NabiKAZ** [php-telegram-bot/core#525]
When I download file, store the file under `photos/file_xxx.jpg` path on disk.
ex: file_11.jpg, file_12.jpg, file_13.jpg
How can I manage file name (`file_xxx.jpg`)?
And also how can I reset `xxx` number in contain of file name?

**Comment by jacklul** [comment]
I believe that name and number is assigned by Telegram and you can't control it, you can only rename it after downloading.

**Comment by NabiKAZ** [comment]
I delete bot and create that again!!! 🤓

**Comment by noplanman** [comment]
> I delete bot and create that again!!! 🤓

Mind explaining what you mean by this? And if this changed anything?

**Comment by NabiKAZ** [comment]
For reset `xxx` number in file name ;-)
