### ISSUE TITLE
Class purpose and usage description in comments

### ISSUE THREAD

**Issue by mbsmt** [php-telegram-bot/core#526]
Hi. I've read some of source codes in this projects and have a suggestion for its authors.
You did your best in commenting and describing class methods, properties, etc. But the main purpose and usage of class is not mentioned in file comments. On the other hand, as I think, all of classes and tools inside PHP Telegram Bot are not described in Wiki. So I think it's better to mention to class usages inside comments or completing Wiki (That is much better).

**Comment by akalongman** [comment]
We are working on this
