### ISSUE TITLE
Restrict BOT Access

### ISSUE THREAD

**Issue by asif-rahman** [php-telegram-bot/core#527]
### Required Information

- Operating system: Windows
- PHP version: 5.12
- PHP Telegram Bot version: Latest
- Using MySQL database: yes
- MySQL version:
- Update Method: Webhook
- Self-signed certificate: yes
- RAW update (if available):

### Extra details
I want to restrict my BOT to certain groups only. I can do that by checking the chat id against the group id. But the problem is I have too many commands and I don't want to add access code to each of the PHP scripts.
I want to implement the code on a single page, like the hook. But how can I do that in the hook or in any other single page?

**Comment by jacklul** [comment]
This should put you in right direction:

```php
$POST = file_get_contents("php://input");
$POST_DATA = json_decode($POST, true);

$user_id = null;
if (isset($POST_DATA['callback_query']['from']['id'])) {
    $user_id = $POST_DATA['callback_query']['from']['id'];
} elseif (isset($POST_DATA['inline_query']['from']['id'])) {
    $user_id = $POST_DATA['inline_query']['from']['id'];
} elseif (isset($POST_DATA['message']['from']['id'])) {
    $user_id = $POST_DATA['message']['from']['id'];
}

$allowed = [];

if (!in_array($user_id, $allowed)) {
exit;
}
```

The code should be before handling the webhook in hook script.

**Comment by noplanman** [comment]
I like this very much, would be cool to implement this into the manager 😇

**Comment by TheXron** [comment]
> This should put you in right direction:
> 
> ```
> $POST = file_get_contents("php://input");
> $POST_DATA = json_decode($POST, true);
> 
> $user_id = null;
> if (isset($POST_DATA['message']['chat']['id'])) {
>     $user_id = $POST_DATA['message']['chat']['id'];
> }
> 
> $allowed = [];
> 
> if (!in_array($user_id, $allowed)) {
> exit;
> }
> ```
> 
> You will have to modify it a bit to consider other types of updates.
> 
> The code should be before handling the webhook in hook script.

Hello bro. How can I set condition if the array is false? I mean I want to send message to user if they are trying to access my bot.

**Comment by jacklul** [comment]
> Hello bro. How can I set condition if the array is false? I mean I want to send message to user if they are trying to access my bot.

That code is very old, the preferred way of achieving this would be extending Telegram class, example approach:

```php
<?php

class TelegramBot extends Telegram
{
    public function executeCommand(string $command): ServerResponse
    {
	$user = $this->update->getUpdateContent()->getFrom();
	$user_id = $user->getId()
		
        if ($user instanceof User && $this->isAuthorized($user_id )) {
            return parent::executeCommand($command);
        }

        return Request::sendMessage(
		[
			'chat_id' => $user_id,
			'text' => 'Goodbye',
		]
	);
    }
}
```
The **isAuthorized(int $user_id)** has to return true of user is allowed to message the bot.

**Comment by TheXron** [comment]
Thanks for reply bro. I still prefer to use your old code because it is more easy to understand. Anyways, After many trial I get some tricks on how to execute sending message to restricted users using your old code but it's not that very clean 😂
