### ISSUE TITLE
Can use `Google Analytics` for see statistics?

### ISSUE THREAD

**Issue by NabiKAZ** [php-telegram-bot/core#528]
I know about `botan` project.
Now can use `Google Analytics` for see statistics?

**Comment by noplanman** [comment]
Not out of the box, but you could implement it I guess.

Would be cool if we had some way to add different analytics tools, but that's not the case at the moment.

@jacklul Any experience apart from Botan?

**Comment by jacklul** [comment]
@noplanman Not enough to integrate it...

**Comment by noplanman** [comment]
Will close here for now. If we do decide to implement analytics functionality, a new issue will be created.
