### ISSUE TITLE
How to sendMessage form database

### ISSUE THREAD

**Issue by noerarief23** [php-telegram-bot/core#531]
### Required Information

- Operating system: Windows
- PHP version: 5.6
- PHP Telegram Bot version: 0.3
- Using MySQL database: yes 
- MySQL version:
- Update Method: Webhook 
- Self-signed certificate: yes / no
- RAW update (if available):

How to sendMessage form database?
### Expected behaviour

```
$db = mysqli_connect('localhost', '***', '***', '***');//on PHP Telegram bot using Mysqli Or PDO?
                ;//on PHP Telegram bot using Mysqli Or DB? 
                $query =    "SELECT store_id FROM store WHERE `user_id` = '$user_id'";
                $res = $db->query($query);
                $row = $res->fetch_assoc();
                 if ($text === '', true)) {

                    $notes['state'] = 0;
                    $this->conversation->update();
                    $data['reply_markup'] = Keyboard::remove(['selective' => true]);

                    $result = Request::sendMessage($row['store_id']);
                    break;
                }

                $notes['store'] = $text;
                $text = '';
```

**Comment by noplanman** [comment]
- First of all, your code is broken near the `if` statement, have another look at it.
- Secondly, it would be easier for you to use the PDO element of the bot by using `DB::getPdo()`, then using that to query any data you need.
- Lastly, to send a message, you need this parameter format:
`Request::sendMessage(['user_id' => $user_id, 'text' => $row['store_id']]);`

Also note, this only works if that user has already initiated a chat with the bot.

Good luck 👍

**Comment by noplanman** [comment]
@noerarief23 Did you get this working? Can I close here?
