### ISSUE TITLE
Dynamical array of callback's data for use in `InlineKeyboard`

### ISSUE THREAD

**Issue by NabiKAZ** [php-telegram-bot/core#533]
I know about `InlineKeyboard` class, can get each inline keyboard buttons as separated argument.
```PHP
new InlineKeyboard($keyboard_buttons1, $keyboard_buttons2, ...);
```
Now I have `$menus` dynamical array of callback's data.
I want to read all the data with `foreach` and make category 3 each for every line I create.

Be like this:
![image](https://user-images.githubusercontent.com/246721/26960612-d507f848-4ced-11e7-9309-b1173ec95a24.png)

Sample code:
```PHP
$menus = [
	'x1'=>'y1',
	'x2'=>'y2',
	'x3'=>'y3',
	'x4'=>'y4',
	'x5'=>'y5',
	'x6'=>'y6',
	'x7'=>'y7',
];
$keyboard_buttons = [];
$keyboard_buttons_line = [];
$n = 0;
foreach ($menus as $key => $value) {
	$n++;
	$keyboard_buttons_line[] = [
		'text'          => $value,
		'callback_data' => $key,
	];
	if ($n % 3 == 0 || count($menus) == $n) {
		$keyboard_buttons[] = $keyboard_buttons_line;
		$keyboard_buttons_line = [];
	}
}

echo "<pre>";
print_r(new InlineKeyboard($keyboard_buttons[0], $keyboard_buttons[1], $keyboard_buttons[2])); //THIS HAVE BUG !!! (I don't know how many argument must be set.)
```

**Comment by NabiKAZ** [comment]
I thinks must be use `[call_user_func_array](http://php.net/manual/en/function.call-user-func-array.php)` function or `[ReflectionClass](http://php.net/manual/en/reflectionclass.newinstanceargs.php)` core class.

**Comment by NabiKAZ** [comment]
I find solution in this: #496 ticket.

Solution #1:
```PHP
return new InlineKeyboard(...$keyboard_buttons);
```

Solution #2:
```PHP
$inline_keyboard = new InlineKeyboard([]);
foreach($keyboard_buttons as $keyboard_button) {
call_user_func_array([$inline_keyboard, 'addRow'], $keyboard_button);
}
return $inline_keyboard;
```

Thanks to @jacklul and @noplanman

**Comment by noplanman** [comment]
Nice solution!

I've done something similar to this in the past, here my solution to give you some inspiration 😇 

```php
$keyboard_buttons = [];
foreach ($menus as $callback_data => $text) {
    $keyboard_buttons[] = new InlineKeyboardButton([
        'callback_data' => $callback_data,
        'text'          => $text,
    ]);
    // Or if you like 1-liners:
    // $keyboard_buttons[] = new InlineKeyboardButton(compact('callback_data', 'text'));
}

$keyboard_rows        = array_chunk($keyboard_buttons, 3);
$data['reply_markup'] = new InlineKeyboard(...$keyboard_rows);
```

and just for the sake of it, a tiny version:
```php
array_walk($choices, function (&$text, $callback_data) {
    $text = new InlineKeyboardButton(compact('callback_data', 'text'));
});
$data['reply_markup'] = new InlineKeyboard(...array_chunk($choices, 3));
```

Note: You'll need at least PHP 5.6 for the [argument unpacking](https://wiki.php.net/rfc/argument_unpacking) to work.

**Comment by NabiKAZ** [comment]
wow that's perfect.
I did not know `array_chunk` function, this is nice function.
