### ISSUE TITLE
Keyboard status

### ISSUE THREAD

**Issue by mohsenshahab** [php-telegram-bot/core#539]
I would like to know about current keyboard status.

Some time keyboard is like this image:
![key](https://user-images.githubusercontent.com/1585961/27251209-86c47f9c-5357-11e7-8b48-c16550e78313.png)
and I dont know How to active keyboard , when keyboard is disabled.

**Comment by jacklul** [comment]
There is no such option in the API for this, you best choice is to send the keyboard with every message when possible.
