### ISSUE TITLE
Help to use

### ISSUE THREAD

**Issue by luiguild** [php-telegram-bot/core#545]
### Required Information

- Operating system: Ubuntu
- PHP version: 5.6.15
- PHP Telegram Bot version: 0.44.1
- Using MySQL database: no
- MySQL version: X
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available): No

### Expected behaviour

I just want try using the example

### Actual behaviour

PHP Fatal error: Class 'TelegramBot\TelegramBotManager\BotManager' not found in manager.php

### Steps to reproduce

All thing are installed, hook runs... I just try execute manager.php

### Extra details

[Wed Jun 21 23:01:37.676864 2017] [:error] [pid 234904] [client 177.12.30.61:55040] PHP Fatal error:  Class 'TelegramBot\\TelegramBotManager\\BotManager' not found in ...

![captura de tela 2017-06-21 as 23 36 58](https://user-images.githubusercontent.com/16566338/27414928-8cb6ea44-56da-11e7-8ed5-ff572735f3ce.png)

**Comment by noplanman** [comment]
Hi @luiguild, I see that you're wanting to use the [PHP Telegram Bot Manager](https://github.com/php-telegram-bot/telegram-bot-manager), which is a layer on top of the core PHP Telegram Bot. 

In your project folder, you need to use the correct project via composer:
`require php-telegram-bot/telegram-bot-manager`

That should get the code that is probably missing now.

(For next time, please open an issue on that repository.)
