### ISSUE TITLE
Deny BOT intersections with groups

### ISSUE THREAD

**Issue by HAlexTM** [php-telegram-bot/core#548]
### Required Information

- Operating system: Ubuntu server
- PHP version: 7.1
- PHP Telegram Bot version: 0.44.1
- Using MySQL database: yes
- MySQL version: I don't remember, we don't need it
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available): nope

### Expected behaviour

If the bot is added to a group it shouldn't be able to interact to commands and messages but it should be able to send messages.
(Users cannot use bot commands etc.)
The button which lists the commands should not appear.

### Actual behaviour

Users can run bot commands and interact with it, they will see the commands list button
### Steps to reproduce

Create a bot, add it to a group, use it.

Is there any way to blind it when in a group?

**Comment by noplanman** [comment]
You mean something like this? #527

**Comment by HAlexTM** [comment]
Not really, I just want it to be restricted in groups
@noplanman

**Comment by HAlexTM** [comment]
I could exit if the ID is set and in negative

**Comment by noplanman** [comment]
Yes, that would be an option 👍 

That will block access completely, even to admins and system commands, just so you know!

There is an open ticket to implement this in the Manager here:
https://github.com/php-telegram-bot/telegram-bot-manager/issues/33

**Comment by HAlexTM** [comment]
Thanks this solved my problem

**Comment by noplanman** [comment]
A better option might be to make use of the `chat->type` data:
```php
$POST_DATA['message']['chat']['type'];
```
Which can be `private`, `group`, `supergroup` and `channel`. So you can limit more finely if required.

**Comment by HAlexTM** [comment]
Awesome! I guess I'm going to use the type

**Comment by chuv1** [comment]
![image](https://user-images.githubusercontent.com/13127366/27512731-3ee68908-5975-11e7-9976-2696ec74b0ff.png)
Or, you could just disable group support for bot via BotFather...

**Comment by HAlexTM** [comment]
The problem is that I need it in a group but users shouldn't use it so I'll
stick with the type check :)

Il Dom 25 Giu 2017, 2:10 AM chuv1 <notifications@github.com> ha scritto:
