### ISSUE TITLE
Can i get details photo from sender?

### ISSUE THREAD

**Issue by noerarief23** [php-telegram-bot/core#555]
### Required Information
Operating system: Windows
PHP version: 5.6
PHP Telegram Bot version: 0.3
Using MySQL database: yes
MySQL version:
Update Method: Webhook
Self-signed certificate: yes / no

### Expected behaviour
I want to get date and any details photo from sender and collect to database

![image](https://user-images.githubusercontent.com/5919917/27852811-c340d3a8-618a-11e7-81a1-d551cb005421.png)

**Comment by jacklul** [comment]
You will have to download it with `getFile` method based on the `file_id` you get with the Update containing the photo, then you can use third party library to extract those details and put it into database.

**Comment by noplanman** [comment]
When a user sends a photo to your bot, you can get the image file like this (remember to set your download path in hook.php, `$telegram->setDownloadPath(...);`):
```php
$message = $this->getMessage();
if ($photo = $message->getPhoto()) {
    // Get the original size.
    $photo = end($photo);

    $file = Request::getFile([
        'file_id' => $photo->getFileId(),
    ]);
    if ($file->isOk() && Request::downloadFile($file->getResult())) {
        // File downloaded successfully, get the local path.
        $photo_location = $this->telegram->getDownloadPath() . '/' . $file->getResult()->getFilePath();

        // Do something with the file...
        $exif_data = exif_read_data($photo_location);
        ...
    } else {
        // Failed to download.
    }
}
```

Getting data from the file is a different thing that we can't support here, but I'll point you to this page:
https://secure.php.net/manual/en/function.exif-read-data.php

You'll find enough resources online if you search for them 😉 

(I haven't fully tested the code above, but it should work)

**Comment by noerarief23** [comment]
I will try :wink: 

Thank you @jacklul @noplanman :smile:

**Comment by noerarief23** [comment]
i get this from exif_read_data.
{"FileName":"file_131.jpg","FileDateTime":1499251437,"FileSize":32297,"FileType":2,,"MimeType":"image\/jpeg","SectionsFound":"","COMPUTED":{"html":"width=\"500\" height=\"500\"","Height":500,"Width":500,"IsColor":1}}

i think that is'nt original file from sender. 
nope :smile: 
i will search other resources.

hemm, @noplanman how i can check if file is exist in path download ?

**Comment by noplanman** [comment]
Telegram most probably strips exif data as it compresses the file before sending it.
The only way to get the full data, is if your users send the file as a document, not a photo.

```php
if (file_exists($photo_location)) {
    // File exists, yay! 🎉
} else {
    // Nope, download must have failed 😒
}
```

**Comment by noplanman** [comment]
@noerarief23 Can we close here? Did you get this working?
