### ISSUE TITLE
Error: Class 'Longman\TelegramBot\Tests\Unit\TestHelpers' not found

### ISSUE THREAD

**Issue by mintux** [php-telegram-bot/core#556]
### Required Information

- Operating system: Linux mint 17.3 64bit
- PHP version: 7.1
- PHP Telegram Bot version: 0.45.0
- Using MySQL database: no

### Expected behaviour
Works without any error

### Actual behaviour
get error: 
`[Wed Jul 05 14:03:38.607093 2017] [php7:error] [pid 7319] [client 127.0.0.1:41634] PHP Fatal error:  Uncaught Error: Class 'Longman\TelegramBot\Tests\Unit\TestHelpers' not found in /home/mrg/www/Project/telegram_bots/seller_bot/index.php:5\nStack trace:\n#0 {main}\n  thrown in /home/mrg/www/Project/telegram_bots/seller_bot/index.php on line 5
`

### Steps to reproduce
i put this code in index.php: 
```
<?php
require __DIR__ . "/../vendor/autoload.php";
var_dump(\Longman\TelegramBot\Tests\Unit\TestHelpers::getFakeRecordedAudio());
```
![selection_001](https://user-images.githubusercontent.com/3824913/27858625-2da4187c-618b-11e7-972b-34512e145c0c.png)

### Extra details
the file TestHelpers.php in /home/mrg/www/Project/telegram_bots/seller_bot/vendor/longman/telegram-bot/tests/unit is exists

**Comment by jacklul** [comment]
Why are you trying to run unit tests just like that? 

If you're sure what you're doing then you have to add php unit into your project and do `composer update`.

**Comment by noplanman** [comment]
@mintux What are you trying to do?

Please *please* **please** don't rely on anything in the tests part of this project, as there will be big changes happening soon that I've been working on. If there's anything you really need, copy it into a separate class of yours and include that into your project 👍
