### ISSUE TITLE
how to control keyboard when user selected something

### ISSUE THREAD

**Issue by 666b666** [php-telegram-bot/core#558]
- Operating system: CentOS 7.1
- PHP version: 7.1
- Update Method: Webhook
- Self-signed certificate: No

hi everyone 
i already have the keyboard.

i want to do something when user selected one of the keys
and i want to find out which key selected, and then i want to run an Method for every individual key when selected.

for example:
i want to give a phone number from user, i have two keys in my keyboard: 1. auto send my number 2. enter manually 

so, how i can control them? i mean i want to do something when user selected one of them , and then do something with the next thing that user sends to bot,
but i've no idea how to do it

**Comment by 666b666** [comment]
first of all, thanks to @noplanman for helping me.
for this purpose that i've, i should use **conversion** and for using that. i needed to rewrite my Command class in new format! what format? [this](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php) format
also i needed to create new mysql db and connect it to the script using root/hook.php file

and there you go!
it works so well

**Comment by noplanman** [comment]
Well done!
