### ISSUE TITLE
Payments

### ISSUE THREAD

**Issue by lexxizz** [php-telegram-bot/core#559]
Are you planning to create payments methods to this core?

**Comment by noplanman** [comment]
Absolutely! But unfortunately there are no desktop clients yet to test the feature properly.

You can find the PR for it here: #543

**Comment by lexxizz** [comment]
Haw can I use Payments methods? Do you have some examples?

**Comment by noplanman** [comment]
We don't have any examples yet. But you can check out the API 3.0 branch here:
https://github.com/noplanman/php-telegram-bot/tree/bot_api_3.0

and then see how to use the commands according to the official API here:
https://core.telegram.org/bots/api#payments

Sorry I don't have any better answer at this time 😞

**Comment by lexxizz** [comment]
But maybe you know when this feature will be realized?

**Comment by noplanman** [comment]
It should already work properly, but we can't test it due to the lack of Telegram clients that actually support it.

I really hope that the official Telegram Desktop clients will support it soon!!
