### ISSUE TITLE
Database Records

### ISSUE THREAD

**Issue by mohsenshahab** [php-telegram-bot/core#560]
My tables in Database (specific update and message Tables)  are grown , and I can't remove old records(foreign key error)
what can I do ?
can I remove these Tables (update AND message )?

**Comment by noplanman** [comment]
Updates table can be emptied without a problem, no foreign key errors there.
As for the others, you could just ignore the foreign key constraints and empty it.
```sql
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE message;
SET FOREIGN_KEY_CHECKS = 1;
```

**Comment by jacklul** [comment]
No idea but editing message that was previously  in database can result in constrain error in this case. 

We might want to implement `cleanup <days>` command for this...
 I have very similar command in one of my bots, I don't forget I'll handle this!

**Comment by jacklul** [comment]
https://github.com/php-telegram-bot/core/pull/563

**Comment by noplanman** [comment]
@mohsenshahab Check out the new `/cleanup` admin command in version 0.46.0 👍
