### ISSUE TITLE
Show contacts list

### ISSUE THREAD

**Issue by lexxizz** [php-telegram-bot/core#561]
Can I use some method to show to user his contacts list where he can share contact with bot?

**Comment by noplanman** [comment]
No, but any of your users can simply go to the contact they would like to share with the bot and choose "Share Contact" and then send it to the bot.
![share-contact](https://user-images.githubusercontent.com/9423417/28112295-c20a771e-66f8-11e7-95c7-c91a2e05fb78.png)

**Comment by lexxizz** [comment]
Thank you!
