### ISSUE TITLE
Error when I try to send a markdown formatted message 

### ISSUE THREAD

**Issue by ognarb** [php-telegram-bot/core#564]
### Required Information
- Operating system: Linux
- PHP version: 7.1
- PHP Telegram Bot version: 0.45 (I use the manager)
- Using MySQL database:  no
- MySQL version: no
- Update Method: Webhook
- Self-signed certificate: no

I'm trying to send a markdown message with `Request::sendMessage($data);`.
The following works well, but it's not formatted :

 ```
$message = $this->getMessage();
        
$chat_id = $message->getChat()->getId();
$text = '*some text*'

$data = [
    'chat_id'  => $chat_id,
    'text' => $text,
 ];

return Request::sendMessage($data);
```

And when I try this, it doesn't work anymore and in my log I get a 400 error:

```
$message = $this->getMessage();
        
$chat_id = $message->getChat()->getId();
$text = '*some text*';

$data = [
    'chat_id' => $chat_id,
    'text' => $text,
    'parse_mode'  => 'MARKDOWN', // I also have tried to use 'Markdown' and 'markdown' instead of 'MARKDOWN' but it doesn't change anything.
 ];

return Request::sendMessage($data);
```

Did I make a error somewhere or it is an error of the library ?

### Extra details
Here the log 

```
> POST /bot<my_api_key>/sendMessage HTTP/1.1
User-Agent: GuzzleHttp/6.2.1 curl/7.38.0 PHP/7.1.3
Content-Type: application/x-www-form-urlencoded
Host: api.telegram.org
Content-Length: 3490

* upload completely sent off: 3490 out of 3490 bytes
< HTTP/1.1 400 Bad Request
* Server nginx/1.10.1 is not blacklisted
< Server: nginx/1.10.1
< Date: Mon, 17 Jul 2017 18:40:35 GMT
< Content-Type: application/json
< Content-Length: 153
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
< 
* Connection #0 to host api.telegram.org left intact
```

Sorry for my poor english skills 

EDIT: I just try to use html instead of markdown, and it's work

**Comment by jasonyqwang** [comment]
I have the same problem

**Comment by jasonyqwang** [comment]
I see ！！！
parse_mode=> 'markdown'
When using mode of markdown，We must Use the following syntax in our message:

> \*bold text*
> \_italic text_
> \[inline URL](http://www.example.com/)
> \[inline mention of a user](tg://user?id=123456789)
> \`inline fixed-width code`
> \```block_language
>    pre-formatted fixed-width code block
> \```

It is not strictly markdown syntax!!!
[Api introduction](https://core.telegram.org/bots/api#markdown-style)
