### ISSUE TITLE
Where is example folder?

### ISSUE THREAD

**Issue by Darkinuyasha** [php-telegram-bot/core#567]
The readme continue to point a "example" folder, but I can't find it.
I can't find it anywhere, I feel so noob right now, but I searched and searched without results. Help :(

**Comment by jacklul** [comment]
I guess our readme is a bit outdated, whoopise!

Take a look here: https://github.com/php-telegram-bot/example-bot

**Comment by noplanman** [comment]
I'm on it, fixing up the readme, which indeed is quite out of date...
