### ISSUE TITLE
.

### ISSUE THREAD

**Issue by abolfazlmohajeri** [php-telegram-bot/core#570]
.

**Comment by abolfazlmohajeri** [comment]
solved 👍

**Comment by noplanman** [comment]
@abolfazlmohajeri 
For the future, please leave your initial issue and make a new comment with the actual solution before closing it.

That way, if another user has the same problem, there is already a solution for it 👍 

Thanks

**Comment by abolfazlmohajeri** [comment]
Im so sorry
