### ISSUE TITLE
can't send local audio file

### ISSUE THREAD

**Issue by ehsand** [php-telegram-bot/core#571]
hi
How can i send audio from local file?

**Comment by jacklul** [comment]
Small snippet to get you started:

```php
$data = [
  'chat_id' => $chat_id, 
  'audio'  => '/var/www/public/audio.mp3'
];

Request:sendAudio($data);
```

(assumes usage of latest version of the library)

**Comment by noplanman** [comment]
@jacklul You'll need to use `Request::encodeFile(...)`:
```php
$data = [
  'chat_id' => $chat_id, 
  'audio'  => Request::encodeFile('/var/www/public/audio.mp3'),
];

Request::sendAudio($data);
```

Passing just a string, Telegram will try to load it as an external source, e.g. `https://example.com/audio.mp3`.

**Comment by jacklul** [comment]
Well then, how about we could detect local path being given there and encode automatically?

**Comment by noplanman** [comment]
@jacklul We could do that, but I was trying to get away from all the custom implementations :grin:

Also, it would introduce the following problem:
```
www.example.com
 - mypic.jpg
hook.php
```

There is also a valid image at `www.example.com/mypic.jpg`.

Which one gets used?

We'd then have to make sure that the scheme (http or https) is always passed to ensure proper loading.

Using the exact functionality that the API provides, it's easier to just use it as it is. Users will have to only learn 1 proper way, which works for all entity types.
