### ISSUE TITLE
getInput() json decode

### ISSUE THREAD

**Issue by seddighi78** [php-telegram-bot/core#575]
hi
why getInput() is as a json format? 
why decod it?

**Comment by jacklul** [comment]
Because Telegram API sends updates as Json object?

**Comment by seddighi78** [comment]
yes its json string fro using in php have to decode it

**Comment by jacklul** [comment]
So where is the problem here? 
If you want Update object use `$this->getTelegram()->getUpdate()`.

**Comment by seddighi78** [comment]
this is get update method i use webhook and i have to use getInput()

**Comment by jacklul** [comment]
No, that method returns current Update object that is already created from the incoming json.

**Comment by seddighi78** [comment]
I can`t use it for while useing webhook

**Comment by jacklul** [comment]
Yes you can. It doesn't refer to getUpdates method, you're misunderstanding it. 

No matter if webhook or getUpdates calling getUpdate inside a command will always return appropriate Update object that is supposed to be processed. 

If you look at the example-bot repository you will see that it's being used in every command.

**Comment by seddighi78** [comment]
Thank you so much, going to test it 👌🏻
