### ISSUE TITLE
Link a site and a bot

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#583]
### Required Information

- PHP Telegram Bot version: Last
- Using MySQL database: Yes
- Update Method: Webhook
- Self-signed certificate: yes

Hi everyone! How can I make sure that on my site, after some action of the user in the admin panel, the bot notifies me that? How correctly connect my site & Telegram API?

Thanks in advance.

**Comment by noplanman** [comment]
In your site's code, you can easily include the PHP Telegram Bot library (if you're already using composer for your site, all the better), then you can add the specific functionality to your code.

e.g. When a user performs an action, inside the code that your site executes, you can do this (assuming your Telegram object is a already initialised during the loading of your request):
```php
Request::sendMessage([
    'chat_id' => 123, // your ID
    'text'    => 'User performed xyz',
]);
```

It's as easy as that!

Or I misunderstood what you're trying to do :grin:

**Comment by noplanman** [comment]
@MyZik Is this solved for you?
