### ISSUE TITLE
get new data

### ISSUE THREAD

**Issue by seddighi78** [php-telegram-bot/core#584]
i want to get new data while webhook is active. my code is:

```
<?php
require_once __DIR__ . "/vendor/autoload.php";

use Longman\TelegramBot\Request as Bot;

$telegram = new \Longman\TelegramBot\Telegram("****:***************");

Bot::sendMessage(['chat_id' => '****', 'text' => 'hello world']);
```

i want to get `user_id` that called the bot and send "hello world" to that

**Comment by noplanman** [comment]
Take a look at the [`/start`](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/StartCommand.php) command.
Also, you might want to read into [creating custom commands](https://github.com/php-telegram-bot/core/wiki/Create-your-own-commands).
