### ISSUE TITLE
cheat on "share contact" button : share another user contact

### ISSUE THREAD

**Issue by jaavid** [php-telegram-bot/core#587]
- Operating system: Linux
- PHP version: 5.6
- PHP Telegram Bot version: 4.7
- Using MySQL database: yes 
- MySQL version:
- Update Method: Webhook 
- Self-signed certificate:  no

### Expected behaviour
in conversation, i have a share your contact button, user must share their contact and check is it true or not.

### Actual behaviour
user share another user contact and the bot not check check user id

![share](https://user-images.githubusercontent.com/1959108/29128080-18cf24dc-7d38-11e7-991b-eecf3956d179.jpg)

**Comment by jaavid** [comment]
🤔

**Comment by viikufa** [comment]
When i'm use request_contact button doing addition  check getFrom->getId() with this user_id, and if this equal then user share to me his contact
