### ISSUE TITLE
Don't send message after selecting the button help me please

### ISSUE THREAD

**Issue by futureclient** [php-telegram-bot/core#588]
- Operating system: Linux srv-plesk20.ps.kz 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64
- PHP version: 7.0.21 (64bit); cgi-fcgi; Linux
- Using MySQL database:  no
- Update Method: Webhook
- Self-signed certificate:  no

### 
I have 2 commands
InfoCallbackqueryCommand.php

```
<?php

namespace Longman\TelegramBot\Commands\SystemCommands;


use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;

class InfoCallbackQueryCommand extends SystemCommand
{
    protected $name = 'callbackquery';
    /**
     * @var string
     */
    protected $description = 'Reply to callback query';
    /**
     * @var string
     */
    protected $version = '1.1.0';
    /**
     * Command execute method
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        $update            = $this->getUpdate();
        $callback_query    = $update->getCallbackQuery();
        $callback_query_id = $callback_query->getId();
        $callback_data     = $callback_query->getData();

        return Request::editMessageReplyMarkup([
           'chat_id' => $update->getMessage()->getChat()->getId(),
           'message_id' => $this->getMessage()->getMessageId(),
           'text' => 'test'
        ]);
    }
}
```
and MenuCommand.php
```
<?php
namespace Longman\TelegramBot\Commands\UserCommands;


use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\InlineKeyboard;
use Longman\TelegramBot\Request;

class MenuCommand extends UserCommand
{
    protected $name = 'menu';
    protected $description = 'Show inline keyboard';
    protected $usage = '/menu';
    protected $version = '1.0.0';

    public function execute()
    {
        $chat_id = $this->getMessage()->getChat()->getId();

        $inline_keyboard = new InlineKeyboard([
            ['text' => 'Помощь', 'callback_data' => 'callbackquery'],
            ['text' => 'Информация', 'callback_data' => '!info'],
        ], [
            ['text' => 'Начало', 'callback_data' => '!start'],
        ]);

        $data = [
            'chat_id'      => $chat_id,
            'text'         => 'Выберите одну из предложенных команд',
            'reply_markup' => $inline_keyboard,
        ];
        return Request::sendMessage($data);
    }
}
```

And I do not understand how to as after pressing to send a message to the same chat. 
my bot @testMnpBot

Thanks!

**Comment by jacklul** [comment]
If that's where the problem is - use `sendMessage` instead of `editMessageText`... 

You can get message object from callback query `$this->getCallbackQuery()->getMessage()->...` from here you can use normal methods as with `Message` object. This does not work for inline messages (posted from inline mode to any chat). 

If you want to reply to whoever clicked button use `$this->getCallbackQuery()->getFrom()->... ` (`User` object).

**Comment by futureclient** [comment]
> You can get message object from callback query $this->getCallbackQuery()->getMessage()->... from here you can use normal methods as with Message object. This does not work for inline messages (posted from inline mode to any chat). 
Ssroy, i'm did not understand you, what u mean. 
i write this :
```
$update            = $this->getUpdate();
        $callback_query    = $update->getCallbackQuery();
        $callback_query_id = $callback_query->getId();
        $callback_data     = $callback_query->getData();
        $data = [
            'chat_id' => $this->getCallbackQuery()->getMessage()->getChat()->getId(),
            'text'              => 'help!',
        ];
        return Request::sendMessage($data);
```
and nothing happens.
How i can call command, after press button?
Thanks

**Comment by futureclient** [comment]
ok, i found this code :
```
$output = json_decode(file_get_contents('php://input'), TRUE);
$chat_id = $output['message']['chat']['id'];
$first_name = $output['message']['chat']['first_name'];
$message = $output['message']['text'];
$callback_query = $output['callback_query'];
$data = $callback_query['data'];
$message_id = ['callback_query']['message']['message_id'];
$chat_id_in = $callback_query['message']['chat']['id'];
switch($message) {
    case '/start':
        sendMessage($chat_id,'test',null);
        break;
    case '/test':
        $inline_button1 = array("text"=>"Google url","callback_data"=>"/test1");
        $inline_button2 = array("text"=>"work plz","callback_data"=>'/plz');
        $inline_keyboard = [[$inline_button1,$inline_button2]];
        $keyboard=array("inline_keyboard"=>$inline_keyboard);
        $replyMarkup = json_encode($keyboard);
        sendMessage($chat_id, "ok", $replyMarkup);
        break;
}
switch($data){
    case '/plz':
        sendMessage($chat_id_in, "plz", null);
        break;
    case '/test1':
        sendMessage($chat_id_in,'test1',null);
}
function sendMessage($chat_id, $message, $replyMarkup) {
    file_get_contents($GLOBALS['api'] . '/sendMessage?chat_id=' . $chat_id . '&text=' . urlencode($message) . '&reply_markup=' . $replyMarkup);
}

```
And as I understood, that you must use the switch.
How i can integrate this code in project?

**Comment by noplanman** [comment]
When using callback queries, I'd recommend to use the new callback feature implemented here: #540 

This allows you to easily add callbacks for inline keyboard queries. Check the example on the PR.

You can then use the switch in your callback, to get the callback data and do whatever you want with it :+1:

**Comment by futureclient** [comment]
> When using callback queries, I'd recommend to use the new callback feature implemented here: #540

This allows you to easily add callbacks for inline keyboard queries. Check the example on the PR.

You can then use the switch in your callback, to get the callback data and do whatever you want with it 👍

Thanks U, again. But i do no understand, how to use this?
maybe i show my example, U correct me? 
Becouse i begginer in use another API and Library, Ssory, And thanks in advance

**Comment by futureclient** [comment]
how i can add my command in callback function?
```
CallbackqueryCommand::addCallbackHandler(function (CallbackQuery $query) {
        if ($query->getData() == "help") {
                --> this? //sendMessage($query->getMessage()->getChat()->getId(),'test',null);
        }
    });
```

**Comment by futureclient** [comment]
and i check this:
```
CallbackqueryCommand::addCallbackHandler(function (CallbackQuery $query) {
       $data = $query->getData();
       switch ($data){
           case "lvl1_help":
               sendMessage($query->getMessage()->getChat()->getId(),'help',null);
               break;
           case "lvl1_info":
               sendMessage($query->getMessage()->getChat()->getId(),'info',null);
               break;
           default:
               sendMessage($query->getMessage()->getChat()->getId(),'not founding',null);
               break;
       }
    });
```
and noting nothing happens.
maybe u have sample for quite such as I?
i'm cry.

**Comment by noplanman** [comment]
Hmm, that works for me!

You sure you've set the `callback_data` correctly for the inline keyboard buttons?

Also, this code needs to be in your hook (or getUpdates) **before** the request is handled!

**Comment by futureclient** [comment]
> Hmm, that works for me!
You sure you've set the callback_data correctly for the inline keyboard buttons?
Also, this code needs to be in your hook (or getUpdates) file before the request is handled!

This is my hook.php
```
use Longman\TelegramBot\Commands\SystemCommands\CallbackqueryCommand;
use Longman\TelegramBot\Entities\CallbackQuery;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Telegram;
use Longman\TelegramBot\TelegramLog;
try {
    // Инициализация бота
    $telegram = new Telegram($API_KEY, $BOT_NAME);
    // Подключение базы данных
    $telegram->enableMySQL($mysql_credentials);
    // Добавление папки commands,
    // в которой будут лежать ваши личные комманды
    $telegram->addCommandsPath(__DIR__ . "/commands/");
    // Добавление администратора бота
    $telegram->enableAdmin((int)$USER_ID);
    // Включение логов
    TelegramLog::initUpdateLog(__DIR__."/logs/update/".date('Y-m-d')."/".$BOT_NAME . '_update.log');
    TelegramLog::initErrorLog(__DIR__."/logs/error/".date('Y-m-d')."/".$BOT_NAME . '_error.log');
    TelegramLog::initDebugLog(__DIR__."/logs/debug/".date('Y-m-d')."/".$BOT_NAME . '_debug.log');
    // Опционально. Здесь вы можете указать кастомный объект update,
    // чтобы поймать ошибки через var_dump.
    $telegram->setCustomInput("");
    //обработчик callback запросов
    CallbackqueryCommand::addCallbackHandler(function (CallbackQuery $query) {
       $data = $query->getData();
       switch ($data){
           case "lvl1_help":
               $data = [
                   'chat_id' => $query->getMessage()->getChat()->getId(),
                   'text' => 'help'
               ];
               Request::sendMessage($data);
               break;
           case "lvl1_info":
               $data = [
                   'chat_id' => $query->getMessage()->getChat()->getId(),
                   'text' => 'info'
               ];
               Request::sendMessage($data);
               break;
           default:
               $data = [
                   'chat_id' => $query->getMessage()->getChat()->getId(),
                   'text' => 'default'
               ];
               Request::sendMessage($data);
               break;
       }
    });
    // Основной обработчик событий
    $telegram->handle();
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    var_dump($e);
} catch (Longman\TelegramBot\Exception\TelegramLogException $e) {
    var_dump($e);
}
```

And my inline-keyboard here^

```
 public function execute()
    {
        $chat_id = $this->getMessage()->getChat()->getId();

        $inline_keyboard = new InlineKeyboard(
             [
                ['text' => 'Помощь','callback_data' => 'lvl1_help'],
                ['text' => 'Информация', 'callback_data' => 'lvl1_info'],
             ],
             [
                ['text' => 'Команды', 'callback_data' => 'lvl1_commands'],
                ['text' => 'Контакты', 'callback_data' => 'lvl1_contact'],
             ],
             [
                ['text' => 'Закончить беседу', 'callback_data' => 'lvl1_stop']
             ]
        );

        $data = [
            'chat_id'      => $chat_id,
            'text'         => 'Добро пожаловать!'. PHP_EOL .' Для продолжения, нажмите на кнопку меню.'. PHP_EOL .'Для вызова меню введите /start',
            'reply_markup' => $inline_keyboard,
        ];
        return Request::sendMessage($data);
    }
```
and my update.log:
```
{"update_id":397555416, "callback_query":{"id":"1855119158854641045","from":{"id":XXX,"first_name":"=> TuVi |","last_name":"xRites <=","language_code":"ru-RU"},"message":{"message_id":1274,"from":{"id":443120385,"first_name":"TuviWaiter","username":"testMnpBot"},"chat":{"id":XXX,"first_name":"=> TuVi |","last_name":"xRites <=","type":"private"},"date":1502884537,"text":"\u0414\u043e\u0431\u0440\u043e \u043f\u043e\u0436\u0430\u043b\u043e\u0432\u0430\u0442\u044c!\n \u0414\u043b\u044f \u043f\u0440\u043e\u0434\u043e\u043b\u0436\u0435\u043d\u0438\u044f, \u043d\u0430\u0436\u043c\u0438\u0442\u0435 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0443 \u043c\u0435\u043d\u044e.\n\u0414\u043b\u044f \u0432\u044b\u0437\u043e\u0432\u0430 \u043c\u0435\u043d\u044e \u0432\u0432\u0435\u0434\u0438\u0442\u0435 /start","entities":[{"type":"bot_command","offset":84,"length":6}]},"chat_instance":"1654208307583307370","data":"lvl1_help"}}
```

**Comment by futureclient** [comment]
Thanks all, it's realy worked!!!
i just remove this:
```
$telegram->setCustomInput("");
```
in my hook.php

**Comment by noplanman** [comment]
Hmm, I noticed that line and tested it on my install, and it should work anyway, as an empty custom input shouldn't be regarded 😕 Must check the code again.

Great that you got it working though!

**Comment by farmaworld** [comment]
i'm sorry but when i put a callbackquery Command in my hook.php i don't need my file CallbackqueryCommand.php?
i have a situation like this post, with multiple button

**Comment by noplanman** [comment]
@farmaworld What do you mean by `put a callbackquery Command in my hook.php`?

All commands should be in the custom command folder, the hook should only be used as an entry point for the request, which then gets passed on to the respective command files.

**Comment by farmaworld** [comment]
``        $chat_id = $this->getMessage()->getChat()->getId();

        $inline_keyboard = new InlineKeyboard([
            ['text' => 'Prova', 'callback_data' => 'testcallback'],
            ['text' => 'Prova1', 'callback_data' => 'testcallback1'],
            ['text' => 'Prova2', 'callback_data' => 'testcallback2'],
        ]);

        $data = [
            'chat_id'      => $chat_id,
            'text'         => 'Benvenuti nel Bot di Farmaworld, attendiamo la tua scelta',
            'reply_markup' => $inline_keyboard,
        ];

        return Request::sendMessage($data);``

**Comment by noplanman** [comment]
Right, you're 2nd example of setting the callback directly in the `hook.php` should work. The only thing that's missing, is to answer the callback at the end of the function with `$query->answer();`

Does the 2nd way not work for you? Does the inline keyboard button not send the message when clicked? Also, do you have logging set up?

**Comment by farmaworld** [comment]
i don't understund
this is my code

``    CallbackqueryCommand::addCallbackHandler(function (CallbackQuery $query) {
        $data = $query->getData();
        switch ($data){
            case "testcallback":
                $data = [
                    'chat_id' => $query->getMessage()->getChat()->getId(),
                    'text' => 'Prova'
                ];
                Request::sendMessage($data);
                break;
            case "testcallback1":
                $data = [
                    'chat_id' => $query->getMessage()->getChat()->getId(),
                    'text' => 'Prova1'
                ];
                Request::sendMessage($data);
                break;
            default:
                $data = [
                    'chat_id' => $query->getMessage()->getChat()->getId(),
                    'text' => 'Prova2'
                ];
                Request::sendMessage($data);
                break;
        }
    }); ``

where i put this?
in hook.php
or in CallbackqueryCommand.php file?

**Comment by noplanman** [comment]
@farmaworld That goes into your `hook.php` before `$telegram->handle();`

**Comment by farmaworld** [comment]
and my CalbackqueryCommand.php file what will happen.
i delete
i'm sorry, when i finish i make a new post with all expication, for all people

**Comment by farmaworld** [comment]
work fine 
i put that in hook.php
and delete CallbacqueryCommand.php

**Comment by noplanman** [comment]
Perfect, glad to hear it's working!

Tip: to keep your `hook.php` light of code, you can move callbacks like that into separate classes and methods and then reference it like this:
```php
CallbackqueryCommand::addCallbackHandler(['MyClass', 'MyMethod']);
```
