### ISSUE TITLE
The NewChatMembersCommand.php does not work

### ISSUE THREAD

**Issue by yylzcom** [php-telegram-bot/core#592]
### Required Information

- Operating system: Debian GNU/Linux 8.6 (jessie)
- PHP version: PHP 5.6.26-0+deb8u1 (cli) (built: Sep 21 2016 12:37:50)
- PHP Telegram Bot version:  Version 0.45.0
- Using MySQL database: no
- MySQL version:
- Update Method: Webhook 
- Self-signed certificate:  no
- RAW update (if available):
{"update_id":4005401xx, "message":{"message_id":114,"from":{"id":32264xxxx,"first_name":"_","last_name":"xxxx","username":"txxyi","language_code":"en-US"},"chat":{"id":-20152xxxx,"title":"Test Group","type":"group","all_members_are_administrators":true},"date":1502760641,"new_chat_participant":{"id":108xxxx62,"first_name":"xx","last_name":"xxx"},"new_chat_member":{"id":1083xxxx2,"first_name":"xx","last_name":"xxx"},"new_chat_members":[{"id":1083xxxx2,"first_name":"xx","last_name":"xxx"}]}}

### Expected behaviour

Send welcome message exactly like NewChatMembersCommand.php  do.

### Actual behaviour

Not message sent

### Extra details

Other commands like /whoami work fine.
Try to enable or disable bot privacy but problem still there.

### Extra
Thanks for providing this great code. 
Really appreciate any suggestions.

**Comment by yylzcom** [comment]
Update to Version 0.47.1 but still no luck to get it work

**Comment by noplanman** [comment]
I've updated the example-bot commands, so please give this one a try:
https://github.com/php-telegram-bot/example-bot/blob/master/Commands/NewchatmembersCommand.php

It works perfectly for me.

**Comment by yylzcom** [comment]
@noplanman  Thanks a lot!
It works perfectly now!
Best regards!
