### ISSUE TITLE
Telegram returned an invalid response!

### ISSUE THREAD

**Issue by mohsenshahab** [php-telegram-bot/core#593]
Operating system: ubuntu
PHP version: 7.0
PHP Telegram Bot version: 0.45.0
Using MySQL database: yes 
MySQL version: 5
Update Method: Webhook
Self-signed certificate:  no

How to  check server response , Before telegram display this error

> 

Telegram returned an invalid response! Please review your bot name and API key.
--
 
I want first check server response (or internet connection) , then send data to telegram

**Comment by noplanman** [comment]
Would have been great if you filled out the issue properly, so I'll ask here again, please answer the following:

- Operating system:
- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes / no
- MySQL version:
- Update Method: Webhook / getUpdates
- Self-signed certificate: yes / no

**Comment by M0H314-hasani** [comment]
I following this tutorial (https://github.com/php-telegram-bot/core) but when i open set.php i  confront with is issue  "Telegram returned an invalid response! Please review your bot name and API key"
what's the problem?

**Comment by akalongman** [comment]
Close due to inactivity
