### ISSUE TITLE
reply_to_message bug?

### ISSUE THREAD

**Issue by jagdtiger9** [php-telegram-bot/core#596]
./longman/telegram-bot/src/DB.php
line:852
$reply_to_message    = $message->getReplyToMessage();
$reply_to_message_id = null;
if ($reply_to_message instanceof ReplyToMessage) {

---
./longman/telegram-bot/src/Entities/Message.php
line:60
'reply_to_message'  => self::class, 

I guess there should be "ReplyToMessage::class" instead, to fulfill DB.php condition
'reply_to_message'  => ReplyToMessage::class,

**Comment by jacklul** [comment]
`ReplyToMessage` will contain regular `Message` object. as you can see `ReplyToMessage` class extends `Message` and adds nothing, it's literally the same thing, just called differently for logic reasons.

**Comment by jagdtiger9** [comment]
So what about this code lines
./longman/telegram-bot/src/DB.php
line:852
$reply_to_message = $message->getReplyToMessage();
$reply_to_message_id = null;
if ($reply_to_message instanceof ReplyToMessage) {
...

it will never gets TRUE, and no message_reply_id will be set

**Comment by jacklul** [comment]
Confirmed, `reply_to_chat` and `reply_to_message` stay empty in the database.

**Comment by jagdtiger9** [comment]
Thank you!
