### ISSUE TITLE
Correctly choose in database

### ISSUE THREAD

**Issue by futureclient** [php-telegram-bot/core#601]
Hi again. I connect in my hook.php
```
$telegram->enableMySql($mysqlData);
```
and i see in my db more tables, and correctly record.

and questions: How i can choose my users_id?

i don't want damp sql strings, looking for any PDO in vendor, and i'm don't understand more.

Unfortunately I did not find examples in repository.

Thank in advance!

**Comment by jacklul** [comment]
You can get PDO object with `DB::getPdo();` and then execute `SELECT` query.

Alternatively look at this command: https://github.com/php-telegram-bot/core/blob/master/src/Commands/AdminCommands/WhoisCommand.php, `DB::selectChats()` function might be what you want.

**Comment by futureclient** [comment]
oh, i see this, i just don't understand how to use this )
this is how i want use 
```
$subscribers = DB::selectUsers->all();
$users[] = $subscribers->id;
foreach($users as $user)
{
   // any code this.
}
```
becouse how i can add static method in project?

**Comment by jacklul** [comment]
```php
$results = DB::selectChats([
      'groups'      => false,
      'supergroups' => false,
      'channels'    => false,
      'users'       => true,
]);

if (is_array($results)) {
    $results = reset($results);
}

foreach ($results as $user) {
    //your code here
    //$user['chat_id'] should be user_id
}

```

**Comment by futureclient** [comment]
Thanks you so match, i try this code tomorrow

**Comment by futureclient** [comment]
@jacklul your choose is correctly and work it that 👍 Thanks you ! So match, again.
