### ISSUE TITLE
Problem with InlineKeyboardMarkup

### ISSUE THREAD

**Issue by dorcu** [php-telegram-bot/core#603]
Hi people!!

I use this code in php to send messages:

<pre>use Longman\TelegramBot\Request;
use Longman\TelegramBot\Entities\InlineKeyboardMarkup;

$telegram = new Longman\TelegramBot\Telegram($bot_api_key, $bot_username);

$inline_keyboard = [
	['text' => 'inline', 'switch_inline_query' => 'true'],
    ['text' => 'callback', 'callback_data' => 'identifier'],
    ['text' => 'open url', 'url' => 'https://github.com/akalongman/php-telegram-bot'],
];

$data = [
	'chat_id' => $MyID,
	'text' => 'Hello!!...',
	//'reply_markup' => new InlineKeyboardMarkup(['inline_keyboard' => [$inline_keyboard]]),
];

echo 'OK';

Request::sendMessage($data);</pre>

But when I decompile the line "reply_markup" my code not working. What happens? Where is the error?

**Comment by noplanman** [comment]
What version of the Bot are you using?

`InlineKeyboardMarkup` doesn't exist any more.

**Comment by noplanman** [comment]
@dorcu Have you updated your bot to the latest version (0.48.0)? Are you still having issues with this?

**Comment by dorcu** [comment]
Yeahh! I change InlineKeyboardMarkup by InlineKeyboard and now it's working
