### ISSUE TITLE
Keyboard cant be included

### ISSUE THREAD

**Issue by myehrajat** [php-telegram-bot/core#606]
require ABS . '/vendor/autoload.php';
//require ABS . '/core-master/src/Entities/Keyboard.php';

use Longman\TelegramBot\Request;
use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\File;
use Longman\TelegramBot\Entities\PhotoSize;
use Longman\TelegramBot\Entities\UserProfilePhotos;
use Longman\TelegramBot\Entities\Keyboard;

return this fatal error however the file exist
Fatal error: Class 'Longman\TelegramBot\Entities\Keyboard' not found in /var/www/vhosts/ejarehkhodro.com/httpdocs/ejarehkhodro.com/XX/index.php on line 34

[اجاره خودرو](https://ejarehkhodro.com)

**Comment by noplanman** [comment]
Hmm, maybe try to update with composer (`composer update`) or simply dump the autoloader (`composer dumpautoload`) to make sure that composer is correctly autoloading.

**Comment by noplanman** [comment]
@myehrajat Did you manage to fix this?

**Comment by akalongman** [comment]
Close due to inactivity
