### ISSUE TITLE
Error: 429 Too Many Requests

### ISSUE THREAD

**Issue by GatoPresto** [php-telegram-bot/core#607]
Hi!

I have a problem with Error: 429 Too Many Requests. Could you help me please?
When I try to set webhook via set.php I get message like this: "Webhook was not set! Error: 429 Too Many Requests: retry after 1". But everything is ok when I try to set webhook manually via curl.

What I do wrong?

**Comment by noplanman** [comment]
What is the output of `getWebhookInfo` when called via curl?

(Remember to remove hook URL before posting!)

**Comment by GatoPresto** [comment]
@noplanman 
```json
{"ok":true,"result":{"url":"<my current webhook>","has_custom_certificate":false,"pending_update_count":36,"last_error_date":1503832948,"last_error_message":"Wrong response from the webhook: 500 Internal Server Error","max_connections":40}}
```

**Comment by noplanman** [comment]
Right, seems that your bot isn't working properly. The `500 Internal Server Error` means that something isn't configured properly on your server.

Is this a blank new bot? What version?

**Comment by chuv1** [comment]
Check [this wiki page](https://github.com/php-telegram-bot/core/wiki/How-to-deal-with-500-errors-(webHook-installation)) - use that code to understand what's wrong.

**Comment by GatoPresto** [comment]
ok, thanks. I'll try to do it later today and give you feedback

**Comment by chuv1** [comment]
btw, @noplanman, maybe it's a good idea to add some sort of `debug` param (like `$telegram->debug = true;`) that could do that by default? It's quite handy to get errors right from the bot if something went wrong.
I'm asking because I see that handling 500 errors is quite common question.

**Comment by noplanman** [comment]
@GatoPresto Mind sharing what your solution was?

**Comment by GatoPresto** [comment]
@noplanman sry, I don't have enough time for this task. I rewrote my bot to Node.js
Thank you for your help
