### ISSUE TITLE
problem with connection to database

### ISSUE THREAD

**Issue by GatoPresto** [php-telegram-bot/core#608]
Hi again! :)

Sry for second issue. All day trying to write bot for work >.<
I spent a lot of time today to understand how to work with database from command file.
I try to use ActiveRecord and PDO in execute method, but I had some problem.

If I use ActiveRecord classes or PDO my command doesn't work. I try to use try-catch, but I can't catch the error. It's just break my command.
For example this line will break a command:
```php
$conn = new PDO('mysql:host=localhost;dbname=test', 'user', 'pass');
```
Also I tried to use TelegramLog::error, etc. Log file is empty.

**Comment by chuv1** [comment]
You can use existing connection via `DB::getPdo()`.

**Comment by GatoPresto** [comment]
@chuv1 should I use enableMySql in hook.php?

PS. I use composer autoloader in hook.php
How can I work with ActiveRecord? I trying to understand the problem.

**Comment by GatoPresto** [comment]
@chuv1 still nothing. This code broke all my commands :(
```php
<?php
namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\DB;

class BindCommand extends UserCommand {
	protected $name = 'bind';
	protected $description = 'Привязать аккаунт';
	protected $usage = '/bind <email>';
	protected $version = '1.0.0';

	public function execute() {
		$message = $this->getMessage();
        $chatId = $message->getChat()->getId();
        $email = trim($message->getText(true));

        // validate email
        if ( !filter_var($email, FILTER_VALIDATE_EMAIL) ) {
        	$text = 'Введите корректный email';
        } else {
        	// find existing user
			$conn = DB::getPdo();
			$users = $conn->query("SELECT id FROM main_users WHERE email = '{$email}'");

    		if ( count($users)) ) {
    			$text = "Пользователь с email: {$email} не найден";
    		} elseif ( !empty($user->telegram_id) ) {
    			$text = 'К данному аккаунту уже привязан телеграмм';
    		} else {
    			// update telegram_id for this user
    			$conn->query("UPDATE main_users SET telegram_id = '{$message->from->id}' WHERE id = {$users[0]['id']}");
    			$text = 'Телеграмм успешно привязан';
			}
        }

        $data = [
            'chat_id' => $chatId,
            'text'    => $text,
        ];

        return Request::sendMessage($data);
	}
}

```

**Comment by chuv1** [comment]
It seems that it happens because you have no `$user` variable defined, but you trying to access it's property `telegram_id`. Please, use [suggested code](https://github.com/php-telegram-bot/core/wiki/How-to-deal-with-500-errors-(webHook-installation)) to catch the error. 

PS. Also you can try to surround code block inside execute method with `try...catch`.
