### ISSUE TITLE
Inline keyboard in conversation

### ISSUE THREAD

**Issue by arkhub** [php-telegram-bot/core#611]
### Required Information
- Operating system:
- PHP version: 7.1
- PHP Telegram Bot version: 0.48
- Using MySQL database: yes
- MySQL version:
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour
Inline keyboard to return text selected from buttons as text originated from sender (like in default keyboard button)

### Actual behaviour
inline keyboard always return pop-up message like in examples repository

### Steps to reproduce
Source code in ExampleCommand : 
``` 
   public function execute()
    {
	$inline_keyboard = new InlineKeyboard([]);
	$keyboard_buttons = [];
	$n = 0;

        if ($result = DB::getPdo()->query('SELECT * FROM my_tables')) {
            $result = $result->fetchAll();
            foreach($result as $row) {
		$n++;
		$keyboard_buttons[] = new InlineKeyboardButton([
			'text'          => ucwords(strtolower($row['field_name'])),
			'callback_data' => $row['field_id'],
		]);
		if ($n % 3 == 0 || count($result) == $n) {
			call_user_func_array([$inline_keyboard, 'addRow'], $keyboard_buttons);
			$keyboard_buttons = [];
		}
	    }
	}

	$chat_id = $this->getMessage()->getChat()->getId();
	$data = [
            'chat_id'      => $chat_id,
            'text'         => 'Keyboard button list from database  : ',
            'reply_markup' => $inline_keyboard,
        ];
        
	return Request::sendMessage($data);	
    }
```

### Extra details
most of the generic script are copied from example repository, is this limitation for inline keyboard?

**Comment by noplanman** [comment]
@arkhub Using InlineKeyboard need 2 command files
1. Your command that creates the keyboard
2. `CallbackqueryCommand` that handles the callback.

If you just get the example commands, you'll see what happens in the [CallbackqueryCommand.php file](https://github.com/php-telegram-bot/example-bot/blob/4c64c25b9a61d1102866604952b7e78ebaf7d8da/Commands/CallbackqueryCommand.php#L52).
It's just an example!

You can override it and implement your own functionality :+1:

Or, you can register callbacks that makes this easier, check #540 for simple example.

**Comment by arkhub** [comment]
Sorry forgot to add my CallbackqueryCommand.php
```
    public function execute()
    {
        //$callback_query    = $this->getUpdate()->getCallbackQuery();
		$callback_query    = $this->getCallbackQuery();
        $callback_query_id = $callback_query->getId();
        $callback_data     = $callback_query->getData();

        $data = [
            'callback_query_id' => $callback_query_id,
            'text'              => $callback_data,
            //'show_alert'        => true,
            //'cache_time'        => 5,
        ];

        return Request::answerCallbackQuery($data);
    }
```
it showns the reply as pop-up message instead of user reply like keyboard does.

p.s : I'll check #540 first.

**Comment by arkhub** [comment]
Just noticed that in botfather when navigating through inline keyboard there's no emulated user reply, is there a way like in examples SurveyCommand.php to navigate from each state and carry previous value using inline keyboard?

**Comment by noplanman** [comment]
You can make use of the conversation inside your callbacks :+1:

All you need is the user and chat id, which link to a specific conversation. You can then get that conversation and do what you like with it, change stage, set/get new data, etc.

What exactly are you trying to do here?
I can help more to find a solution, if I know your end goal.

**Comment by arkhub** [comment]
Sorry my first purpose is a bit unclear
I want to create conversation like SurveyCommand.php in examples, but instead of Keyboard I want to use Inline Keyboard, now the problem is I don't know how to pass variable after button pressed in inline keyboard because in examples it shows as popup notification instead emulating text send by requester / user.

I have created the SurveyCommand and replace the keyboard with inline keyboard but I seems cannot get pass the first question (first question is using inline keyboard, so is the second one). I already set my CallbackqueryCommand.php like above, also GenericmessageCommand.php like in examples, it works fine when using standard keyboard but not inline keyboard (when passing the data to second question and change the state).

**Comment by arkhub** [comment]
> All you need is the user and chat id, which link to a specific conversation. You can then get that conversation and do what you like with it, change stage, set/get new data, etc.

if I put conversation in `CallbackqueryCommand.php` , do I have to put all inline keyboard question in callback too or in my command?

The result I'm trying to achieve is like : /survey -> show first question in inline keyboard -> get it's value -> show second question with inline keyboard -> get it's value -> etc...

After days trying, I'm bit understand how callback query works but still I'm stuck, some scenario that I've tried : 
1. my `SurveyCommand.php` generate first inline keyboard which redirect to `CallbackqueryCommand.php`, from there I could send `editMessageText` command with another inline keyboard static command to `SurveyCommand.php`. The problem is each inline keyboard question is dynamic (requires variable) so using static function is out of question. (I copy the example in #436 which similar to what I want but with conversation).

My CallbackqueryCommand.php :
```
    public function execute()
    {
		
        $update         = $this->getUpdate();
        $callback_query = $update->getCallbackQuery();
        $callback_data  = $callback_query->getData();

        // Only do something for the 'category' selection.
        if (strpos($callback_data, 'category_') !== 0) {
            return Request::emptyResponse();
        }

        // Get the real category from the callback_data.
        $category = substr($callback_data, strlen('category_'));
		
        return Request::editMessageText([
            'chat_id'    => $callback_query->getMessage()->getChat()->getId(),
            'message_id' => $callback_query->getMessage()->getMessageId(),
			'text'		 => "choose the second option : " . $category,
            'reply_markup' => TestCommand::testone(),
			
        ]);
		
    }
```
SurveyCommand.php :
```
    public static $categories = [
        'apple'  => 'Yay, an apple!',
        'orange' => 'Sweetness...',
        'cherry' => 'A cherry on top.',
    ];
	
    public function execute()
    {
        $keyboard_buttons = [];
        foreach (self::$categories as $key => $value) {
            $keyboard_buttons[] = new InlineKeyboardButton([
                'text'          => ucfirst($key),
                'callback_data' => 'category_' . $key,
            ]);
        }
        $data = [
            'chat_id'      => $this->getMessage()->getChat()->getId(),
            'text'         => 'Choose a category:',
            'reply_markup' => new InlineKeyboard($keyboard_buttons),
        ];

        return Request::sendMessage($data);
    }
	
    public static $valone = [
        'one'  => 'The first',
        'two' => 'Second one',
        'three' => 'And the third',
    ];
	
	public function testone()
	{
		$keyboard_buttons = [];
		foreach (self::$valone as $key => $value) {
			$keyboard_buttons[] = new InlineKeyboardButton([
				'text'          => ucfirst($key),
				'callback_data' => 'category_' . $key,
			]);
		}
		return new InlineKeyboard($keyboard_buttons);
	}
}
```

2. Adding
```
$conversation = new Conversation(
    $this->getCallbackquery()->getMessage()->getFrom()->getId(),
    $this->getCallbackquery()->getMessage()->getChat()->getId(),
 );
```
in `CallbackqueryCommand.php` and trying to get it's value shows null, after debugging the value between chatId and FromId in database both came from the user, but in callbackquery the fromId is from the bot. But the real problem is setting the state, and returning to the `SurveyCommand.php` and call the second question.

**Comment by noplanman** [comment]
> The result I'm trying to achieve is like : /survey -> show first question in inline keyboard -> get it's value -> show second question with inline keyboard -> get it's value -> etc...

Right, this kind of implies that your questions can all be answered with the buttons provided, yes? There would be the option of reading messages sent and then deleting them again, but that could get a bit messy.

> The problem is each inline keyboard question is dynamic (requires variable) so using static function is out of question.

Please elaborate on this. What variables are we talking about here?

> after debugging the value between chatId and FromId in database both came from the user, but in callbackquery the fromId is from the bot.

Yes, for this reason, just get the conversation using the user's id for both `user_id` and `chat_id` 👍 
This will only work when in a private chat though:
```php
$chat_id      = $this->getCallbackquery()->getMessage()->getChat()->getId();
$conversation = new Conversation($chat_id, $chat_id);
```

**Comment by arkhub** [comment]
`Please elaborate on this. What variables are we talking about here?`
the keyboard button array is generated from database according to previous responses like when someone choose button "animal" in first question of [animal, plants], it will be given option [mammals, reptile] in the second question.

**Comment by noplanman** [comment]
Ok. Just save the necessary details to your conversation notes 👍 
Is that not enough to save the variable details required to query the next question/answers?

```php
$conversation->notes = [...];
```

**Comment by akalongman** [comment]
Looks like its resolved in direct messages. Feel free to open if you want to continue discussion

**Comment by platonovpavel** [comment]
Hello dear developers, can anyone suggest, we are making a conversation with the InlineKeyboard, and when the button is pressed, a message is sent to the conversation, as the Bot will send it (I will give the code below). And the conversation doesn't move on to the next question.

My CallbackqueryCommand.php :

    public function execute(): ServerResponse
    {
        // Callback query data can be fetched and handled accordingly.
        $callback_query    = $this->getCallbackQuery();
        $callback_query_id = $callback_query->getId();
        $callback_data     = $callback_query->getData();
    
        Request::sendMessage([
            'chat_id'    => $callback_query->getMessage()->getChat()->getId(),
            'message_id' => $callback_query->getMessage()->getMessageId(),
            'text'       => $callback_data,
        ]);

        $conversation = new Conversation($callback_query->getMessage()->getChat()->getId(), $callback_query->getMessage()->getChat()->getId());
        $conversation->notes['state'] = "3";
        $conversation->notes['whocome'] = $callback_data;
        $conversation->update();
        // $conversation->start();
    }

I would like to ask, please, нow to make a conversation right, using InlineKeyboard?

**Comment by Hitmare** [comment]
Have a look at this: https://pastebin.com/qxQAekwj
also please open your own issue instead of digging up a almost 3 years old issue :)
