### ISSUE TITLE
How to interact with bot's database?

### ISSUE THREAD

**Issue by shareholder** [php-telegram-bot/core#612]
Hello. Can you please tell where can I find all the ways of interacting with database that a bot connected to? How can I find the commands which I can use to retreive or modify database entries? For example, I need to get all user's "locations" and send it back. How can I 
``SELECT location FROM message WHERE user_id = $this->getMessage()->getChat()->getId() ORDER BY date DESC LIMIT 0, 5`` ?

Where can I find the list of methods that I can use inside a SomeCommand.php file to read and write custom queries? Or I have to write it by myself like a regular PDO queries right inside a SomeCommand.php file?

**Comment by jacklul** [comment]
`DB::getPdo();` will return already connected PDO object.

**Comment by shareholder** [comment]
Thanx. And where can I find all the methods that already exist? Like ``getId()``, ``getMessage()``. To determine if I have to make a custom PDO query.

**Comment by jacklul** [comment]
Take a look at class docblocks in `Entities`.

**Comment by noplanman** [comment]
@shareholder Even though this is a late reply...

Best would be to use an IDE that inspects the objects and shows you the available methods for each object. You can also just look in the files themselves and see the docblock comments above the classes, for example [the `Message` entity](https://github.com/php-telegram-bot/core/blob/f7cac58dcf4efd766f4737f40bba473ced0d4cc8/src/Entities/Message.php#L21)

Apart from that, can we close here?

**Comment by akalongman** [comment]
Closed due to inactivity
