### ISSUE TITLE
Invalid parameter number' in DB.php:1099

### ISSUE THREAD

**Issue by kruteev** [php-telegram-bot/core#615]
### Required Information

- Operating system: Debian 8
- PHP version: 5.6.30
- PHP Telegram Bot version: 0.48.0
- Using MySQL database: yes
- MySQL version: 5.6.35
- Update Method: Webhook
- Self-signed certificate: yes
- RAW update (if available):

### Expected behaviour

exception 'Longman\TelegramBot\Exception\TelegramException' with message 'SQLSTATE[HY093]: Invalid parameter number' in .../vendor/longman/telegram-bot/src/DB.php:1099

### Steps to reproduce

launch /whois command without param "/whois"

### Extra details

How to fix?

**Comment by noplanman** [comment]
Ah, I see, it's due to the [multiple `:text` tokens](https://github.com/php-telegram-bot/core/blob/0.48.0/src/DB.php#L1077).

Will get this fixed soon :+1:
