### ISSUE TITLE
User unlock key

### ISSUE THREAD

**Issue by DickerPeter** [php-telegram-bot/core#617]
### Required Information

- Operating system: debian
- PHP version: 7.1.8 (64bit); fpm-fcgi; Linux
- PHP Telegram Bot version: 0.48
- Using MySQL database: yes 
- MySQL version: 10.0.32-MariaDB-0+deb8u1
- Update Method: Webhook 
- Self-signed certificate: no
- RAW update (if available):

Would like to create my users for the Bot a kind of release key.
and only through this is the bot unlocked in all its functions.

Has anyone built something like this before and could help me here?

**Comment by Hitmare** [comment]
It isn't the first time i've read that kind of request. 
I think it would be awesome if it could be implemented into the Bot. 
I have actually already a Idea how to implement this and basicly how to Code it.

**Comment by sharkydog** [comment]
#613 might help, it examples an authentication with google authenticator.
It uses [PHPGangsta/GoogleAuthenticator](https://github.com/PHPGangsta/GoogleAuthenticator) wrapped in a static call (ShdGoogleAuth::verify()) for simplicity.

**Comment by DickerPeter** [comment]
@sharkydog I need only a one-time release for each user / room. So I think the GoogleAuthenticator would be a bit exaggerated.

@Hitmare that sounds interesting, yes the whole completely as a function would be nice.
But then I need a different solution.

**Comment by Hitmare** [comment]
@DickerPeter i'm working on it right now. I think that i will finish the code this week, but no promis here 
https://github.com/Hitmare/unlockPTB

**Comment by DickerPeter** [comment]
Thanks @Hitmare for this nice work
