### ISSUE TITLE
[Feature Request] PHPMailer Class implemention

### ISSUE THREAD

**Issue by Hitmare** [php-telegram-bot/core#619]
Hello

At start: If this is the Wrong section, I'm sorry. Please tell me where to put Features Request instead for the future

I had the Idea to implement the PHPMailer Class into the Telegram Bot. 
I've done this allready for my Bot witout editing the Bots source code so I can Update the Bot without to implement the PHPMailer Class everytime

If the Implementation isn't possibly for certain things (License etc) how about an How-To for the Implementation of the PHPMailer Class ? 

Github link of the PHPMailer Class https://github.com/PHPMailer/PHPMailer

The PHPMailer Class is a Class that allows yout to send and recieve E-Mails through PHP. Its also allows ,otherwise as the standard mail() function from PHP as far i know, to send and recieve over an external E-Mail server.

BR
Hitmare

**Comment by jacklul** [comment]
A helper class with static functions would do the trick I guess...?

**Comment by noplanman** [comment]
Hi @Hitmare 

To use PHPMailer (or any external component), it's easiest to add it to your project using composer.

For PHPMailer, look here: https://github.com/PHPMailer/PHPMailer#installation--loading

Then you can easily use it in your library. I don't understand why we should add it to the core library, as it's as easy as `composer require phpmailer/phpmailer` in your project.

So instead of adding bulk to the core library, you can just add what you need in your own project. Maybe someone prefers SwiftMailer, or some other lib 😉

**Comment by Hitmare** [comment]
Ohhh okey ^^.
Have not that much experience with composer so i don't knwo how much it can do ^^

**Comment by noplanman** [comment]
Just to give you a quick example, here is a demo `/mail` command. For the values being set in the `sendMail` method, best to load them from your environment or config file. Apart from that, it's a static method you could put anywhere 👍 

(You'll obviously need to do `composer require phpmailer/phpmailer` before, to have the library in your project)

```php
<?php

namespace Longman\TelegramBot\Commands\AdminCommands;

use Longman\TelegramBot\Commands\AdminCommand;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\TelegramLog;
use PHPMailer\PHPMailer\PHPMailer;

/**
 * Admin "/mail" command
 */
class MailCommand extends AdminCommand
{
    /**
     * @var string
     */
    protected $name = 'mail';

    /**
     * @var string
     */
    protected $description = 'Send mail';

    /**
     * @var string
     */
    protected $usage = '/mail <to>;<subject>;<text>';

    /**
     * @var string
     */
    protected $version = '1.0.0';

    /**
     * @var bool
     */
    protected $private_only = true;

    /**
     * Command execute method
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute()
    {
        $message = $this->getMessage();
        $chat_id = $message->getChat()->getId();
        $text    = trim($message->getText(true));
        $parts   = explode(';', $text);

        // Make sure we have the vital bits of information.
        if (count($parts) < 3) {
            $text = 'Command usage: ' . $this->getUsage();
            return Request::sendMessage(compact('chat_id', 'text'));
        }
        
        $to      = array_shift($parts);
        $subject = array_shift($parts);
        $body    = implode(';', $parts);

        // Let the user know something is happening while we're sending the mail.
        Request::sendChatAction(['chat_id' => $chat_id, 'action' => 'typing']);

        $text = 'Failed to send message, check error log.';

        if (self::sendMail($to, $subject, $body)) {
            $text = 'Successfully sent message!';
        }

        return Request::sendMessage(compact('chat_id', 'text'));
    }

    /**
     * Send an email!
     *
     * @param string $to
     * @param string $subject
     * @param string $body
     *
     * @return bool
     */
    public static function sendMail($to, $subject, $body)
    {
        $mail = new PHPMailer(true);
        try {
            // Server settings
            $mail->isSMTP();
            $mail->Host       = 'smtp.example.com';
            $mail->SMTPAuth   = true;
            $mail->Username   = 'username';
            $mail->Password   = 'password';
            $mail->SMTPSecure = 'tls';
            $mail->Port       = 587;

            // Recipient
            $mail->setFrom('me@example.com');
            $mail->addAddress($to);

            // Content
            $mail->Subject = $subject;
            $mail->Body    = $body;

            return $mail->send();
        } catch (\Exception $e) {
            TelegramLog::error($e->getMessage());
            return false;
        }
    }
}
```
