### ISSUE TITLE
kick bot and user who added it

### ISSUE THREAD

**Issue by sadeghesfahani** [php-telegram-bot/core#620]
hello, i want to check group added users, anybody added a bot kick bot and the member who added it. there is no command to do this, please help me if you can.

**Comment by jacklul** [comment]
Newchatmembers command.

You make a check if added user is not account and then kick it.

**Comment by sadeghesfahani** [comment]
what about who added it?

**Comment by jacklul** [comment]
The person who added will be carried with the update object ... It will be in from field.

**Comment by sadeghesfahani** [comment]
it is not a long programm could you please give me an example of all these wanted? please

**Comment by sadeghesfahani** [comment]
<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;

/**
 * New chat member command
 */
class NewchatmembersCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = 'newchatmembers';

    /**
     * @var string
     */
    protected $description = 'New Chat Members';

    /**
     * @var string
     */
    protected $version = '1.2.0';

    /**
     * Command execute method
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        $message = $this->getMessage();

        $chat_id = $message->getChat()->getId();
        $members = $message->getNewChatMembers();
        $text = 'سلام، من از گروهتون محافظت می کنم!';

        if (!$message->botAddedInChat()) {
            $member_names = [];
            foreach ($members as $member) {
                $member_names[] = $member->tryMention();
            }
            $text = 'به گروه ما خوش آمدید ' . implode(', ', $member_names) . '!';
        }else{

            foreach ($members as $member){
                if($member->getIsBot()){
                    $user_id=$member->getId();
                    $data = [
                        'chat_id' => $chat_id,
                        'text'    => $user_id,
                    ];

                    Request::sendMessage($data);
                    $data = [
                        'chat_id' => $chat_id,
                        'user_id' => $user_id,
                    ];
                    Request::execute('kickChatMember',$data);
                }
            }
        }

        $data = [
            'chat_id' => $chat_id,
            'text'    => $text,
        ];

        return Request::sendMessage($data);
    }
}




why is not working?

**Comment by sadeghesfahani** [comment]
i wrote it. if anybody want these codes are here:
<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;

/**
 * New chat member command
 */
class NewchatmembersCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = 'newchatmembers';

    /**
     * @var string
     */
    protected $description = 'New Chat Members';

    /**
     * @var string
     */
    protected $version = '1.2.0';

    /**
     * Command execute method
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        $message = $this->getMessage();

        $chat_id = $message->getChat()->getId();
        $members = $message->getNewChatMembers();
        $text = 'سلام، من از گروهتون محافظت می کنم!';

        if (!$message->botAddedInChat()) {
            $member_names = [];
            foreach ($members as $member) {
                $member_names[] = $member->tryMention();
                if ($member->getIsBot()){
                    $user_id=$member->getId();
                    $data = [
                        'chat_id' => $chat_id,
                        'user_id' => $user_id,
                    ];
                    Request::execute('kickChatMember',$data);
                    $whoadded=$this->update->getMessage()->getFrom()->getId();
                    $data = [
                        'chat_id' => $chat_id,
                        'user_id' => $whoadded,
                    ];
                    return Request::execute('kickChatMember',$data);
                }
            }
            $text = 'به گروه ما خوش آمدید ' . implode(', ', $member_names) . '!';
        }

        $data = [
            'chat_id' => $chat_id,
            'text'    => $text,
        ];

        return Request::sendMessage($data);
    }
}

**Comment by sadeghesfahani** [comment]
let me try your suggestion, its more orgenazied

**Comment by sadeghesfahani** [comment]
@noplanman thank you so much it works as a clock

**Comment by noplanman** [comment]
@sadeghesfahani You're welcome, i'm glad it works for you.

(I have also updated your comment above and cleaned up the PHP, to make it readable)
