### ISSUE TITLE
Bot not replying - fresh install

### ISSUE THREAD

**Issue by Maxiride** [php-telegram-bot/core#621]
### Required Information

- Operating system:  Ubuntu 16.04.3 LTS
- PHP version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- PHP Telegram Bot version: Latest, did git clone half an hour ago
- Using MySQL database: No
- MySQL version: -
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour
Bot replying "A command for test"

### Actual behaviour
Nothing happens

### Steps to reproduce

1. `composer require longman/telegram-bot
`
1. created hook.php and set.php, set bot token, username and webhook url, `set.php` ran fine.
1. followed the steps for [creating a custom command](https://github.com/php-telegram-bot/core/wiki/Create-your-own-commands). I literally copy pasted the final code.

### Extra details
hook.php, $bot_api_key and $bot_username are in the included file myVars.php so that I can keep them separated from the code when copying it around and versioning it on github.
```php
<?php
// Load composer
require __DIR__ . '/vendor/autoload.php';

// Load secret variables
include 'myVars.php';

$commands_paths = [
    __DIR__ . '/Commands',
];

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($bot_api_key, $bot_username);

    // Handle telegram webhook request
    $telegram->handle();
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // Silence is golden!
    // log telegram errors
    // echo $e->getMessage();
}
```

```
tree -L 2
.
├── Commands
│   ├── SplashCommand.php
│   └── TestCommand.php
├── composer.json
├── composer.lock
├── hook.php
├── myVars.php
├── README.md
├── set.php
└── vendor
    ├── autoload.php
    ├── composer
    ├── guzzlehttp
    ├── longman
    ├── monolog
    └── psr
```

I'm still messing aroud with the code and the server to figure out something, I will update the ticket asap if I find something.

**Comment by Maxiride** [comment]
Found the issue, in the `hook.php` one needs to add `$telegram->addCommandsPaths($commands_paths);` inside the `try{}`

Found out while skimming through the example bot. [The guide](https://github.com/php-telegram-bot/core/wiki/Create-your-own-commands) on custom commands needs to be updated with this missing step ;)

**Comment by noplanman** [comment]
@Maxiride Nice catch, thanks for updating the wiki 👍
