### ISSUE TITLE
detect Deleted account and kick them as soon as possible (fake accounts will change their name to deleted account for safety)

### ISSUE THREAD

**Issue by sadeghesfahani** [php-telegram-bot/core#624]
### Required Information

- Operating system: windows 10 and linux in host
- PHP version: 5.5
- PHP Telegram Bot version:
- Using MySQL database: yes / no
- MySQL version:
- Update Method: Webhook 
- Self-signed certificate:  no
- RAW update (if available):

hello, thanks for involving this, i need to detect deleted accounts because they add bots, and with new bots they challenge our management of group. i am using webhook,  GenericmessageCommand and NewchatmembersCommand is fully customized for defending our group from spammers, porn content and "bot added". these groups will change their account name to Deleted Account like telegram leavers. i need to detect who change his/her name to this. i need a method to allow me check is the update, changed name? and if is it, what is new name? thanks for your time.

**Comment by noplanman** [comment]
If you kick or ban a user, it blocks the user's ID, not the username. So even if a user changes their name, they are still blocked.

You can always check the name of a user by doing `$this->getMessage()->getFrom()->getUsername()`. Or you can also `getFirstName()` and `getLastName()`.

If I haven't understood correctly, please explain more.

**Comment by sadeghesfahani** [comment]
can i have access to every group members in every update?
i want to check member names when for example my friend told hello in group.
how can access to these name? can you put these names in $groupmembernames[] ? thanks for you fully support.

**Comment by jacklul** [comment]
I don't think you can get member list with bot API yet...

**Comment by noplanman** [comment]
Nope, not possible.
