### ISSUE TITLE
delete this message on group: <botname> removed <user>

### ISSUE THREAD

**Issue by sadeghesfahani** [php-telegram-bot/core#625]
### Required Information

- Operating system:
- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes
- MySQL version:
- Update Method: Webhook 
- Self-signed certificate:  no
- RAW update (if available):

### Extra details

hello, my bot will kick users when they use porn content, i need to delete telegram report too, commonly their username has bad words. after my bot remove them telegram will show this message: <botname> removed <user>, how can i delete this post?

**Comment by noplanman** [comment]
I'm not sure you can delete that, as it's a status message that the bot does not get any information about. I've tried to delete the message from the `LeftchatmemberCommand`, but it does nothing 😕 The only message that the bot gets, is that someone left/joined the group, you can't do anything with the message though.

@jacklul Do you know if it's possible?

**Comment by jacklul** [comment]
If the bot is an admin it should be possible based on the message id (it is considered a message after all).

**Comment by noplanman** [comment]
@jacklul You're absolutely right!

Weird, I tried it and it didn't work at first. Now I tried it again and it did 😕
