### ISSUE TITLE
TelegramLog calls in the hook breaks the bot normal behavior 

### ISSUE THREAD

**Issue by Maxiride** [php-telegram-bot/core#626]
### Required Information

- Operating system:  Ubuntu 16.04.3 LTS
- PHP version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- PHP Telegram Bot version: Latest, did git clone yesterday
- Using MySQL database: No
- MySQL version: -
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour
Bot replying to the /test command as in the commands example, this doesn't happen and I would expect some logs but none are generated.

### Actual behaviour
No answer, no logs.

### Steps to reproduce
Plain fresh install that works fine without the log calls int he hook try{}. Indeed if I comment these lines everything works.

```php
  // Logging (Error, Debug and Raw Updates)
    Longman\TelegramBot\TelegramLog::initErrorLog(__DIR__ . "/{$bot_username}_error.log");
    Longman\TelegramBot\TelegramLog::initDebugLog(__DIR__ . "/{$bot_username}_debug.log");
    Longman\TelegramBot\TelegramLog::initUpdateLog(__DIR__ . "/{$bot_username}_update.log");
```

### Extra details
Nothing to add except that I have to admit that I have no idea of what I'm doing with this monolog calls so I'm picking the example code and the wiky as _black boxes_ :disappointed_relieved: 
Once I manage to get some logs around I'm confident to begin debugging myself my code.

[Here](https://hastebin.com/acoriniboh.xml) is my `hook.php`

**Comment by Maxiride** [comment]
The issue can be broke down in two separate issues thanks to further investigation:
* The nginx user didn't had the permission to write file which has been solved by running
`# chown -R www-data:www-data path-to-bot-root-folder`
* After this the framework managed to create the _debug, _error and _update log as expected!

However the bot is still not replying to the /test command.

**Comment by Maxiride** [comment]
I've cloned the example-bot, uncommented the TelegramLog:: lines and set my bot infos, the example-bot works fine.
So even if my hook.php is _identical_ to the hook of the example-bot mine doesn't work. Weird.

I'll close the issue even if it's actually *unsolved* and further troubleshooting would have been needed, but as said the beginning the example-bot works so who knows what's the issue but for sure it's on my side and not the framework. So we are good =) :smiley:

**Comment by noplanman** [comment]
Probably an issue with file encoding, but glad that you've manage to solve it with a workaround.
