### ISSUE TITLE
BOT problem with Self-signed certificate

### ISSUE THREAD

**Issue by gmalexmush** [php-telegram-bot/core#632]
### Required Information

- Operating system: Debian 8.8
- PHP version: 5.6.30-0+deb8u1
- PHP Telegram Bot version:0.31.0
- Using MySQL database: yes
- MySQL version: 5.5.55 
- Update Method: Webhook
- Self-signed certificate: yes
- RAW update (if available):

### Expected behaviour

if you use the standard SSL port (443) and good certificate, then everything works.
If you use self-signed certificate, the Telegram does not respond.
### Actual behaviour

BOT refuses to work with self-signed certificate
### Steps to reproduce

Use self-signed certificate.
### Extra details

telegram_alexm_bot.log  - is empty.

**Comment by noplanman** [comment]
What is the output of `getWebhookInfo` if you call it directly via curl?
`$ curl https://api.telegram.org/bot<api_key>/getWebhookInfo`

Also, when using a self-signed certificate, make sure you are using a certificate that has the full chain in it.

**Comment by sharkydog** [comment]
Just use a free certificate from [Let’s Encrypt](https://letsencrypt.org/) / [Certbot](https://certbot.eff.org/).
For Jessie it's in backports, links above hold all the information you will ever need.
Basically, this thing puts some files in <webroot>/.well-known directory for your domain, remote service verifies this way that you are holding the domain and issues a short lived certificate, updated before expiring by checking that you are still holding the domain.
You can get one certificate for several (sub)domains, you can get several certificates, etc.
So you have to do nothing after setting it up and it is accepted everywhere.

**Comment by noplanman** [comment]
Also, building on top of @sharkydog's comment, I'd recommend [acme.sh](https://acme.sh) as the Let's Encrypt registration client.

**Comment by gmalexmush** [comment]
Hi noplanman!  With port 8443 isn't a problems. right!
sharkydog - thankyou! bot works after installation and configuration - certbot!
The problem was in the certificate.
