### ISSUE TITLE
Work bot , without command , without slash '/' 

### ISSUE THREAD

**Issue by dmbrega** [php-telegram-bot/core#635]
### Required Information

- Operating system: Debian 7
- PHP version: 7.0
- PHP Telegram Bot version: 
- Using MySQL database: no
- MySQL version:
- Update Method: Webhook 
- Self-signed certificate: yes 
- RAW update (if available):

### Expected behaviour
Hi. How bot might read any messages from chat and give automatical answer? Without command , without slash '/',  simple text
Example:
Q: white color
A: Thanks, you  write white. 

Example standart API Telegram:
```php
$bot->on(function($Update) use ($bot){
	$message = $Update->getMessage();
	$mtext = $message->getText();
	$cid = $message->getChat()->getId();
	
	if(mb_stripos($mtext,"власть советам") !== false){
		$bot->sendMessage($message->getChat()->getId(), "Смерть богатым!");
	}
}, function($message) use ($name){
	return true; // когда тут true - команда проходит
});
```

Thanks!
Source code:
[revcom_bot_php.zip](https://github.com/php-telegram-bot/core/files/1297623/revcom_bot_php.zip)

**Comment by noplanman** [comment]
That can be handled in `GenericmessageCommand`.

There are a few issues regarding this already, check here:
#315 or #185

**Comment by dmbrega** [comment]
Thanks so match!
