### ISSUE TITLE
Check admin / user

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#636]
I think these features will come in handy :)
```php
if (isAdmin($user_id))
{
// Content for Admins
}
```

```php
if (!isAdmin($user_id))
{
// Content for Users
}
```
I have 6 administrators of my bot. And to check the existence of everyone's rights is too cumbersome :D

**Comment by chuv1** [comment]
It's already there.

**public function Telegram::isAdmin($user_id = null) bool** 

Check if the passed user is an admin
If no user id is passed, the current update is checked for a valid message sender.

``$this->getTelegram()->isAdmin();``

**Comment by MyZik** [comment]
@chuv1 oh, thank you!
