### ISSUE TITLE
WhoisCommand and create /commandID

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#637]
Hi!
The command /whois doesn't work correctly. If I write `/whois150142952` - he doesn't respond. And if I write `/whois 150142952` - bot shows me user info.
How can I fix that? I remember earlier this command worked well...
I didn't change anything in code, I think this bug occurred after the update.

And second question.
How can I create custom commands like WhoisCommand?
Ex: `/setclose111222` (**NOT** `/setclose 111222`) - closes order with ID 111222 

Thanks in advance!

**Comment by jacklul** [comment]
If you use own version of `GenericCommand.php` then please look here and copy the code https://github.com/php-telegram-bot/example-bot/blob/master/Commands/GenericCommand.php

Thats also a way to implement own command like this.

**Comment by noplanman** [comment]
For the `/whois` command to work properly, you also need the example [`GenericCommand.php`](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/GenericCommand.php#L54) file.

You'll see there how to handle commands like the one you're trying to make 👍

**Comment by MyZik** [comment]
@jacklul @noplanman Thanks!

**Comment by noplanman** [comment]
@jacklul Seriously, you beat me again by a minute?! 😹
