### ISSUE TITLE
Edit all message

### ISSUE THREAD

**Issue by mohsenshahab** [php-telegram-bot/core#638]
### Required Information

- Operating system: ubuntu
- PHP version: 7.0
- PHP Telegram Bot version: 0.45.0
- Using MySQL database: yes 
- MySQL version: 5
- Update Method: Webhook
- Self-signed certificate:  no
- RAW update (if available):

my Bot sends message to users with 
Request::sendMessage($data);
This method works perfect and sends message to all users.

but when I want edit these message , only is edited one message (for one user).

my code : 

> 
 foreach ($users_id as $user_id) {   
         $data['chat_id'] = $user_id;    
          $data['message_id'] = $postid['message_id'];
          $data['text'] = $txt;
   $result = Request::editMessageText($data);
        }

**Comment by jacklul** [comment]
You have to save `message_id` of each sent message and connect it with the user and store it somewhere in database.

I can assume from your code that you only save one of the `message_id`'s, that won't work since it will be different for each user.

**Comment by mohsenshahab** [comment]
thanks a lot
