### ISSUE TITLE
Get @username from user ID

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#640]
Hi! I have a value userID in the field in the table. How can I get user @login (username) if I know the number?
Is there any easy way?

**Comment by noplanman** [comment]
Here are 2 small methods you could use in your command or custom code somewhere in your project. Better use the first one with direct SQL query, but I put the other one there too, which could be helpful to know about 😉 
Both return the username, or false if no user found.

```php
// Using direct SQL query.
public static function getUsername($user_id)
{
    $stmt = DB::getPdo()->prepare('SELECT `username` FROM ' . TB_USER . ' WHERE `id` = :user_id');
    $stmt->execute([':user_id' => $user_id]);

    return $stmt->fetchColumn();
}
```

```php
// Using DB::selectChats method.
public static function getUsername($user_id)
{
    if ($chats = DB::selectChats(['chat_id' => $user_id])) {
        $chat = reset($chats);
        return isset($chat['username']) ? $chat['username'] : false;
    }

    return false;
}
```

This gets the chat started with the user and then extracts the username from it.

**Comment by MyZik** [comment]
@noplanman oh, easy and beaty 😆 
Thank you again!

**Comment by ttvd94** [comment]
Have the same question, but want to get user info from telegram instead of searching in my DB

**Comment by jacklul** [comment]
Actually you can get the info about the user knowing only his ID without using DB (but assuming user already message the bot) with [getChat](https://core.telegram.org/bots/api#getchat) request which returns [Chat](https://core.telegram.org/bots/api#chat) object containing user first and last name, as well as username (if set).

Finding info about the user knowing only his username is not possible.

**Comment by ttvd94** [comment]
> Finding info about the user knowing only his username is not possible.

Oh, didn't know that!
Thanks @jacklul
