### ISSUE TITLE
ChatAdminCommand

### ISSUE THREAD

**Issue by Ishodnikov** [php-telegram-bot/core#642]
Add a new command type for Chat Administrators. For example, ChatAdminCommand. And show these commands only to administrators.

**Comment by jacklul** [comment]
This can't be done without doing additional `getChatAdministrators` request each time incoming update is processed, you will be better with creating your own command class that extends `Command` and implement this logic in there.

**Comment by Ishodnikov** [comment]
If add information about administrators to the database when adding or starting a bot?

**Comment by jacklul** [comment]
Yeah but what when that user will no longer be an admin? There would have to be constant background process updating the admin list.
