### ISSUE TITLE
Is it possible to send a keyboard without text?

### ISSUE THREAD

**Issue by Daniyal-Javani** [php-telegram-bot/core#643]
### Required Information

- Operating system: Cent os (openshift 2)
- PHP version: 7.0.13
- PHP Telegram Bot version:Bot API 3.0-3.3
- Using MySQL database: yes
- MySQL version: 5
- Update Method: Webhook
- Self-signed certificate: no

### Expected behaviour
Send a keyboard without text.
### Actual behaviour
Do not send anything.
### Steps to reproduce

```
       $chat_id = $message->getChat()->getId();
         $data = [ 'chat_id' => $chat_id];

        $data['reply_markup'] = (new Keyboard(['support', 'edit']))
            ->setResizeKeyboard(true);
        $result = Request::sendMessage($data);
```

### Extra details
Is it related to Telegram API?

**Comment by noplanman** [comment]
What was the problem then?

**Comment by noplanman** [comment]
As far as I know that's not possible. You will always have to send some kind of content together with a keyboard.

(P.S. Please just create a new issue for a new problem, don't edit an existing issue, as it becomes useless, thanks!)
