### ISSUE TITLE
Sending photos from disk [Question]

### ISSUE THREAD

**Issue by 0xEAB** [php-telegram-bot/core#649]
How does one send a photo from disk (e.g. `/var/misc/images/p01.png`) using `Request::sendPhoto()` and `Request::sendToActiveChats()`?
https://core.telegram.org/bots/api#inputfile

Thank you in advance 🙈

**Comment by noplanman** [comment]
Using `sendPhoto`:
```php
Request::sendPhoto([
    'chat_id' => 123,
    'photo'  => Request::encodeFile('/var/misc/images/p01.png'),
]);
```

and to send to all active chats:
```php
Request::sendToActiveChats([
    'sendPhoto',
    ['photo' => Request::encodeFile('/var/misc/images/p01.png')]
]);
```

`Request::sendToActiveChats()` has a third parameter that allows to filter which chats to send to, have a look at the [available options](https://github.com/php-telegram-bot/core/blob/0.49.0/src/DB.php#L980).

**Comment by 0xEAB** [comment]
Thank you 👌🏻

Yeah, I'm aware of that 3rd param, and I'm already using it ☺️
