### ISSUE TITLE
Not method getChatMembersCount

### ISSUE THREAD

**Issue by dmbrega** [php-telegram-bot/core#650]
Hi!
Not method **getChatMembersCount**

**Comment by Hitmare** [comment]
? and whats the Question?

**Comment by dmbrega** [comment]
I'm sorry, I found it. The method was added 4 days ago.

**Comment by noplanman** [comment]
More like 1.5 years ago... 😁 
https://github.com/php-telegram-bot/core/commit/379038e59d61ac12fc7eaa593c86801d5da14b77#diff-a788147295d6b475ecb28d093c1ba121R743

But glad you found it 👍
