### ISSUE TITLE
Send to Admin(s)

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#651]
Is there any method like `sendToActiveChats` but witch only sends message to admin(s)?

**Comment by Hitmare** [comment]
you mean to the Bot Admins ?

**Comment by ttvd94** [comment]
Yes

**Comment by noplanman** [comment]
Just loop the array of admins and send them all a message (which is literally what `sendToActiveChats` does too)

**Comment by ttvd94** [comment]
Oh thanks. 
So how can I get a list of all admins?

**Comment by jacklul** [comment]
```php
foreach ($this->getTelegram()->getAdminList() as $admin_id) {
	Request::sendMessage([
		'chat_id' => $admin_id,
		'text' => 'NOTICE'
	]);
}
```

**Comment by ttvd94** [comment]
Thank you @jacklul, but wouldn't telegram server block my bot if there are many requests to many admins? (as this article says: [https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this))

**Comment by jacklul** [comment]
Add ```sleep(1)``` after each request or enable request limiter in hook script.

**Comment by ttvd94** [comment]
Thanks @jacklul for your help;
