### ISSUE TITLE
detect new user in bot

### ISSUE THREAD

**Issue by amin1softco** [php-telegram-bot/core#653]
### Required Information

- Operating system:
- PHP version:  7.0.22 (64bit); fpm-fcgi; Linux
- PHP Telegram Bot version:0.49.0
- Using MySQL database: yes 
- MySQL version: 5.5.31
- Update Method: Webhook
- Self-signed certificate: no

### Extra details
How to detect if the current user is a new user?
may be if this two date equal ?
````
$text .= 'First time seen: ' . $created_at . PHP_EOL;
$text .= 'Last activity: ' . $updated_at . PHP_EOL;
````

**Comment by noplanman** [comment]
Yes, that should work.

You can simply query the DB like so:
```php
$sth = DB::getPdo()->prepare('
    SELECT *
    FROM ' . TB_USER . '
    WHERE `id` = ?
');
$sth->execute([$user_id]);
$user = $sth->fetch(\PDO::FETCH_ASSOC);

if ($user['created_at'] === $user['updated_at']) {
    // New user!
} else {
    // User is known to bot!
}
```

**Comment by noplanman** [comment]
Oh, just saw you closed, what was your solution in the end?

**Comment by amin1softco** [comment]
@noplanman  yeah i detect with checking date like you.
