### ISSUE TITLE
Handling request_contact and request_location

### ISSUE THREAD

**Issue by estevan83** [php-telegram-bot/core#656]
Hi all I'm new of telegram and this very powefull API.

After create keyboard with Share Contact and share location I need to get this informations in bot.

I need to create an handler to manage it ?? Like custom command?
How I can do it?
this is the log string incoming to the bot.
{"update_id":313033835, "message":{"message_id":1347,"from":{"id":XXXXXX,"is_bot":false,"first_name":"Estevan","username":"estevan83","language_code":"it-IT"},"chat":{"id":XXXXXX,"first_name":"Estevan","username":"estevan83","type":"private"},"date":1506275882,"contact":{"phone_number":"yyyyyyyyy","first_name":"Estevan","user_id":XXXXXX}}}

Solution: I need to extends   
public function processUpdate(Update $update) of Telegram class?

Thanks!

**Comment by akalongman** [comment]
Looks like this issue was solved. feel free to open is the issue remains
