### ISSUE TITLE
Invoke command from Keyboard

### ISSUE THREAD

**Issue by estevan83** [php-telegram-bot/core#657]
Hi need to invoke command (for example /help) from a button
This is my code 

```
$keyboards[] = new Keyboard(			
            [
                    'Help' => '/help', 
                    '/help' => 'Help'
            ]
        );
```
On the first case I've caption and command /help
in the second case "Help"
Is there a way to have Caption "Help" that invoke "/help" command?
is a bug of the library or is not possible achieve it?

Here the image of keyborad http://prntscr.com/gp6ilo
Thanks!!

**Comment by chuv1** [comment]
Check #485

**Comment by sharkydog** [comment]
Keyboard can have only button text:
```php
$kb = new Keyboard(
  [ '/help', 'help'],
  [ 'text'=>'/help', 'text'=>'help'] // same thing
);
```
"/help" should be executed directly, "help" will go to GenericmessageCommand, then see #485.

InlineKeyboard can have text and label, but is bit more complicated to use it, see #631.
