### ISSUE TITLE
after - composer update (update to version 0.49.0) bot dont working

### ISSUE THREAD

**Issue by gmalexmush** [php-telegram-bot/core#664]
### Required Information

- Operating system: Debian jessie (Debian 8.8)
- PHP version: 5.6.30-0+deb8u1
- PHP Telegram Bot version: version = '0.49.0'
- Using MySQL database: yes
- MySQL version: 5.5.55
- Update Method: Webhook
- Self-signed certificate: no (letsencrypt via certbot)
- RAW update (if available):

### Expected behaviour

the bot should work ...
### Actual behaviour

The old version (version = '0.31.0') of the bot worked without problems!
After I executed: composer update there is no reaction even to command: /start at all.
New version of the telegram bot is:  '0.49.0'.
There is no reaction at all to any commands!
scripts:
https://sample.dp.ua/telegram/unset.php
https://sample.dp.ua/telegram/set.php
executed without errors!
If execute script:
https://sample.dp.ua/telegram/hook.php
in browser, no errors too.
### Steps to reproduce

If i knew!
### Extra details

There are no logs, because the hook.php is not called.

**Comment by noplanman** [comment]
The problem here is that you're updating from 0.31.0, which is a very old version.
There are a LOT of changes since then.

Please make sure that your DB structure is up-to-date. (check `structure.sql` in the root directory)

**Comment by gmalexmush** [comment]
The encoding has been changed in all tables from: 
DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
to: 
DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

found differences in the structure.
There are a lot of differences in the structure of the tables!
There are such changes that some fields are deleted, and new ones are added. And this is a serious problem.
I could do export, then change the structure and make the import. But deleting fields, and adding new ones, will not allow me to make structure changes through export-import.
What do i do? maybe you have a set of scripts to change the structure of the database?

**Comment by noplanman** [comment]
I was working on this for a while, but never got a 100% solution merged into the core repo.

**Before you try anything, make a backup of your DB!**

You can see my work here, which hopefully is enough for you to get this solved.
https://github.com/noplanman/php-telegram-bot/tree/db_schema_update/utils/db-schema-update/migration

Best if you manually go through each script and execute the commands. Some might fail due to the foreign key constraint indexes, so you'll need to update those manually. For the majority though, they should work fine.

As for the DB schema updates for 0.44.1+, look here: https://github.com/php-telegram-bot/core/tree/master/utils/db-schema-update

**Comment by gmalexmush** [comment]
Thank you. I will try it!

**Comment by gmalexmush** [comment]
Hi noplanman!
Help me  please! 
ALTER TABLE `message`
  ADD CONSTRAINT `message_ibfk_4` FOREIGN KEY (`forward_from_chat`) REFERENCES `chat` (`id`);
it does cause a mysql error:
ERROR 1005 (HY000): Can't create table 'telegram.#sql-8de_3e1e' (errno: 121)
Because `message_ibfk_4`  already exists! What do i do? give it another name? or remove this constrain? how it will be correct?
Sincerely, Alexander.

**Comment by noplanman** [comment]
Easiest is to delete and recreate the constraints.
These guys are the main problem regarding an auto migration script.

**Comment by gmalexmush** [comment]
I finished the migration with your scripts. in my logs there were first records. but the database structure is not yet up to the latest version of the bot. the bot is not working yet.
does not work the creating an object - ReplyKeyboardMarkup
What can be missing in the database structure?

**Comment by noplanman** [comment]
`ReplyKeyboardMarkup` doesn't exist any more!
Use just `Keyboard` instead. Check [this example](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/KeyboardCommand.php) to see how it works.

**Comment by gmalexmush** [comment]
the command start - working! but there is a problem. we have 10 buttons!
The old version showed all the buttons, and the new one can show only one row of buttons.
there is an array with buttons:
$keyb = [
 ['📈  Currency rates','📍  Near you'],
 ['💳  Payments','👝  Services'],
 ['📃  News','⭐ Promotions'],
 ['📞','📱','👍','⚙']
]
but I can show only one row of buttons:
$keyboards	= ( new Keyboard( $keyb[ 0 ]  )  )
				->setResizeKeyboard( $resize_keyb )
				->setOneTimeKeyboard( $one_time_keyb )
                 		->setSelective( $selective );
$data['reply_markup'] = $keyboards;
How can I show the all elements array with buttons? $keyb[ 0 ], $keyb[ 1 ], $keyb[ 2 ] and $keyb[ 3 ] ?

**Comment by gmalexmush** [comment]
excuse me, Keyboard works good.
I did this as follows:
$keybparam = [
			'keyboard'			=> $keyb,
			'resize_keyboard'		=> $resize_keyb,
			'one_time_keyboard'	=> $one_time_keyb,
			'selective'				=> $selective
		 ];

if( class_exists('Longman\TelegramBot\Entities\Keyboard' ) ) {
				$data['reply_markup']	= new Keyboard( $keybparam );
        } elseif( class_exists('Longman\TelegramBot\Entities\ReplyKeyboardMarkup' ) ) {
				$data['reply_markup']	= new ReplyKeyboardMarkup($keybparam );
}

thank you!
