### ISSUE TITLE
Bug in Entities/InlineKeyboardButton.php (!empty())

### ISSUE THREAD

**Issue by demon-ru** [php-telegram-bot/core#670]
try this code: new InlineKeyboard([['text'=>'0', 'callback_data' => '0']])
Is it legal?

It is not working. The reason is in Entities/InlineKeyboardButton.php line 64:
            if (!empty($this->getProperty($param))) {

Will it be better to use isset()?

**Comment by noplanman** [comment]
Is fixed and will be in the next release, thanks @demon-ru 🎉

**Comment by demon-ru** [comment]
I have tested the fix and it solved the problem.
Thanks.
