### ISSUE TITLE
How can i receive message from users?

### ISSUE THREAD

**Issue by abolfazlmohajeri** [php-telegram-bot/core#676]
How can i receive message from users?
e.g:
bot:What is your name?
user:abolfazl

**Comment by noplanman** [comment]
Have a look at the [`/survey`](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php) example command.

Also, please open a new issue for different things, instead of renaming an existing one 👍

**Comment by abolfazlmohajeri** [comment]
oh sorro ok.
could you plese tell me how can i set webhook on laravel?
i wrote this controller to set webhook is it right?

`<?php

namespace App\Http\Controllers;

use Longman\TelegramBot\Request;
use Longman\TelegramBot\Telegram;


class telegramm extends Controller
{
    /*-----------------------------------------------!  telegram  !-----------------------------------------------*/
    public function sethook()
    {
        // Add you bot's API key and name
        $bot_api_key  = '...';
        $bot_username = '...';
        // Define the URL to your hook.php file
        $hook_url     = 'https://mysite.ir/hook';
        // Create Telegram API object
        $telegram = new Telegram($bot_api_key, $bot_username);

        // Set webhook
        $result = $telegram->setWebhook($hook_url);

        if ($result->isOk()) {
            echo $result->getDescription();
        }
    }
    public function hook(){
        // Add you bot's API key and name
        $bot_api_key  = '...';
        $bot_username = '...';
        $telegram = new Telegram($bot_api_key, $bot_username);
        $telegram->handle();
    }
}`

I received Wrong response from the webhook: 500 Internal Server Error

**Comment by wp-src** [comment]
@abolfazlmohajeri  Have u created a command? This library only works with commands. u call a handle and give the library a path to your commands, then copy paste library existing commands into your project.
as an example u can see this example watermark bot which is written in lumen:
https://github.com/wp-src/watermark-bot

**Comment by abolfazlmohajeri** [comment]
@wp-src thanks for responds. but what do you mean by create command?
i set webhook and i want to sendmessage with below simple code:
$data = [
            'chat_id' => 218751234,
            'text' => 'Your utf8 text ðŸ˜œ ...'
        ];
Request::sendMessage($data);
I tested this code without laravel but for now when i use laravel i receive that error.

**Comment by noplanman** [comment]
What error do you get? Are you sure you've initialised the `Telegram` object correctly? Also, make sure you have the correct `use` code for the `Request` class at the top of your file.

**Comment by abolfazlmohajeri** [comment]
The error is : 
FatalErrorException
Call to a member function getBotUsername() on null
yes i used correct use for Request but i dont know why i got that error.

**Comment by noplanman** [comment]
Can you share the piece of code that you're using?

**Comment by abolfazlmohajeri** [comment]
<?php
namespace App\Http\Controllers;

use Longman\TelegramBot\Telegram;
use Longman\TelegramBot\TelegramLog;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;


class telegramm extends Controller
{
    /*-----------------------------------------------!  telegram  !-----------------------------------------------*/
    public function a(){
        $data = [
            'chat_id' => 218751234,
            'text' => 'Your utf8 text ðŸ˜œ ...'
        ];
        Request::sendMessage($data);
    }
}

**Comment by abolfazlmohajeri** [comment]
`
<?php
namespace App\Http\Controllers;
use Longman\TelegramBot\Telegram;
use Longman\TelegramBot\TelegramLog;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;
class telegramm extends Controller
{
    /*-----------------------------------------------!  telegram  !-----------------------------------------------*/
    public function a(){
        $data = [
            'chat_id' => 218751234,
            'text' => 'Your utf8 text ðŸ˜œ ...'
        ];
        Request::sendMessage($data);
    }
}
`

**Comment by wp-src** [comment]
@abolfazlmohajeri  این کتابخونه فقط با یک سری کلاس به اسم کامند کار میکنه.
از این لینک:
https://github.com/php-telegram-bot/example-bot
ربات نمونه رو دانلود کن و با کامپوسر فایل های مورد نیازشو نصب کن بعد اطلاعات رباتت رو توی فایل هاش وارد کن و وب هوک رو ست کن و بعدش کامند 
/survey
 یا کامندهای دیگه رو برای رباتت بفرست اینجوری راحت تر متوجه میشی طرز کارش رو

**Comment by abolfazlmohajeri** [comment]
![untitled](https://user-images.githubusercontent.com/19857443/31579291-382e982e-b0e8-11e7-92b6-9667dd4ea7c6.png)

**Comment by noplanman** [comment]
Where are you declaring the `$telegram` object with your API key?

**Comment by abolfazlmohajeri** [comment]
Oh Im sorry @noplanman  it's my fault and its work thanks

**Comment by abolfazlmohajeri** [comment]
``Qwrqwrqwrqrqwrqwrqw''
