### ISSUE TITLE
Sending message does not work in wampserver

### ISSUE THREAD

**Issue by ZohaBanam** [php-telegram-bot/core#677]
- Operating system: windows7
- PHP version:7.0.10
- PHP Telegram Bot version:0.49.0
- Using MySQL database: yes
- MySQL version:5.7.14
- Update Method:getUpdates . but i want just send message ,  not get message
- Self-signed certificate: i am using on local

i can send my message with file_get_contents but i want to use your by your code
so . 
i created hook.php file and getUpdatesCLI.php files . 
when i execute hook.php output is "input is empty "
and getUpdatesCLI.php : output is "#!/usr/bin/env php " and : "telegram returned an invalid response! please review your bot name and API key."

although i just want to send a message, not to receive messages
now if I run send.php That Its the code : 
```
try{
    $telegram = new Telegram(BOT_TOKEN,BOT_USERNAME);
    Request::sendMessage([
        "chat_id" => $chat_id,
        "text"  => "test"
    ]);
}catch (\Longman\TelegramBot\Exception\TelegramException $e){
    echo $e->getMessage();
}
```
error is : 
Telegram returned an invalid response! Please review your bot name and API key.

my token code is ok , can you help me solve this problem?

**Comment by noplanman** [comment]
Not documented yet, but for Windows you need to disable the Guzzle's connection verification:
There is an exact issue for that already: #381 
And the solution is here: #536

**Comment by ZohaBanam** [comment]
O yeah . I have not seen this. Thanks
