### ISSUE TITLE
How to get message from web hook URL

### ISSUE THREAD

**Issue by offthegrid-mike** [php-telegram-bot/core#678]
Hi all, 

I am new in this php telegram bot. I am planning to get the sender id and the message before handled in it's own commands(e.g. start/ generic/ inlinekeyboard).

Is there any way the can get those information in the webhook URL that I've set for telegram bot to connect with? OR is there any location that I can handle the message before those messages is handled in their own command files?

Thanks!

**Comment by sharkydog** [comment]
Extend Telegram class and override processUpdate()
```php
class MyTelegram extends Longman\TelegramBot\Telegram {
  public function processUpdate(Longman\TelegramBot\Entities\Update $update) {
    if($message = $update->getMessage()) {
      $sender = $message->getFrom();
      $sender_id = $sender->getId();
      $sender_username = $sender->getUsername();
      $chat = $message->getChat();
      $chat_id = $chat->getId();
      $message_text = $message->getText();
      // etc etc ....
    }

    return parent::processUpdate($update);
  }
}

**Comment by offthegrid-mike** [comment]
it works thanks!
