### ISSUE TITLE
Unable to forward a public channel post

### ISSUE THREAD

**Issue by naser** [php-telegram-bot/core#679]
Bots not forward public channels posts with forwardMessage method. It was easy to do this before and it was just needed to call forwardMessage method and pass the channel username, post id and receiver id. But now it gives :
{"ok":false,"error_code":400,"description":"Bad Request: message to forward not found"}

It seems telegram has changed something on their side and does not allow bots to forward posts from channels that they are not in.

Any thought/solution on this?

**Comment by jacklul** [comment]
ask @BotSupport

**Comment by MOHAMMAD026** [comment]
I have this problem!
Does it have a solution?

**Comment by dav1ddramb** [comment]
Have you found the solution by any chance? :) 
Please, respond if you have

**Comment by noplanman** [comment]
This was a Telegram internal problem, nothing to do with the library here, sorry!

Get in touch with https://t.me/BotSupport
