### ISSUE TITLE
How to create a step by step bot?

### ISSUE THREAD

**Issue by offthegrid-mike** [php-telegram-bot/core#680]
Hi all,

I am planning to develop a bot that ask question and based on the answer to provide related solution.
Here is my idea...

1. - At first there will be a inline-keyboard(with `callback_data`) with two options A, B
2. - after user click the `inline-keyboard-button`, bot will return respective question
3. - based on user input, bot will return text to user ("You've selected option A with answer XXX")

so far I am completed 1 and 2. However, since I've only get `Message` from `Update`, how can I know user is selected options A or B in his/her previous selection?

Thanks all to inspire me for that!

**Comment by sharkydog** [comment]
You need to start a conversation, save the selection in the conversation notes and end the conversation when you are all done.
Conversations require a database to be set up. If don't like that, you can come up with some sort of sessions on your own, like json files named with userid, chatid and command.

**Comment by offthegrid-mike** [comment]
In order word, this git repository don't provide any convenient way to do so, right?

**Comment by sharkydog** [comment]
It does - Conversations

**Comment by offthegrid-mike** [comment]
Thanks @sharkydog  for prompt reply!
Is there any real code/ example that I can refer to? Thanks!

**Comment by sharkydog** [comment]
Somewhere among the issues is an example.

Basic usage is like this:
1. Open a Conversation with userid, chatid and command, this will load an existing conversation or start a new one.
$conversation = new \Longman\TelegramBot\Conversation($user_id, $chat_id, $command);
2. Save whatever you want in $conversation->notes, it will be saved in database as json when you call $conversation->update();
3. Open the same conversation with userid and chatid, but not command, this time if conversation does not exists, new one will not be created.
$conversation = new \Longman\TelegramBot\Conversation($user_id, $chat_id);
if($conversation->exists()) // do stuff with $conversation->notes
4. Close the conversation.
$conversation->stop();

**Comment by sharkydog** [comment]
A point to note is when you open a conversation, all plain text messages (not commands, like "/cmd sth") will go to the command that started the conversation, until it is closed.

**Comment by alalapp** [comment]
Where can I see the real example of conversation ?

**Comment by klimf** [comment]
I need example of conversation too

**Comment by noplanman** [comment]
Check out the [`/survey`](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php) command in the example-bot repo 😊
