### ISSUE TITLE
InlineKeyboard Buttons from DB and executeCommand

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#682]
Hi everyone. I have a table `tasks` with fields (`id`, `user_id`, `name`, `description`, `time`) in my database.
I want to create /tasks command. When user uses the command, he will receive a message:

_**Choose your tasks**_
And InlineKeyboard Buttons from table `tasks` where `user_id` = current user id.
And if the user clicks on one of them, bot sends message with info from `tasks` (name, description and time) + InlineKeyboard Buttons "DELETE". If the user clicks on one of them, then uses _executeCommand_ `/deleteCURRENT_ID_FROM_TASKS`. For example: _/delete**212121**_.

If there are no tasks, then bot send a message "No tasks

How can I do this? I would be grateful for a detailed example.
Thanks in advance!

**Comment by noplanman** [comment]
@MyZik Have you managed to do this in the meantime?

**Comment by MyZik** [comment]
yeap, thanks! :)



Отправлено из мобильной Почты Mail.Ru


четверг, 12 апреля 2018 г., 23:39 +0300 от notifications@github.com  <notifications@github.com>:
