### ISSUE TITLE
Reply to inline message

### ISSUE THREAD

**Issue by gusma95** [php-telegram-bot/core#683]
### Required Information

- Operating system: Linux 4f02e907-5938-4afc-822d-4d6d990d9f4a 3.13.0-133-generic #182-Ubuntu SMP Tue Sep 19 15:49:21 UTC 2017 x86_64
- PHP version: 7.1.10 (64bit); fpm-fcgi; Linux
- PHP Telegram Bot version: 0.48.0
- Using MySQL database: yes
- MySQL version: 5.5.56-log
- Update Method: Webhook
- Self-signed certificate: no

### Expected behaviour
Hi,
I'm trying to reply a date to the inline keyboard, now I show an inline keyboard with today and tomorrow buttons, and I would like to add the possibility to reply to the message with a custom date dd/mm/yyyy and handle the request in the callbackquery or in another command.
How can I do it?

**Comment by noplanman** [comment]
You could make use of conversations!
Does it have to be an inline keyboard? For something like this, it would make sense to have a normal keyboard, which also allows a custom input as a normal message.

**Comment by gusma95** [comment]
Thank you for your advice, I will try with conversations :)
