### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by sachin-lalaworld** [php-telegram-bot/core#684]
I created custom command by following steps as mentioned in url
https://github.com/php-telegram-bot/core/wiki/Create-your-own-commands
and executed that but commend not executed, even predefined commands also executed but it also not working. Please help me out.

**Comment by sharkydog** [comment]
maybe posting your code would help us out helping you out

**Comment by grandsilence** [comment]
Not working lib.

**Comment by noplanman** [comment]
I see you're on Windows, which needs a custom Guzzle client with disabled verification.
Look at #381 and #536.

**Comment by grandsilence** [comment]
Thx, but solution for me is disable CSRF token for API in Laravel moving route to another middleware (from 'web' to 'api').

**Comment by noplanman** [comment]
Ok! So the commands are working for you then? Also without the Windows Guzzle fix?

@sachin-lalaworld What about you?

**Comment by sachin-lalaworld** [comment]
My issue has been resolved.

Regards

Sachin Sharma

Software Developer
