### ISSUE TITLE
No response in sendAudio

### ISSUE THREAD

**Issue by anonymousPM** [php-telegram-bot/core#685]
Hi all, 
I am developing a bot which have inlineKeyboard. It is expected to send an audio when user click a inlineKeyboard button. However, I tried sending the audio by `sendAudio` but sadly it doesn't have any response. Moreover, I hardcode to send the audio through URL directly in my webhook url(which I type my webhook URL in browser to trigger the `sendAudio` function), it success.

Could anyone can recommend some solution ? Below is my snippet of code. Thanks all!

```php
class CallbackqueryCommand extends SystemCommand
{
    public function execute()
    {
        // .... do something ....
        
        $mp3_dl_url = "https://drive.google.com/uc?export=download&id=".$mp3_id;

        $data = [
            "chat_id"   => $chat_id,
            "message_id"    => $message_id,
            "text"      => "Downloading",
            "parse_mode"    => "Markdown"
        ];

        Request::editMessageText($data); 

        $data = [
            "chat_id"   => $chat_id,
            "audio"  => $mp3_dl_url,
            "caption"   => $mp3_dl_url
        ];
        Request::sendAudio($data);

        $data = [
            'callback_query_id' => $callback_query_id#,
        ];
        return Request::answerCallbackQuery($data);
    }
}
```

**Comment by noplanman** [comment]
Hi @anonymousPM 

So the message gets successfully edited, but the audio file doesn't get sent?

Is there any output in your logs? (if you have them enabled)

**Comment by anonymousPM** [comment]
Hi @noplanman  

True, the message is able to edit, but can't send the file. I've also try adding `Request::sendMessage` below `Request::sendAudio`, and it can receive that message to.

I haven't enable the log, will try and update the status. Thanks!

**Comment by anonymousPM** [comment]
@noplanman just enable the log and find there is failure in `sendAudio`
```
[2017-10-26 11:32:38] bot_log.DEBUG: Verbose HTTP Request output:
<POST https://api.telegram.org/botxxx/sendAudio> [CONNECT] 
<POST https://api.telegram.org/botxxx/sendAudio> [FAILURE] severity: "2" message: "HTTP/1.1 400 Bad Request
" message_code: "400" 
<POST https://api.telegram.org/botxxx/sendAudio> [MIME_TYPE_IS] message: "application/json" 
<POST https://api.telegram.org/botxxx/sendAudio> [FILE_SIZE_IS] message: "Content-Length: 99" bytes_max: "99" 
<POST https://api.telegram.org/botxxx/sendAudio> [PROGRESS] bytes_max: "99" 
```

**Comment by anonymousPM** [comment]
I finally figure out the cause... It is due to my URL link is exceed 20MB, it there any work around that can able to send as multipart/form-data, which have maximum 50MB of file size

**Comment by sharkydog** [comment]
Set "document" as resource (fopen handle), Request should detect that and setup multipart stuff for you.

**Comment by anonymousPM** [comment]
Thanks @sharkydog reply!
Is it okay to send the document/audio via the resource handle by just using `fopen` ?

**Comment by noplanman** [comment]
To send a local file, you can use [`Request::encodeFile(...)`](https://github.com/php-telegram-bot/core/blob/54823db1306a791830a7915072f03ff84fd7c4f3/src/Request.php#L419), which is the same as `fopen(...)` if you check the code:
```php
'document' => Request::encodeFile($local_path),
```

**Comment by anonymousPM** [comment]
@noplanman for `Request::encodeFile`, is it support to pass URL directly if `allow_url_fopen` is enabled in php global setting?

**Comment by sharkydog** [comment]
It just wraps fopen.
Opens file in read binary mode and throws exception if failed.
https://github.com/php-telegram-bot/core/blob/master/src/Request.php#L419

**Comment by anonymousPM** [comment]
Thanks @sharkydog reply!
I've modified a bit so I can download it to temp file and send to telegram api
```
$tmpfname = tempnam(sys_get_temp_dir(), $tmpfprefix."_");
$tempHandle = fopen($tmpfname, "w+"); // use w+, haven't try to use binary mode. 
fwrite($tempHandle, file_get_contents($url));

$data = [
    "chat_id"   => $chat_id,
    "document"  => $tempHandle
];
$message = Request::sendDocument($data);

fclose($tempHandle);
unlink($tmpfname);
```
