### ISSUE TITLE
I need to create a keyboard on which I can click only once

### ISSUE THREAD

**Issue by gmalexmush** [php-telegram-bot/core#686]
I need to create a keyboard on which I can click only once. After the click, the keyboard should be deleted or become unavailable until the server send a response.
Now I do it like this:
```php
class PhonePrepareCalcCommand extends UserCommand
{
    protected $name = 'phonepreparecalc';
    protected $description = 'Mobile phone replenishment - prepare calc amount request';
    protected $usage = '/phonepreparecalc';
    protected $version = '';

    public function execute()
   {
   $message			= $this->getMessage();
   $chat_id			= $message->getChat()->getId();
   $userid				= $message->getFrom()->getId();
   $data['chat_id']	        = $chat_id;

    .....................

   $data['parse_mode']	= 'Markdown';
   $data['text']			= 'some text ... ';
   $keybparam			= [
 						'keyboard'				=> [ ['Calc'], ['Back'] ],
						'resize_keyboard'		=> true,
						'one_time_keyboard'		=> false,
						'selective'				=> false
						];

    $data['reply_markup']	= new Keyboard( $keybparam );
    return Request::sendMessage( $data );
   }
}
```
In the hook.php:
```php
...
case 'Calc':
        $telegram->executeCommand( 'phonecalcamount' );
        break;
...
```
When the 'Calc' button is pressed, the command is called. The executing duration of this command is 3-5 seconds. And until this command is executed, the 'Calc' button remains available! And some people click this button again. Is it possible to avoid this as something?

Sincerely, Alexander.

**Comment by noplanman** [comment]
Instead of
```php
'one_time_keyboard' => false,
```
try
```php
'one_time_keyboard' => true,
```

**Comment by gmalexmush** [comment]
Oh, it helped! Thank you so much!
But this partially solves this problem. Is there any option that deletes the button after the click?
In the web interface some craftsmen are able to quickly open the keyboard and click again :D

**Comment by noplanman** [comment]
Ok, to completely remove the keyboard, you can use
```php
'reply_markup' => Keyboard::remove(),
```
when sending a message.

For example:
```php
return Request::sendMessage([
    'chat_id'      => $chat_id,
    'text'         => 'Calculation in progress, please wait...',
    'reply_markup' => Keyboard::remove(),
]);
```

That will delete the keyboard. But as I said before, the user could also just resend the text `Calc` to your bot, which would also execute the command again...

You'd have to remember if the command is already being executed, to make sure that it can't be called again before it's complete.

**Comment by gmalexmush** [comment]
should I place this code in hook.php ?
```
...
Request::sendMessage([
    'chat_id'      => $chat_id,
    'text'         => 'Calculation in progress, please wait...',
    'reply_markup' => Keyboard::remove(),
]);
$telegram->executeCommand( 'phonecalcamount' );
break;
...
```
or this part should be in the command  PhonePrepareCalcCommand.php: 
```
...
Request::sendMessage([
    'chat_id'      => $chat_id,
    'text'         => 'Calculation in progress, please wait...',
    'reply_markup' => Keyboard::remove(),
]);
...

```
and this part in hook.php:
```
...
case 'Calc':
        $telegram->executeCommand( 'phonecalcamount' );
        break;
...

```
?
But if so, then in the command 'PhonePrepareCalc' I will no longer have a button to 'Calc' or even a keyboard at all?
The first variant I tried - it does not work.

**Comment by noplanman** [comment]
I see, so it will need some clever procedure to ensure only a single execution 🤔 

As for the location of the message to remove the keyboard, inside the command probably makes more sense than the hook.
Either way, why are you putting this code into the hook instead of `GenericmessageCommand.php`?

**Comment by gmalexmush** [comment]
Hi noplanman!
Do you have an example of using GenericMessageCommand.php?
Unfortunately, I do not know anything about this yet.
I found this file in the sources, but I do not know how it can be used :(
Can I read about it somewhere?
It seems that I did everything wrong :(

**Comment by noplanman** [comment]
@gmalexmush It's not that you did everything wrong, it just makes sense to split your code into places where it makes more sense 😇 

Any message that isn't a command will be handled by `GenericmessageCommand`. So you can make a copy of `GenericmessageCommand.php` (in SystemCommands folder) to your custom commands folder and put your code in the `execute()` method there.
