### ISSUE TITLE
Why preg_match() expects parameter 2 to be string, object given?

### ISSUE THREAD

**Issue by mrKorg** [php-telegram-bot/core#687]
### Required Information
- Operating system:
- PHP version: 7.1
- PHP Telegram Bot version: 0.50.0
- Using MySQL database: no
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

I only install it to laravel project. After that a have error:

> preg_match() expects parameter 2 to be string, object given
> in Telegram.php (line 153)

What is wrong?

**Comment by noplanman** [comment]
Can you share your hook.php? (remember to remove any private info, like API key and bot name)

**Comment by noplanman** [comment]
@mrKorg Did you manage to get this fixed? Can I close here?
