### ISSUE TITLE
How to add text so that the command is executed in addition to / ?

### ISSUE THREAD

**Issue by MaximMikulich** [php-telegram-bot/core#696]
Can I add a variable? which will also be taken into account when calling: Either through /, or a specific text? How so to implement?

protected $text_command = 'Hello';
in HelloCommand.php???

**Comment by noplanman** [comment]
Text messages that start with `/` are commands. They can be handled by creating a custom command class:
For `/hello`, you would have a `HelloCommand` class in `HelloCommand.php`.

For generic messages, you will need to create your own `GenericmessageCommand` class in `GenericmessageCommand.php` and add all functionality there.

As for the variables, you can add whatever variables you like to your custom command classes.
Or have I missed something? What will you need these variables for?

**Comment by MaximMikulich** [comment]
Oh, ok. A do this on `GenericmessageCommand` )) Thx!
