### ISSUE TITLE
How Add Information In insertUser() text t.me/bot?start=THIS_MESSAGE?

### ISSUE THREAD

**Issue by MaximMikulich** [php-telegram-bot/core#699]
I add new Col on DataBase and don't know how add information when user start bot /start=message....

**Comment by noplanman** [comment]
Look here how to get the passed parameter inside your `/start` command:
https://github.com/php-telegram-bot/core/issues/688#issuecomment-341046363

As to saving that data to the database, you can create your own table and then simply use `DB::getPdo()` to get the PDO object to make any MySQL queries you like 👍

**Comment by MaximMikulich** [comment]
@noplanman  If I do this inside `/start` command - I already have a ready database with the user and I have to update the field. And you need to be added together. For the referral system.

How to make that added together? and if there is already such a person with a zero field, then the field does not update?
