### ISSUE TITLE
Cannot get Invite Link.

### ISSUE THREAD

**Issue by juanjofm** [php-telegram-bot/core#701]
- Operating system:
- PHP version: 7.0
- PHP Telegram Bot version: 0.50
- Using MySQL database: no
- MySQL version: 0
- Update Method: Webhook 
- Self-signed certificate: no

My bot is on a group with admin privileges. Group invite link is created.
I use this code of example:
$chatinfo = Request::getChat(['chat_id' => $chat_id]);

I try to get the invite link like this:
$link = $chatinfo->getResult()->getInviteLink();

### Expected behaviour
I should get the invite link.

### Actual behaviour
Return null.

### Extra details
On response json: for example json_encode($chatinfo) or json_encode($chatinfo->getResult()) there is nothing like group invite link or description.

In raw response ok = true.

**Comment by noplanman** [comment]
As stated in the docs, you can only retrieve an invite link from supergroups and channels.

Is the chat you're requesting maybe a normal group?

**Comment by juanjofm** [comment]
No no, its a supergroup.

**Comment by noplanman** [comment]
Ah, right, I see what you mean. As you say, even directly querying the API doesn't return that info.
Hmm, seems to be an issue on Telegrams side, as the bot gets exactly what the API returns 😕 

Maybe it's temporary and it gets fixed soon.

I'll leave this open for now, even though it has nothing to do with the PHP Telegram Bot library, but when it does work again, we can make sure that it works 100% 👍

**Comment by noplanman** [comment]
@juanjofm This is now working for me, what about you?

**Comment by juanjofm** [comment]
@noplanman it is not working for me... how are you using it?

**Comment by noplanman** [comment]
Is your group private or public?

Also, if you need just the invite link, it's better to use `Request::exportChatInviteLink(['chat_id' => $chat_id]);` method 👍

**Comment by juanjofm** [comment]
LOL. That works, thanks! I even didn't noticed that the function exportChatInviteLink existed in Telegram API ....

But what I cannot understand is why the method I used doesn't work...
 $chatinfo = Request::getChat(['chat_id' => $chat_id]);
$link = $chatinfo->getResult()->getInviteLink();

Well, Since it's working this way I close the thread.

Working way:

Request::exportChatInviteLink(['chat_id' => $chat_id]);

**Comment by mohandes66** [comment]
exportChatInviteLink method, revoke the chat invite link and return e new one

I dont want revoke invite link

**Comment by noplanman** [comment]
@mohandes66 You're right!
@juananpe I missed that it revokes any existing links, so maybe that's not what you want.

Might be best to save the invite link the first time you generate one, so that it can be reused.

All that said though, the `$chat->getInvliteLink()` method should do the trick.
Have you tried it again?

**Comment by mohandes66** [comment]
@noplanman  do you mean getChat methode?
