### ISSUE TITLE
PHP function mb_substr doesn't return the true message length

### ISSUE THREAD

**Issue by mehseyrafi** [php-telegram-bot/core#702]
### Required Information

- Operating system: any
- PHP version: 5
- PHP Telegram Bot version: any
- Using MySQL database: any
- MySQL version: any
- Update Method: any
- Self-signed certificate: any
- RAW update (if available):

### Expected behavior
As it can be seen in the record, the length of link and so total length of the text is 18. I expected mb_length() to return 18!

### Actual behaviour
mb_strlen() returns 15. And so mb_substr(0, 18) for extracting the link, doesn't work properly
Also same happened with function strlen() and substr().

### Steps to reproduce
I explain by a simplified example:
A message containing just a link with three consecutive emojicon inside it like below:
www.gg😀😀😀le.com
which in bot it is like this:
"text":"www.gg\ud83d\ude00\ud83d\ude00\ud83d\ude00le.com","entities":[{"offset":0,"length":18,"type":"url"}]

echo mb_strlen($text); // outputs 15. I was expecting 18

### Extra details
Actually I need to put the message in a html format so I need to extract links and other types of entities like mentions and hashtag, email, bold (bold text), italic (italic text), code (monowidth string), pre (monowidth block), text_link (for clickable text URLs), text_mention (for users without usernames) and etc.

So I need an exhaustive way and not just a way to find the links.

**Comment by noplanman** [comment]
Maybe this will help: https://stackoverflow.com/a/30607540

**Comment by akalongman** [comment]
Also you can look at his as well https://stackoverflow.com/questions/49035310/php-telegram-bot-extract-url-in-utf-16-code-units
