### ISSUE TITLE
How to use sendDocument for multipart/form-data?

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#703]
I want to **send a CSV file** created using PHP (and is not stored on the disk) via `sendDocument` method using `multipart/form-data` since it has no URL, but didn't find any guide about it.
Can someone plz help?

**Comment by noplanman** [comment]
You should be able to just pass your stream to the `document` parameter of `sendDocument`.
Does this work for you? #484

**Comment by ttvd94** [comment]
Yes, it worked perfect.
But when the file is stored on the disk, code below does not work.
```
$file = file_get_contents('file.xlsx');
$data['document'] = $file ;
$data['chat_id'] = 1234;
Request::sendDocument($data);
```

**Comment by sharkydog** [comment]
You need to send the resource, not contents
$data['document'] = fopen('file.xlsx', 'rb');

**Comment by ttvd94** [comment]
Thanks @sharkydog , I will try that out.
