### ISSUE TITLE
how to run a command from another command

### ISSUE THREAD

**Issue by Daniyal-Javani** [php-telegram-bot/core#704]
How can I run a command for user, when it's in another command? e.g user is in survey command and I want when user finish the survey, the /start command automatically run for him.

**Comment by juanjofm** [comment]
Try 

$this->getTelegram()->executeCommand("commandName");

**Comment by Daniyal-Javani** [comment]
Not working. In start command I tried:
`$this->getTelegram()->executeCommand("/inlinekeyboard");`
`$this->getTelegram()->executeCommand("inlinekeyboard");`
`$this->getTelegram()->executeCommand("InlinekeyboardCommand");`

I fount [IT!](https://github.com/php-telegram-bot/core/issues/631#issuecomment-329143208) but it's very complicated!
