### ISSUE TITLE
Reply button and forward button on telegram 

### ISSUE THREAD

**Issue by sanna-osamu** [php-telegram-bot/core#705]
Sorry for my bad english. 

1. I need to execute something when someone in my supergroup reply to a message using the “reply” button
2. I need to forward a message to a channel

**Comment by chuv1** [comment]
1. Inside execute() of GenericmessageCommand:
```
$message = $this->getMessage();

if($message->getReplyToMessage() && $message->getChat()->getType() == 'supergroup'){
    // add your code, for example
    $this->replyToChat('Thanks for reply!');
}
```
2. Add your bot as admin to a channel, use `Request::sendMessage();` as usual to send message by id.
You can get channel id by forwarding a message from that channel to https://t.me/ShowJsonBot, for example.

**Comment by sanna-osamu** [comment]
Thank you so much!!!
