### ISSUE TITLE
sendMediaGroup method is missing

### ISSUE THREAD

**Issue by zahhar** [php-telegram-bot/core#706]
For some reason, current implementations seems missing sendMediaGroup method: https://core.telegram.org/bots/api#sendmediagroup

As this method operates already known parameters, it should be very simple to introduce it in Request class. Going to create a PR.

**Comment by jacklul** [comment]
It looks like it was silently added with the albums update...

**Comment by chuv1** [comment]
Yep, it was just added to API documentation without any announce.

**Comment by irshst** [comment]
Wait for new version

**Comment by mehdikhody** [comment]
Use this.
https://github.com/botstan/API#inputmedia

**Comment by noplanman** [comment]
Merged with #718
