### ISSUE TITLE
how to send keyboard only without reply

### ISSUE THREAD

**Issue by alainbelez** [php-telegram-bot/core#710]
currently, i use replyKeyboardMarkup and the result is

![image](https://user-images.githubusercontent.com/6648110/33161586-69f78d8e-d05f-11e7-982e-aca99b50874e.png)

how do you send keyboard only with the "reply" like this:

![image](https://user-images.githubusercontent.com/6648110/33161593-739fd1b6-d05f-11e7-9aed-8959b185cb96.png)

**Comment by chuv1** [comment]
There is no way to send Keyboard only. Message text is required by API.

**Comment by alainbelez** [comment]
none that i know of, i'm only passing these via reply_markup on sendMessage
```
$keyboard = [
    ['/getcurrentprice'],
    ['/addpricenotify'],
    ['/removepricenotify']
];

'keyboard' => $keyboard, 
'resize_keyboard' => true, 
'one_time_keyboard' => true,
```

**Comment by noplanman** [comment]
@alainbelez Have you managed to get this working?

If not, could you explain more what exactly you want to do?
