### ISSUE TITLE
use wordpress database 

### ISSUE THREAD

**Issue by bijanbiria** [php-telegram-bot/core#711]
hello,
my Writing english is not good And I'm sorry for the spelling mistakes.
i want define **wordpress** database in  getUpdatesCLI.php and save data.
This does not create a problem for **wordpress** database information?
my **wordpress** site is **run** and I do not want to clear **WordPress** information.
Thanks in advance for your guidance

**Comment by Hitmare** [comment]
as long the wordpress tables do not interfere with the table names of the structure.sql you can import the structure sql into the wordpress database

**Comment by jacklul** [comment]
You can still use table prefix like 'bot_', all you need to do is one change in hook script and sql queries from structure.sql.
