### ISSUE TITLE
How can I send message from another php script

### ISSUE THREAD

**Issue by Daniyal-Javani** [php-telegram-bot/core#713]
Hi
I can't find a way to send message from another php script that's not related to the library. For example when the user loged in my website, send a message to him.

**Comment by sharkydog** [comment]
```php
require_once '/path/to/vendor/autoload.php';
$bot = Longman\TelegramBot\Telegram('token','username');
Longman\TelegramBot\Request::sendMessage(['chat_id' => $chatid, 'text' => $msg]);
```
assuming you have no other stuff (your website) to autoload composer stuff.

or you separate this in a script to be called with cli, like
php /path/to/script.php chatid "some message"
using exec() or similar, then you can get $chatid and $msg through $argv

or in a script behind your webserver to be called with file_get_contents(), then chatid and message would be passed with $_GET
