### ISSUE TITLE
Telegram Return invalid ...

### ISSUE THREAD

**Issue by ParhamHatan** [php-telegram-bot/core#714]
### Required Information

- Operating system: Windows10
- PHP version:7.1.9
- PHP Telegram Bot version:0.50
- Using MySQL database: no
- MySQL version:
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour

Webhook Set
### Actual behaviour

Telegram Return invalid ...
### Steps to reproduce

i checked 3 times and 3 times with test bots and doesnt work
with official link webhook set with no problem
bot_username = 'mara...';

**Comment by jacklul** [comment]
Windows has issues with certificates which causes this, you can either:
- use solution from [here](https://github.com/php-telegram-bot/core/pull/536) (second code)
- download updated '[cacert.pem](https://curl.haxx.se/docs/caextract.html)' and update your **php.ini** configuration `openssl.cafile=C:\PATH\TO\cacert.pem`

**Comment by ParhamHatan** [comment]
Worked!
Tnx
