### ISSUE TITLE
Press button for view a post on telegram channel for viewing a post

### ISSUE THREAD

**Issue by doliskani** [php-telegram-bot/core#716]
Hi
i'm new for bot telegram programming with php and i want to create 3 button under post that one of theme after click on it by user increase the number of view of the post and does not increase this number with scrolling on content of the channel!
sorry for my language
please help.

**Comment by noplanman** [comment]
You mean inline keyboard buttons? Like a vote counter or something?

**Comment by doliskani** [comment]
No, i mean that when a user see the post in telegram channel , a method like a counter call for increasing the post views count, and I want user click on the button for call this method to increase the post views count and this button by bot has been placed under the channel posts and user must click on it to increase the post views count.

**Comment by noplanman** [comment]
Hmm, i think that view count is automatic and counted by Telegram itself, to show how many users in the channel have seen it.

Happy to stand corrected though, maybe @Hitmare @jacklul @chuv1 know more.

**Comment by doliskani** [comment]
Yes, that's I mean, tnx for your reply.

**Comment by noplanman** [comment]
I don't think you can do anything about that, which kind of makes sense, as that is managed by Telegram.

**Comment by doliskani** [comment]
I've seen before this functionality on telegram bot that forcing you to join telegram channel and that channel, under each post three button was there and one of those by user clicks increase the post views count and I was very surprised and after I searched for this functionality, but I did not find anything.

**Comment by Hitmare** [comment]
as far as is used google to find such a function in the BOT API i could not find one. Maybe it was an bot based on the Telegram Client API which we are not supporting here.

**Comment by doliskani** [comment]
OK, thanks,after a while I think so
