### ISSUE TITLE
Using Keyboard and InlineKeyboard both together in one message

### ISSUE THREAD

**Issue by moonrider441** [php-telegram-bot/core#721]
i want to send both keyboard type in one message.

help me plz

### Required Information
- PHP version: 7.1
- PHP Telegram Bot version:
- Using MySQL database: yes
- Update Method: Webhook 
- Self-signed certificate: no

**Comment by noplanman** [comment]
@moonrider441 you can only use either one, not both. If you define both `keyboard` and `inline_keyboard` in the `reply_markup` field, `keyboard` takes preference.
