### ISSUE TITLE
Why Inline_Button doesn't work in channel?

### ISSUE THREAD

**Issue by MostafaSh** [php-telegram-bot/core#723]
hi!
there is a problem in inline button when I send it to a channel via my bot. 
when i click that button through my channel i get this error:

> PHP Catchable fatal error:  Argument 1 passed to Longman\TelegramBot\DB::insertUser() must be an instance of Longman\TelegramBot\Entities\User, null given, called in /home/mybotpro/public_html/FumTweet/vendor/longman/telegram-bot/src/DB.php on line 723 and defined in /home/mybotpro/public_html/FumTweet/vendor/longman/telegram-bot/src/DB.php on line 335

this is my callbackquerycommand file:
[CallbackqueryCommand.php.zip](https://github.com/php-telegram-bot/core/files/1563450/CallbackqueryCommand.php.zip)

this is my DB.php file:
[DB.php.zip](https://github.com/php-telegram-bot/core/files/1563458/DB.php.zip)

I'm really looking forward a kind friend to help me!

**Comment by noplanman** [comment]
Please just put your code into the issue directly, not as zip files.

Also, are you adding custom code to your DB.php?
You should never touch core files, as an update will delete all your changes!

The error shows that something is wrong in your DB.php, so i suggest you use the latest version of the bot and try again.

**Comment by MostafaSh** [comment]
thanks @noplanman !
I fixed the problem by just updating DB.php

but i got a new problem!
I'm using a shared hosting for my bot. and it has limitation of 60 requests per second.

i created a rating ability for my channel posts. the channel has 8k members.

when i launched this new ability, the inline buttons were too slow, and all actions got lag.

and I don't know why! What can it be? and how can i solve this problem?

sorry for my poor English !

**Comment by noplanman** [comment]
Maybe your server is too slow. Can you check to see if your server resources are enough to handle all the requests?
