### ISSUE TITLE
Referral link /start

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#727]
Hi everyone!
I saw this in other bots. Referral (partner) links like `@testBot?start=MY_ID`.
After the user (id: 123456 for example) has started work by my referral link (id: 777777) the field `invited_by_id` in table `user` changed:

`id: 123456` (my refferer)
`invited_by_id: 777777` (my id)

How can I do it?

**Comment by noplanman** [comment]
Look here: #688

**Comment by noplanman** [comment]
@MyZik Did you get this to work then?

**Comment by MyZik** [comment]
@noplanman Oh, I have not tried it yet, but i'm sure it works!

**Comment by sowrov23** [comment]
819310971:AAFF3E2yugAZglOQQJmKytKWfVyDAIdgrLQ
