### ISSUE TITLE
Execute function/command each x minutes

### ISSUE THREAD

**Issue by sup3rgiu** [php-telegram-bot/core#729]
Hi,
I was wondering if is possibile execute a function/a command each x minutes without an user input.

For example:
1) The user start the bot
2) The user add a link through a command, then a function do some magic and some values got from the page loaded from the link are saved in my database
3) The bot each x minutes load this link, performs some checks and if he finds differences between the new values and the ones saved in the database, it sends a message to the user.

I already have the working code for everything, the only thing that I don't know is how repeat the checks each x minutes without the user input.

Really thanks in advance and thanks for this awesome API!

**Comment by jacklul** [comment]
https://github.com/php-telegram-bot/core/wiki/Running-with-cron-(scheduled-commands)

**Comment by sup3rgiu** [comment]
Really thanks, didn't see this!

Just a question: in this way, the ID taken with $chat_id = $this->getMessage()->getChat()->getId(); is the ID of the user (if the bot is running in private) as usual, or not?

Thanks

**Comment by jacklul** [comment]
When run by cron it will have bot's ID, when run normally it will act as usually and have user's chat id. Also: notice first advice on that wiki page if you want to do 'hybrid' commands.

**Comment by sup3rgiu** [comment]
Yes I saw the advice, thanks :)

So there is now way to get the user's chat id? Because when the command is called by cron, it should get the user's chat ID to use it in order the execute a SQL query.

**Comment by sharkydog** [comment]
> The user add a link through a command, then a function do some magic and some values got from the page loaded from the link are saved in my database.

save also the user id who posted that link, then

> The bot each x minutes load this link, performs some checks and if he finds differences between the new values and the ones saved in the database, it sends a message to the user.

the cron script will load the user id along with the link, you can use it as chat id to send a private message

**Comment by noplanman** [comment]
@sup3rgiu Is this solved for you now?
