### ISSUE TITLE
run command in cron

### ISSUE THREAD

**Issue by ahmad201494** [php-telegram-bot/core#734]
Hi,

i use hook.php
how to run one command every hour?
for example: send message to all user hourly.

**Comment by MyZik** [comment]
Hi! You can use that: https://github.com/php-telegram-bot/core/wiki/Running-with-cron-(scheduled-commands)

**Comment by noplanman** [comment]
You can find the example file here:
https://github.com/php-telegram-bot/example-bot/blob/master/cron.php

**Comment by ahmad201494** [comment]
thank you.
