### ISSUE TITLE
InlineKeyboardButton problem

### ISSUE THREAD

**Issue by candeman242** [php-telegram-bot/core#735]
### Required Information

- PHP version: 5
- PHP Telegram Bot version: 3
- Using MySQL database: yes / no
- MySQL version:
- Update Method: Webhook 
- Self-signed certificate: yes

'switch_inline_query', 'switch_inline_query_current_chat' allows for empty string value ("") but it throws an error if set to an empty string.

This bit of code below needs to be modified to allow for empty values for both **'switch_inline_query', 'switch_inline_query_current_chat',** Currently it ignores those two parameters if they are empty strings

```
 foreach (['url', 'callback_data', 'switch_inline_query', 'switch_inline_query_current_chat', 'pay'] as $param) {
            if ($this->getProperty($param, '') !== '') {
                $num_params++;
            }
        }
```

**Comment by noplanman** [comment]
@candeman242 You're absolutely right!

PR to be merged shortly, thanks a lot!! 👍

**Comment by candeman242** [comment]
Great, glad I could help.
