### ISSUE TITLE
DB::insertUser() sets 'created_at' and/or 'updated_at' fields to NULL

### ISSUE THREAD

**Issue by jacklul** [php-telegram-bot/core#737]
Make sure date is not empty otherwise set it with `self::getTimestamp()`!
  
Edit: same with `DB::insertChat()`!

**Comment by noplanman** [comment]
Do you have any more details as to when the date field is empty?
So basically we just set it to the current timestamp then?

Will check to see if that makes sense in all cases.

**Comment by jacklul** [comment]
I think this happens for non-message objects or objects that carry User object that is not sender of that update (forwarded messages).
