### ISSUE TITLE
StartCommand not work

### ISSUE THREAD

**Issue by samuelyeshua** [php-telegram-bot/core#740]
Actually I do not know where the problem is, I checked several examples and could not understand what was wrong. Where is the error?

### Required Information

- Operating system: Debian 9 Stretch 4.13.13-1~bpo9+1
- PHP version: PHP 7.0.27-0+deb9u1
- PHP Telegram Bot version: ^0.52.0
- Using MySQL database: no
- MySQL version:
- Update Method: Webhook
- Self-signed certificate:
- RAW update (if available):

### Expected behaviour
I expected that after the command to start a keyboard was sent to the client

### Actual behaviour
Nothing is happening, but the update log shows the updates received

### Steps to reproduce
hook.php

	require 'vendor/autoload.php';

	use Longman\TelegramBot\Telegram;
	use Longman\TelegramBot\TelegramLog;

	$config = [
		'commands' => [
			__DIR__ . '/Commands/'
		],
		'bot' => [
			'bot_token' => 'SECRET',
			'username'	=> 'SECRET',
			'admin'		=> ''
		]
	];

	try {
		$telegram = new Telegram( $config['bot']['bot_token'], $config['bot']['username'] );
		$telegram->addCommandsPath( $config['commands'] );

		TelegramLog::initErrorLog( __DIR__ . "/Logs/{$config['bot']['username']}_error.log" );
		TelegramLog::initDebugLog( __DIR__ . "/Logs/{$config['bot']['username']}_Debug.log" );
		TelegramLog::initUpdateLog( __DIR__ . "/Logs/{$config['bot']['username']}_Update.log" );

		$telegram->enableLimiter();
		$telegram->handle();
	} catch (Longman\TelegramBot\Exception\TelegramException $e) {
	    // Silence is golden!
	    //echo $e;
	    // Log telegram errors
	    TelegramLog::error($e);
	} catch (Longman\TelegramBot\Exception\TelegramLogException $e) {
	    // Silence is golden!
	    // Uncomment this to catch log initialisation errors
	    echo $e;
	}

StartCommand.php

    namespace Longman\TelegramBot\Commands\UserCommands;

    use Longman\TelegramBot\Commands\UserCommand;
    use Longman\TelegramBot\Entities\InlineKeyboardMarkup;
    use Longman\TelegramBot\Entities\InlineKeyboardButton;
    use Longman\TelegramBot\Request;

    class StartCommand extends UserCommand
    {
    	
    	protected $description = 'Start command';
        protected $usage = '/start';
        protected $version = '1.1.0';

        public function execute()
        {
        	$keyboardStart = [
        		new InlineKeyboardButton(['text' => 'Yes!!', 'callback_data' => 'yesStart']),
        		new InlineKeyboardButton(['text' => 'No!!', 'callback_data' => 'noStart'])
        	];

        	$message = $this->getMessage();
        	$chat = $message->getChat();

        	$data = [
        		'chat_id' => $chat->getId(),
        		'text' => 'message here',
        		'reply_markup' => new InlineKeyboardMarkup(['inline_keyboard' => [$keyboardStart]])
        	];

        	return Request::sendMessage($data); 
        }
    }

**Comment by noplanman** [comment]
As you're adding the whole commands paths array, you need to use `$telegram->addCommandsPaths(...)` (notice the plural "Path**s**")

Also, there is no `InlineKeyboardMarkup` class any more, you need to use `InlineKeyboard` directly.

Check this example to set up an inline keyboard:
https://github.com/php-telegram-bot/example-bot/blob/master/Commands/InlinekeyboardCommand.php

**Comment by samuelyeshua** [comment]
This example of InlineKeyboardMarkup was just one of the tests I was doing to try to make it work.

you're correct, the command is wrong, but even after the fix it was still not working, but then I changed the namespace to system command and it worked. Thanks for the feedback
