### ISSUE TITLE
Share contact pop-up gets overlapped by regular keyboard on small iPhones

### ISSUE THREAD

**Issue by ikolubr** [php-telegram-bot/core#742]
Hi guys, share_contact on a markup keyboard gets overlapped on small screen phones. I tested on a iPhone 5 and the share button on the little pop-up that shows up gets overlapped by the regular keyboard.

I guess this is a OS problem, not specific to the telegram app, but any help would be appreciated.

Is there anyway to hide the regular keyboard or any other tips to make it work?
### Required Information

- Operating system: iOS
- PHP version: n/a
- PHP Telegram Bot version: Bot API 3.5.
- Using MySQL database: no
- MySQL version: n/a
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour

Share contact pop-up not overlapped by regular keyboard.
### Actual behaviour

Share contact pop-up gets overlapped by regular keyboard and user can't share its contact.
### Steps to reproduce

![photo_2018-01-10_09-55-49](https://user-images.githubusercontent.com/2576482/34787544-7720c0b8-f5ec-11e7-8f41-5ca1f73d0f88.jpg)

### Extra details

![photo_2018-01-10_09-55-49](https://user-images.githubusercontent.com/2576482/34787631-c95cf716-f5ec-11e7-910d-f8703891253b.jpg)

**Comment by chuv1** [comment]
It's a bug on IOS App. You can use `Keyboard::remove()` method in previous message to hide it.

**Comment by ikolubr** [comment]
@chuv1, thank you for your reply...
I'm not using the php-telegram-bot api.. I'm writing the code myself.. do you mind telling me how I call the keyboard remove using just regular php?

Like, this is the array I will be converting to json to send to the telegram API, where I would put the keyboard remove option?

array('chat_id' => $chat_id, "text" => "Hi blah blah balh... I need you contact info", 'reply_markup' => array(
                'keyboard' => array(array(array("text" => "Send Contact Info", "request_contact" => true))),
                'one_time_keyboard' => true,
                'resize_keyboard' => true)))

Thank you,

**Comment by ikolubr** [comment]
@chuv1, I guess I got it.
changing the on_time_keuboard para false doesn;t bring the regular keyboard up .. so it doesn't overlap.
