### ISSUE TITLE
PHP Fatal error isOk

### ISSUE THREAD

**Issue by blogaster** [php-telegram-bot/core#746]
### Required Information

- Operating system: Linux
- PHP version:  7.0.27-1~dotdeb+8.1 (64bit)
- PHP Telegram Bot version: 0.46.0
- Using MySQL database: yes
- MySQL version: 10.0.32-MariaDB-0+deb8u1
- Update Method: Webhook 

Hello! I connected my class
`namespace Longman\TelegramBot;`
`use Longman\TelegramBot\Entities\Keyboard;`
`use Longman\TelegramBot\Convert2ePub;`
`use Longman\TelegramBot\Helpers;`
`class Link`
`{...`

index.php
`require_once ('Classes/Link.php');`

Call from GenericmessageCommand.php
`return new Link($message);`

It's work correctly
But in server error log I get error
` PHP Fatal error:  Uncaught Error: Call to private method Longman\\TelegramBot\\CheckLink::isOk() from context 'Longman\\TelegramBot\\Telegram' in /home/blogaster/bots/bot-core/longman/telegram-bot/src/Telegram.php:389\nStack trace:\n#0 /home/blogaster/bots/pdfgraph_bot5445/index.php(34): Longman\\TelegramBot\\Telegram->handle()\n#1 {main}\n  thrown in /home/blogaster/bots/bot-core/longman/telegram-bot/src/Telegram.php on line 389`

Why?
Pleace help me. Thank you

**Comment by noplanman** [comment]
What exactly are you trying to do here? What is the `Link` class doing.

Also, please update your bot, the latest version is 0.52.0 and has a lot of changes since 0.46.0.
Check the [CHANGELOG.md](https://github.com/php-telegram-bot/core/blob/master/CHANGELOG.md)
