### ISSUE TITLE
sendtoall command issue

### ISSUE THREAD

**Issue by HamidBaseri** [php-telegram-bot/core#750]
### Required Information

- Operating system:
- Web Server: LiteSpeed
- PHP version: 7.0.9 (64bit); litespeed; Linux
- PHP Telegram Bot version: 0.44.1
- Maximum PHP script execution time: 60 seconds
- Using MySQL database: yes
- MySQL version: 5.6.37
- Update Method: Webhook 
- Self-signed certificate: yes
- RAW update (if available):
- curl version: 7.38.0; OpenSSL/1.0.0

### Expected behaviour

Hi dear developers...!
When i use /sendtoall command if my bot's users whats too many ( about 700-800 and more) the command does not response and some times a user give my message more than one time.
to solve it i will add limit to db:selectchats and will send my message.
whats wrong ?
 some times ishould limit it to 300 chats at once.

**Comment by noplanman** [comment]
@jacklul, limiter issue again here?
Maybe related to #754

**Comment by jacklul** [comment]
The problem might be the difference between time in script and time converted in database or something...

**Comment by noplanman** [comment]
@hamid3pich Have you managed to get this sorted?
Have you tried the suggestion that @jacklul made?
