### ISSUE TITLE
get contact

### ISSUE THREAD

**Issue by saeed2922** [php-telegram-bot/core#751]
this code not work plz help me

if($telegram->getUpdateType()=='contact')
	   {
		   $content = array('chat_id' => $chat_id, 'text' => 'is contact');
      	   $telegram->sendMessage($content);
	   }

**Comment by MyZik** [comment]
Hi!
Do you want to get user contact (phone number) after user send it?

**Comment by jacklul** [comment]
`$this->getUpdate()->getMessage()->getContact();`.

**Comment by cyc0der** [comment]
‌ ح‌ ه

**Comment by cyc0der** [comment]
‌‌‌از ‌‌‌ ‌

**Comment by cyc0der** [comment]
‌‌‌‌‌‌‌‌‌‌‌‌ ‌‌‌از ‌‌‌‌‌
