### ISSUE TITLE
Delete all messages in chat from none-admin users

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#752]
Hi!

Is it possible? I have a supergroup with invite link. I want the bot to delete all messages from none-admin users.

For example:
User writes "Hi everyone"
And bot delete message at once.

How should the command look like? Do I need to change the `Request::sendMessage` method in `vendor`?

Thanks you a lot!

**Comment by noplanman** [comment]
In `GenericmessageCommand` you can check if the user is an admin, if not, delete the message:
(untested, but you get the idea)
```php
$message    = $this->getMessage();
$message_id = $message->getMessageId();
$chat_id    = $message->getChat()->getId();
$user_id    = $message->getFrom()->getId();

if (!$this->getTelegram()->isAdmin($user_id)) {
    return Request::deleteMessage(compact('message_id', 'chat_id'));
}
```

**Comment by MyZik** [comment]
@noplanman thank you a lot!
