### ISSUE TITLE
sendMessage freeze if I try send more than 20 message / per minute for different users

### ISSUE THREAD

**Issue by sautchenkov** [php-telegram-bot/core#754]
Hello! I try to send a message to all bot users. In the documentation, I see the only 30/sec limit. But when I try to send, if I send more than 20/min sendMessage freeze for 30 sec. And I can send more than 20/per minute to separate users. Does anyone get this limit?

**Comment by noplanman** [comment]
Summoning the limit-master @jacklul 😇

**Comment by jacklul** [comment]
There must be something wrong with your handling, if **request limiter is on** it shouldn't let this happen.
In one of my bots I used to send announcements to over 1000 chats (script also saved each result into log file so I could see errors and chats that banned my bot) and it worked perfectly.

If your bot is popular and while you're mass sending message other users are actively using it then their messages will count towards the limit aswell.

If possible - for mass messaging / announcements code a function that sends no more than `5-10` messagges per second in for or do...while loop which sleeps for second or two after sending `5-10` messages. I would also suggest putting some kind of debug function that writes to fixed file a line about what is going on (including result of the sendMessage) - `file_put_contents('sendMessage.log', date("Y-m-d H:i:s") .' - Sending to chat ID: ' . $chat_id . PHP_EOL . print_r($result, true), FILE_APPEND) . PHP_EOL`.

**Comment by noplanman** [comment]
@sautchenkov Is this limit still being reached and preventing your bot from running smoothly?

**Comment by akalongman** [comment]
@sautchenkov any update?
