### ISSUE TITLE
is possible to use only required tables for conversation?

### ISSUE THREAD

**Issue by ahmadbadpey** [php-telegram-bot/core#755]
I installed this package in laravel. and there I used default users table that laravel is provided to Auth and login operations. 

In the other hand to register users that comes form telegram bot, we know that should use conversations feature to get some user information like firs_name , last_name , ... . to use conversation we should enable MySQL feature in your package. and in this case you offer that run [structure.sql](https://github.com/php-telegram-bot/core/blob/master/structure.sql) file that included many tables that I do not need. 

I just need tables that conversation need them. and other tables like `inline_query` ,`callback_query`,`edited_message` is not useful in this case. 

Now I want to know is possible to use required tables to conversation only? and what are them ? in the other words ,Why do we need to use an unused table

**Comment by jacklul** [comment]
You could copy `Conversation.php` and `ConversationDB.php` then modify it so that it uses your own PDO connection and nothing more (literally you could copy some code from `DB.php`), then you can overwrite this class with either autoloader or `require()`.
