### ISSUE TITLE
Can not delete or rename file after send it and result failed

### ISSUE THREAD

**Issue by NabiKAZ** [php-telegram-bot/core#757]
I want to `rename` or `unlink` the file after send file to telegram. but I can not do it!

See this sample code:
```PHP
<?php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config.php';

use Longman\TelegramBot\Request;
use Longman\TelegramBot\Telegram;

$telegram = new Telegram($bot_api_key, $bot_username);

$file = 'a.jpg';

$data = array(
	'chat_id' => $channel_name,
	'caption' => 'سلام',
	'photo' => Request::encodeFile($file),
);

$result = Request::sendPhoto($data);
if ($result->isOk()) {
	echo "ok";
} else {
	echo "error: " . $result->printError(true);
}

rename($file, 'x.jpg'); //OR: unlink($file);
```

In this case, if result was `ok` there are not any problem.
But when result `$result->isOk()` return `false`, Can not do `rename` or `unlink` (seem this problem just there are on windows).

Return these errors:
```
error: Error N: 400, Description: Bad Request: photo caption must be encoded in UTF-8
Warning: rename(a.jpg,x.jpg): The process cannot access the file because it is being used by another process. (code: 32) in a.php on line 27

error: Error N: 400, Description: Bad Request: photo caption must be encoded in UTF-8
Warning: unlink(a.jpg): Permission denied in a.php on line 28
```

Any way seem this is caused by https://github.com/php-telegram-bot/core/blob/master/src/Request.php#L423 and open file and don't close it.

For resolve the problem, I close file pointer manualy before `rename` or `unlink` command, by this command:
```
fclose($data['photo']);
```
And my problem resolve temporary, But I thinks must fix this in code basically.

**Comment by noplanman** [comment]
Not quite sure how this can be solved, as the handle of the file is required for the sending.

An option would be to simply close all file handles after a send command is called, but maybe a user passes the handle and then re-uses it to do other operations on the file. It would be a strange side-effect for the file handle to be closed suddenly.

So your solution of closing the handle yourself is the correct way I think.

**Comment by NabiKAZ** [comment]
This code work well temporary:

```
<?php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config.php';

use Longman\TelegramBot\Request;
use Longman\TelegramBot\Telegram;

$telegram = new Telegram($bot_api_key, $bot_username);

$file = 'a.jpg';
$file_pointer = Request::encodeFile($file); //keep pointer of file

$data = array(
	'chat_id' => $channel_name,
	'caption' => 'سلام',
	'photo' => $file_pointer, //use pointer of file
);

$result = Request::sendPhoto($data);
if ($result->isOk()) {
	echo "ok";
} else {
	echo "error: " . $result->printError(true);
}

@fclose($file_pointer); //close pointer of file manually

rename($file, 'x.jpg'); //OR: unlink($file); //this work well

```
