### ISSUE TITLE
only first question shown in conversation

### ISSUE THREAD

**Issue by ahmadbadpey** [php-telegram-bot/core#758]
I fully copied [SurveyCommand.php](https://raw.githubusercontent.com/php-telegram-bot/example-bot/master/Commands/SurveyCommand.php) file to my project and then send `/survey` to telegram bot but only first question is asked and when send answer second and other question not asked. 

This is `BotController`  that I wrote to handle bot : 

```php
	class BotController extends Controller
	{
		public $bot_api_key;
		public $bot_username;
		public $hook_url;
		public $commands_paths;
		public $prefix_table;

		function __construct ()
		{
			$this->bot_api_key    = '*****************';
			$this->bot_username   = '****_bot';
			$this->prefix_table   = 'telegram';
			$this->hook_url       = 'https://e18ee456.ngrok.io/webhook';
			$this->commands_paths = [
				app_path('Commands')
			];

			TelegramLog::initErrorLog($this->commands_paths[0] . "/{$this->bot_username}_error.log");
			TelegramLog::initDebugLog($this->commands_paths[0] . "/{$this->bot_username}_debug.log");
			TelegramLog::initUpdateLog($this->commands_paths[0] . "/{$this->bot_username}_update.log");

		}

		public function setWebhook ()
		{
			try {
				// Create Telegram API object
				$telegram = new \Longman\TelegramBot\Telegram($this->bot_api_key, $this->bot_username);
				// Set webhook
				$result = $telegram->setWebhook($this->hook_url);

				if ($result->isOk()) {
					echo $result->getDescription();
				}
			} catch (\Longman\TelegramBot\Exception\TelegramException $e) {
				// log telegram errors
				echo $e->getMessage();
			}
		}

		public function Webhook ()
		{
			try {
				// Create Telegram API object
				$telegram = new \Longman\TelegramBot\Telegram($this->bot_api_key, $this->bot_username);

				$telegram->addCommandsPaths($this->commands_paths);

				$mysql_credentials = [
					'host'     => 'localhost',
					'user'     => 'test',
					'password' => '123456',
					'database' => 'bar'
				];

				$telegram->enableMySql($mysql_credentials, $this->prefix_table . '_');

				Request::setClient(new \GuzzleHttp\Client([
					'base_uri' => 'https://api.telegram.org',
					'verify'   => false
				]));

				// Handle telegram webhook request
				$telegram->handle();
			} catch (\Longman\TelegramBot\Exception\TelegramException $e) {
				// Silence is golden!
				// log telegram errors
				echo $e->getMessage();
			}

		}
	}

```

what is problem ?

**Comment by noplanman** [comment]
Anything in the logs?
I assume `TelegramLog` and `Request` classes are correctly `use`d at the top of your file, yes?

**Comment by Sh3R** [comment]
@ahmadbadpey can you handled it? I encountered the same problem.

**Comment by noplanman** [comment]
@ahmadbadpey Have you managed to get this sorted?
Also, since the conversations require the database, make sure the database is set up correctly.

**Comment by ent00** [comment]
I have the same problem. The database is connected. In table "conversations" I see first question. The same as in Telegram. That's all. Further questions are not issued. Error file is empty. Where is error?

**Comment by noplanman** [comment]
@ent00 Do you have a custom `GenericmessageCommand`?
If so, make sure you have [these lines](https://github.com/php-telegram-bot/core/blob/ed50346851088a13f2af27e067d3f595b900b55f/src/Commands/SystemCommands/GenericmessageCommand.php#L61) added.

**Comment by ent00** [comment]
Thank you. It's all worked.

**Comment by Leonid74** [comment]
Unfortunately, I have the same problem now with latest version of bot. I have installed core + example bot. The database is connected. In "conversations" table I see first question only (as in Telegram) on /survey. That's all.

**Comment by noplanman** [comment]
@Leonid74 You've copied `GenericmessageCommand.php` as well, right?

**Comment by Leonid74** [comment]
i have two GenericmessageCommand.php:
1. in the vendor/..../SystemCommands:
`<?php

/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Entities\ServerResponse;
use Longman\TelegramBot\Exception\TelegramException;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Telegram;

/**
 * Generic message command
 */
class GenericmessageCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = Telegram::GENERIC_MESSAGE_COMMAND;

    /**
     * @var string
     */
    protected $description = 'Handle generic message';

    /**
     * @var string
     */
    protected $version = '1.2.0';

    /**
     * @var bool
     */
    protected $need_mysql = true;

    /**
     * Execution if MySQL is required but not available
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function executeNoDb()
    {
        // Try to execute any deprecated system commands.
        if (self::$execute_deprecated && $deprecated_system_command_response = $this->executeDeprecatedSystemCommand()) {
            return $deprecated_system_command_response;
        }

        return Request::emptyResponse();
    }

    /**
     * Execute command
     *
     * @return ServerResponse
     * @throws TelegramException
     */
    public function execute()
    {
        // Try to continue any active conversation.
        if ($active_conversation_response = $this->executeActiveConversation()) {
            return $active_conversation_response;
        }

        // Try to execute any deprecated system commands.
        if (self::$execute_deprecated && $deprecated_system_command_response = $this->executeDeprecatedSystemCommand()) {
            return $deprecated_system_command_response;
        }

        return Request::emptyResponse();
    }
} `

2. in the Commands folder:
`<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Conversation;
use Longman\TelegramBot\Request;

/**
 * Generic message command
 *
 * Gets executed when any type of message is sent.
 */
class GenericmessageCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = 'genericmessage';

    /**
     * @var string
     */
    protected $description = 'Handle generic message';

    /**
     * @var string
     */
    protected $version = '1.1.0';

    /**
     * @var bool
     */
    protected $need_mysql = true;

    /**
     * Command execute method if MySQL is required but not available
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function executeNoDb()
    {
        // Do nothing
        return Request::emptyResponse();
    }

    /**
     * Command execute method
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        //If a conversation is busy, execute the conversation command after handling the message
        $conversation = new Conversation(
            $this->getMessage()->getFrom()->getId(),
            $this->getMessage()->getChat()->getId()
        );

        //Fetch conversation command if it exists and execute it
        if ($conversation->exists() && ($command = $conversation->getCommand())) {
            return $this->telegram->executeCommand($command);
        }

        return Request::emptyResponse();
    }
} `

if i remove GenericmessageCommand.php in the folder 2 - /survey did't respond ))

**Comment by Leonid74** [comment]
any idea? please :)

**Comment by noplanman** [comment]
Hmm, is there any error output in your logs?

Also, try using getUpdates method and executing directly from CLI to see if there are any warnings that may be the cause.

You've updated your DB to the latest version too, right?

**Comment by Leonid74** [comment]
no error in logs (error/debug/update).

> You've updated your DB to the latest version too, right?

hmm... installed from git with composer 4 days left. Where can i find version number ?

will try getUpdatesCLI...

**Comment by Leonid74** [comment]
file structure.sql is 20580 bytes

**Comment by noplanman** [comment]
Are you using a completely fresh database with the latest `structure.sql`?

If not, you can find the DB update scripts here:
https://github.com/php-telegram-bot/core/tree/master/utils/db-schema-update

Try to execute the latest ones and try again.

**Comment by Leonid74** [comment]
tried getUpdatesCLII.php - the same result when i run it, only first question:
```
typed in telegram: /survey
run getUpdatesCLI.php -> printed in browser: #!/usr/bin/env php 2020-07-26 20:09:35 - Processed 1 updates -> printed on telegram: Type your name:
typed in telegram: 123
run getUpdatesCLI.php -> printed in browse: #!/usr/bin/env php 2020-07-26 20:09:37 - Processed 1 updates -> printed on telegram: none
```

> Are you using a completely fresh database with the latest `structure.sql`?
> 
> If not, you can find the DB update scripts here:
> https://github.com/php-telegram-bot/core/tree/master/utils/db-schema-update
> 
> Try to execute the latest ones and try again.

i think that i use the latest version, coze install it 3 day ago with composer. Compared with actual version on git - the same

very strange problem, coze i have an another older version bot (about 1 year ago) at the same host ad it worked well...

**Comment by noplanman** [comment]
Strange. Could you try to completely empty your new database?

**Comment by Leonid74** [comment]
yeah, did it, unsuccessful.
did a fresh clear install but with bot manager - all the same, all worked but /survey - not.
may be something wrong with install structure.sql into mysql ? i just import this file to mysql. should i do something else with it ?

**Comment by Leonid74** [comment]
@noplanman I understand that you do not have much time to find out the causes of various problems, but please help me solve this strange problem. Reinstalled several times and in different modes, everything works except /survey, i.e. conversation does not work. What else can we assume or where else can we look for a solution to the problem? 

what is the correct procedure for installing the structure.sql file ? I use a file import or does the bot do it itself during the installation process ?

**Comment by noplanman** [comment]
@Leonid74 It seems the way you set it up is correct, so this seems like a strange environment anomaly or something 🤔 

Will get in touch with you privately to get this fixed

**Comment by Leonid74** [comment]
ok, will waiting!))

**Comment by noplanman** [comment]
I've already messaged you, not sure you're getting them though.

Ping me on Telegram please: https://t.me/noplanman

**Comment by Leonid74** [comment]
@noplanman thank you, all things sorted. you are best))
