### ISSUE TITLE
Do I need to update the database separately?

### ISSUE THREAD

**Issue by gmalexmush** [php-telegram-bot/core#759]
### Required Information

- Operating system: Linux debian stretch amd64
- PHP version: PHP Version 7.0.27-0+deb9u1
- PHP Telegram Bot version: 0.52.0
- Using MySQL database: yes / no
- MySQL version: 5.5.9999
- Update Method: Webhook
- Self-signed certificate: yes
- RAW update (if available):

### Actual behaviour

It is ok.
The version of my bot was 0.50.0. I made an update for the bot (composer update). The version of my bot is now 0.52.0 2018.01.07.
Do I need to do any updates for the database?
The bot is working.

**Comment by noplanman** [comment]
Hi @gmalexmush, check the readme for what has changed.
It also shows if a DB update is necessary.
Updates to DB need to be executed manually at the moment.

**Comment by gmalexmush** [comment]
Thank you noplanman! 
I found changes to the database and applied. There were not enough two fields in the message table. I found the scripts to update the database in the /longman/telegram-bot/db-schema-update folder. Now I will know where to look for changes for the database.

**Comment by noplanman** [comment]
Perfect! :ok_hand:
