### ISSUE TITLE
System Commands not working

### ISSUE THREAD

**Issue by sachin-lalaworld** [php-telegram-bot/core#770]
I have integrated all commands but system command is not working. But custom commands are working fine
Please resolve the issue.

### Required Information

- Operating system:
- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes / no
- MySQL version:
- Update Method: Webhook / getUpdates
- Self-signed certificate: yes / no
- RAW update (if available):

**Comment by noplanman** [comment]
Could you be a bit more explicit please, what exactly isn't working? Specific commands?

And please, the issue template is here for a reason, please fill it out so we can help you better.
I've added it to your initial comment, please enter all the values, thanks.

**Comment by sachin-lalaworld** [comment]
What exactly issue I am getting the none of system commands is working.
Operating system: Ubuntu 17.04
PHP version: 7.0.1
PHP Telegram Bot version: 
Using MySQL database: yes / no - no
MySQL version:
Update Method: Webhook / getUpdates Webhook
Self-signed certificate: yes / no yes
RAW update (if available):

**Comment by noplanman** [comment]
Which commands are you trying to execute?
System commands aren't supposed to be called by the user, that's what User and Admin commands are for.

Are you overriding them with your own commands then?

I can't help if I don't know what it is you're trying to do, so you would really make it easier for me if you explained a bit more...

**Comment by sachin-lalaworld** [comment]
I understood, I have created custom commands in UserCommands directory but custom command is working fine but when I execute SystemCommands like welcome message for newchatmembers,genericmessageCommand and to delete none-admin message it was not working. I checked all systemcommand to excute but not working.

**Comment by jacklul** [comment]
Can you give us an example what one of your system commands file looks like?

Did you set up custom commands dir in config?

**Comment by sachin-lalaworld** [comment]
Yes that I have been already disable. Here is my repository link

https://github.com/sachin-lalaworld/uat

**Comment by jacklul** [comment]
That repository doesnt seem to contain any commands but I found code that suggests you are putting your commands inside "vendor/php-teleram-bot" which is terrible practice and you shouldn't do it.

**Comment by sachin-lalaworld** [comment]
Okay thanks, can you please share me the sample?

**Comment by jacklul** [comment]
https://github.com/sachin-lalaworld/uat/blob/master/app/Http/Controllers/BotController.php#L45

You should create commands directory somewhere in your project directory and put your custom commands there then adjust the path in the linked lines.

**Comment by sachin-nex** [comment]
Thats is fine but the issue doesn't resolve.

**Comment by jacklul** [comment]
Show us your NewchatmembersCommand and GenericmessageCommand.

Also: what php-teleram-bot library version you're using ?

**Comment by noplanman** [comment]
@sachin-lalaworld @sachin-nex 
Have you managed to get this working? Can I close off here?

**Comment by akalongman** [comment]
@sachin-nex any update?
