### ISSUE TITLE
User calling System commands fails

### ISSUE THREAD

**Issue by noplanman** [php-telegram-bot/core#772]
Because System commands can be called in the same way that User and Admin commands are called, simply executing a System command from the chat shouldn't be possible.

A quick fix would be simply edit each System command to see if it has been called by a User or the bot itself.
The `/start` command would need special treatment, because that should still work as a normal User command too.

As for the others, maybe it would make sense to do the check further up instead of inside the command itself.

What do you guys think @php-telegram-bot/developers

**Comment by jacklul** [comment]
Let's just prevent running system commands via /command and move /start to user commands (after all it is an actual command).

**Comment by noplanman** [comment]
Yes, that would be the best for sure.

Working on that now 👍
(almost done already)

**Comment by noplanman** [comment]
@NCLS96 Good question! I only just saw your comment here, must have missed it somehow :confused: 

The `$usage` property was (and still is) used by the [`/help`](https://github.com/php-telegram-bot/example-bot/blob/90bfde028f71bda1aedd51bdc225984a68b5c276/Commands/HelpCommand.php) command that you can find in the [example-bot](https://github.com/php-telegram-bot/example-bot) repository. You're correct in that we could just check for that. But since the whole commands need redesigning anyway, I don't think it matters too much which "fix" (or rather, "hack") is used in the meantime :grin:

**Comment by noplanman** [comment]
@NCLS96 I take back what I said in my previous comment, your suggestion is much better and a lot easier to implement.

I've replaced my previous PR (#776) with a new one (#970)

**Comment by jah0wl** [comment]
But it actually doesn't run the System commands... they run as user commands. I'm trying to run Newchatmembers Command and it fails because of the $usage solution... And when I say I'm trying, it's not by using /Newchatmembers, but actually adding new members to a group.

**Comment by noplanman** [comment]
@jah0wl I suggest you check how it has been implemented in the [support bot](https://github.com/php-telegram-bot/support-bot).

Having a system command file for each system event was removed and these are now handled by `GenericmessageCommand`. If you want to keep the old way (by having a system command for each, e.g. `NewchatmembersCommand.php`, etc.) you can set a newly introduced `$execute_deprecated` variable in the `SystemCommand` class like this:

```php
SystemCommand::$execute_deprecated = true;
```

**Comment by Cintrust** [comment]
@noplanman the old method of executing system command was much better. any reason for the change. 
secondly this change kinda invalidates the need for class of `SystemCommand`s since each commands are now being called by a set of if statements inside the `GenericmessageCommand`, And adds another complexity add an extra if for each new `SystemCommad` one wish to execute.

**Comment by noplanman** [comment]
The main reason was that it limited commands allowed to be called by users.

So if for example you have a custom command called `/poll`, it wouldn't fire, as there was a `SystemCommand` that would override it. With the current solution, I understand it's a bit more complex in that everything needs to be handled in the `GenericmessageCommand` class, but that also "forces" to organise the code more.
