### ISSUE TITLE
Callback not working in StartCommand

### ISSUE THREAD

**Issue by sergey89d** [php-telegram-bot/core#775]
# **How to get data from callback_data ?**

### Required Information
- Operating system: ubuntu 17.10
- PHP version: php7.1-fpm
- PHP Telegram Bot version: 0.52
- Using MySQL database: yes
- MySQL version: 5.7
- Update Method: Webhook
- Self-signed certificate: yes

### Expected behaviour
In the logs there is an answer, but I dont see him in the bot. And me need save in cookie language code uz or ua.

### Extra details
```php

public function execute()
    {
        $lang = Lang::chooseLang();

        $inlineKeyboard = new InlineKeyboard([
            ['text' => 'Украинский', 'callback_data' => 'ua'],
            ['text' => 'Узбекский', 'callback_data' => 'uz'],
        ]);

        $data = [
            'chat_id' => $this->getMessage()->getChat()->getId(),
            'text' => $lang[ 'choose_lang' ],
            'reply_markup' => $inlineKeyboard
        ];
        Request::sendMessage($data); // its working

        $callbackAnswer = [
            'callback_query_id' => $this->getCallbackQuery()->getId(),
            'text'              => $this->getCallbackQuery()->getData(),
            'show_alert'        => true,
            'cache_time'        => 0
        ];

        return Request::answerCallbackQuery($callbackAnswer); // its not working
        // And i still tried  Request::sendMessage($callbackAnswer); // its not working too
    }
```

**Comment by jacklul** [comment]
Assuming you redirected callbacks to your command (or registered your command as a handler):

When callback query hits posted code it will error out with exception in line ` 'chat_id' => $this->getMessage()->getChat()->getId(),`, `getMessage()` will return null in that case and stop code execution, you have to `if ($this->getMessage()) {} elseif ($this->getCallbackQuery()) {}` those lines.

_PS. Callbacks are generally handled by `CallbackqueryCommand` system command._

**Comment by sergey89d** [comment]
Thanks. I'll try

**Comment by sergey89d** [comment]
`if ($this->getCallbackQuery()) {}` 
This condition does not work

**Comment by jacklul** [comment]
Try putting callback query the code into `CallbackqueryCommand.php` system command instead.

**Comment by sergey89d** [comment]
I dont quite understand how, please show example

**Comment by sergey89d** [comment]
Callback_data has worked. This is good, thx. 
But, many commands will work with callback_data, how to send text in `"text" => here text` ?

**Comment by jacklul** [comment]
The easiest way is to have something on the beggining of the callback data, examples:
```
lang_en
lang_ru
```
then you can `explode('_', $callback_data)` it. This way you can handle different callbacks.

**Comment by sergey89d** [comment]
hm.... good idea. I will use it. Thanks!

**Comment by sergey89d** [comment]
I have another question xD
How do I process these buttons? I need to process their pressing and take their text and after hide the  keyboard. Here you can use a callback ?

For example
```php
 $keyboardButtons = new Keyboard(
            ['text' => 'USA'],
            ['text' => 'UA']
);

$data = [
            'chat_id' => $message->getChat()->getId(),
            'text' => $lang['choose_lang'],
            'reply_markup' => $keyboardButtons
                ->setResizeKeyboard(true)
                ->setOneTimeKeyboard(true)
                ->setSelective(false)
        ];
return Request::sendMessage($data);
````

**Comment by jacklul** [comment]
They send generic text message on press.
`GenericmessageCommand.php` & `$this->getMessage()->getText(true)`

**Comment by sergey89d** [comment]
A next question 😄 
How to hide unnecessary admin commands in bot?
Instead of the admin will sit the operator and he should not know about these commands.
I know about the parameter `$show_in_help = false;`, but can eat another way?

**Comment by jacklul** [comment]
Admin commands doesn't show up if you extended `AdminCommand` class.

**Comment by sergey89d** [comment]
The operator will be like an admin, but he should not know about admin commands

**Comment by jacklul** [comment]
Don't make him an admin then ?
Code your own operator class and on the begining of operator commands make check if the person calling it is an operator.

**Comment by sergey89d** [comment]
It's a long way, maybe there is a shorter?

**Comment by jacklul** [comment]
No better ideas here, sorry

**Comment by sergey89d** [comment]
I have an idea, skip only the necessary commands,but I'm not sure if it works
For example
```php
 $admin_commands = array_filter($commands, function ($command) {
            if(in_array(['command1', 'command2', etc...], $command))) continue;
            return $command->isAdminCommand();
        });
```
