### ISSUE TITLE
command "sendtochannel" not send a message to private channel

### ISSUE THREAD

**Issue by coxa** [php-telegram-bot/core#777]
### Required Information

- Operating system: Mac OS
- PHP version: 7.1.8
- PHP Telegram Bot version: 0.52.0
- Using MySQL database: yes
- MySQL version: 5.7.21
- Update Method: getUpdates
- Self-signed certificate: no
- RAW update (if available): no sorry

### Expected behaviour
me: /sendtochannel
Bot: Insert the channel name: (@yourchannel)
me: @myPrivateChannelName
Bot: Insert the content you want to share: text, photo, audio...
me: ggg
bot: Message will look like this:

gggg
bot: Would you like to post it?
me: yes
bot: Message sent successfully to: @myPrivateChannelName

### Actual behaviour
me: /sendtochannel
Bot: Insert the channel name: (@yourchannel)
me: @myPrivateChannelName
Bot: Insert the content you want to share: text, photo, audio...
me: ggg
bot: Message will look like this:

gggg
bot: Would you like to post it?
me: yes
bot: Message not sent to: @myPrivateChannelName
- Does the channel exist?
- Is the bot an admin of the channel?

### Steps to reproduce
* create a new private channel
* add bot as admin with all privileges except 'bot can add new admins'
* try to use sendtochannel command to your channel

### Extra details
when you'll try change channel privacy to public - than bot will send message to channel

**Comment by noplanman** [comment]
You're sure that the bot is an admin in the group, yes?

**Comment by coxa** [comment]
I'm sure.
I have to try only with one channel.

**Comment by noplanman** [comment]
Have you also tried it with the ID of the channel?

e.g. `/sendtochannel -123456789`

**Comment by coxa** [comment]
I tried it without minus sign.
I'll try it and let you know

**Comment by coxa** [comment]
chat id like -123456789 work fine for private chats

**Comment by noplanman** [comment]
You can also try `/sendtochannel @channel_name` in one message.

Have you by any chance set the command config and added your channel there?

**Comment by coxa** [comment]
Are you mean like this?
`$telegram->setCommandConfig('sendtochannel', ['your_channel' => ['@mychannelname']]);`
I tried this but no luck

**Comment by jacklul** [comment]
Speaking from experience:
@channel_username only work for public channels, for private ones ID must be used. In both cases bot must be channel admin.

If for some reason it doesn't work there is something else going on, try capturing result of the request and `print_r` it (file or console) to see what Telegram API is saying?

**Comment by coxa** [comment]
`object(Longman\TelegramBot\Entities\ServerResponse)#40 (5) {
  ["ok"]=>
  bool(false)
  ["error_code"]=>
  int(400)
  ["description"]=>
  string(27) "Bad Request: chat not found"
  ["raw_data"]=>
  array(3) {
    ["ok"]=>
    bool(false)
    ["error_code"]=>
    int(400)
    ["description"]=>
    string(27) "Bad Request: chat not found"
  }
  ["bot_username"]=>
  string(13) "name_bot"
}`

**Comment by coxa** [comment]
So seems it is just Telegram feature. Will be cool add this knowledge to README.md or somewhere else. I think this issue can be closed.

**Comment by noplanman** [comment]
True, private channels don't have a name. I think when you switch from public to private, the name still works for a while, but then the ID is required.

You can also override the original `/sendtochannel` command to get the channel ID from the database or the command config (by adding your own items), when you try to send using the channel name (which was set when the channel was public). This can be tricky though, especially if you choose to change the channel name at some point. Just trying to find a different solution for you 😊

**Comment by androidformax** [comment]
You may add to channel @myidbot anв get ID with them, and instead of the name @namechannel  use it in the format ID: 
$channel = '-1001144543810';
Code change not needed;

**Comment by noplanman** [comment]
@androidformax We also have our own support bot that can give chat infos.

You can find it here: [@PHP_Telegram_Support_Bot](https://t.me/PHP_Telegram_Support_Bot). You can use the `/id` command there.
