### ISSUE TITLE
Recursively Custom commands calling

### ISSUE THREAD

**Issue by sachin-lalaworld** [php-telegram-bot/core#780]
### Required Information

- Operating system: Ubuntu 17.10
- PHP version: 7.0.1
- PHP Telegram Bot version:^0.52.0
- Using MySQL database:  no 
- MySQL version:
- Update Method: Webhook
- Self-signed certificate: yes
- RAW update (if available):

### Expected behaviour

Created custom commands as per documentation, whenever it calls it should reply back
### Actual behaviour

When custom command called, the command response recursively. I need to stop this. I need response once not many time
### Steps to reproduce

Bot Username - @lalaworld_bot

**Comment by jacklul** [comment]
Your webserver might be replying to webhook with non-200 reply, your code might be returning PHP warning or error - see your webserver logs to check whenever your answers to Telegram are http code 200.

**Comment by sachin-lalaworld** [comment]
Can you please share request format to check on postman by hitting api.

**Comment by sachin-lalaworld** [comment]
I have checked neither error has created nor warnings in web server logs.

**Comment by noplanman** [comment]
@sachin-lalaworld Is this recursion still happening to you?
Sometimes it can happen that Telegram has server issues, which pass by.

**Comment by JONAGUIPER** [comment]
Hello, the same problem is happening to me today and I do not know how to stop it

**Comment by akalongman** [comment]
@JONAGUIPER can you share your code? Also, do you use request logging?
