### ISSUE TITLE
How to handle pre_checkout_query update?

### ISSUE THREAD

**Issue by lutov** [php-telegram-bot/core#781]
### Required Information

- Operating system: CentOS7
- PHP version: 7.1
- PHP Telegram Bot version: 0.52.0
- Using MySQL database: yes
- MySQL version: 5.6
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour

I need the way to handle update types different from "message" which seems to be the only type available in commands. For example how to get pre_checkout_query update from payment system? It doesn't seem to appear in GenericmessageCommand.

### Actual behaviour

When I dump $this->getUpdate() in GenericmessageCommand I get only "message" type.

### Steps to reproduce

Try to implicate payment in bot.

**Comment by lutov** [comment]
Oh, sorry, my bad. It's GenericCommand obviously.

**Comment by jacklul** [comment]
**PreCheckoutQuery** is **Update** object not appearing **Message** object (see Telegram API documentation for reference).

Probably you need to create command called `PrecheckoutqueryCommand`.

**Comment by lutov** [comment]
Yes, I have been confused. Other types of update only triggers GenericCommand, not Generic_message_Command. Thank you.

**Comment by lutov** [comment]
@jacklul 
>GenericCommand catches every command or update type that doesn't have any handler created

So, it's just like that? If name of the command matches update type it will automatically handle this update? Otherwise I'm still not sure how to handle this type of update other then check it in GenericMessage.

**Comment by lutov** [comment]
Oh, that is nice, I didn't expect it to be that simple. Thanks.
