### ISSUE TITLE
Executing commands for multiple users with cron

### ISSUE THREAD

**Issue by lutov** [php-telegram-bot/core#785]
### Required Information

- Operating system: CentOS7
- PHP version: 7.1
- PHP Telegram Bot version: 0.52.0
- Using MySQL database: yes
- MySQL version: 5.6
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour

I want to execute command for different users in cycle. The problem is that command is higly dependant on $this->getMessage(). Originally it was manualy triggering. But command doesn't have this context when executing with cron. It there any way to pass user parameteres to command? Duplicating all code to cron file feels really wrong.

### Actual behaviour

Command executes for bot itself.

**Comment by noplanman** [comment]
You can extract any features you need outside of a command and then just access that from inside the command. Then you don't need to duplicate anything and you can use it everywhere :+1:

**Comment by lutov** [comment]
So, how exactly can I get variables from the outside in the command? I thought it's only possible to access variables within the command scope.

**Comment by lutov** [comment]
OK, I have figured out one way to achieve my goal - to create an update and execute an instance of the command with it.

```
	$update = json_decode($this->update->toJson(), true);

	$update['message']['from']['id'] = $value['user_id'];
	$update['message']['from']['first_name'] = $user['first_name'];
	$update['message']['from']['last_name'] = $user['last_name'];
	$update['message']['from']['username'] = $user['username'];
	$update['message']['chat']['id'] = $value['chat_id'];
	$update['message']['text'] = $command_call;

	(new CompleteCommand($this->telegram, new Update($update)))->preExecute();
```

Is it a proper (or only) way to do it?

**Comment by jacklul** [comment]
Yes, this is the only way currently.

Remember that if something you need to do doesn't have to be a command then don't go this way, you can listen to @noplanman's suggestion and probably create seperated class for doing this.

How is your command very dependent on `getMessage`? You known you can get users from the database, iterate and use `Request` class (remmeber to initialize it manually earlier) to send messages, right?

**Comment by lutov** [comment]
> You known you can get users from the database, iterate and use Request class to send messages, right?

Yes, sure. It so happened that I created some overlay classes for Message entity before demand to use both responces and cron came. Then to change initial data I should be changing all these classes or develop separate cron version of the command. With the custom update I can can actually reuse the same command.
