### ISSUE TITLE
is it possible to get public channel messages to bot

### ISSUE THREAD

**Issue by sunildabhi** [php-telegram-bot/core#787]
i have implemented InlineKeyboard successfully.

i want to display images from public channel when request callback(on button click)

for example if user click on "display images" then i want to display all images from our public channel https://t.me/harismruti (images posted today in channel)

please help me with code, how to do that if it's possible.

**Comment by jacklul** [comment]
Not possible if bot isn't admin on that channel.

**Comment by sunildabhi** [comment]
ok, can i change admin of my current channel to my bot?

and if possible to change admin then how to get images from that?

**Comment by jacklul** [comment]
I think you misunderstood me, bot will have to be admin on the channel you want the images from.

Every new post will be sent to the bot so it can store it (in database for example). Then it's just matter of pulling the data from database and sending to user.

It can't be done a simpler way.

**Comment by sunildabhi** [comment]
my question is for example channel is since 1 year and we regularly upload images to it, now i created bot and it's admin of that channel also now (right now two admin 1. me and 2. bot).

so, how can i get old data or image using php?

**Comment by jacklul** [comment]
I don't think you can fetch old posts.
