### ISSUE TITLE
Chat->getPhoto() returns Array instead ChatPhoto

### ISSUE THREAD

**Issue by vinnik-dmitry07** [php-telegram-bot/core#788]

**Comment by noplanman** [comment]
Hi @3Pi0FomTatuin, please have a look at the official documentation here:
https://core.telegram.org/bots/api#message

You'll see that the `photo` field returns an array of `PhotoSize` objects.

This is the correct behaviour and this array contains all sizes, from smallest to biggest.

**Comment by noplanman** [comment]
Whoops, just totally misread your issue title, sorry!!

Will check this out... :+1:

**Comment by noplanman** [comment]
@3Pi0FomTatuin All good now? Can I close here?

**Comment by akalongman** [comment]
@3Pi0FomTatuin any update?
