### ISSUE TITLE
sendVideo not working

### ISSUE THREAD

**Issue by sunildabhi** [php-telegram-bot/core#790]
### Required Information

- Operating system: Linux
- PHP version: 5.6.30
- PHP Telegram Bot version: 0.52.0
- Using MySQL database: no
- MySQL version:
- Update Method: Webhook
- Self-signed certificate:  no
- RAW update (if available):

### Expected behaviour

it should show youtube video

### Actual behaviour

nothing is happening

### Extra details

            $data = [
                'chat_id' => $chat_id,
            ];

            $data['caption'] = 'Atmiya Yuva Mahotsav 2018';
            $data['parse_mode'] = 'Markdown';
            $data['video'] = 'https://www.youtube.com/watch?v=TmodQMGITZw';

            return Request::sendVideo($data);

**Comment by jacklul** [comment]
https://core.telegram.org/bots/api#sendvideo

Link must be direct link to MP4 file, it won't work with YouTube links, you can instead send it with `sendMessage`.
