### ISSUE TITLE
Save super group message in mysql

### ISSUE THREAD

**Issue by IranDeveloper** [php-telegram-bot/core#791]
hi all
i disable privacy mod, but GenericCommand work with '/' 
i need get all message from group and super group.
can i save messages not started with '/' in mysql?

**Comment by IranDeveloper** [comment]
hi please help me how can i get command start without / in private chat in group and super group?

**Comment by jacklul** [comment]
`GenericmessageCommand` is what your looking for.

**Comment by IranDeveloper** [comment]
hi jackul
thank you for help 
i use GenericmessageCommand  and work successful but 
how can i undestand other command like /sendtochannel and /survey not runing ?

for example user type /survey  and type name 

> finish

and in GenericmessageCommand  i handle 

> 'finish'

**Comment by jacklul** [comment]
Use conversation feature, check readme.

**Comment by IranDeveloper** [comment]
thank you jacklul

`Use conversation feature, check readme. `
Do you mean checking the code?

and i can not understand what is botan?


i use $telegram->enableBotan('your_token');
and use `Botan::shortenUrl('https://github.com/php-telegram-bot/core', $user_id);` in ShortenerCommand.

output : 

> https://github.com/php-telegram-bot/core
> GitHub
> php-telegram-bot/core
> core - PHP Telegram Bot based on the official Telegram Bot API
