### ISSUE TITLE
how to run a command from another command 

### ISSUE THREAD

**Issue by shoxabbos** [php-telegram-bot/core#794]
How can I run a command for user, when it's in another command? e.g user is in survey command and I want when user finish the survey, the /start command automatically run for him.

**Comment by jacklul** [comment]
```$this->getTelegram()->executeCommand('start');```

**Comment by shoxabbos** [comment]
I already tried it so it does not work like this ((

**Comment by jacklul** [comment]
If `/start` can be executed normally then there should be no reason `executeCommand('start');` wouldn't work...

**Comment by akalongman** [comment]
Jacklul's solution is working :+1: 

@shoxabbos did you solved your problem?

**Comment by shoxabbos** [comment]
Yes, I understood how it works. ))

**Comment by shoxabbos** [comment]
I tried to run a command from CallbackqueryCommand.

**Comment by jacklul** [comment]
You gotta always remember that those are two different updates that carry different objects, you always have to prepare your code when you want to executed "message" command on callback query button press.

**Comment by shoxabbos** [comment]
Many thanks
