### ISSUE TITLE
how to request input from user?

### ISSUE THREAD

**Issue by saeedghafar** [php-telegram-bot/core#796]
I know how to use telegram commands, and know how to read what command has been executed. What I would like to do is something like this:

> User: /send_address
Bot: Hello, please type your address..
User: my address...
Bot:Thanks

how can do ?

**Comment by noplanman** [comment]
Have a look at the sample `/survey` command in the example-repo.

https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php
