### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#797]
Hi everyone!
I want to use lib inside of clear Laravel project. And I have some questions about that.

1. What should my routes file (/routes/web.php) look like? To set webhook, commands path, commands handler, etc.
2. Where can I create my commands Controller? And what name should I use? SurveyCommandController.php?
3. What should the command Controller look like? For example, I need a survey command, should I use execute method in my Controller?

**Comment by akalongman** [comment]
@MyZik I plan to add Laravel integration to this package, but before

> What should my routes file (/routes/web.php) look like? To set webhook, commands path, commands handler, etc.

Its everything up to you, you are not limited.

> Where can I create my commands Controller? And what name should I use? SurveyCommandController.php?

Same here. just create `TelegramController` and add methods mapped to routes, or create separate controllers for each command.

> What should the command Controller look like? For example, I need a survey command, should I use execute method in my Controller?

Yes

**Comment by MyZik** [comment]
@akalongman still there is no full Laravel-support of the library?  It seems to me that a separate package would look cool

**Comment by sergey89d** [comment]
i found this https://github.com/irazasyed/telegram-bot-sdk

**Comment by akalongman** [comment]
Official Laravel integration for this library will be added soon

**Comment by MBoretto** [comment]
@akalongman How you think to integrate the database migrations in the laravel framework?
@MyZik  https://github.com/MBoretto/Nostickers

**Comment by akalongman** [comment]
@MBoretto I am still thinking about that

**Comment by ranrinc** [comment]
@akalongman I hope the package will come in soon... wanted to do it badly.. hahahaha

**Comment by akalongman** [comment]
@ranrinc yes, yes. Do you want to help with testing?

**Comment by akalongman** [comment]
Ok guys, here we go https://github.com/php-telegram-bot/laravel

Do not forget that its pre-release and may be bugs :) Please help us in testing and let us know what we should fix or improve
