### ISSUE TITLE
sendtochannel not work with photo or video

### ISSUE THREAD

**Issue by IranDeveloper** [php-telegram-bot/core#798]
```
TelegramBot version: 0.52.0
Download path: /home/pebg/public_html/bots/core-master/Download/
Upload path: /home/pebg/public_html/bots/core-master/Upload/
Commands paths:
[
    "/home/pebg/public_html/bots/core-master/Commands/",
    "/home/pebg/public_html/bots/core-master/src/Commands/SystemCommands",
    "/home/pebg/public_html/bots/core-master/src/Commands/AdminCommands"
]
PHP version: 5.6.22 (64bit); litespeed; Linux
Maximum PHP script execution time: 60 seconds
MySQL version: 5.6.38
Operating System: 
Web Server: LiteSpeed
curl version: 7.58.0; OpenSSL/1.0.1e
```

`    $telegram->enableAdmin(220130139);
    $telegram->setCommandConfig('sendtochannel', ['your_channel' => ['@MyChannel','@MyChannel2']]);`

I type /sendtochannel and bot send message :

> Select a channel from the keyboard:
I select @MyChannel

bot send message :
> Insert the content you want to share: text, photo, audio...
if i type text work successful but, if I send photo or video bot say :

> Would you like to insert a caption?
I type Yes

bot send message :
> Insert caption:
I send Test 

bot send message :
> Message will look like this:

Then nothing happens until but when I type No and bot send message :
> Abort by user, message not sent..

If type Yes nothing happens.

Please Help Me.

**Comment by IranDeveloper** [comment]
Please help me I can not resolve my problem.

**Comment by IranDeveloper** [comment]
Please help me

**Comment by jacklul** [comment]
Any logs? Enable full PHP logging.

**Comment by IranDeveloper** [comment]
Hi jacklul

**Comment by jacklul** [comment]
Does normal text messages work though ?

@php-telegram-bot/developers

**Comment by noplanman** [comment]
This is due to the change to `__callStatic` usage instead of explicit methods, meaning that PHP can't find a valid method called `sendPhoto` (for example), so it fails.

I'm on a fix as I type this :+1:
