### ISSUE TITLE
Example of payments

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#800]
Hi everyone!

I tried to use payments system inside of my Telegram bot.

1. How should the invoice be displayed to the user?
2. Is there an example of a payments callback? For example, I paid 1$ and get 100 coins in my bot :smile:

Thanks in advance!

**Comment by noplanman** [comment]
I don't have any working example for you, but you can test all the payment things using a dummy credit card number, look here:
https://core.telegram.org/bots/payments#testing-payments-the-stripe-test-mode-provider

**Comment by noplanman** [comment]
@MyZik Have you given this a try? Maybe you can now share an example of your own?

**Comment by MyZik** [comment]
No, that was not need :(



Отправлено из мобильной Почты Mail.Ru


четверг, 12 апреля 2018 г., 22:24 +0300 от notifications@github.com  <notifications@github.com>:
