### ISSUE TITLE
Telegram Bot doesn't respond messages

### ISSUE THREAD

**Issue by Gsere** [php-telegram-bot/core#804]
Maybe this helps someone.

If you have been programming commands and suddenly your bot stops responding, verify that the last command that you have copied to the command directory does not have bugs.

It has happened to me that a bug in one command blocks the execution of all the others.
I think the reason is that even if you have requested the execution of a command, the bot (hook.php) loads all the commands available prior to executing the requested command.

A bug in any command stops the bot completely, even if the other commands come working correctly.

For this reason is a very bad idea to write a new command inside the /Commands directory directly.

**Comment by noplanman** [comment]
Yes, this is true. Thanks for pointing this out for new people :+1:
