### ISSUE TITLE
User authentication using channel

### ISSUE THREAD

**Issue by supersh86** [php-telegram-bot/core#807]
hello
How to make bot work only for channel subscribers?

I have the code.

```php
$infochat = Request::getChatMember(['chat_id'=> '@channelname', 'user_id'=> 'userid']);
$infochatarr =  json_decode($infochat, true);

if ($infochatarr['result']['status'] == 'left') {
    $infos = [
        'chat_id' => 'userid',
        'text' => 'please subscribe to @channelname'
    ];
    Request::sendMessage($infos);
}
```

Now I need to understand how to block the work of the bot while the user does not subscribe to the channel.

**Comment by jacklul** [comment]
Best solution would be to extend `Telegram` class and add filtering logic to `processUpdate` method.

**Comment by supersh86** [comment]
please example

**Comment by akalongman** [comment]
@supersh86 there is a good example by @jacklul https://github.com/php-telegram-bot/core/issues/792#issuecomment-369743676

**Comment by minhvn** [comment]
Is it still working?
$infochat = Request::getChatMember(['chat_id'=> '@channelname', 'user_id'=> 'userid']);
Im using that for chat user has join group but in return chat not found :(

**Comment by KraToS-zz** [comment]
> 
> 
> @supersh86 there is a good example by @jacklul [#792 (comment)](https://github.com/php-telegram-bot/core/issues/792#issuecomment-369743676)

Can you send a working example for this ? i dont get it :-(

**Comment by noplanman** [comment]
@KraToS-zz What exactly don't you understand with the example that @jacklul posted?

You can create a new file with that code in it and then use `new TelegramBot` instead of `new Telegram` in your webhook or getUpdates.
