### ISSUE TITLE
executeCommand  error

### ISSUE THREAD

**Issue by a1994n1373** [php-telegram-bot/core#821]
hi .
when i want use executeCommand get this error : 
  PHP Fatal error:  Uncaught Error: Call to a member function getChat() on null

my callbackquery file : 

```
    public function execute()
    {
        $callback_query = $this->getUpdate()->getCallbackQuery();
        $chat_id = $callback_query->getFrom()->getId();
        $query_id = $callback_query->getId();
        $query_data = $callback_query->getData();

        if ($query_data = "test") {
                return $this->telegram->executeCommand('help');
        }
    }
```

please help me . best regards .

**Comment by jacklul** [comment]
Your help command expects message object.

When you call it from callbackquery message object is not present.

**Comment by a1994n1373** [comment]
thanks jacklul .
i just use StartCommand for example .
how i can fix it ?

**Comment by jacklul** [comment]
Easiest would be to check within help command if it's a callbackquery and get chat id from query instead of message.

**Comment by a1994n1373** [comment]
i'm newbie in php-telegram-bot .
if you can please tell me how i can send chatid and form id with executeCommand ?

**Comment by a1994n1373** [comment]
i fixed my problem with : 

https://github.com/php-telegram-bot/core/issues/631#issuecomment-329164101
