### ISSUE TITLE
Blocked Telegram in Russia

### ISSUE THREAD

**Issue by PallacHH** [php-telegram-bot/core#822]
As you know, telegrams were blocked in Russia and this caused difficulties in working with the bot. Can I add a proxy to the core when I request it?

**Comment by jacklul** [comment]
https://github.com/php-telegram-bot/core/issues/667#issuecomment-334851805

**Comment by PallacHH** [comment]
I can edit it only in files libary or i can Request::setClient(new \GuzzleHttp\Client([
                'base_uri' => 'https://api.telegram.org',
                'proxy' => 'http://proxy',
            ])); ?

**Comment by NovikovRoman** [comment]
```
...
$telegram = new Telegram($apiKey, $botName);
Request::setClient(new \GuzzleHttp\Client([
        'base_uri' => 'https://api.telegram.org',
        'proxy' => 'http://111.111.111.111:1080',
]));
...
```

**Comment by PallacHH** [comment]
Thanks

**Comment by noplanman** [comment]
As @jacklul already mentioned, just set the proxy client before handling the request.

Here is an example for using a local Tor proxy with SOCKS5:
```php
$telegram = new Telegram(...);
...
Request::setClient(new Client([
    'base_uri' => 'https://api.telegram.org',
    'proxy'    => 'socks5://127.0.0.1:9050',
]));
...
$telegram->handle();
```

**Comment by kirush0280** [comment]
set.php:
try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($API_KEY, $BOT_NAME);

    $telegram = Request::setClient(new \GuzzleHttp\Client([    'proxy'    => 'socks5://alex:xxxx@xxx.xxx.240.10:8088',]));

    // Set webhook
    $result = $telegram->setWebhook($hook_url);

    // Uncomment to use certificate
    //$result = $telegram->setWebhook($hook_url, ['certificate' => $path_certificate]);

...
PHP Fatal error:  Uncaught Error: Class 'Request' not found in var/www/help.xxx.net/xxx/telegram/set.php:12

How to enable it right?

**Comment by akalongman** [comment]
@kirush0280 

1. You have to import `Request` class first
2. You do not need assign `Request::setClient` call to `$telegram` variable

**Comment by kirush0280** [comment]
Thank you. It works.

**Comment by 31337Ghost** [comment]
Also when your DNS traffic is spoofed you should to use `'proxy'    => 'socks5h://` against `socks5://` whithout **h**

**Comment by timurkayzer** [comment]
Hi! @akalongman would you please tell what kind of Request it is, from which library?

**Comment by akalongman** [comment]
@timurkayzer 

`\Longman\TelegramBot\Request`

**Comment by frozencodeuz** [comment]
thanks it worked like a charm!
