### ISSUE TITLE
Get live location user 

### ISSUE THREAD

**Issue by 2pai** [php-telegram-bot/core#829]
hi , is that possible to get live location user after user send current live location ?

**Comment by MyZik** [comment]
Yeap, you can get coordinates of user's location.
https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php

**Comment by akalongman** [comment]
@2pai did you figured out how to get the live location?

**Comment by eugenee** [comment]
I didn't find solution in topics, so I just put my way here
I've added columns _`latit`_, _`longit`_ to table **edited_message**
than here
https://github.com/php-telegram-bot/core/blob/b6ea355a4d16e8b1879b6a485d664a6a5a9c6ea3/src/DB.php#L1188
I add values of coordinate location
            $edited_message->getLocation()->getLatitude()
            $edited_message->getLocation()->getLongitude()

so it looks like
            ```
$sth = self::$pdo->prepare('
                INSERT IGNORE INTO `' . TB_EDITED_MESSAGE . '`
                (`chat_id`, `message_id`, `user_id`, `edit_date`, `text`, `entities`, `caption`,`latit`,`longit`)
                VALUES
                (:chat_id, :message_id, :user_id, :edit_date, :text, :entities, :caption, :latit, :longit)
            ');

            $user_id = $user ? $user->getId() : null;

            $sth->bindValue(':chat_id', $chat->getId());
            $sth->bindValue(':message_id', $edited_message->getMessageId());
            $sth->bindValue(':user_id', $user_id);
            $sth->bindValue(':edit_date', $edit_date);
            $sth->bindValue(':text', $edited_message->getText());
            $sth->bindValue(':entities', self::entitiesArrayToJson($edited_message->getEntities() ?: []));
            $sth->bindValue(':caption', $edited_message->getCaption());
            $sth->bindValue(':latit', $edited_message->getLocation()->getLatitude());
            $sth->bindValue(':longit', $edited_message->getLocation()->getLongitude());
            return $sth->execute();
```
And you will get coordinate inside edited_message table with _message_id_
