### ISSUE TITLE
Send Message to certain user_id

### ISSUE THREAD

**Issue by andibastian** [php-telegram-bot/core#834]
How bot can send message to certain user ?

Here is my code : 
$from       = $message->getFrom();
$user_id    = $from->getId();

$message='Halloooo ';

$data = [ 
'chat_id' => $chat_id,
'text'    => $message, 
'parse_mode' => 'markdown',
];        
return Request::sendMessage($data);   

i'm confuse how to do that..

**Comment by jacklul** [comment]
chat id = user id

Remember that bots cannot start conversation with people, they have to message them first.

**Comment by andibastian** [comment]
@jacklul , so chat_id is same as user_id ? and i can replace it with user_id number ?

**Comment by jacklul** [comment]
Yes, for private one-on-one chats that number is the same.
