### ISSUE TITLE
Re-connecting to the database [HELP]

### ISSUE THREAD

**Issue by filipemansano** [php-telegram-bot/core#843]
on the server I use has a time limit for 15 seconds connection, I can not change this...
and my bot take more than 15 seconds to process an specific item in conversation..
consequently on call update crash the application

PHP Fatal error: Uncaught Longman\\TelegramBot\\Exception\\TelegramException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /vendor/longman/telegram-bot/src/DB.php:1189

how could I do it in DB.php for when this error recreates the connection?

**Comment by jacklul** [comment]
You might've luck extending PDO and writing reconnect logic there then initializing DB connection using your own PDO proxy class.

**Comment by filipemansano** [comment]
@jacklul i create a class and enable External Mysql, for the query and exec command in PDO works, but when use prepared Statement not work :(

```
$pdo = new BetterPDO(... connections parameters);
$telegram->enableExternalMySql($pdo);
```

```
class BetterPDO
{
	protected $dsn, $username, $password, $pdo, $driver_options;

	const RETRY_ATTEMPTS = 3;

	public function __construct($dsn, $username = "", $password = "", $driver_options = array()) {
		$this->dsn = $dsn;
		$this->username = $username;
		$this->password = $password;
		$this->driver_options = $driver_options;

		$this->connect();
	}

	public function __call($method, $arguments){

		$retry = 0;
		try_again:

		try {
			return call_user_func_array(array($this->pdo, $method), $arguments);
		} catch(\Exception $e) {

			if($retry >= self::RETRY_ATTEMPTS || $e->getCode() != 'HY000' || !stristr($e->getMessage(), 'server has gone away')) {
				throw $e;
			}

			++$retry;
			$this->reconnect();
			goto try_again;
		}
	}

	public function connect() {
		$this->pdo = new \PDO($this->dsn, $this->username, $this->password, (array) $this->driver_options); 
		$this->pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
		return $this->pdo;
	}

	public function reconnect() {
		$this->pdo = null;
		return $this->connect();
	}
}
```
