### ISSUE TITLE
Looking for help to refactor callbackquery commands

### ISSUE THREAD

**Issue by sineverba** [php-telegram-bot/core#848]
Hi to all,
I'm working on implementation of TelegramBOT to control Domoticz (a domotic webapp).

The bot works very well, but I'm looking for your help to understand if I could perform better the callbackquery answers.

Preamble: development branch, not master.

On my webhook (https://github.com/sineverba/domapi/blob/development/app/models/Telegram/TelegramWebHook.php) I have this callback handle:

```
\Longman\TelegramBot\Commands\SystemCommands\CallbackqueryCommand::addCallbackHandler(function (\Longman\TelegramBot\Entities\CallbackQuery $query) use($telegram) {
						
				$callback_data = $query->getData();
				switch ( $callback_data ) {
					
					case "getlistsensor":
								
						$telegram->executeCommand('getsensor');
																
					break;
							
					case "getlistswitch":
								
						$telegram->executeCommand('getswitch');
																
					break;
							
					default:
								
						if (strpos($callback_data, "sensor_") === 0) { // se non inizia con sensor_ ... trova la prima occorrenza, e deve essere a zero
						
							$telegram->executeCommand('getsensor');
							
						}
								
						if (strpos($callback_data, "rele_") === 0) { // se non inizia con sensor_ ... trova la prima occorrenza, e deve essere a zero
						
							$telegram->executeCommand('getswitch');
									
						}
								
						if (strpos($callback_data, "level_") === 0) { // se non inizia con sensor_ ... trova la prima occorrenza, e deve essere a zero
						
							$telegram->executeCommand('getswitch');
									
						}
								
					break;
							
				}
						
			});
			
			/*** / callback *******/
```

Leaving outside the meaning of every command, I can notice that adding another callback (taken from https://github.com/sineverba/domapi/blob/development/app/models/Telegram/Commands/DomoticzCommand.php ) will add another test inside switch.

I did try to follow others issues, but this method is the only one that I got working.

So, question is... can I perform better this? 

Thank you very much in advance!

**Comment by sineverba** [comment]
Sorry for the up, but I would have clean code as much possible :)

I'm doing my homework and trying this, from #436 

I did change in CategoryCommand the namespace, inside UserCommands, and it works very well.

```
<?php

namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\InlineKeyboard;
use Longman\TelegramBot\Entities\InlineKeyboardButton;
use Longman\TelegramBot\Request;

class CategoryCommand extends UserCommand
{
    protected $name = 'category';
    protected $description = 'Choose a category, inline.';
    protected $usage = '/category';
    protected $version = '1.0.0';

    /** @var array Inline button categories (can also be dynamically generated) */
    public static $categories = [
        'apple'  => 'Yay, an apple!',
        'orange' => 'Sweetness...',
        'cherry' => 'A cherry on top.',
    ];

    public function execute()
    {
        $keyboard_buttons = [];
        foreach (self::$categories as $key => $value) {
            $keyboard_buttons[] = new InlineKeyboardButton([
                'text'          => ucfirst($key),
                'callback_data' => 'category_' . $key,
            ]);
        }
        $data = [
            'chat_id'      => $this->getMessage()->getChat()->getId(),
            'text'         => 'Choose a category:',
            'reply_markup' => new InlineKeyboard($keyboard_buttons),
        ];

        return Request::sendMessage($data);
    }
}
```

Issue coming copying the CallbackqueryCommand (I edited, to match the namespace and the commands on top of file)

```
<?php

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\Commands\CategoryCommand;
use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;

class CallbackqueryCommand extends SystemCommand
{
    protected $name = 'callbackquery';
    protected $description = 'Reply to callback query';
    protected $version = '1.0.0';

    public function execute()
    {
        $update         = $this->getUpdate();
        $callback_query = $update->getCallbackQuery();
        $callback_data  = $callback_query->getData();

        // Only do something for the 'category' selection.
        if (strpos($callback_data, 'category_') !== 0) {
            return Request::emptyResponse();
        }

        // Get the real category from the callback_data.
        $category = substr($callback_data, strlen('category_'));

        return Request::editMessageText([
            'chat_id'    => $callback_query->getMessage()->getChat()->getId(),
            'message_id' => $callback_query->getMessage()->getMessageId(),
            'text'       => CategoryCommand::$categories[$category],
        ]);
    }
}
```
PHP complains for (of course)  `Fatal error: Cannot declare class Longman\\TelegramBot\\Commands\\SystemCommands\\CallbackqueryCommand, because the name is already in use`

So, I cannot delete the command in vendor folder (I didn't try also, I know next update it will be there). How do this? 

Changing command Callbackquery produce no results at all.

Thank you very much

**Comment by sineverba** [comment]
Made some other progress...

First of all, I did try to extend the Callbackquery. no more error of duplicated class but no answer at all.

Looking for original CallbackqueryCommand.php in vendor folder, I did notice the callbacks property.

So, I did copy and paste in my Command folder the CallbackqueryCommand.php and added my button callback data inside that property:

```
<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;

/**
 * Callback query command
 */
class CallbackqueryCommand extends SystemCommand
{
    /**
     * @var callable[]
     */
    protected static $callbacks = ['getsensorlist'];

    /**
     * @var string
     */
    protected $name = 'callbackquery';

    /**
     * @var string
     */
    protected $description = 'Reply to callback query';

    /**
     * @var string
     */
    protected $version = '1.0.0';

    /**
     * Command execute method
     *
     * @return mixed
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        //$callback_query = $this->getUpdate()->getCallbackQuery();
        //$user_id        = $callback_query->getFrom()->getId();
        //$query_id       = $callback_query->getId();
        //$query_data     = $callback_query->getData();

        // Call all registered callbacks.
        foreach (self::$callbacks as $callback) {
            $callback($this->getUpdate()->getCallbackQuery());
        }

        return Request::answerCallbackQuery(['callback_query_id' => $this->getUpdate()->getCallbackQuery()->getId()]);
    }

    /**
     * Add a new callback handler for callback queries.
     *
     * @param $callback
     */
    public static function addCallbackHandler($callback)
    {
        self::$callbacks[] = $callback;
    }
}

```

Now, I got a `call to undefined function getsensorlist()`. I did try to add a simple GetsensorlistCommand.php in my folder but I got the same error.

Any idea? :(

**Comment by sineverba** [comment]
Up :) Any help is appreciated :)

**Comment by noplanman** [comment]
Hi, hope to help :blush: 

Is the `getsensorlist` function defined?
Maybe you forgot to define the class it lives in?

**Comment by sineverba** [comment]
Thank you for your answer! Happy to see around here :)

Are you referring to mine last try? Do I need to create a GetsensorlistCommand.php, all right? Or a class (what name?) with that function?

Because I  I did try to add a simple GetsensorlistCommand.php in my folder but I got the same error.

**Comment by noplanman** [comment]
Yes, I'm referring to your last try where you call `getsensorlist`.
Are you sure you have that method / function defined somewhere?

**Comment by sineverba** [comment]
No, I don't have (anymore) that method defined. I did try to add a simple GetsensorlistCommand.php in my folder but I got the same error.

This is the folder with command: https://github.com/sineverba/domapi/tree/master/app/models/Telegram/Commands

For the moment, the last try is not present (neither in development). Please, can you make me a simplest example of a class with that stub command inside?

**Comment by Hitmare** [comment]
i don't unterstand the part where you have added this 
```/**
     * @var callable[]
     */
    protected static $callbacks = ['getsensorlist'];```

you defined the variable `$callbacks` with the an singly array value. 
then you do a foreach loop with this single value 

What did you try to achieve?

**Comment by sineverba** [comment]
@Hitmare It was a try, that I cannot have my goal.

I'm stucked to very first one code (this, to undestand: https://github.com/sineverba/domapi/blob/master/app/models/Telegram/TelegramWebHook.php )

It works, but I would refine and render more light and understable.
