### ISSUE TITLE
Handle dynamical callbacks

### ISSUE THREAD

**Issue by ashvechikov** [php-telegram-bot/core#849]
### Required Information

- Operating system:
- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes / no
- MySQL version:
- Update Method: Webhook / getUpdates
- Self-signed certificate: yes / no
- RAW update (if available):

### Expected behaviour

Hi! I have a problem with handle my callbacks.
I have a class Order. (execute method)
```php
public function execute()
    {
        $message = $this->getMessage();
        $from = $message->getFrom();
        $user_id = $from->getId();
        $chat_id = $message->getChat()->getId();

        $orders = DB::getOrders($user_id);


        $items = array_map(function ($o)
        {
            return
                [
                    'text'          => $cat['v_info'],
                    'callback_data' => 'order_' . $cat['id'],
                ];
        }, $orders);

        $max_per_row  = 2; // or however many you want!
        $per_row      = sqrt(count($items));
        $rows         = array_chunk($items, $per_row === floor($per_row) ? $per_row : $max_per_row);
        $reply_markup = new InlineKeyboard(...$rows);

$data =
            [
                'chat_id' => $chat_id,
                'text' => 'Choose order:',
                'reply_markup' => $reply_markup
            ];
        return Request::sendMessage($data);
    }
```
After this telegram shows array of inline buttons
It's OK!

But , how can i handle my callbacks

This is general part 'order_'
But , for example '87453' it is can be too many values.

How can i handle it??

all my orders i save in database.

**Comment by Hitmare** [comment]
Use the CallbackqueryCommand.php from the Example bot to handle your callbacks

there you can use 
``` $order_id = str_replace("order_", "",$callback_data); ````
to get your order id

**Comment by noplanman** [comment]
@ashvechikov Did you try what @Hitmare suggested? Is it working for you?
