### ISSUE TITLE
Cannot use Request::getMemberChat

### ISSUE THREAD

**Issue by minhvn** [php-telegram-bot/core#853]
I make a request in Generic Command:
$dba = ['chat_id' => NUMBER, 'user_id' => userId];
$chatUser = Request::getChatMember($dba);
userId: Im uid in group with id is Number.
My bot is admin this group.

=> Resule object:

Longman\TelegramBot\Entities\ServerResponse":5:{s:2:"ok";b:0;s:10:"errorcode";i:400;s:11:"description";s:27:"Bad Request: chat not found";s:8:"rawdata";a:3:{s:2:"ok";b:0;s:10:"errorcode";i:400;s:11:"description";s:27:"Bad Request: chat not found";}s:12:"botusername";s:17:"MYBOT"}/

Please help me.
Thank guys.

**Comment by jacklul** [comment]
Chat ID might be incorrect.

**Comment by minhvn** [comment]
I chat in that group, and got CHATID.

**Comment by jacklul** [comment]
Note that this method works only in SUPERGROUPS.

**Comment by minhvn** [comment]
Yes, sure, I got from chat table in datatabases, and type  => supergroup, but it notwork :( please help me.

**Comment by jacklul** [comment]
If you're sure that ID is correct, the group is supergroup, bot is in that group, has admin permissions and still getting this issue you should be asking @BotSupport on Telegram for help.

**Comment by minhvn** [comment]
Hic, I join https://t.me/BotTalk and member talk "there is no method getMemberChat"

**Comment by minhvn** [comment]
I see telethon have function GetParticipantsRequest but didn't here.

**Comment by minhvn** [comment]
I resolve to collect user from user chat, event new chat member :)
Thank you very much.
