### ISSUE TITLE
getFrom() in Callbackquery return bot ID, how to retrieve user id ? 

### ISSUE THREAD

**Issue by Britskiy** [php-telegram-bot/core#856]
In example file CallbackqueryCommand.php:
This code return only bot id
`$this->getCallbackQuery()->getMessage()->getFrom()->getId()`
How to get user id or whole user object? 

### Required Information

- Operating system:
- PHP version: 7
- PHP Telegram Bot version: 0.53
- Using MySQL database: no
- Update Method: Webhook
- Self-signed certificate: yes

**Comment by volandku** [comment]
Same situation, did you found decision?

**Comment by Britskiy** [comment]
@volandku At the moment of my post I used next code: 
`$from = $this->getCallbackQuery()->getFrom()->getId();`
