### ISSUE TITLE
Add Chat Action constants

### ISSUE THREAD

**Issue by smoqadam** [php-telegram-bot/core#858]
Sending chat actions would be like below to prevent from future mistakes like typos: 

```
Request::sendChatAction([
        'chat_id' => $chat_id, 
        'action' => Longman\TelegramBot\Telegram::ACTION_TYPING
]);
 ```

**Comment by akalongman** [comment]
We have plans for improving the code. Thank you for the good suggestion :+1: 

Btw, feel free to submit PR :heart:

**Comment by smoqadam** [comment]
@akalongman Thanks. I sent a pull request. take a look at #859

**Comment by noplanman** [comment]
Thanks again for this @smoqadam :tada:
