### ISSUE TITLE
Add Forward to chat code

### ISSUE THREAD

**Issue by Nanoteck47** [php-telegram-bot/core#863]
Hi. I have a button created with an array under a message with a callbackquery -> /share. I would like to can forward that message once I click the button to other chats like telegram do. Is there a way?

### Required Information
- Operating system:
- PHP version:7
- PHP Telegram Bot version:
- Using MySQL database: yes
- MySQL version:
- Update Method: Webhook
- Self-signed certificate: yes / no
- RAW update (if available):

**Comment by jacklul** [comment]
No.

**Comment by Nanoteck47** [comment]
And how should I use it?

**Comment by jacklul** [comment]
You would have to use inline mode to generate the message again, somehow.
