### ISSUE TITLE
Send chat action automatically

### ISSUE THREAD

**Issue by smoqadam** [php-telegram-bot/core#864]
Sending chat action automatically by calling any `send...` command. for example the following command send `typing...` chat action:

```php
$result = Request::sendMessage([
    'chat_id' => $chat_id,
   'sendChatAction' => true,
    'text'   => 'test',
]);
```

**Comment by noplanman** [comment]
@smoqadam I like this idea!
We'd have to establish a safe way of passing the value though, as the `$data` array is what gets sent to the Telegram API. So we'd either have to make sure that it is a key that will *never* be used by Telegram, or (and maybe better), have an extra parameter for `$extras` like this.

@php-telegram-bot/developers 
What do you guys think about this?
Do you use the chat actions often enough to make this a necessary / 'makes sense' addition?

**Comment by jacklul** [comment]
As API says it should only be used if bot is about to do something that is gonna take some time, it should definitely not be default behaviour.

**Comment by noplanman** [comment]
@jacklul It isn't default! That's why it would be passed as an extra parameter :+1:

**Comment by smoqadam** [comment]
@jacklul @noplanman 
you mean like this?
```php
Request::sendMessage([
    'chat_id' => $chat->getId(),
    'text' => 'test'
], ['sendChatActiob'=>true]);
```

**Comment by noplanman** [comment]
@chuv1 I like things that make it easier for the user, but I agree with you that it's a question of adding a single line to send the chat action separately.

I do see the advantage of the parameter though, to easily define a long operation with a boolean and have the chat action be managed automatically, without any extra `if` or anything.

@smoqadam Yes, something like that was in my head. Haven't checked to see if that makes complete sense, but it should do the trick i think.
Before coding more, let's first establish that it's something that would be merged in the first place :blush:

**Comment by jacklul** [comment]
Actually, @chuv1 is right.

**Comment by noplanman** [comment]
Aah... Of course... I read his comment wrongly.
Of course it should be sent as the request comes in, not out.

**Comment by noplanman** [comment]
So all ok to close this then?

@smoqadam Thanks a lot for the idea though! Keep them coming :+1:

**Comment by smoqadam** [comment]
@noplanman no problem.

 I'm glad I to be helpful if I can
