### ISSUE TITLE
communicate with bot with plain text not with commands

### ISSUE THREAD

**Issue by smoqadam** [php-telegram-bot/core#867]
Hi guys,

I want to make a bot to interact with me with plain text. in other words **I want to send my commands to bot without `/` at the start.** 

for example:

```
me: Hi
bot: Hi there
me: what's up?
bot: not much.
```
or sending a file link like this `http://example.com/a.mp3` to bot and it download and send it to me:

I want this process without using command like this:
```
/downlaod http://example.com/a.mp3
```

is there anyway to do this now, or it must be implemented?

**Comment by noplanman** [comment]
@smoqadam I assume you managed to solve this?
