### ISSUE TITLE
AdminCommands are loaded/executed although I'm no admin

### ISSUE THREAD

**Issue by xiokax** [php-telegram-bot/core#873]
Hello,
my commands are stored under ./Commands.
my admin commands are stored under ./Commands/AdminCommands
They're loaded as shown in the example bot:

```
$commands_paths = [
    __DIR__ . '/Commands/',
];
.....
$telegram = new Longman\TelegramBot\Telegram($bot_api_key, $bot_username);
$telegram->addCommandsPaths($commands_paths);
```

I have an empty list of admin users ($telegram->enableAdmins([]))
and a simple Echo Command (taken from example-bot) that extends AdminCommand and is stored under ./Commands/AdminCommands/AdminEchoCommand.php.

First, when I use /help, the "AdminEchoCommand" is shown under Admin Commands List: section. I supposed it won't be shown since my user id is not in the admins array.

Moreover, I can execute the admin command and I receive a valid result.

Did I make any mistakes? How can I restrict AdminCommands to admins only?

Best regards
xiokax

**Comment by noplanman** [comment]
Can you post your `AdminEchoCommand.php` file please?

**Comment by xiokax** [comment]
Oh, sure!
```
<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Request;
use Longman\TelegramBot\Commands\AdminCommand;

/**
 * User "/echo" command
 *
 * Simply echo the input back to the user.
 */
class AdminEchoCommand extends AdminCommand
{

    /**
     *
     * @var string
     */
    protected $name = 'adminecho';

    /**
     *
     * @var string
     */
    protected $description = 'Show text';

    /**
     *
     * @var string
     */
    protected $usage = '/adminecho <text>';

    /**
     *
     * @var string
     */
    protected $version = '1.1.0';

    /**
     * Command execute method
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        $message = $this->getMessage();
        $chat_id = $message->getChat()->getId();
        $text = trim($message->getText(true));
        if ($text === '') {
            $text = 'Command usage: ' . $this->getUsage();
        }

        $data = [
            'chat_id' => $chat_id,
            'text' => $text
        ];

        return Request::sendMessage($data);
    }
}
?>
```

**Comment by chuv1** [comment]
It is correct behavior, since your command is under `UserCommands` namespace
`namespace Longman\TelegramBot\Commands\UserCommands;`

**Comment by xiokax** [comment]
D'oh! Checked code(s) & structure X times and didn't see it. My focus lied on the extends part. Thank you! 

However, as a developer, it's very confusing that namespace plays such an important role. If Command X extends AdminCommand, I assume it is treated as an admin command irrespective of its namespace. Would be worth thinking about it to ease development, I guess.

Thanks again!
