### ISSUE TITLE
Cannot make a command in Korean.

### ISSUE THREAD

**Issue by imdevs** [php-telegram-bot/core#876]
### Required Information

- Operating system: CentOS7
- PHP version: PHP 7.1.21
- PHP Telegram Bot version: Installed as Composer 2018-08-22
- Using MySQL database: yes
- MySQL version: mysql  Ver 15.1 Distrib 5.5.60-MariaDB
- Update Method: Webhook 
- Self-signed certificate: yes

### Actual behaviour

I am a beginner developer living in Korea.

Copy the SurveyCommand.php file as it is in the example.

The file name and test for $name, $description, and $usage.

Command name worked well in English. So it doesn't seem to be a mistake.

However, there was a problem when the command name was Korean.

It is on the /help list but it is not linked.
And it can't be done.

I am bad at English.
But I tried to convey my message.

Ask for help.

### Steps to reproduce

Make a command in Korean.
ex ) /좋아요

**Comment by noplanman** [comment]
Fixed by naming file and class correctly.

**Comment by imdevs** [comment]
I solved this problem in chatting.
2-byte language user had to leave the command in the file name.

ex ) 한글Command.php

a very kind solution
Thank you very much.
