### ISSUE TITLE
Send bold and italic messages

### ISSUE THREAD

**Issue by NabiKAZ** [php-telegram-bot/core#877]
When I send this text: `__italic__ **bold** normal` by used this command: `Request::sendMessage` to the channel, The text received in the channel was not bold and italic, and I was get that plain be like original message: `__italic__ **bold** normal`.
Why is this and resolve for send bold or italic messages?

**Comment by jacklul** [comment]
> parse_mode | String | Optional. Send Markdown or HTML, if you want Telegram apps to show bold, italic, fixed-width text or inline URLs in the media caption.

**Comment by wanderleihuttel** [comment]
Hello Guys About this item.

If I had the following text:
Some_long_text_with_underline

The telegram understanding this is markdown, but is not.
How to avoid to happen this things?

**Comment by noplanman** [comment]
@wanderleihuttel You will need to escape the underscores with a backslash, like this:
`Some\_long\_text\_with\_underline`
