### ISSUE TITLE
How use to create chat?

### ISSUE THREAD

**Issue by pws2016** [php-telegram-bot/core#882]
i want create a chat function using your code, How i can do?
please details steps.. thanks

**Comment by noplanman** [comment]
Have a look at the [`/survey`](https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php) command :+1:

**Comment by oxygenfox** [comment]
Sir How to send or forward Message Result from /survey comand to admin bot? @noplanman
