### ISSUE TITLE
No response in sendAudio

### ISSUE THREAD

**Issue by sunildabhi** [php-telegram-bot/core#886]
### Required Information

- Operating system:Linux 
- PHP version:5.6.30
- PHP Telegram Bot version:0.54.0
- Using MySQL database: yes
- MySQL version:5.5.60-cll 
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour

There should be mp3 file with play button for play it.
### Actual behaviour

but not getting any response
### Steps to reproduce

bellow is code for sending it:
```php
$url = str_replace(" ", "%20", $audio['file']);
$data['caption'] = $audio['title'];
$data['title'] = $audio['artist'];
$data['audio'] = Request::encodeFile($url);

Request::sendAudio($data);
```
### Extra details

bellow is log when i am sending audio file:
```
[2018-09-06 12:17:39] bot_log.ERROR: exception 'Longman\TelegramBot\Exception\TelegramException' with message 'Telegram returned an invalid response!' in /vendor/longman/telegram-bot/src/Request.php:472
Stack trace:
#0 [internal function]: Longman\TelegramBot\Request::send('sendAudio', Array)
#1 /vendor/longman/telegram-bot/src/Request.php(574): call_user_func_array('static::send', Array)
#2 /Commands/CallbackqueryCommand.php(102): Longman\TelegramBot\Request::__callStatic('sendAudio', Array)
#3 /Commands/CallbackqueryCommand.php(102): Longman\TelegramBot\Request::sendAudio(Array)
#4 /vendor/longman/telegram-bot/src/Commands/Command.php(173): Longman\TelegramBot\Commands\SystemCommands\CallbackqueryCommand->execute()
#5 /vendor/longman/telegram-bot/src/Telegram.php(537): Longman\TelegramBot\Commands\Command->preExecute()
#6 /vendor/longman/telegram-bot/src/Telegram.php(505): Longman\TelegramBot\Telegram->executeCommand('Callbackquery')
#7 /vendor/longman/telegram-bot/src/Telegram.php(423): Longman\TelegramBot\Telegram->processUpdate(Object(Longman\TelegramBot\Entities\Update))
#8 /hook.php(52): Longman\TelegramBot\Telegram->handle()
#9 {main} [] []
```

**Comment by sunildabhi** [comment]
i tried but still no action, i attached log files check it
[SHATest_Bot_update.log](https://github.com/php-telegram-bot/core/files/2409644/SHATest_Bot_update.log)
[SHATest_Bot_debug.log](https://github.com/php-telegram-bot/core/files/2409645/SHATest_Bot_debug.log)

**Comment by noplanman** [comment]
Hi @sunildabhi 
I have removed your log files, as they contained your bot API token.

:exclamation: **Please reset them immediately via `@BotFather`** :exclamation: 

Regarding your issue, your debug log showed a `400 Bad Request` error, which means your request has invalid data in it.
Have another look at the official [`sendAudio` documentation](https://core.telegram.org/bots/api#sendaudio) to make sure you have filled all necessary fields and that they are valid.

**Comment by sunildabhi** [comment]
i have audio file with size of 65mb can you tell me how to send it? because using url there is limit max size 20mb.

**Comment by chuv1** [comment]
Sent it to your bot via  your messenger and get `file_id` of the file. Send file by it's `file_id`.

**Comment by noplanman** [comment]
@sunildabhi Can we close off here?

**Comment by sunildabhi** [comment]
yes it want to working because file size was about to 65mb, thanks for help.
