### ISSUE TITLE
"Get" requests not working, when data is empty

### ISSUE THREAD

**Issue by scrobbleme** [php-telegram-bot/core#888]
Hello,

It isn't possible to just call get-Methods without data.

**Not working**

`$result = Request::send('getMe');`

**Working**

`$result = Request::send('getMe', array('empty', 'empty');`

Generally it looks like a problem on Telegrams end, as they don't seem to handle post requests without a body.

**Proposal**

* Add a 3rd optional parameter to Request::send
  ` public static function send($action, array $data = null, $post = true)`
* If $post is false, make a get-Request instead of a post-Request

**Comment by chuv1** [comment]
Check `Request::getMe();` method ;)

**Comment by scrobbleme** [comment]
@chuv1 Arggg.... Sorry. Thank you, this was hint I needed.

This is the first time for me working with Composer and the Telegram API ...

- Composer just resolved a very old version (0.0.5) of this package -> all the needed methods weren't there ;)
- Reason: Misconfiguration of my local PHP version (missing extensions needed for newer version)

Nice thing: IntelliJ is everything hiding from me, so I wasn't aware the API version was very old. 

After setting up PHP correctly -> everything works now ;)

Side note: It would be better if the documentation just states the latest verson as lowest (and not the *). Setting explicitly the latest version as requirement showed me the problem immidiatly.
