### ISSUE TITLE
nested commands

### ISSUE THREAD

**Issue by FerX** [php-telegram-bot/core#89]
you can enable / disable the command according the last command executed?

es. 

command10 -> command enable: command20 - command30
command20 -> command enable: command21, command22, command23.... command10 (return back)
in command10 is not possible command22

thanks.

**Comment by FerX** [comment]
I found #7,
plan to implement it?
thanks.

**Comment by FerX** [comment]
I found #7,
plan to implement it?
thanks.

**Comment by noplanman** [comment]
The "conversations" (as they are called now and being wonderfully implemented by @MBoretto) does not offer this functionality. What the conversations do, is allow for "conversations" with the bot. So it's more like a dialogue, than functionality altering commands.

What you're looking for is a way to allow only certain commands depending on a previously executed one, right?
This requires a new feature, as the available commands are read at the very beginning and would need to take previously executed commands into account.

We'll keep this in mind though!

**Comment by noplanman** [comment]
I'll close off here and point here: #227
