### ISSUE TITLE
nice solution for pass callback query data to command

### ISSUE THREAD

**Issue by momohammadi** [php-telegram-bot/core#893]
I recently got to know this platform, and I found that it was very user-friendly and simple, but the problem I was faced with was sending data from inline keyboards into a custom command class that I had created myself.
I read the posts of others, but I could find a very simple solution to this, which I will explain below.
Step 1  :
add bellow code in try block of hook file : 

```php
$commands_paths = [__DIR__ . '/Commands'];
$telegram->addCommandsPaths($commands_paths);
```

Step 2 : 
copy `CallbackqueryCommand.php` from Systemcommand to your custom command directory with a few changes 
complete contain of this file 
name : `CallbackqueryCommand.php`
contain : 
```php
<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;

/**
 * Callback query command
 */
class CallbackqueryCommand extends SystemCommand
{
    /**
     * @var callable[]
     */
    protected static $callbacks = [];

    /**
     * @var string
     */
    protected $name = 'callbackquery';

    /**
     * @var string
     */
    protected $description = 'Reply to callback query';

    /**
     * @var string
     */
    protected $version = '1.0.0';
     
    /**
     * Command execute method
     *
     * @return mixed
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {
        //$callback_query    = $this->getUpdate()->getCallbackQuery();
		$callback_query    = $this->getCallbackQuery();
        $callback_query_id = $callback_query->getId();
        $callback_data     = $callback_query->getData();
        $data = [
            'callback_query_id' => $callback_query_id,
            'text'              => $callback_data,
            //'show_alert'        => true,
            //'cache_time'        => 5,
        ];     
        if(preg_match("[@]",$data['text'])){
            $arr = explode('@',$data['text']);
            $arrcommand = $arr['0'];
            $this->telegram->executeCommand($arrcommand);   
        }else{
          return Request::answerCallbackQuery($data);
        }
    }
    /**
     * Add a new callback handler for callback queries.
     *
     * @param $callback
     */
    public static function addCallbackHandler($callback)
    {
        self::$callbacks[] = $callback;
    }
}
```
Step 3 : 
put your wanted data for inline keyboard in your custom command with "command@data"
example : my custom command name is "start"

```php
$allQueryData= $this->getCallbackQuery();
$queryData = $allQueryData->getData(true);
$queryData = (preg_match("[@]",$queryData))?explode("@",$queryData)[1]:"";
$data['text']         = "choose language";
$data['chat_id'] = $chat_id;
$data['lang']     = [ ['text' =>'en', 'callback_data' => 'start@en-US'], ['text' => 'fa', 'callback_data' => 'start@fa-IR']  ];
$data['reply_markup'] = new InlineKeyboard($data['lang']);
$result = Request::sendMessage($data);
```
with this hack when your client press on inline keyboard these data send to your command file and you can do anything you want with this data :)

**Comment by noplanman** [comment]
Thanks @momohammadi for sharing your solution.

I will close this issue, but of course it's available for anybody searching here :ok_hand:

**Comment by vihatsoft** [comment]
when press inline button then call back run continuessss send same message continuessss.. not run only once. 
when i put time with message then all second is different. means call back send in loop.

i use bellow code in my command file for call back.

```
 $allQueryData         = $this->getCallbackQuery();

 if($allQueryData != null) {
     $callback_query = $this->getCallbackQuery();
      $message = $callback_query->getMessage();
     $chat_id = $message->getChat()->getId();

} else {
 $message = $this->getMessage();
            $from       = $message->getFrom();
            $chat_username = $from->getUsername();
            $chat_id    = $message->getChat()->getId();
            $user_id        = $message->getFrom()->getId();
}
```

then simple send with bellow 
```
    $data =  [
            'chat_id' => $chat_id,
            'text'    => "test message",
            'disable_web_page_preview'    => true,
            'parse_mode' => 'html',
        ];

   return  Request::sendMessage($data);
```  
"test message" message repeat continuessss....
   
   please help. how to solve it..

**Comment by jacklul** [comment]
> please help. how to solve it..

Are you using webhook or getUpdates method?
Telegram in their documentation says it is necessary to answer to each callback query even if you don't display any text to the user.

Calling this before somewhere near the final part of your command should fix this:
```php
Request::answerCallbackQuery(['callback_query_id' => $this->getCallbackQuery()->getId()]);
```

**Comment by vihatsoft** [comment]
use webhook method.  i use answerCallbackQuery and sendmessage but not work. still same message repeat. 
i also run AnswerCallback with sendMessage but answer callback  show only one time and sendMessage run continuess...

![2021-07-23_185551](https://user-images.githubusercontent.com/49095830/126788515-d6f61655-2cd2-4cad-9a74-c74ce4735d40.png)

**Comment by vihatsoft** [comment]
how to clear set empty call back data  for  $this->getCallbackQuery()->getData(); ?

**Comment by jacklul** [comment]
Also: Make sure your webserver returns HTTP 200 code otherwise Telegram will assume failure.

**Comment by vihatsoft** [comment]
[Solved] problem in momohammadi code.
missing return in bellow. if possible update this code. thank you.
`$this->telegram->executeCommand($arrcommand)
`

**Comment by vihatsoft** [comment]
> Also: Make sure your webserver returns HTTP 200 code otherwise Telegram will assume failure.
> 
> > i also run AnswerCallback with sendMessage but answer callback show only one time and sendMessage run continuess...
> 
> Once a callback is replied to it does not accept any more.



> Also: Make sure your webserver returns HTTP 200 code otherwise Telegram will assume failure.
> 
> > i also run AnswerCallback with sendMessage but answer callback show only one time and sendMessage run continuess...
> 
> Once a callback is replied to it does not accept any more.

[Solved] problem in momohammadi code.
missing "return" in bellow so continue send call back message. 
if possible update this code. thank you.
`$this->telegram->executeCommand($arrcommand)
`

**Comment by noplanman** [comment]
@vihatsoft I've added an edit to the original code, for anybody else that comes here. Thanks for pointing it out.
