### ISSUE TITLE
input is empty ! 

### ISSUE THREAD

**Issue by rad1k4l** [php-telegram-bot/core#894]
my hook.php
```php
$file = 'data.txt';

$current = file_get_contents($file);

$current .= serialize($_POST);

file_put_contents($file, $current);
```

my data.txt

`a:0:{}a:0:{}`

when i try this with library on puts in data.txt : `Input is empty!`

### Required Information

- Operating system:
- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes / no
- MySQL version:
- Update Method: Webhook / getUpdates
- Self-signed certificate: yes / no
- RAW update (if available):

**Comment by noplanman** [comment]
Hi @rad1k4l 

When calling the webhook directly in a browser, that is the correct output, as the webhook should only be called by Telegram directly, which provides the input for the bot.

**Comment by rad1k4l** [comment]
> Hi @rad1k4l
> 
> When calling the webhook directly in a browser, that is the correct output, as the webhook should only be called by Telegram directly, which provides the input for the bot.
> 
> What are you trying to achieve with your code exactly?

i am fix this very thanks /   and   i how to get chat id or text  message in this library ?  i am serialize php://input to get id s and text /

**Comment by noplanman** [comment]
You can retrieve messages and all data that comes with them, in commands.

Have a look at the [example `/start` command](https://github.com/php-telegram-bot/example-bot/blob/90bfde028f71bda1aedd51bdc225984a68b5c276/Commands/StartCommand.php) to get an idea how it works.
