### ISSUE TITLE
How do you use a callback button to set off a command?

### ISSUE THREAD

**Issue by KaidenRogers** [php-telegram-bot/core#896]
### Required Information

- Operating system: CentOS Linux 7.5.1804 (Core)‬
- PHP version: 5.6.36
- Using MySQL database: yes
- MySQL version: 5.5.56-2.el7
- Update Method: Webhook
- Self-signed certificate: No

### Expected behaviour
I'm trying to use a call back button to send a command to another chat instance.
I've used [this](https://github.com/php-telegram-bot/core/issues/251) as a guide. Everything looks like it's working up to passing the variable `$command` to the reply script. when I use the script as a normal command it works. Even changing the `$text` variable to the testing instance's chat ID works when I run the /reply command from my instance. 

also,
> At the moment there is no clean way to execute a subcommand.

is this still the case?

Context: I'm trying to use a bot to collect information and send it to me along with an inline keyboard that will contain buttons to either approve, deny, or message the applicant.  Upon clicking on approve or decline I want it to run another command on said applicants chat instance.

### Actual behaviour
Nothing. 

### Steps to reproduce
script that runs on the applicants chat instance sending the inline keyboard
```
...
$inline_keyboard = new InlineKeyboard([
	['text' => 'Message '.$username, 'url' => 'https://t.me/'.$username],
	['text' => 'reply', 'callback_data' => 'reply_' . $chat_id], //this line
]);
$ndata = [
        'chat_id'      => '{my instance's chat id}',
        'text'         => 'Select an option',
        'reply_markup' => $inline_keyboard,
];
	return Request::sendMessage($ndata);
...
```
callback query script
```
...
$data = $callback_query->getData();
		$command = explode('_', $data);
		$command = $command[0];
		
				
		if ($this->getTelegram()->getCommandObject($command)) {
					return $this->getTelegram()->executeCommand($command);
		}
...
```
reply script

```
...
$testtext = explode('reply_', $command);
$text = $testtext[1];

		/*$message = $this->getMessage(); //verify this script works as a normal command
		$chat    = $message->getChat();
		$chat_id = $chat->getId();
                $text = $chat_id;*/

$data = [
            'chat_id' => $text,
            'text'    => 'worked',
 ];

return Request::sendMessage($data);
    }
}

```

### Extra details
error log says nothing. (like it's hasn't actually been updated by the bot for a couple days now, not sure if it's even functioning propperly.)
debug log says:
```
...
* upload completely sent off: 20 out of 20 bytes
< HTTP/1.1 400 Bad Request
< Server: nginx/1.12.2
< Date: Fri, 12 Oct 2018 03:27:25 GMT
< Content-Type: application/json
< Content-Length: 75
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
< 
* Connection #0 to host api.telegram.org left intact

 [] []

```
and in the update log i can see that the callback data does have the correct information
`"data":"reply_{chat id}"} `

**Comment by chuv1** [comment]
One can make a callback handler inside a command (check if `$this->getCallbackQuery()` is not null, execute another branch of code), and stop trying to pass a parameter.

Personally, I did some sort of router inside `CallbackqueryCommand.php`. 
It check first parameter of `callback_data` and execute appropriate command. 
Later in that particular command I rewrote `execute()` method to route update to appropriate branch of code, and created `executeMessage()` and `executeCallback()` methods to handle different types of updates.

**Comment by chuv1** [comment]
Consider this example:

For example we have `SurveyCommand.php` that sends callback with `survey:param1:param2:...:paramN` data.

First we need a router that will decide what command should be called upon sent data,

**CallbackqueryCommand.php:**
```php
...

public function execute()
{
    
    // Explode query_data into chunks
    $query_data     = $this->getUpdate()->getCallbackQuery()->getData();
    $query_data     = explode(':', $query_data);

    // If there are two pieces, consider first one a command name and execute it
    if(\count($query_data) >=2){
        return $this->getTelegram()->executeCommand($query_data[0]);
    }

    return Request::answerCallbackQuery(['callback_query_id' => $this->getUpdate()->getCallbackQuery()->getId()]);

}

....
```

Code above will pass execution to `SurveyCommand.php` that should be able to handle it.
First e need to create a router to let user execute command directly as well as with callback.
Rename your `execute()` method into `executeMessage()` and add router into default `execute()` method.

**SurveyCommand.php:**
```php
public function execute()
{

    // Command triggered with callback
    if($this->getCallbackQuery()){
        return $this->executeCallback();
    }

    // Command triggered with regular message
    return $this->executeMessage();

}
```

And last step - create `executeCallback()` method and add code that should be able to handle incoming callback data. 

**SurveyCommand.php:**
```php
public function executeCallback()
{

    // Explode query_data into chunks
    $query_data     = $this->getUpdate()->getCallbackQuery()->getData();
    $query_data     = explode(':', $query_data);

    // Do not forget to answer callback query here!
    Request::answerCallbackQuery(['callback_query_id' => $this->getUpdate()->getCallbackQuery()->getId()]);

    // Do something, like running different logic depending on first parameter, for example
    switch($query_data[1]){
        case 'param_1': 
            // Logic goes here
        break;
    }

}
```

I hope now it's clear. )

**Comment by jacklul** [comment]
Also in addition to the one above you can take a look at my similar approach: https://github.com/jacklul/inlinegamesbot/blob/master/src/Command/System/CallbackqueryCommand.php

(Sometimes putting full command name into callback data can be a waste since the field can hold maximum of 64 characters.)

**Comment by KaidenRogers** [comment]
@chuv1 I tried that and I get this error

`mod_fcgid: stderr: PHP Fatal error: Call to a member function getChat() on null in /var/www/vhosts/.../Commands/SurveyCommand.php on line 81`

and I'm using this to get the chat id

`       $message = $this->getMessage();
	$chat    = $message->getChat();
	$chat_id = $chat->getId();`

**Comment by KaidenRogers** [comment]
@chuv1 Thanks that worked! But how would one fetch user input in that survey?
`trim($message->getText(true)); ` doesn't work as `$message` is null.

**Comment by chuv1** [comment]
In this case there are no user input except `query_data` sent with a callback. 
So if you use `Conversation` class, you can invoke it via 
```php
// Getting ID of the user that clicked inline button (note that no message used in this case)
$user_id = $this->getUpdate()->getCallbackQuery()->getFrom()->getId();

// Getting ID of the chat that have that message with button (note that this message is from the bot)
$chat_id = $this->getUpdate()->getCallbackQuery()->getMessage()->getChat()->getId();

// Invoke conversation
$conversation = new Conversation($user_id,$chat_id);

// And use as usual...
```

**Comment by KaidenRogers** [comment]
Awesome, it worked! Thank you so much!
