### ISSUE TITLE
Method "sendPhoto" not found in class Request.

### ISSUE THREAD

**Issue by 0xEAB** [php-telegram-bot/core#897]
### Required Information

- Operating system: Linux
- PHP version: 7.1.22 (64bit)
- PHP Telegram Bot version: 0.54.0
- Using MySQL database: yes
- MySQL version: 10.1.29-MariaDB
- Update Method: Webhook
- Self-signed certificate: no

### Expected behaviour
Photo is sent.

### Actual behaviour
```
Method "sendPhoto" not found in class Request.
```

### Steps to reproduce
```php
Longman\TelegramBot\Request::sendToActiveChats(
    'sendPhoto',
    ['photo' => Longman\TelegramBot\Request::encodeFile($row['path'])],
    [
        true, // Send to chats (group chat)
        true, // Send to chats (super group chat)
        true, // Send to users (single chat)
        null, // 'yyyy-mm-dd hh:mm:ss' date range from
        null  // 'yyyy-mm-dd hh:mm:ss' date range to
    ]
);
```

### Extra details
Fix for #666 didn't fix this

**Comment by noplanman** [comment]
You sure you have the latest version of the bot installed?

**Comment by noplanman** [comment]
Ah right, I see what you mean now, will get this fixed ASAP!

**Comment by 0xEAB** [comment]
Thanks :)

**Comment by noplanman** [comment]
Ok, 0.54.1 is released with the fix :+1:

**Comment by 0xEAB** [comment]
thank you
