### ISSUE TITLE
Bot not respond on /start command.

### ISSUE THREAD

**Issue by sahilr2050** [php-telegram-bot/core#901]
Hello,

As per the given details, I have done all the things and everything is working well except responding on any command for example "/start" from the telegram bot.

In the log file generated by below coding line.
`Longman\TelegramBot\TelegramLog::initUpdateLog(__DIR__ . "/{$bot_username}_update.log");`

I can see the Bot Subscriber Clicked on Start button. But Bot is not responding on that.

here is the output of the log file.

`{"update_id":278944553, "message":{"message_id":14,"from":{"id":623248824,"is_bot":false,"first_name":"Ultimate","last_name":"Crypto","username":"Ucryp"},"chat":{"id":623248824,"first_name":"Ultimate","last_name":"Crypto","username":"Ucryp","type":"private"},"date":1540657897,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}}
`

What I am missing? 
### Required Information

- PHP version: 7.0.2
- PHP Telegram Bot version: latest (27th Oct 2018)
- Using MySQL database: no
- MySQL version: n/a
- Update Method: Webhook
- Self-signed certificate: yes / no --> Domain Name is secured with HTTPS

### Expected behaviour
It should respond as 

Hi there!
Type /help to see all commands!

### Actual behaviour
Nothing.

**Comment by noplanman** [comment]
Could you post your `hook.php` file without the bot name and API key please?

**Comment by noplanman** [comment]
@mogilka Have a look at the [example-bot](https://github.com/php-telegram-bot/example-bot/) repo, especially the [`Commands/StartCommand.php`](https://github.com/php-telegram-bot/example-bot/blob/90bfde028f71bda1aedd51bdc225984a68b5c276/Commands/StartCommand.php) file.

Then, as you mentioned, in your hook you can add the custom folder that has the `StartCommand.php` file in it, and that should be all that's necessary!

**Comment by mogilka** [comment]
@noplanman thank you! it works and now it's clear =)

**Comment by mirkafe** [comment]
I face the same problem. What the solution? Should I upload hook.php and Commands/StartCommand.php from [example-bot](https://github.com/php-telegram-bot/example-bot/)?

**Comment by noplanman** [comment]
@mirkafe Make sure you have the `StartCommand.php` in your custom commands folder and that it gets loaded in your hook.

**Comment by mirkafe** [comment]
> @mirkafePastikan Anda memiliki `StartCommand.php`folder perintah khusus Anda dan itu dimuat di hook Anda.

I understand the logic, but can't apply it :((
