### ISSUE TITLE
Method getChat()->getPinnedMessage() always return null

### ISSUE THREAD

**Issue by BoGnY** [php-telegram-bot/core#905]
### Required Information
- Operating system: Ubuntu 18.04.01 LTS kernel 4.15.0-36 x64
- PHP version: 7.2.11-4 FPM version
- PHP Telegram Bot version: 0.54.1
- Using MySQL database: no
- Update Method: webhook
- Self-signed certificate: no
- RAW update (if available): 
```json
{"update_id":733840824, "message":{"message_id":724,"from":{"id":173163602,"is_bot":false,"first_name":"BoGnY","username":"BoGnY","language_code":"it"},"chat":{"id":-1001230336412,"title":"SbancaCrypto test bot chat","username":"BoGnYBotTest","type":"supergroup"},"date":1541447910,"pinned_message":{"message_id":669,"from":{"id":173163602,"is_bot":false,"first_name":"BoGnY","username":"BoGnY","language_code":"it"},"chat":{"id":-1001230336412,"title":"SbancaCrypto test bot chat","username":"BoGnYBotTest","type":"supergroup"},"date":1541270215,"text":"MESSAGGIO PINNATO DI PROVA!!!"}}}
```

### Expected behaviour
The method getChat()->getPinnedMessage() would return pinned text message.

### Actual behaviour
The method getChat()->getPinnedMessage() always return null.

### Steps to reproduce
`src/Commands/AdminCommands/PinnedmessageCommand.php`
```php
<?php

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\TelegramLog;

class PinnedmessageCommand extends SystemCommand {
    protected $name = "pinnedmessage";
    protected $description = "Comando eseguito quando un messaggio viene pinnato.";
    protected $version = "1.0.0";

    public function execute() {
        $message = $this->getMessage();

        $chat_id = $message->getChat()->getId();
        $chat_type = $message->getChat()->getType();
        $chat_username = $message->getChat()->getUsername();
        $user_id = $message->getFrom()->getId();
        $user_username = $message->getFrom()->getUsername();
        $pinned_message = $message->getChat()->getPinnedMessage(); // <- HERE

        if (DEBUG) {
            TelegramLog::debug("Pinnedmessage command executed by @" . $user_username . " on " . $chat_type . " chat @" . $chat_username);
            TelegramLog::debug("Pinned message: " . $pinned_message);
        }

        return Request::emptyResponse();
    }
}
```

### Extra details
If changing
`$pinned_message = $message->getChat()->getPinnedMessage();`
with
`$pinned_message = $message->getPinnedMessage();`
it works, but this is not correct because, as described in `Entities\Chat.php` documentation:
`* @method   Message   getPinnedMessage()               Optional. Pinned message, for supergroups. Returned only in getChat.`
the pinned message must be returned on getChat() method

**Comment by noplanman** [comment]
As stated in the documentation: `Returned only in getChat`
https://core.telegram.org/bots/api#getchat

So you'll have to do `Request::getChat($chat_id)->getPinnedMessage();`

The `getChat` method on the `Message` object is different, but I can totally understand the confusion there :confused:

**Comment by solo-way** [comment]
Correct and working way:
$target_chat = Request::getChat(['chat_id' => xxxxxxx]);
$pinned_msg = $target_chat->getResult()->getPinnedMessage();
