### ISSUE TITLE
get chat id from cli means?

### ISSUE THREAD

**Issue by devendrasingh17** [php-telegram-bot/core#908]
### Required Information

- Operating system:
- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes / no
- MySQL version:
- Update Method: Webhook / getUpdates
- Self-signed certificate: yes / no
- RAW update (if available):

**Comment by jacklul** [comment]
I don't think anyone will have any idea what you mean.
Care to explain your issue?

**Comment by devendrasingh17** [comment]
I meant that I want to send messages on user's telegram, when user signups
on my website.

**Comment by jacklul** [comment]
Once user logs in you just initialize `Telegram` object (check repository readme!) and use `Request:sendMessage()` method.

Example of log-in script is on Telegram docs.

**Comment by noplanman** [comment]
@devendrasingh17 As this should be very straight forward, I'll close off here. You can reopen or comment if need be.
