### ISSUE TITLE
handleGetUpdates stuck on initial run

### ISSUE THREAD

**Issue by gr1m** [php-telegram-bot/core#909]
### Required Information
- Operating system: any
- PHP version: any
- PHP Telegram Bot version: 0.54.*
- Using MySQL database:  no
- MySQL version: any
- Update Method: getUpdates
- Self-signed certificate: any
- RAW update (if available): -

### Expected behaviour
`handleGetUpdates` method should return `$response` right after getting response from Telegram API
### Actual behaviour
`handleGetUpdates` is stuck on "Mark update(s) as read after handling" on initial usage of `handleGetUpdates` method

### Steps to reproduce
just run `handleGetUpdates` method in `useGetUpdatesWithoutDatabase` mode

### Extra details
On initial run when `handleGetUpdates` getting first update it marks update as read by requesting `getUpdates` with the same timeout as it was set. In long polling case it can take couple minutes (or more) and initial $response is not being returned.
Please, consider changing this [timeout](https://github.com/php-telegram-bot/core/blob/master/src/Telegram.php#L390) to 1 second

**Comment by noplanman** [comment]
@gr1m Regarding the timeout, you can override it yourself with the `$timeout` parameter when calling [`handleGetUpdates()`](https://github.com/php-telegram-bot/core/blob/7701428356a70b0b5d88404248a060ca1c43c6ba/src/Telegram.php#L332).

Are you talking about the initial run of the bot itself, or every time you run a script with a loop?

**Comment by jacklul** [comment]
Note that running without database is only optimal for looping inside PHP, looping through bash script will put a large delay on the execution.

**Comment by gr1m** [comment]
@noplanman it's the case when I'm just starting script. If I would change `$timeout` it will affect long polling timeout, and I would like to have long polling timeout about 2-5 minutes.
As alternative to changing timeout it would be good to have option to skip [step](https://github.com/php-telegram-bot/core/blob/master/src/Telegram.php#L384) "Mark update(s) as read after handling" when using this lib without DB...

**Comment by noplanman** [comment]
@gr1m Did you manage to figure out why your script gets stuck?
Or did you find some other solution for your issue?

**Comment by gr1m** [comment]
@noplanman its stuck only on first message, because this lib is trying to mark this message as read with my initial timeout (https://github.com/php-telegram-bot/core/blob/0.61.0/src/Telegram.php#L383) instead of letting my code process this first message.
