### ISSUE TITLE
Wrong return type while sending message to bot

### ISSUE THREAD

**Issue by AlexeySurnin** [php-telegram-bot/core#911]
While sending to bot this message: "0", it returns wrong type of message. It should return 'text', but it returns 'message'.
![image](https://user-images.githubusercontent.com/28294403/50304573-03b1c480-0499-11e9-99ff-a13b487eda53.png)

![image](https://user-images.githubusercontent.com/28294403/50304978-31e3d400-049a-11e9-8cd0-0db6679263e1.png)

**Comment by noplanman** [comment]
@AlexeySurnin Thanks for letting us know about this one :+1:
