### ISSUE TITLE
does not find the command if use switch_inline_query_current_chat

### ISSUE THREAD

**Issue by saSHADE** [php-telegram-bot/core#912]
when using switch_inline_query_current_chat, the input field substituted  "@bot_username string"
If you substitute the /command in a string the script will not process it.

Perhaps it's better to still handle such a string as a command?

**Comment by noplanman** [comment]
Hi @saSHADE, could you please explain in more depth what you were trying here and what should be happening?

**Comment by saSHADE** [comment]
Hi. I don't know English well, I think it would be better if I write in my native language and you translate it.

Когда я создаю inline кнопку switch_inline_query_current_chat, то при нажатии на неё у пользователя в поле ввода вставляется текст с именем бота и заданным текстом - @bot_name some_text
Если использовать эту возможность для подстановки нужной команды (@bot_name /any_command some_text), то скрипт не воспринимает это как вызов команды.

**Comment by noplanman** [comment]
Inline queries are separate from executing commands!

If you want to execute a command with the bot directly you need to use `/any_command@bot_name some_text`.

For more details about how inline queries are used, [look here](https://core.telegram.org/bots/inline)
