### ISSUE TITLE
Is the editing the media content of messages method implemented (Bot API 4.0)?

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [php-telegram-bot/core#915]
I can't find these methods in the Request class((

**Comment by noplanman** [comment]
@CaliforniaMountainSnake You're absolutely right, they got forgotten 🙄
I'm on it...

**Comment by CaliforniaMountainSnake** [comment]
:thumbsup: Thanks you, man, I am very waiting its in the master branch!
