### ISSUE TITLE
How we can delete old bot message from group by cron? '(

### ISSUE THREAD

**Issue by ponysonata** [php-telegram-bot/core#918]
How we can delete old bot message from group by cron? Can you example a programm please? <3

**Comment by NabiKAZ** [comment]
@noplanman And so what about old messages of another users?

**Comment by noplanman** [comment]
@NabiKAZ If you don't have the message ID, there is no way to delete it via the bot.

**Comment by NabiKAZ** [comment]
@noplanman Does can way to access to old user's messages? for get IDs.

**Comment by noplanman** [comment]
Unfortunately not, as I mentioned in my previous comment :confused:

**Comment by NabiKAZ** [comment]
So I thinks must be use of [MadelineProto ](https://github.com/danog/MadelineProto) or [telegram-cli](https://github.com/vysheng/tg) or similar programs.
