### ISSUE TITLE
"error_code":404,"description":"Not Found"}

### ISSUE THREAD

**Issue by zzroche** [php-telegram-bot/core#922]
### Required Information

- Operating system:  Linux w-63.th.seeweb.it 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64
- PHP version: PHP Version 7.1.25-1+0~20181207224650.11+stretch~1.gbpf65b84
- PHP Telegram Bot version: latest
- Using MySQL database: yes 
- MySQL version:5.7.24
- Update Method: Webhook 
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour

I'v do a personal ph script to work with a bot and works fine. 
Actually I would use Longman\TelegramBot Api because seems superb but I never be able to make it work.
I've doing a chat with my bot, where i do commands.
Mysql works and logs too. 

### Actual behaviour

At the handle function, the answer at this line: "  if ($response = $this->processUpdate(new Update($post, $this->bot_username))) {"
is:
{"ok":false,"error_code":404,"description":"Not Found"}

**Comment by noplanman** [comment]
@zzroche Have you managed to figure out here what the problem was? Mind sharing the (re)solution?
