### ISSUE TITLE
Return array of responses on sendMessage

### ISSUE THREAD

**Issue by Abduvokhid** [php-telegram-bot/core#923]
Please, change `Request::sendMessage` to return the array of responses in case if the text is longer than 4096 symbols. Now, this method is returning the response of last sent message.

![image](https://user-images.githubusercontent.com/16443812/52114760-b8a9d600-262e-11e9-8e99-7b13314838f9.png)

**Comment by jacklul** [comment]
Ideally it would be good to keep this backwards compatible by adding responses into separated `ServerResponse` field and making root `ok` field return `True` when all messages where sent and `False` when at least one failed.

**Comment by noplanman** [comment]
I agree that this should change.

I can see some different ways of solving this:
- return an array or `ServerResponse` (breaks backwards compatibility)
- return a single custom response object, ok if all messages sent successfully, response objects nested in root response (what @jacklul mentioned above)
- add an extra parameter by reference, which contains all response objects, e.g. `sendMessage($data, $responses);` (doesn't break backwards compatibility, but not sure if it's the prettiest)

@jacklul So you're saying to add an extra custom field to the `ServerResponse` class?

**Comment by Abduvokhid** [comment]
Or you can add an array of responses into last|first response of `sendMessage`. This array will be set if the text is divided into parts and sent. In this case, the developer has to check if this array is set or not.

**Comment by vontend** [comment]
I have just get problem with this case. A work around is split your message send overloop and return the last one
