### ISSUE TITLE
How to disable all your command

### ISSUE THREAD

**Issue by FerX** [php-telegram-bot/core#93]
Hello,
is possible with a setting disable all commands already present?

**Comment by noplanman** [comment]
As far as I know, no. You could edit the files in the `src/Commands` folder and set the `$enabled` variable to `false` or simply delete the command files you don't need. This might raise issues when updating through composer though, not sure what would happen.

It's a great idea though, will see if we can implement it in a future version, thanks!

@MBoretto @akalongman 
Please correct me if I'm wrong.

**Comment by noplanman** [comment]
The restructuring of the commands is being discuss in #87

**Comment by rbakhvala** [comment]
Hi, so even "New command structure" is closed, there is still no way to disable all commands, right?

I am using composer and when I add my custom commands, example commands(whoami, weather, etc) still show up and available to users. The only ways for me to disable them:
1. Delete them from original library's folder. Will need to do it with each composer update.
2. For each command that is currently present in `src/Command`, create same command in my custom commands folder and set `$enabled` to `false`. This will solve the problem with Composer updates. Unless somebody will add another example command. In this case, it will automatically show as available to all my users.

Is my understanding right? Is there another way to use the library without modifying its contents?

Thank you for your work! It's amazingly useful and needed!

**Comment by noplanman** [comment]
We haven't implemented this feature yet, which is why the issue is still open. But as you mention, creating a custom command with the same name and setting `$enabled` to `false` is a simple workaround for now.

We're aiming to have this implemented in version **0.29**.
At the moment we're working on releasing **0.28** soon!

Thanks for the patience :+1:

**Comment by MBoretto** [comment]
Command could be disable in group chat or vice-versa. Keep this in mind developing this feature

**Comment by MBoretto** [comment]
A good approach is this one that I included in this example: 
https://github.com/MBoretto/Nostickers/blob/master/app/Commands/UserCommands/EchoCommand.php

Hope that help

**Comment by noplanman** [comment]
As of 0.44.0, default commands have been moved to a [separate repository](https://github.com/php-telegram-bot/example-bot).
