### ISSUE TITLE
Syntax error, unexpected '{' on Request.php  $e->getResponse()->getBody() : ''; 

### ISSUE THREAD

**Issue by kejebear** [php-telegram-bot/core#931]
### Required Information

- Operating system: CENTOS 7.6 
- PHP version: 5.6
- PHP Telegram Bot version: 
- Using MySQL database: yes 
- MySQL version: 5.7.25
- Update Method: Webhook
- Self-signed certificate: yes 
- RAW update (if available):

My bot not reply message, and I check error_log 
PHP Parse error:  syntax error, unexpected '{' in  vendor/longman/telegram-bot/src/Request.php on line 343

    public static function execute($action, array $data = [])
    {
        //Fix so that the keyboard markup is a string, not an object
        if (isset($data['reply_markup'])) {
            $data['reply_markup'] = json_encode($data['reply_markup']);
        }
        $result                  = null;
        $request_params          = self::setUpRequestParams($data);
        $request_params['debug'] = TelegramLog::getDebugLogTempStream();
        try {
            $response = self::$client->post(
                '/bot' . self::$telegram->getApiKey() . '/' . $action,
                $request_params
            );
            $result   = (string) $response->getBody();
            //Logging getUpdates Update
            if ($action === 'getUpdates') {
                TelegramLog::update($result);
            }
        } catch (RequestException $e) {
            $result = ($e->getResponse()) ? (string) $e->getResponse()->getBody() : '';
        } finally {  //====>>> line 34
            //Logging verbose debug output
            TelegramLog::endDebugLogTempStream('Verbose HTTP Request output:' . PHP_EOL . '%s' . PHP_EOL);
        }
        return $result;
    }
![image](https://user-images.githubusercontent.com/32185380/53615764-14f21c80-3c12-11e9-8634-b1ed01eb6028.png)

how to fix it, before it is no problem?

**Comment by jacklul** [comment]
Line 343 in latest release is empty https://github.com/php-telegram-bot/core/blob/0.55.1/src/Request.php#L343

You have damaged installation, clean vendor directory and `composer update`.

**Comment by kejebear** [comment]
I have changed the request file, it still has an error, the error changes to line 377,, 
error :
/vendor/longman/telegram-bot/src/Request.php on line 377

what do you mean 
clean vendor directory and `composer update`? I replace it with the latest vendor directories?

**Comment by kejebear** [comment]
> Line 343 in latest release is empty https://github.com/php-telegram-bot/core/blob/0.55.1/src/Request.php#L343
> 
> You have damaged installation, clean vendor directory and `composer update`.

I have changed the request file, it still has an error, the error changes to line 377,,
error :
/vendor/longman/telegram-bot/src/Request.php on line 377

what do you mean
clean vendor directory and `composer update`? I replace it with the latest vendor directories?

**Comment by jacklul** [comment]
Another thing that comes to my mind is that you might be running a PHP lower that 5.5 which didn't have `finally` support. Are you sure you're running 5.6? I've seen some webhosts having 5.2 as default...

**Comment by kejebear** [comment]
> Another thing that comes to my mind is that you might be running a PHP lower that 5.5 which didn't have `finally` support - in that case it might try using it as a function but finds no `() `.
> 
> Verify it by running a script which echos `phpversion()`.
> 
> Are you sure you're running 5.6? I've seen some webhosts having 5.2 as default...

ohh yess,, i check again phpversion it 5.4, and i change 5.6 it work .. Thank you very much 👍
