### ISSUE TITLE
How to get the join message?

### ISSUE THREAD

**Issue by Spixmaster** [php-telegram-bot/core#932]
Do you know how to get the join message? Is it even possible?

**Comment by jacklul** [comment]
`NewchatmembersCommand.php`

**Comment by Spixmaster** [comment]
@jacklul I already knew that but I need the person who added the users or the whole join message as a string.

**Comment by jacklul** [comment]
https://github.com/php-telegram-bot/example-bot/blob/master/Commands/NewchatmembersCommand.php

`$message->getFrom()` will contain `User` object of the person who added member(s).

**Comment by Spixmaster** [comment]
@jacklul I thank you! It works. I am too happy right now.
