### ISSUE TITLE
poll together InlineKeyboardButton

### ISSUE THREAD

**Issue by medness** [php-telegram-bot/core#933]
how can I send a poll from the bot to the channel along with InlineKeyboardButton? 
Thanks!

**Comment by jacklul** [comment]
I don't think bots can send polls at all. 
https://core.telegram.org/bots/api

**Comment by medness** [comment]
Here is an example bot, create a poll and send it to the channel https://telegram.me/vote

**Comment by jacklul** [comment]
That bot creates polls using inline keyboards, you can't forward those or add own buttons.

**Comment by jacklul** [comment]
With inline buttons making callback queries back to the bot.
You obviously have to code that - a good approach will be pasting the polls from inline interface (`InlinequeryCommand`) and then handling the poll and votes in `CallbackqueryCommand`.

**Comment by medness** [comment]
I don’t need the code!

**Comment by jacklul** [comment]
Then what more do you need?
