### ISSUE TITLE
how to get data after command?

### ISSUE THREAD

**Issue by yosefi** [php-telegram-bot/core#935]
Hello.
I want after run command, like "/my_command", bot waiting for new response.

sample:
user: /my_command
bot: please insert name:
user: blabla
bot: your name is blabla

**Comment by jacklul** [comment]
Take a look at `example-bot` repository, especially https://github.com/php-telegram-bot/example-bot/blob/master/Commands/SurveyCommand.php file.

**Comment by noplanman** [comment]
@yosefi Did you manage to get this to work? Can we close this issue?
