### ISSUE TITLE
SQLSTATE[HY000][1040]Too many connections. Telegram Exception received.

### ISSUE THREAD

**Issue by ishanrakitha** [php-telegram-bot/core#936]
Hi,

For the past 4 months i was using this without any issues. MYSQL Max connections - 150 (default) Even 350 is the same now. After Ubuntu 18.04 security update last week i'm getting this error time to time. 

Codeignitor Version - 3.1.9

Please advice. Appreciate your support in advance.

- Operating system: Ubuntu 18.04.1 LTS
- PHP version: PHP Version 7.0.33-1+ubuntu18.04.1+deb.sury.org+1 
- PHP Telegram Bot version: 0.55.0
- Using MySQL database: yes
- MySQL version: Server version: 5.7.25-0ubuntu0.18.04.2 (Ubuntu)
- Update Method: Webhook
- Self-signed certificate: yes
- RAW update (if available):
![IMG_4100](https://user-images.githubusercontent.com/3178753/54392812-892ac680-46ce-11e9-9d1e-0fd87cd929a8.jpg)

Thanks & Regards,
Ishan.

**Comment by jacklul** [comment]
Try using custom PDO instance that you close manually after handling the webhook.

**Comment by noplanman** [comment]
Also, this is a MySQL issue, maybe there is a low limit for allowed connections?

You can check this by connecting to your MySQL database and executing the following query:
```sql
SHOW VARIABLES LIKE 'max_connections';
```

You can increase that value by using:
```sql
SET GLOBAL max_connections := 10000;
```

Better though, is to set it in your MySQL config file. ([Here explained with MariaDB](https://mariadb.com/kb/en/library/configuring-mariadb-with-option-files/))
