### ISSUE TITLE
How to send Unicode?

### ISSUE THREAD

**Issue by Spixmaster** [php-telegram-bot/core#938]
How can I send unicode with the bot?

**Comment by noplanman** [comment]
You should be able to just send unicode characters.

Is this not working for you?

**Comment by Spixmaster** [comment]
```
wchar_t a[] = L"🎊";
bot.getApi().sendMessage(message->chat->id, '@' + message->from->username + " " + a + " Before doing anything in this group activate the bot (@" + bot.getApi().getMe()->username + ")!");
```

I have absolutely no idea. This is what is intended. How would this work?
I use a C++ API.

**Comment by jacklul** [comment]
This is repository for the PHP library, I think you posted in the wrong one.
