### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Telegram' not found in

### ISSUE THREAD

**Issue by sinamotraghi** [php-telegram-bot/core#941]
i get 
`
Fatal error: Uncaught Error: Class 'Telegram' not found in /storage/ssd3/778/8987778/public_html/ZarinPal/ZarinPal/Saman/pec.shaparak.ir/NewIPG/index.php:18 Stack trace: #0 {main} thrown in /storage/ssd3/778/8987778/public_html/ZarinPal/ZarinPal/Saman/pec.shaparak.ir/NewIPG/index.php on line 18
`

> 
?php

    const CHAT_ID = 791531683; #ایدی عددی شما
    const TOKEN = '-REMOVED-'; #توکن شما

    public static function sendMessage($message)
    {
        $url = "https://api.telegram.org/bot" . self::TOKEN . "/sendMessage?chat_id=" . self::CHAT_ID;
        $url = $url . "&text=" . urlencode($message);
        $ch = curl_init();
        $optArray = array(
            CURLOPT_URL => $url,
            CURLOPT_RETURNTRANSFER => true
        );
        curl_setopt_array($ch, $optArray);
        $result = curl_exec($ch);
        curl_close($ch);
    }

}
 >

can any one fix it?

**Comment by jacklul** [comment]
You're mentioning `Telegram` class yet you post a code that does not use it, explain?

**Comment by sinamotraghi** [comment]
not my code . this is all the telegram.php i dont know whi its asking for telegram class

**Comment by noplanman** [comment]
Not using this library.
