### ISSUE TITLE
Cannot access manager.php in web

### ISSUE THREAD

**Issue by Pakev** [php-telegram-bot/core#942]
> [[Sun Mar 24 11:31:08.220224 2019] [:error] [pid 101021] [client 109.91.17.98:59181] PHP Fatal error:  Uncaught TelegramBot\\TelegramBotManager\\Exception\\InvalidAccessException: Invalid access in /var/www/tg/vendor/php-telegram-bot/telegram-bot-manager/src/BotManager.php:594\nStack trace:\n#0 /var/www/tg/vendor/php-telegram-bot/telegram-bot-manager/src/BotManager.php(131): TelegramBot\\TelegramBotManager\\BotManager->validateRequest()\n#1 /var/www/tg/manager.php(83): TelegramBot\\TelegramBotManager\\BotManager->run()\n#2 {main}\n  thrown in /var/www/tg/vendor/php-telegram-bot/telegram-bot-manager/src/BotManager.php on line 594

**Comment by jacklul** [comment]
Not related to this repository, closing.
