### ISSUE TITLE
Cannot select value from DB

### ISSUE THREAD

**Issue by prtnsu** [php-telegram-bot/core#949]
### Required Information

- Operating system: Linux us231.siteground.us 3.12.18-clouder0 #4 SMP PREEMPT Wed Feb 27 16:08:06 EET 2019 x86_64
- PHP version: 7.1.28 (64bit); cgi-fcgi; Linux
- PHP Telegram Bot version:  0.55.1
- Using MySQL database: yes
- MySQL version: 5.6.40-84.0-log
- Update Method: Webhook
- Self-signed certificate: no
- RAW update (if available):

### Expected behaviour
Returns DB value

### Actual behaviour
Returns nothing

---

Hi, could you please tell why this returns nothing, but if I set 
`$hahas = 170;`
Code works correctly?

Also, if I replace 

```
 $haha = $pdo->prepare("SELECT id FROM forward WHERE id = '117'");

$haha->execute();
$hahas = $haha->fetchAll();
        
```
with

```
$pdo->query("INSERT INTO `forward` (`user_id`, `chat_id`, `message_id`) VALUES ({$user_id}, {$chat_id}, {$message_id})");



        $update = json_decode($this->update->toJson(), true);
```
  
New record adds to the DB table, so looks like it's not a DB connection issue.

![image](https://user-images.githubusercontent.com/16436988/56464142-a3ea0c80-63eb-11e9-913c-0441553bdb7d.png)

```

<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\SystemCommands;

use Longman\TelegramBot\Commands\SystemCommand;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\DB;
use PDO;
use Longman\TelegramBot\TelegramLog;





/**
 * Start command
 *
 * Gets executed when a user first starts using the bot.
 */
class RepostCommand extends SystemCommand
{
    /**
     * @var string
     */
    protected $name = 'repost';

    /**
     * @var string
     */
    protected $description = 'Repost command';

    /**
     * @var string
     */
    protected $usage = '/repost';

    /**
     * @var string
     */
    protected $version = '1.1.0';

    /**
     * @var bool
     */

    
    
    protected $need_mysql = true;






    /**
     * Command execute method
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
     
     
     
     
     
     
    public function execute()
    {
    
    
     
    
     $message = $this->getMessage();
        $chat    = $message->getChat();
        $message_id = $message->getMessageId();
        $chat_id = $message->getChat()->getId();
        $user_id = $message->getFrom()->getId();
        $text    = trim($message->getText(true));
        $pdo = DB::getPdo();


  
  $haha = $pdo->prepare("SELECT id FROM forward WHERE id = '117'");

$haha->execute();
$hahas = $haha->fetchAll();
        
        
       




        $data = [
              'text' => $hahas,
   		 'chat_id' => '@xxx',
        ];
        
           


      
  


return Request::sendMessage($data);


        
    }
}


```

And the second little question, could you please tell why 
/cleanup
returns
Cleaning up tables:
botan_shortener (30 days)
callback_query (30 days)
chosen_inline_result (30 days)
conversation (30 days)
edited_message (30 days)
inline_query (30 days)
message (30 days)
request_limiter (1 minute)
telegram_update (30 days)
No data to clean!
?
While the data exist (for example see screenshot above)

Thank you!

**Comment by jacklul** [comment]
The first question is generic PDO question, not related to the library, might be because you're only selecting ID? Did you tried with `->query` instead? 

Did the bot run for at least 30 days? 
That command won't cleanup your custom tables, it was only made for cleaning those created by the library.

**Comment by prtnsu** [comment]
Hi jacklul,

Thank you for the response!
1. Unfortunately, -`>query` doesn't work as well. And looks like it's the problem of library or of my code inside within the library because the same code works correctly outside of the library:

```
try {
    $pdo = new PDO("mysql:host=xxx;dbname=xxx","xxx","xxx");
 
    echo "SUCCESS!";
    
   
        
  

   
}   catch (PDOException $e) {
    echo "FAILED!";
     var_dump($e->getMessage());
    die();
}

 $haha = $pdo->prepare("SELECT id FROM forward WHERE id = '117'");
      

$haha->execute();
$hahas = $haha->fetchAll();




print_r($hahas);
```

Result:
SUCCESS!Array ( [0] => Array ( [id] => 117 [0] => 117 ) )

2. No, the bot is working about a week. Got the answer. Thank you!
