### ISSUE TITLE
Old messages are getting deleted after time without calling /cleanup

### ISSUE THREAD

**Issue by UnitedComet** [php-telegram-bot/core#950]
Hello guys, 
I have such a question, after some time, some data from **message**  table is getting deleted. 
I found out that there is a /cleanup command for that, but I am not using it. How to stop the deleting proccess?

### Required Information

- Operating system: linux
- PHP version: 7.2.7
- PHP Telegram Bot version: 0.56.0
- Using MySQL database: yes
- MySQL version: 5.6.42-cll-lve
- Update Method: Webhook 
- Self-signed certificate: yes 
- RAW update (if available):

### Expected behaviour
Not cleaning message table by its own

### Actual behaviour
Cleaning the old data from message table after some time, without calling the /cleanup

**Comment by jacklul** [comment]
As far as I know we are not removing any records anywhere else than /cleanup command.
Is it possible that your database server has some kind of cleanup build-in ?

**Comment by noplanman** [comment]
@UnitedComet This really is strange, as there is no other place that we delete content from the database, except when calling the `/cleanup` command.

Is it really just deleting older entries or what gets deleted exactly?
Does this happen with any command or just specific ones you've written?
