### ISSUE TITLE
Query about recomposing markdown or html

### ISSUE THREAD

**Issue by josegarzi2** [php-telegram-bot/core#951]
Good

I'm new and I'm a little lost.

From what I have seen when you forward a publication to the bot, telegram separates the text from the format in the json sent.

I've been looking but I have not seen any utility to recompose the publication in markdown or html format.

Is there any?

Thank you

**Comment by noplanman** [comment]
Hi @josegarzi2 

If by "recompose" you mean to edit an existing message, have a look at the official API:
https://core.telegram.org/bots/api#editmessagetext

You can simply pass along the `parse_mode` parameter there too, same as sending a new message.

**Comment by josegarzi2** [comment]
What I am trying is:

 Forward a post to the bot.  Telegram sends a json where it separates the format text (bold, italics, ...)

 What I want is to convert the text with its format to markdown or html to be able to edit it and modify the publication that was forwarded.

 I do not know if there is a helper for this

**Comment by jacklul** [comment]
You will need to write yourself a parser that puts back the formating entities on their place.
This can be a bit buggy eot multibyte characters so watch out.

**Comment by josegarzi2** [comment]
thanks
