### ISSUE TITLE
Duplicate update received, processing aborted!

### ISSUE THREAD

**Issue by josegarzi2** [php-telegram-bot/core#953]
Good Morning

I have created an assistant to transform the Json format that sends telegram to Markdown format.

For her I have created a class with a static function so that it can be called from any point.

The problem comes when trying to use it. If you use it, it gives the Duplicate update error and if it is not used, the command works correctly.

I'm probably doing something wrong, but as much as I try to see the fault I can not find it.

I show you how I currently have the code, since I have reduced it to the minimum expression.

### Required Information

- Operating system: linux
- PHP version: 7.2
- PHP Telegram Bot version: 0.56.0
- Using MySQL database: yes 
- MySQL version: 5.6
- Update Method: Webhook 
- Self-signed certificate: no
- RAW update (if available):

Command code

```
public function execute()
    {
        $message = $this->getMessage();
        $chat    = $message->getChat();
        $user    = $message->getFrom();
        $text    = trim($message->getText(true));
        $text    = App\Helpers\HelperJsonToMarkdown::JsonToMarkdown($text,"");
        //$text    = trim($message->getText(true));
        $chat_id = $chat->getId();
        $user_id = $user->getId();
```

Helper code

```
namespace App\Helpers;

class HelperJsonToMarkdown {
    public static function JsonToMarkdown($text, $entities){
        return $text;
   }
}
```

As you can see at present, the helper only returns the text that has been sent to it. Even so it gives the duplicate error.

I was looking at the previous comments and they said that deleting the content of the database was fixed, but in my case it has not been like that.

I would appreciate the help.

Thank you.

**Comment by noplanman** [comment]
Hmm, this is very strange :thinking: 

And that is the only thing that makes it give you the "Duplicate update" received error?
Are you sure you're not calling the same update multiple times somewhere else in your code?

**Comment by noplanman** [comment]
@josegarzi2 Did you manage to get this fixed? If yes, would you be open to sharing what the issue was please?

**Comment by shoxabbos** [comment]
> @josegarzi2 Did you manage to get this fixed? If yes, would you be open to sharing what the issue was please?

This happens when you enable caching.
