### ISSUE TITLE
Convert Chat object to a User object

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#960]
As the `getChat()` function returns a chat object, and a chat is sometimes a user, how can I treat it as an actual `User` object? I know that the functionality works fine (like `getFirstName()` method), but I want it to be an actual instance of **User class**.

**Comment by noplanman** [comment]
The two types are quite different! Check the API docs to compare them:
- https://core.telegram.org/bots/api#user
- https://core.telegram.org/bots/api#chat

What do you need this for exactly? What are you trying to achieve?

**Comment by ttvd94** [comment]
I'm trying to get a user's info by knowing the `user_id`. I'm aware of the difference between these two, but when it comes to private chats, both are very similar.

Being more specific, I'm passing a `User` object to a function which only accepts instances of `User` class. Sometimes the object I'm passing is a `Chat` object fetched by `getChat` method.

**Comment by noplanman** [comment]
You can simply make yourself (or just copy-paste :wink:) a little helper that converts it for you:
```php
use \Longman\TelegramBot\Entities\Chat;
use \Longman\TelegramBot\Entities\User;

/**
 * Function to convert a Chat to a User object.
 *
 * @param Chat  $chat The Chat object to be converted.
 * @param array $data Pass and override any default value (e.g. ['language_code' => 'fr']).
 *
 * @return User
 */
function convertChatToUser(Chat $chat, array $data = [])
{
    return new User(array_merge([
        'id'            => $chat->getId(),
        'first_name'    => $chat->getFirstName(),
        'last_name'     => $chat->getLastName(),
        'username'      => $chat->getUsername(),
        'is_bot'        => false,
        'language_code' => 'en',
    ], $data));
}
```

**Comment by ttvd94** [comment]
Thanks @noplanman , but I've already found a simpler way. Just wanted to see if there's a built-in method for that, since it seems to be very useful. Currently I go:
`$user = new User((array)$chat)`
