### ISSUE TITLE
Relative path in Request::encodeFile()

### ISSUE THREAD

**Issue by viktor02** [php-telegram-bot/core#961]
### Required Information

- Operating system: Ubuntu 14.04.4
- PHP version: 5.5.9
- PHP Telegram Bot version: 0.56.6
- Using MySQL database: no
- Update Method: Webhook 
- Self-signed certificate: no

### Expected behaviour

Method can get relative paths /img/xxxxx.png
### Actual behaviour

ErrorException:  fopen(img/xxxxx.png): failed to open stream: No such file or directory;

### Code
Error

	$imgurl = "img/".$row['path'].".png";
	$photo = Request::encodeFile($imgurl);

Works at full path

	$imgurl = "/home/webserver/domain/public_html/img/".$row['path'].".png";
	$photo = Request::encodeFile($imgurl);

**Comment by noplanman** [comment]
I don't think this is an error. It's better practice to pass the full path anyway.

For your case, you can use the following:
```php
$imgurl = __DIR__ . "/img/{$row['path']}.png";
```
