### ISSUE TITLE
mysql database not connected my telegram bot

### ISSUE THREAD

**Issue by anandlakhera** [php-telegram-bot/core#962]
### Required Information

- Operating system:
- PHP version:
- PHP Telegram Bot version:
- Using MySQL database: yes / no
- MySQL version:
- Update Method: Webhook / getUpdates
- Self-signed certificate: yes / no
- RAW update (if available):

**Comment by noplanman** [comment]
@anandlakhera Please edit your issue and fill in the required details and explain what isn't working.

Have you read and followed the [readme](https://github.com/php-telegram-bot/core/blob/master/README.md) file?

Feel free to reopen if you still have a problem after following the readme.
