### ISSUE TITLE
Background worker

### ISSUE THREAD

**Issue by IranDeveloper** [php-telegram-bot/core#974]
Is the robot capable of working on the ground?
For example, send message to channel every 5 min without any /command.

**Comment by IranDeveloper** [comment]
Please help me

**Comment by noplanman** [comment]
Hi @IranDeveloper, excuse the late reply!

You can make a script that gets executed every 5 minutes via cron, yes.

If it's just to send a simple message, you can create a new script something like this:
```php
#!/usr/bin/env php
<?php

use Longman\TelegramBot\Request;
use Longman\TelegramBot\Telegram;

require_once __DIR__ . '/vendor/autoload.php';

new Telegram('<your_api_key>');
Request::sendMessage([
    'chat_id' => '<your_channel_id_or_@username>',
    'text'    => 'Your message',
]);
```

Then execute that via cron :+1:
