### ISSUE TITLE
Telegram returned an invalid response

### ISSUE THREAD

**Issue by webzlodimir** [php-telegram-bot/core#975]
### Required Information
- Operating system: Linux
- PHP version: 7.1.22
- PHP Telegram Bot version: 0.57.0
- Using MySQL database: no
- Update Method: Webhook
- Self-signed certificate: no

### Expected behaviour
Set webhook

### Actual behaviour
Error: Telegram returned an invalid response

### Steps to reproduce

```
<?php
// Load composer
require __DIR__ . '/vendor/autoload.php';

$bot_api_key  = 'API_KEY';
$bot_username = 'NAME';
$hook_url     = 'HOOK';

try {
    // Create Telegram API object
    $telegram = new Longman\TelegramBot\Telegram($bot_api_key, $bot_username);

    // Set webhook
    $result = $telegram->setWebhook($hook_url);
    if ($result->isOk()) {
        echo $result->getDescription();
    }
} catch (Longman\TelegramBot\Exception\TelegramException $e) {
    // log telegram errors
    var_dump($e);
    echo $e->getMessage();
}
```

**Comment by jacklul** [comment]
I believe Telegram got banned in Russia?
Please look here: https://github.com/php-telegram-bot/core/issues/822

**Comment by webzlodimir** [comment]
> I believe Telegram got banned in Russia?
> Please look here: #822

Yes, but my server is in Germany. And yesterday everything worked fine.
