### ISSUE TITLE
Get notified when the bot is promoted to admin in a chat

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#976]
There is nothing like "`promoted_chat_member`" field for a message. So how can we get notified once the bot is promoted to a group/channel's admin?

**Comment by jacklul** [comment]
You can't, the best you can do is to call `getChatMember` on random member and by [documentation](https://core.telegram.org/bots/api#chatmember) it will contain extra fields if the bot is administrator.

**Comment by ttvd94** [comment]
Thanks @jacklul , but isn't it possible to catch the event using `GenericmessageCommand`? Cause I'm starting to see that `NewchatmembersCommand` is going to be removed in future versions.

**Comment by jacklul** [comment]
Telegram does not send anything when bot is promoted, there is nothing to catch.
See https://core.telegram.org/bots/api#message

**Comment by ttvd94** [comment]
You're right. OK then. Thanks
