### ISSUE TITLE
How do make your own System Command

### ISSUE THREAD

**Issue by davidchagalidze** [php-telegram-bot/core#977]
### Support Question
Is there is a way to make new SystemCommand, and how it can be triggerd?

#### Required Information

| ? | ! |
| - | - |
| Operating system          | Linux Debian 3.16.51-3 (2017-12-13) x86_64
| PHP Telegram Bot version  | 0.54.0
| PHP version               | 5.6.39-0+deb8u1
| MySQL version             | 5.5.62-0+deb8u1
| Update Method             | Webhook 
| Self-signed certificate   | no
| RAW update (if available) | `{...}`

#### Summary

I try to copy source of command to another class (new system command), but if i change class name it not work automatically. (only triggerd by / "description"
 
I found comment on github (https://github.com/php-telegram-bot/core/issues/820#issuecomment-381985293) @noplanman advise some one just re-write exact system command. But is there is a way to make new one, and how it can be triggerd?.

**Comment by noplanman** [comment]
Hi @davidchagalidze 

What is your exact use case for this? Please explain what you're trying to achieve, for us to help better!

System commands are commands that Telegram API has, so we only react to what already exists there.

**Comment by davidchagalidze** [comment]
> System commands are commands that Telegram API has, so we only react to what already exists there.

thx @noplanman.  That make sense.
