### ISSUE TITLE
No username for channels

### ISSUE THREAD

**Issue by ttvd94** [php-telegram-bot/core#980]
`username` field is empty for any chat with type `channel`  in table `chat`.

**Comment by noplanman** [comment]
This should work fine if a username is set in the channel.
Is the channel you're using private by any chance?

**Comment by ttvd94** [comment]
The channel is public and has a username. Bots can only be admins in channels after all.

**Comment by noplanman** [comment]
Hmm, that is strange indeed...

Does it add the field correctly after removing the existing (wrong) entry from the `chat` table?

**Comment by ttvd94** [comment]
Thank you @noplanman, yeah that was strange. I removed the record and figured that I need to post a message to my channel to force the bot recognize the chat. And then the username was there. Actually at the time of opening the issue, none of the channels had username field filled, but now most of them have. 

PS. Found out that adding the bot to a channel, would not trigger `NewchatmembersCommand`.

**Comment by noplanman** [comment]
`NewchatmembersCommand` only gets called when a member gets added to a chat where the bot **is already present**.

As far as I know there is no way of finding out what channel/group the bot gets added to initially. Only after some messages have been posted, which the bot then picks up.

**Comment by ttvd94** [comment]
According to Telegram's API doc, a message have `new_chat_members` property which is array of `User`s and is set when new members were added to the group or supergroup (they didn't mention "channel"). As a user gets added to a group, a message will be sent specifying the information about the user, bot not in channels.

I had to read docs more carefully.

**Comment by noplanman** [comment]
@ttvd94 So we can close off here then, yes?

**Comment by ttvd94** [comment]
Yes @noplanman
