### ISSUE TITLE
 PSR-3 logging deprecation notice even without using logging

### ISSUE THREAD

**Issue by laurin1** [php-telegram-bot/core#982]
|  ?                        |  !
| ---                       | ---
| Operating system          | Windows 10 x64 1809
| PHP Telegram Bot version  | 0.59.0
| PHP version               | 7.3.7
| MySQL version             | none
| Update Method             | Not used
| Self-signed certificate   | N/A
| RAW update (if available) | >?

#### Summary

We upgraded from 0.56.0 to 0.59.0, which ~broke our implementation~ is now causing a deprecation notice even without using logging:

A PSR-3 compatible LoggerInterface object must be provided. Initialise with a preconfigured logger instance.

#### Previous behaviour

No errors.

#### How to reproduce

Send a message without logging configured. 

#### Expected behaviour

Previously, logging configuration was not required and we don't ~care about logging anything~ have logging configured. ~More importantly, why was a BC breaking change implemented in a minor version?~, so not sure why we are getting this notice.

**Comment by noplanman** [comment]
Hi @laurin1, thanks for reporting this!

It shouldn't be BC breaking, as only a deprecation warning is output.
I totally agree with you though, that having no logging enabled should never even touch that code, I'll get that fixed :hammer: 

Due to the nature of not being v1 yet, minor versions may contain bigger changes.

Sorry for any inconvenience this may have caused!

**Comment by noplanman** [comment]
@laurin1 Would you be able to test this fix please?
https://github.com/noplanman/php-telegram-bot/commit/5002857e6ab401d0100dfc33486f558e8669ca68#diff-c686a02e33036e126be940fad368ab7b

**Comment by laurin1** [comment]
Works.

**Comment by noplanman** [comment]
Ok, will release a new version tomorrow.

Did the script break for you with the deprecation messages or was it just the output that was bothersome?

**Comment by laurin1** [comment]
It broke - the messages would not send.

**Comment by noplanman** [comment]
Right, must have to do with the PHP error reporting configuration of your install :thinking: 

Anyway, tomorrow you can fetch the new version with the fix :muscle:

**Comment by Alexfuse** [comment]
Same message 
"Deprecated: A PSR-3 compatible LoggerInterface object must be provided. Initialise with a preconfigured logger instance. in ../vendor/longman/telegram-bot/src/TelegramLog.php on line 93
Telegram returned an invalid response!"
I try run set.php

**Comment by laurin1** [comment]
Oh, I see what the problem is - it's throwing a E_USER_DEPRECATED (16384), not a E_DEPRECATED (8192) error. Apparently, when I wrote this portion of our error handler (years ago), I left off E_USER_DEPRECATED and so it was showing up as an "unknown" error type, which looked like an actual error, not a deprecation notice. I'll fix that now.

**Comment by noplanman** [comment]
@Alexfuse That shouldn't have anything to do with this. It's probably a timeout that you are experiencing.

@laurin1 Ok, that makes sense now. Still thanks a lot for letting us know about this, because as you correctly pointed out, code that isn't used shouldn't be called! So this is definitely a good lesson for the future :pray:

**Comment by laurin1** [comment]
Should we change the issue summary or leave it?

**Comment by Alexfuse** [comment]
@noplanman I tried to connect via the webhook and onUpdate without a database, I tried different proxies (because we are from Russia). and the result is always the same.

**Comment by noplanman** [comment]
@laurin1 I've changed the title, feel free to strike through and update the initial summary, thanks!

@Alexfuse Still, it's a different problem than the issue here. Get in touch with me directly on Telegram: `@noplanman`

**Comment by noplanman** [comment]
@laurin1 I have just released version 0.59.1 with the change/fix.

**Comment by laurin1** [comment]
Works. Thanks.
