### ISSUE TITLE
I have an error when I try to run set.php

### ISSUE THREAD

**Issue by Azizbek17** [php-telegram-bot/core#984]
When I try to run set.php i have an error as follows:
Parse error: syntax error, unexpected '{' in /home/metalpro/public_html/metalbot/vendor/longman/telegram-bot/src/Request.php on line 502

**Comment by noplanman** [comment]
Hi @Azizbek17!

What version of the bot are you using?
(You can find the `$version` number it in the file `/vendor/longman/telegram-bot/src/Telegram.php`)

**Comment by Azizbek17** [comment]
php version is 5.6.40
bot version is 0.59.0

**Comment by noplanman** [comment]
Hmm, that is very strange. Are you very sure the code is being executed with PHP 5.6?

The `finally` block was introduced in PHP 5.5, so it kind of sounds like your PHP is lower :thinking:

**Comment by Azizbek17** [comment]
![Безымянный](https://user-images.githubusercontent.com/31073841/61533532-983bcf80-aa46-11e9-91b2-6d3311988d68.png)
Here it is. PHP version is 5.6.40

**Comment by Azizbek17** [comment]
I downgraded to 0.49.0 version and now it says:
Parse error: syntax error, unexpected '{' in /home/metalpro/public_html/metalbot/vendor/longman/telegram-bot/src/Request.php on line 354

**Comment by Azizbek17** [comment]
Sorry, my fault! I checked php version from wrong destination, it was 5.4! I changed it and it worked! 
Thank you very much!

**Comment by noplanman** [comment]
Ok, glad you got is sorted :tada:
