### ISSUE TITLE
Date Input

### ISSUE THREAD

**Issue by asif-rahman** [php-telegram-bot/core#987]
I need to take a date input in survey command, is there any inline calendar functionality is developed already? If not then how can I create a calendar in conversation?

**Comment by noplanman** [comment]
You mean via [inline keyboard](https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating) or [inline query](https://core.telegram.org/bots/inline) input?

**Comment by asif-rahman** [comment]
inline keyboard will be great

**Comment by noplanman** [comment]
There is nothing existing like that, so you would need to code it yourself 😊

**Comment by MaxDenusenko** [comment]
https://github.com/donicom/EventListManager/blob/master/BL/Calendar.php
