### ISSUE TITLE
How to add new line or HTML in reply.

### ISSUE THREAD

**Issue by technoknol** [php-telegram-bot/core#988]
#### Summary

How can I add new line character in response to messages. Or other HTML tags as well e.g. bold, italics etc. 

Thank you,

**Comment by noplanman** [comment]
A new line can be added with `\n` and have a look at the [allowed HTML tags](https://core.telegram.org/bots/api#html-style) from the Bot API.

So you could do something like:
```php
Request::sendMessage([
    'chat_id'    => <chat_id>,
    'text'       => "<b>Bold</b> and <i>Italic</i> text with\nnew lines!",
    'parse_mode' => 'html',
]);
```

**Comment by technoknol** [comment]
@noplanman thanks for quick reply. I didn't find this `parse_mode` in readme. 

I can send PR for readme to include this example if you wish to.

**Comment by noplanman** [comment]
Thanks for the kind suggestion, but the main documentation for the bot API you should consult is: https://core.telegram.org/bots/api

It doesn't make sense to duplicate that documentation and list everything in the readme.

**Comment by technoknol** [comment]
> Thanks for the kind suggestion, but the main documentation for the bot API you should consult is: https://core.telegram.org/bots/api
> 
> It doesn't make sense to duplicate that documentation and list everything in the readme.

I just meant an example that shows `parse_mode` only. Not whole documentation 😁

**Comment by noplanman** [comment]
Yes, I understood that :wink: 

What about all the other parameters for all the other methods?
This library is simply a wrapper for the official API, all specifics should be looked for there :+1: 

You might be interested in exploring the [example-bot](https://github.com/php-telegram-bot/example-bot) repo too, which has a few commands that make use of a bunch of features that this library provides.
