### ISSUE TITLE
Help using Conversation in Command

### ISSUE THREAD

**Issue by mhdreem** [php-telegram-bot/core#992]
I need Help With using Conversation in Command ...

I work on command That ask user to Enter Mobile Number and store it in mysql DataBase ..

**Comment by mhdreem** [comment]
this is My Code

`<?php
/**
 * This file is part of the TelegramBot package.
 *
 * (c) Avtandil Kikabidze aka LONGMAN <akalongman@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Longman\TelegramBot\Commands\UserCommands;
use Longman\TelegramBot\Conversation;
use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Request;
use Longman\TelegramBot\Commands\View_Studnet;
use Longman\TelegramBot\Commands\View_TelegramUser;
use Longman\TelegramBot\Commands\HelpCommand;
use Longman\TelegramBot\Commands\WhoamiCommand;
/**
 * User "/forcereply" command
 *
 * Force a reply to a message.
 */
class PhoneNumberCommand extends UserCommand
{
    /**
     * @var string
     */
    protected $name = 'phonenumber';

    /**
     * @var string
     */
    protected $description = 'الحصول على رقم هاتف المفعل عليه التلغرام';

    /**
     * @var string
     */
    protected $usage = '/phonenumber';

    protected $need_mysql = true;

    protected $conversation;
    /**
     * @var string
     */
    protected $version = '0.1.0';

    /**
     * Command execute method
     *
     * @return \Longman\TelegramBot\Entities\ServerResponse
     * @throws \Longman\TelegramBot\Exception\TelegramException
     */
    public function execute()
    {       
        
        $chat_id = null;
        $first_name= null;
        $LastName = null;
        $user_id= null;
        $message_id = null;
        $Username = null;
        $from  = null;
        $phone= null;
        $message = null;
        $text =null;
        $chat = null;

        try {
          

          
            $message = $this->getMessage();
            $chat = $message->getChat();          
            $text    = trim($message->getText(true));
            $chat_id    = $message->getChat()->getId();
            $first_name= $message->getChat()->getFirstName();                
            $from       = $message->getFrom();
            $user_id    = $from->getId();           
            $message_id = $message->getMessageId();
            $FirstName  = $from->getFirstName();
            $LastName   = $from->getLastName();
            $Username   = $from->getUsername();
            $message = $this->getMessage();            // Get Message object            
          }                    
          catch(Exception $e) {
            echo 'Message: ' .$e->getMessage();
          } 

          

          if ($chat->isGroupChat() || $chat->isSuperGroup()) {
            //reply to message id is applied by default
            //Force reply is applied by default so it can work with privacy on
            $data['reply_markup'] = Keyboard::forceReply(['selective' => true]);
        }
        $data = [
            'chat_id' => $chat_id,
        ];

        

          $this->conversation = new Conversation($user_id, $chat_id, 'phonenumber');
         
          $result = Request::emptyResponse();

          $notes = &$this->conversation->notes;
          !is_array($notes) && $notes = [];
          //cache data from the tracking session if any
          $state = 0;
          if (isset($notes['state'])) {
              $state = $notes['state'];
          }
          $notes['state'] = 0;
          $this->conversation->update();

                if ($text === '') {
                    $data['text']         = 'Please Enter The Phone Number';
                   
                    $result =Request::sendMessage($data);

                }else
        {
            $data['text']         = ' ALL Right >>User Enter The Phone';
            

            $result =Request::sendMessage($data);
            $this->conversation->stop();           


        }
 

            return $result;

            
                   
       
    }
}
`

**Comment by mhdreem** [comment]
please help me noplanman #

**Comment by noplanman** [comment]
Hi @mhdreem 

First of all, you can clean up that command a lot, there seems to be a lot of unnecessary code in there. I've taken the liberty to rewrite and free it up a bit, see below.

What exactly wasn't working with your command?

The main thing that needs to be in place for the conversations to work, is a `GenericmessageCommand`.

**Note, if you don't have an own `GenericmessageCommand` you can ignore this, as the default library does this for you!**

In case you do have a custom `GenericmessageCommand`, make sure it has the necessary functionality in the `execute` method, which you can see here:
https://github.com/php-telegram-bot/core/blob/f55fd1c2eb75b4f8e9ab468066ce96acba9e6b68/src/Commands/SystemCommands/GenericmessageCommand.php#L61-L75


```php
<?php

namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Conversation;
use Longman\TelegramBot\Entities\Keyboard;
use Longman\TelegramBot\Request;

class PhonenumberCommand extends UserCommand
{
    protected $name = 'phonenumber';

    protected $description = 'الحصول على رقم هاتف المفعل عليه التلغرام';

    protected $usage = '/phonenumber';

    protected $need_mysql = true;

    protected $version = '0.2.0';

    public function execute()
    {
        try {
            $message    = $this->getMessage();
            $chat       = $message->getChat();
            $user       = $message->getFrom();
            $number     = trim($message->getText(true));
            $extra_data = [];

            if ($chat->isGroupChat() || $chat->isSuperGroup()) {
                // reply to message id is applied by default
                // Force reply is applied by default so it can work with privacy on
                $extra_data['reply_markup'] = Keyboard::forceReply(['selective' => true]);
            }

            $conversation = new Conversation($user->getId(), $chat->getId(), $this->name);

            if ($number === '') {
                return $this->replyToChat('Please Enter The Phone Number', $extra_data);
            }

            // Save the entered number to the database.
            $conversation->notes = ['number' => $number];
            $conversation->update();
            $conversation->stop();

            return $this->replyToChat('ALL Right >>User Enter The Phone>>> Here We Put The insert phone number in database', $extra_data);
        } catch (Exception $e) {
            echo 'Message: ' . $e->getMessage();
        }

        return Request::emptyResponse();
    }
}
```

**Comment by mhdreem** [comment]
Thanks very much noplanman 
You are a man who loves to help

**Comment by noplanman** [comment]
I try 😉

So all is working now?
