### ISSUE TITLE
 Extract User Message Using SystemCommand Class

### ISSUE THREAD

**Issue by gabrielmarcato** [php-telegram-bot/core#997]
#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | linux
| PHP Telegram Bot version  | final
| PHP version               | 7.2.12
| MySQL version             | 5.7.24
| Update Method             | Webhook 
| Self-signed certificate   | yes

#### Summary

Hello

One doubt, I'm using inlineKeyboard and getting the information via callbackquery.
I wonder if it is possible to receive the data entered by the user or for his work as two performances, user and system command.

**Comment by noplanman** [comment]
Hi @gabrielmarcato!

I don't fully understand what you mean.

Could you please elaborate and explain what it is you're trying to achieve?

(also, `final` is not a version, please enter the correct version number so we know what you're using, thanks 😃)
