### ISSUE TITLE
i cant handle generic messages in groups

### ISSUE THREAD

**Issue by fakirpic** [php-telegram-bot/core#998]
hi by editing GenericmessageCommand.php i couldnt my bot work with normal texts not commands so i just edited core files to force use GenericCommand.php instead of GenericmessagesCommand.php now it works, but in groups bot doesnt take care of normal messages but still replies to commands

**Comment by noplanman** [comment]
Hi @fakirpic

Could you please explain more what you're trying to do and what you've done exactly?

Also, never change any code directly in the core (`vendor` folder).
Instead, create a new folder for your custom commands and add them there. You can copy the `GenericmessageCommand.php` file from the core to your own commands folder and modify it there.

Then in your hook file you need to add that directory using `$telegram->addCommandsPath($path);`.

**Comment by fakirpic** [comment]
GenericmessageCommand.php was not working for me, but i fixed it it was releated a setting with my bot , its configurable by @botfather

**Comment by noplanman** [comment]
Ok, glad you got it to work 👍

**Comment by davidchagalidze** [comment]
> Hi @fakirpic
> 
> Could you please explain more what you're trying to do and what you've done exactly?
> 
> Also, never change any code directly in the core (`vendor` folder).
> Instead, create a new folder for your custom commands and add them there. You can copy the `GenericmessageCommand.php` file from the core to your own commands folder and modify it there.
> 
> Then in your hook file you need to add that directory using `$telegram->addCommandsPath($path);`.

If i need to make custom CallbackqueryCommand functionality, how should i proceed in that situation?

**Comment by noplanman** [comment]
@davidchagalidze Same thing applies, create a custom commands folder and add it there.

(Please open a new issue if need be, instead of continuing on this closed one that is a different topic 👌)
